In [ ]:
!pip install gcloud
!gcloud auth application-default login

Collecting gcloud
  Downloading gcloud-0.18.3.tar.gz (454 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 454.4/454.4 kB 7.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: httplib2>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from gcloud) (0.32.0)
Requirement already satisfied: googleapis-common-protos in /usr/local/lib/python3.12/dist-packages (from gcloud) (1.75.0)
Requirement already satisfied: oauth2client>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from gcloud) (4.1.3)
Requirement already satisfied: protobuf!=3.0.0.b2.post1,>=3.0.0b2 in /usr/local/lib/python3.12/dist-packages (from gcloud) (5.29.6)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from gcloud) (1.17.0)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2>=0.9.1->gcloud) (3.3.2)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (0.6.4)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (0.4.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (4.9.1)
Building wheels for collected packages: gcloud
  Building wheel for gcloud (setup.py) ... done
  Created wheel for gcloud: filename=gcloud-0.18.3-py3-none-any.whl size=602927 sha256=7bbc2eca7d291ed54e6db38c68a9f742707d9b4514791572a9d168babc879936
  Stored in directory: /root/.cache/pip/wheels/2a/62/75/3d74209bfebb8805823ae74afa28653aa1ea76d8b5a9d741ff
Successfully built gcloud
Installing collected packages: gcloud
Successfully installed gcloud-0.18.3
Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fapplicationdefaultauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=Ql2FsXkRK7uQ13Mzb1LQA3m9ycuvWN&prompt=consent&token_usage=remote&access_type=offline&code_challenge=2vxmVJJqYJDJICAqMTX_WyaL0GKiGYRQD7mgBqZc4TE&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0AXEQxIC3bTLKtO4RWh4C0daoZ5d3-eogeM43YMxiwUl0lGH8mavd_-thDlGq7kG5FpoX6A

Credentials saved to file: [/content/.config/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.


To take a quick anonymous survey, run:
  $ gcloud survey

In [ ]:
import pandas as pd
import numpy as np
import os
import pandas_gbq
from google.cloud import bigquery
import glob
import openpyxl

# o Ano de 2024

In [ ]:
df = pd.read_excel('/content/Base_Estadic_2024.xlsx', sheet_name='Informática e comunicação')
df

,Cod UF,Sigla UF,Nome UF,PopUF,Região,Etic011,Etic012,Etic013,Etic014,Etic015,...,Etic347,Etic348,Etic35,Etic361,Etic362,Etic363,Etic364,Etic365,Etic366,Etic367
0,11,RO,RONDÔNIA,1746227,1 - Norte,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Não,Não,Não,Não
1,12,AC,ACRE,880631,1 - Norte,Não,Não,Sim,Não,Sim,...,Não,Não,Sim,Sim,Não,Não,Não,Não,Não,Não
2,13,AM,AMAZONAS,4281209,1 - Norte,Não,Não,Sim,Sim,Não,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
3,14,RR,RORAIMA,716793,1 - Norte,Sim,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
4,15,PA,PARÁ,8664306,1 - Norte,Não,Não,Não,Sim,Sim,...,Não,Não,Sim,Sim,Sim,Não,Sim,Não,Não,Não
5,16,AP,AMAPÁ,802837,1 - Norte,Sim,Sim,Sim,Não,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Sim,Não,Não,Não
6,17,TO,TOCANTINS,1577342,1 - Norte,Não,Não,Sim,Não,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Não,Não,Não,Não
7,21,MA,MARANHÃO,7010960,2 - Nordeste,Não,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
8,22,PI,PIAUÍ,3375646,2 - Nordeste,Sim,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Sim,Não,Não,Não
9,23,CE,CEARÁ,9233656,2 - Nordeste,Sim,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Sim,Não,Sim,Não,Não,Não
10,24,RN,RIO GRANDE DO NORTE,3446071,2 - Nordeste,Não,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
11,25,PB,PARAÍBA,4145040,2 - Nordeste,Não,Não,Não,Sim,Não,...,-,-,Sim,Não,Não,Não,Não,Sim,Não,Não
12,26,PE,PERNAMBUCO,9539029,2 - Nordeste,Não,Não,Sim,Não,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Sim,Não,Não,Não
13,27,AL,ALAGOAS,3220104,2 - Nordeste,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Não,Não,Não,Não,Não
14,28,SE,SERGIPE,2291077,2 - Nordeste,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Não,Sim,Sim,Sim,Não,Não,Não
15,29,BA,BAHIA,14850513,2 - Nordeste,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
16,31,MG,MINAS GERAIS,21322691,3 - Sudeste,Não,Não,Sim,Sim,Não,...,Não,Não,Sim,Sim,Não,Sim,Não,Não,Não,Não
17,32,ES,ESPÍRITO SANTO,4102129,3 - Sudeste,Não,Não,Sim,Não,Sim,...,Não,Não,Sim,Sim,Sim,Não,Não,Não,Não,Não
18,33,RJ,RIO DE JANEIRO,17219679,3 - Sudeste,Sim,Não,Sim,Não,Não,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
19,35,SP,SÃO PAULO,45973194,3 - Sudeste,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Sim,Não,Não,Não
20,41,PR,PARANÁ,11824665,4 - Sul,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Não,Não,Não,Não
21,42,SC,SANTA CATARINA,8058441,4 - Sul,Não,Não,Sim,Não,Sim,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
22,43,RS,RIO GRANDE DO SUL,11229915,4 - Sul,Sim,Não,Não,Não,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Não,Não,Não,Não
23,50,MS,MATO GROSSO DO SUL,2901895,5 - Centro-Oeste,Sim,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Não,Não,Não,Não
24,51,MT,MATO GROSSO,3836399,5 - Centro-Oeste,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Não,Não,Não,Não
25,52,GO,GOIÁS,7350483,5 - Centro-Oeste,Não,Não,Sim,Sim,Não,...,Não,Não,Sim,Sim,Não,Sim,Não,Não,Não,Não
26,53,DF,DISTRITO FEDERAL,2982818,5 - Centro-Oeste,Sim,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Sim,Não,Não,Não

In [ ]:
df = df[['Cod UF', 'Etic12a7', 'Etic12b12', 'Etic12a4', 'Etic12a5', 'Etic12a6', 'Etic12b1']]
df

    Cod UF Etic12a7 Etic12b12 Etic12a4 Etic12a5 Etic12a6 Etic12b1
0       11      Sim       Sim      Sim      Sim      Sim      Sim
1       12      Sim       Sim      Sim      Sim      Sim      Sim
2       13      Sim       Não      Sim      Sim      Sim      Sim
3       14      Sim       Não      Sim      Sim      Sim      Sim
4       15      Sim       Sim      Sim      Sim      Sim      Sim
5       16      Sim       Sim      Sim      Sim      Sim      Sim
6       17      Sim       Sim      Sim      Sim      Sim      Sim
7       21      Sim       Sim      Sim      Sim      Sim      Sim
8       22      Sim       Sim      Sim      Sim      Sim      Sim
9       23      Sim       Sim      Sim      Sim      Sim      Sim
10      24      Sim       Sim      Sim      Sim      Sim      Sim
11      25      Sim       Não      Sim      Sim      Sim      Sim
12      26      Não       Não      Não      Não      Não      Sim
13      27      Sim       Sim      Sim      Sim      Sim      Sim
14      28      Sim       Sim      Sim      Sim      Sim      Sim
15      29      Não       Não      Sim      Sim      Não      Sim
16      31      Sim       Sim      Sim      Sim      Sim      Sim
17      32      Sim       Não      Sim      Sim      Sim      Sim
18      33      Sim       Sim      Sim      Sim      Sim      Sim
19      35      Sim       Sim      Sim      Sim      Sim      Sim
20      41      Não       Não      Não      Sim      Não      Sim
21      42      Sim       Sim      Sim      Sim      Sim      Sim
22      43      Sim       Não      Sim      Sim      Sim      Sim
23      50      Sim       Sim      Sim      Sim      Sim      Sim
24      51      Sim       Não      Sim      Sim      Sim      Sim
25      52      Sim       Sim      Sim      Sim      Sim      Sim
26      53      Sim       Sim      Sim      Sim      Sim      Sim

In [ ]:
df = df.rename(columns={'Cod UF': 'cod_uf',
                        'Etic12a7':'concursos_publicos',
                        'Etic12b12':'pesquisa_satisfacao_servicos_estado',
                        'Etic12a4':'diario',
                        'Etic12a5':'legislacao',
                        'Etic12a6':'financas',
                        'Etic12b1':'ouvidoria_atendimento_cidadao'})

In [ ]:
cod_uf = pd.read_csv('/content/ESTADIC_2019 - Variáveis externas.csv', sep=',')[['UF','COD_UF']]

In [ ]:
x= cod_uf.pivot_table(columns=('UF','COD_UF'), aggfunc='size')

In [ ]:
cod_uf = pd.DataFrame(x).reset_index()[['UF','COD_UF']]

In [ ]:
df = df.merge(cod_uf, right_on='COD_UF',left_on='cod_uf')
df

,cod_uf,concursos_publicos,pesquisa_satisfacao_servicos_estado,diario,legislacao,financas,ouvidoria_atendimento_cidadao,UF,COD_UF
0,11,Sim,Sim,Sim,Sim,Sim,Sim,RO,11
1,12,Sim,Sim,Sim,Sim,Sim,Sim,AC,12
2,13,Sim,Não,Sim,Sim,Sim,Sim,AM,13
3,14,Sim,Não,Sim,Sim,Sim,Sim,RR,14
4,15,Sim,Sim,Sim,Sim,Sim,Sim,PA,15
5,16,Sim,Sim,Sim,Sim,Sim,Sim,AP,16
6,17,Sim,Sim,Sim,Sim,Sim,Sim,TO,17
7,21,Sim,Sim,Sim,Sim,Sim,Sim,MA,21
8,22,Sim,Sim,Sim,Sim,Sim,Sim,PI,22
9,23,Sim,Sim,Sim,Sim,Sim,Sim,CE,23
10,24,Sim,Sim,Sim,Sim,Sim,Sim,RN,24
11,25,Sim,Não,Sim,Sim,Sim,Sim,PB,25
12,26,Não,Não,Não,Não,Não,Sim,PE,26
13,27,Sim,Sim,Sim,Sim,Sim,Sim,AL,27
14,28,Sim,Sim,Sim,Sim,Sim,Sim,SE,28
15,29,Não,Não,Sim,Sim,Não,Sim,BA,29
16,31,Sim,Sim,Sim,Sim,Sim,Sim,MG,31
17,32,Sim,Não,Sim,Sim,Sim,Sim,ES,32
18,33,Sim,Sim,Sim,Sim,Sim,Sim,RJ,33
19,35,Sim,Sim,Sim,Sim,Sim,Sim,SP,35
20,41,Não,Não,Não,Sim,Não,Sim,PR,41
21,42,Sim,Sim,Sim,Sim,Sim,Sim,SC,42
22,43,Sim,Não,Sim,Sim,Sim,Sim,RS,43
23,50,Sim,Sim,Sim,Sim,Sim,Sim,MS,50
24,51,Sim,Não,Sim,Sim,Sim,Sim,MT,51
25,52,Sim,Sim,Sim,Sim,Sim,Sim,GO,52
26,53,Sim,Sim,Sim,Sim,Sim,Sim,DF,53

In [ ]:
df = df.drop(['COD_UF'], axis=1)
df

,cod_uf,concursos_publicos,pesquisa_satisfacao_servicos_estado,diario,legislacao,financas,ouvidoria_atendimento_cidadao,UF
0,11,Sim,Sim,Sim,Sim,Sim,Sim,RO
1,12,Sim,Sim,Sim,Sim,Sim,Sim,AC
2,13,Sim,Não,Sim,Sim,Sim,Sim,AM
3,14,Sim,Não,Sim,Sim,Sim,Sim,RR
4,15,Sim,Sim,Sim,Sim,Sim,Sim,PA
5,16,Sim,Sim,Sim,Sim,Sim,Sim,AP
6,17,Sim,Sim,Sim,Sim,Sim,Sim,TO
7,21,Sim,Sim,Sim,Sim,Sim,Sim,MA
8,22,Sim,Sim,Sim,Sim,Sim,Sim,PI
9,23,Sim,Sim,Sim,Sim,Sim,Sim,CE
10,24,Sim,Sim,Sim,Sim,Sim,Sim,RN
11,25,Sim,Não,Sim,Sim,Sim,Sim,PB
12,26,Não,Não,Não,Não,Não,Sim,PE
13,27,Sim,Sim,Sim,Sim,Sim,Sim,AL
14,28,Sim,Sim,Sim,Sim,Sim,Sim,SE
15,29,Não,Não,Sim,Sim,Não,Sim,BA
16,31,Sim,Sim,Sim,Sim,Sim,Sim,MG
17,32,Sim,Não,Sim,Sim,Sim,Sim,ES
18,33,Sim,Sim,Sim,Sim,Sim,Sim,RJ
19,35,Sim,Sim,Sim,Sim,Sim,Sim,SP
20,41,Não,Não,Não,Sim,Não,Sim,PR
21,42,Sim,Sim,Sim,Sim,Sim,Sim,SC
22,43,Sim,Não,Sim,Sim,Sim,Sim,RS
23,50,Sim,Sim,Sim,Sim,Sim,Sim,MS
24,51,Sim,Não,Sim,Sim,Sim,Sim,MT
25,52,Sim,Sim,Sim,Sim,Sim,Sim,GO
26,53,Sim,Sim,Sim,Sim,Sim,Sim,DF

In [ ]:
df['ano']=2024

In [ ]:
df = df.rename(columns={'UF':'sigla_uf'})

In [ ]:
df = df[['ano','sigla_uf','cod_uf', 'concursos_publicos', 'pesquisa_satisfacao_servicos_estado', 'ouvidoria_atendimento_cidadao', 'diario', 'legislacao', 'financas']]

In [ ]:
df

,ano,sigla_uf,cod_uf,concursos_publicos,pesquisa_satisfacao_servicos_estado,ouvidoria_atendimento_cidadao,diario,legislacao,financas
0,2024,RO,11,Sim,Sim,Sim,Sim,Sim,Sim
1,2024,AC,12,Sim,Sim,Sim,Sim,Sim,Sim
2,2024,AM,13,Sim,Não,Sim,Sim,Sim,Sim
3,2024,RR,14,Sim,Não,Sim,Sim,Sim,Sim
4,2024,PA,15,Sim,Sim,Sim,Sim,Sim,Sim
5,2024,AP,16,Sim,Sim,Sim,Sim,Sim,Sim
6,2024,TO,17,Sim,Sim,Sim,Sim,Sim,Sim
7,2024,MA,21,Sim,Sim,Sim,Sim,Sim,Sim
8,2024,PI,22,Sim,Sim,Sim,Sim,Sim,Sim
9,2024,CE,23,Sim,Sim,Sim,Sim,Sim,Sim
10,2024,RN,24,Sim,Sim,Sim,Sim,Sim,Sim
11,2024,PB,25,Sim,Não,Sim,Sim,Sim,Sim
12,2024,PE,26,Não,Não,Sim,Não,Não,Não
13,2024,AL,27,Sim,Sim,Sim,Sim,Sim,Sim
14,2024,SE,28,Sim,Sim,Sim,Sim,Sim,Sim
15,2024,BA,29,Não,Não,Sim,Sim,Sim,Não
16,2024,MG,31,Sim,Sim,Sim,Sim,Sim,Sim
17,2024,ES,32,Sim,Não,Sim,Sim,Sim,Sim
18,2024,RJ,33,Sim,Sim,Sim,Sim,Sim,Sim
19,2024,SP,35,Sim,Sim,Sim,Sim,Sim,Sim
20,2024,PR,41,Não,Não,Sim,Não,Sim,Não
21,2024,SC,42,Sim,Sim,Sim,Sim,Sim,Sim
22,2024,RS,43,Sim,Não,Sim,Sim,Sim,Sim
23,2024,MS,50,Sim,Sim,Sim,Sim,Sim,Sim
24,2024,MT,51,Sim,Não,Sim,Sim,Sim,Sim
25,2024,GO,52,Sim,Sim,Sim,Sim,Sim,Sim
26,2024,DF,53,Sim,Sim,Sim,Sim,Sim,Sim

In [ ]:
df.columns

Index(['ano', 'sigla_uf', 'cod_uf', 'concursos_publicos',
       'pesquisa_satisfacao_servicos_estado', 'ouvidoria_atendimento_cidadao',
       'diario', 'legislacao', 'financas'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 9 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ano                                  27 non-null     int64
 1   sigla_uf                             27 non-null     object
 2   cod_uf                               27 non-null     int64
 3   concursos_publicos                   27 non-null     object
 4   pesquisa_satisfacao_servicos_estado  27 non-null     object
 5   ouvidoria_atendimento_cidadao        27 non-null     object
 6   diario                               27 non-null     object
 7   legislacao                           27 non-null     object
 8   financas                             27 non-null     object
dtypes: int64(2), object(7)
memory usage: 2.0+ KB

# Consumindo o ano de 2019 através do GBQ

In [ ]:


query = """SELECT * FROM `repositoriodedadosgpsp.participacao_transparencia.ESTADIC_transparencia_internet` WHERE ano = 2019"""
# Execute the query using pandas_gbq.read_gbq and load the result into a pandas DataFrame called 'df'.
# The 'project_id' specifies the Google Cloud Project to use.
df_2019 = pandas_gbq.read_gbq(query, project_id='repositoriodedadosgpsp')

Downloading: 100%|██████████|

In [ ]:
df_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ano                                  27 non-null     Int64
 1   sigla_uf                             27 non-null     object
 2   cod_uf                               27 non-null     Int64
 3   concursos_publicos                   27 non-null     object
 4   pesquisa_satisfacao_servicos_estado  27 non-null     object
 5   diario_legislacao_financas           27 non-null     object
 6   ouvidoria_atendimento_cidadao        27 non-null     object
dtypes: Int64(2), object(5)
memory usage: 1.7+ KB

In [ ]:
for col in ['diario', 'legislacao', 'financas']:
    df_2019[col] = df_2019['diario_legislacao_financas']

In [ ]:
df_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 10 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ano                                  27 non-null     Int64
 1   sigla_uf                             27 non-null     object
 2   cod_uf                               27 non-null     Int64
 3   concursos_publicos                   27 non-null     object
 4   pesquisa_satisfacao_servicos_estado  27 non-null     object
 5   diario_legislacao_financas           27 non-null     object
 6   ouvidoria_atendimento_cidadao        27 non-null     object
 7   diario                               27 non-null     object
 8   legislacao                           27 non-null     object
 9   financas                             27 non-null     object
dtypes: Int64(2), object(8)
memory usage: 2.3+ KB

In [ ]:
df_2019.head(10)

,ano,sigla_uf,cod_uf,concursos_publicos,pesquisa_satisfacao_servicos_estado,diario_legislacao_financas,ouvidoria_atendimento_cidadao,diario,legislacao,financas
0,2019,RO,11,Sim,Sim,Sim,Sim,Sim,Sim,Sim
1,2019,AP,16,Sim,Sim,Sim,Sim,Sim,Sim,Sim
2,2019,TO,17,Sim,Sim,Sim,Sim,Sim,Sim,Sim
3,2019,CE,23,Sim,Sim,Sim,Sim,Sim,Sim,Sim
4,2019,PB,25,Sim,Sim,Sim,Sim,Sim,Sim,Sim
5,2019,SE,28,Sim,Sim,Sim,Sim,Sim,Sim,Sim
6,2019,MG,31,Sim,Sim,Sim,Sim,Sim,Sim,Sim
7,2019,ES,32,Sim,Sim,Sim,Sim,Sim,Sim,Sim
8,2019,MT,51,Sim,Sim,Sim,Não,Sim,Sim,Sim
9,2019,AC,12,Sim,Não,Sim,Sim,Sim,Sim,Sim

In [ ]:
df_2019 = df_2019.drop(columns=['diario_legislacao_financas'])

In [ ]:
df_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 9 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ano                                  27 non-null     Int64
 1   sigla_uf                             27 non-null     object
 2   cod_uf                               27 non-null     Int64
 3   concursos_publicos                   27 non-null     object
 4   pesquisa_satisfacao_servicos_estado  27 non-null     object
 5   ouvidoria_atendimento_cidadao        27 non-null     object
 6   diario                               27 non-null     object
 7   legislacao                           27 non-null     object
 8   financas                             27 non-null     object
dtypes: Int64(2), object(7)
memory usage: 2.1+ KB

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 9 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ano                                  27 non-null     int64
 1   sigla_uf                             27 non-null     object
 2   cod_uf                               27 non-null     int64
 3   concursos_publicos                   27 non-null     object
 4   pesquisa_satisfacao_servicos_estado  27 non-null     object
 5   ouvidoria_atendimento_cidadao        27 non-null     object
 6   diario                               27 non-null     object
 7   legislacao                           27 non-null     object
 8   financas                             27 non-null     object
dtypes: int64(2), object(7)
memory usage: 2.0+ KB

In [ ]:
df_final = pd.concat([df, df_2019], ignore_index=True)

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 9 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ano                                  54 non-null     Int64
 1   sigla_uf                             54 non-null     object
 2   cod_uf                               54 non-null     Int64
 3   concursos_publicos                   54 non-null     object
 4   pesquisa_satisfacao_servicos_estado  54 non-null     object
 5   ouvidoria_atendimento_cidadao        54 non-null     object
 6   diario                               54 non-null     object
 7   legislacao                           54 non-null     object
 8   financas                             54 non-null     object
dtypes: Int64(2), object(7)
memory usage: 4.0+ KB

# Subindo para o GBQ

In [ ]:
# Define the BigQuery table schema with Portuguese descriptions
schema=[bigquery.SchemaField('ano','INTEGER',description='Ano de referência da observação'),
        bigquery.SchemaField('cod_uf','INTEGER',description='Código do IBGE da UF'),
        bigquery.SchemaField('sigla_uf','STRING',description='Sigla da Unidade da Federação'),
        bigquery.SchemaField('concursos_publicos','STRING',description='Serviços disponibilizados na internet sobre concursos públicos'),
        bigquery.SchemaField('pesquisa_satisfacao_servicos_estado','STRING',description='Serviços disponibilizados na internet sobre pesquisa de satisfação relacionada aos serviços prestados pelo estado'),
        bigquery.SchemaField('diario','STRING',description='Serviços disponibilizados na internet sobre diário oficial'),
        bigquery.SchemaField('legislacao','STRING',description='Serviços disponibilizados na internet sobre legislação estadual e finanças públicas'),
        bigquery.SchemaField('financas','STRING',description='Serviços disponibilizados na internet sobre finanças públicas'),
        bigquery.SchemaField('ouvidoria_atendimento_cidadao','STRING',description='Serviços disponibilizados na internet sobre ouvidoria e serviços de atendimento ao cidadão'),
]

# Initialize BigQuery client connection
client = bigquery.Client(project='repositoriodedadosgpsp')

# Create reference to target dataset
dataset_ref = client.dataset('participacao_transparencia')

# Create reference to target table with standardized naming convention:
# FONTE_algo_intuitivo_dado (MUNIC_quantidade_vinculos_mapa_v1)
table_ref = dataset_ref.table('ESTADIC_transparencia_internet_v1')

# Configure the load job with our schema definition
job_config = bigquery.LoadJobConfig(
    schema=schema,
    # Optional parameters (commented out):
    # write_disposition="WRITE_TRUNCATE",  # Overwrites table if exists
    # create_disposition="CREATE_IF_NEEDED"  # Default behavior
)

# Execute the load job to upload DataFrame to BigQuery
job = client.load_table_from_dataframe(
    dataframe=df_final,
    destination=table_ref,
    job_config=job_config
)

# Wait for the job to complete
job.result()

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

LoadJob<project=repositoriodedadosgpsp, location=US, id=dc3decb0-0998-443e-a1d1-303697a9bdc7>