In [ ]:
!pip install gcloud
!gcloud auth application-default login

Collecting gcloud
  Downloading gcloud-0.18.3.tar.gz (454 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 454.4/454.4 kB 8.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: httplib2>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from gcloud) (0.32.0)
Requirement already satisfied: googleapis-common-protos in /usr/local/lib/python3.12/dist-packages (from gcloud) (1.75.0)
Requirement already satisfied: oauth2client>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from gcloud) (4.1.3)
Requirement already satisfied: protobuf!=3.0.0.b2.post1,>=3.0.0b2 in /usr/local/lib/python3.12/dist-packages (from gcloud) (5.29.6)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from gcloud) (1.17.0)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2>=0.9.1->gcloud) (3.3.2)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (0.6.4)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (0.4.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (4.9.1)
Building wheels for collected packages: gcloud
  Building wheel for gcloud (setup.py) ... done
  Created wheel for gcloud: filename=gcloud-0.18.3-py3-none-any.whl size=602927 sha256=5d9bb1bdaa8a16c9c016d081f2ba111787da85274a84155866e68d9fb05b2336
  Stored in directory: /root/.cache/pip/wheels/2a/62/75/3d74209bfebb8805823ae74afa28653aa1ea76d8b5a9d741ff
Successfully built gcloud
Installing collected packages: gcloud
Successfully installed gcloud-0.18.3
Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fapplicationdefaultauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=5N4uxs4iOIsBVHIFB1DrDjXMM23j1H&prompt=consent&token_usage=remote&access_type=offline&code_challenge=BBqwgaqBbRFkOEP0mcNsyi9NhTfxdyFRIDDpYVKFygE&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0AXEQxIDIfztbN70Q_aASzcs-9qXwl7e_2zWA_X_oHWJt4CsLu-5NTlvxeslTcfWvDIIFew

Credentials saved to file: [/content/.config/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.


To take a quick anonymous survey, run:
  $ gcloud survey

In [ ]:
import pandas as pd
import numpy as np
import os
import pandas_gbq
from google.cloud import bigquery
import glob
import openpyxl

# O Ano de 2024

In [ ]:
df = pd.read_excel('/content/Base_Estadic_2024.xlsx', sheet_name='Governança', nrows=29)
df

,Cod UF,Sigla UF,Nome UF,PopUF,Região,Egov01,Egov011a,Egov011b,Egov0121,Egov0122,...,Egov3115,Egov3116,Egov3117,Egov3118,Egov3119,Egov32,Egov33,Egov34,Egov35,Egov36
0,11,RO,RONDÔNIA,1746227,1 - Norte,Não informou,Não informou,Não informou,Não informou,Não informou,...,Não informou,Não informou,Não informou,Não informou,Não informou,Não informou,Não informou,Não informou,Não informou,Não informou
1,12,AC,ACRE,880631,1 - Norte,Sim,7977,2014,Não,Sim,...,-,-,-,-,-,Sim,Em comitê ou comissão estadual específica,Não sabe,Sim,Não
2,13,AM,AMAZONAS,4281209,1 - Norte,Sim,48999,2024,Não,Sim,...,-,-,-,-,-,Sim,Na Controladoria ou Corregedoria estadual,Sim,Sim,Não
3,14,RR,RORAIMA,716793,1 - Norte,Sim,20477,2016,Sim,Sim,...,-,-,-,-,-,Não,-,Sim,Sim,Não
4,15,PA,PARÁ,8664306,1 - Norte,Sim,1359,2015,Não,Sim,...,-,-,-,-,-,Sim,No departamento ou área de TecnoIogia da Infor...,Sim,Sim,Sim
5,16,AP,AMAPÁ,802837,1 - Norte,Sim,2149,2017,Sim,Sim,...,-,-,-,-,-,Sim,No departamento ou área de TecnoIogia da Infor...,Sim,Sim,Não
6,17,TO,TOCANTINS,1577342,1 - Norte,Sim,4839,2013,Não,Sim,...,-,-,-,-,-,Sim,Não sabe,Não,Sim,Sim
7,21,MA,MARANHÃO,7010960,2 - Nordeste,Sim,10217,2015,Sim,Sim,...,-,-,-,-,-,Sim,Na Controladoria ou Corregedoria estadual,Sim,Sim,Não
8,22,PI,PIAUÍ,3375646,2 - Nordeste,Sim,15188,2013,Sim,Não,...,Não,Sim,Não,Não,Não,Sim,"Na Secretaria de Administração, Finanças ou Pl...",Sim,Sim,Sim
9,23,CE,CEARÁ,9233656,2 - Nordeste,Sim,15175,2012,Não,Sim,...,-,-,-,-,-,Sim,Na Controladoria ou Corregedoria estadual,Sim,Sim,Sim
10,24,RN,RIO GRANDE DO NORTE,3446071,2 - Nordeste,Sim,9963,2015,Sim,Sim,...,-,-,-,-,-,Sim,Na Controladoria ou Corregedoria estadual,Sim,Sim,Sim
11,25,PB,PARAÍBA,4145040,2 - Nordeste,Sim,33050,2012,Não,Sim,...,Não,Sim,Não,Não,Não,Sim,Outra,Não,Não,Sim
12,26,PE,PERNAMBUCO,9539029,2 - Nordeste,Sim,14804,2012,Não,Sim,...,-,-,-,-,-,Sim,Na Controladoria ou Corregedoria estadual,Não sabe,Sim,Sim
13,27,AL,ALAGOAS,3220104,2 - Nordeste,Sim,82871,2019,Sim,Sim,...,-,-,-,-,-,Sim,Em comitê ou comissão estadual específica,Sim,Sim,Sim
14,28,SE,SERGIPE,2291077,2 - Nordeste,Sim,30947,2017,Não,Sim,...,-,-,-,-,-,Sim,Na Controladoria ou Corregedoria estadual,Não,Não,Sim
15,29,BA,BAHIA,14850513,2 - Nordeste,Sim,12618,2012,Sim,Sim,...,-,-,-,-,-,Não sabe,-,Não sabe,Sim,Não
16,31,MG,MINAS GERAIS,21322691,3 - Sudeste,Sim,45969,2012,Não,Sim,...,Não,Sim,Não,Não,Não,Sim,Em comitê ou comissão estadual específica,Sim,Sim,Sim
17,32,ES,ESPÍRITO SANTO,4102129,3 - Sudeste,Sim,3152,2012,Sim,Sim,...,Não,Não,Não,Não,Não,Sim,Em comitê ou comissão estadual específica,Sim,Sim,Sim
18,33,RJ,RIO DE JANEIRO,17219679,3 - Sudeste,Sim,46475,2018,Não,Sim,...,-,-,-,-,-,Sim,Outra,Sim,Sim,Sim
19,35,SP,SÃO PAULO,45973194,3 - Sudeste,Sim,68155,2023,Não,Sim,...,Não,Sim,Não,Não,Não,Sim,Em comitê ou comissão estadual específica,Sim,Sim,Sim
20,41,PR,PARANÁ,11824665,4 - Sul,Sim,10285,2014,Não,Sim,...,-,-,-,-,-,Sim,Na Controladoria ou Corregedoria estadual,Sim,Sim,Sim
21,42,SC,SANTA CATARINA,8058441,4 - Sul,Sim,1048,2012,Não,Sim,...,-,-,-,-,-,Sim,No departamento ou área de TecnoIogia da Infor...,Sim,Sim,Não
22,43,RS,RIO GRANDE DO SUL,11229915,4 - Sul,Sim,49111,2012,Sim,Sim,...,-,-,-,-,-,Sim,No departamento jurídico ou procuradoria estadual,Sim,Sim,Sim
23,50,MS,MATO GROSSO DO SUL,2901895,5 - Centro-Oeste,Sim,16352,2023,Não,Sim,...,-,-,-,-,-,Sim,No gabinete do(a) Governador(a),Não,Sim,Sim
24,51,MT,MATO GROSSO,3836399,5 - Centro-Oeste,Sim,806,2021,Não,Sim,...,-,-,-,-,-,Não,-,Não,Não,Não
25,52,GO,GOIÁS,7350483,5 - Centro-Oeste,Sim,18025,2013,Sim,Sim,...,Sim,Sim,Não,Não,Sim,Sim,Em comitê ou comissão estadual específica,Sim,Sim,Sim
26,53,DF,DISTRITO FEDERAL,2982818,5 - Centro-Oeste,Sim,4990,2012,Não,Sim,...,Não,Sim,Não,Não,Não,Sim,Outra,Sim,Sim,Sim

In [ ]:
df = df[['Cod UF','Egov01']]
df

    Cod UF        Egov01
0       11  Não informou
1       12           Sim
2       13           Sim
3       14           Sim
4       15           Sim
5       16           Sim
6       17           Sim
7       21           Sim
8       22           Sim
9       23           Sim
10      24           Sim
11      25           Sim
12      26           Sim
13      27           Sim
14      28           Sim
15      29           Sim
16      31           Sim
17      32           Sim
18      33           Sim
19      35           Sim
20      41           Sim
21      42           Sim
22      43           Sim
23      50           Sim
24      51           Sim
25      52           Sim
26      53           Sim

In [ ]:
cod_uf = pd.read_csv('/content/ESTADIC_2019 - Variáveis externas.csv', sep=',')[['UF','COD_UF']]

In [ ]:
x= cod_uf.pivot_table(columns=('UF','COD_UF'), aggfunc='size')

In [ ]:
cod_uf = pd.DataFrame(x).reset_index()[['UF','COD_UF']]

In [ ]:
df = df.merge(cod_uf, right_on='COD_UF',left_on='Cod UF')
df

    Cod UF        Egov01  UF  COD_UF
0       11  Não informou  RO      11
1       12           Sim  AC      12
2       13           Sim  AM      13
3       14           Sim  RR      14
4       15           Sim  PA      15
5       16           Sim  AP      16
6       17           Sim  TO      17
7       21           Sim  MA      21
8       22           Sim  PI      22
9       23           Sim  CE      23
10      24           Sim  RN      24
11      25           Sim  PB      25
12      26           Sim  PE      26
13      27           Sim  AL      27
14      28           Sim  SE      28
15      29           Sim  BA      29
16      31           Sim  MG      31
17      32           Sim  ES      32
18      33           Sim  RJ      33
19      35           Sim  SP      35
20      41           Sim  PR      41
21      42           Sim  SC      42
22      43           Sim  RS      43
23      50           Sim  MS      50
24      51           Sim  MT      51
25      52           Sim  GO      52
26      53           Sim  DF      53

In [ ]:
df = df.drop(['COD_UF'], axis=1)
df

    Cod UF        Egov01  UF
0       11  Não informou  RO
1       12           Sim  AC
2       13           Sim  AM
3       14           Sim  RR
4       15           Sim  PA
5       16           Sim  AP
6       17           Sim  TO
7       21           Sim  MA
8       22           Sim  PI
9       23           Sim  CE
10      24           Sim  RN
11      25           Sim  PB
12      26           Sim  PE
13      27           Sim  AL
14      28           Sim  SE
15      29           Sim  BA
16      31           Sim  MG
17      32           Sim  ES
18      33           Sim  RJ
19      35           Sim  SP
20      41           Sim  PR
21      42           Sim  SC
22      43           Sim  RS
23      50           Sim  MS
24      51           Sim  MT
25      52           Sim  GO
26      53           Sim  DF

In [ ]:
df['ano']=2024

In [ ]:
df.columns

Index(['Cod UF', 'Egov01', 'UF', 'ano'], dtype='object')

In [ ]:
df = df.rename(columns={'Cod UF': 'cod_uf',
                        'UF':'sigla_uf',
                        'Egov01':'existencia_legislacao_LAI'})

In [ ]:
df = df[['ano','cod_uf','sigla_uf', 'existencia_legislacao_LAI']]

In [ ]:
df['existencia_legislacao_LAI'].unique()

array(['Não informou', 'Sim'], dtype=object)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ano                        27 non-null     int64
 1   cod_uf                     27 non-null     int64
 2   sigla_uf                   27 non-null     object
 3   existencia_legislacao_LAI  27 non-null     object
dtypes: int64(2), object(2)
memory usage: 996.0+ bytes

In [ ]:
df

     ano  cod_uf sigla_uf existencia_legislacao_LAI
0   2024      11       RO              Não informou
1   2024      12       AC                       Sim
2   2024      13       AM                       Sim
3   2024      14       RR                       Sim
4   2024      15       PA                       Sim
5   2024      16       AP                       Sim
6   2024      17       TO                       Sim
7   2024      21       MA                       Sim
8   2024      22       PI                       Sim
9   2024      23       CE                       Sim
10  2024      24       RN                       Sim
11  2024      25       PB                       Sim
12  2024      26       PE                       Sim
13  2024      27       AL                       Sim
14  2024      28       SE                       Sim
15  2024      29       BA                       Sim
16  2024      31       MG                       Sim
17  2024      32       ES                       Sim
18  2024      33       RJ                       Sim
19  2024      35       SP                       Sim
20  2024      41       PR                       Sim
21  2024      42       SC                       Sim
22  2024      43       RS                       Sim
23  2024      50       MS                       Sim
24  2024      51       MT                       Sim
25  2024      52       GO                       Sim
26  2024      53       DF                       Sim

# Consumindo o ano de 2019 através do GBQ

In [ ]:


query = """SELECT * FROM `repositoriodedadosgpsp.participacao_transparencia.ESTADIC_acesso_informacao_LAI` WHERE ano = 2019"""
# Execute the query using pandas_gbq.read_gbq and load the result into a pandas DataFrame called 'df'.
# The 'project_id' specifies the Google Cloud Project to use.
df_2019 = pandas_gbq.read_gbq(query, project_id='repositoriodedadosgpsp')

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

Downloading: 100%|██████████|

In [ ]:
df_2019

     ano  cod_uf sigla_uf existencia_legislacao_LAI
0   2019      11       RO                       Sim
1   2019      12       AC                       Sim
2   2019      13       AM                       Sim
3   2019      14       RR                       Sim
4   2019      15       PA                       Sim
5   2019      16       AP                       Sim
6   2019      17       TO                       Sim
7   2019      21       MA                       Sim
8   2019      22       PI                       Sim
9   2019      23       CE                       Sim
10  2019      24       RN                       Sim
11  2019      25       PB                       Sim
12  2019      26       PE                       Sim
13  2019      27       AL                       Sim
14  2019      28       SE                       Sim
15  2019      29       BA                       Sim
16  2019      31       MG                       Sim
17  2019      32       ES                       Sim
18  2019      33       RJ                       Sim
19  2019      35       SP                       Sim
20  2019      41       PR                       Sim
21  2019      42       SC                       Sim
22  2019      43       RS                       Sim
23  2019      50       MS                       Sim
24  2019      51       MT                       Sim
25  2019      52       GO                       Sim
26  2019      53       DF                       Sim

In [ ]:
df_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ano                        27 non-null     Int64
 1   cod_uf                     27 non-null     Int64
 2   sigla_uf                   27 non-null     object
 3   existencia_legislacao_LAI  27 non-null     object
dtypes: Int64(2), object(2)
memory usage: 1.0+ KB

In [ ]:
df_2019['ano'].unique()

<IntegerArray>
[2019]
Length: 1, dtype: Int64

# Agregando os anos

In [ ]:
df_final = pd.concat([df, df_2019], ignore_index=True)

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ano                        54 non-null     Int64
 1   cod_uf                     54 non-null     Int64
 2   sigla_uf                   54 non-null     object
 3   existencia_legislacao_LAI  54 non-null     object
dtypes: Int64(2), object(2)
memory usage: 1.9+ KB

In [ ]:
df_final['ano'].unique()

<IntegerArray>
[2024, 2019]
Length: 2, dtype: Int64

Subindo para o GBQ

In [ ]:
# Import the bigquery library from google.cloud
from google.cloud import bigquery

# Initialize the BigQuery client, specifying the Google Cloud project ID.
# This client object is used to interact with the BigQuery API.
client = bigquery.Client(project='repositoriodedadosgpsp')

In [ ]:
# Import the bigquery library from google.cloud
from google.cloud import bigquery

# Initialize the BigQuery client, specifying the Google Cloud project ID.
# This client object is used to interact with the BigQuery API.
client = bigquery.Client(project='repositoriodedadosgpsp')
dataset_ref = client.dataset('participacao_transparencia')

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

In [ ]:
schema=[bigquery.SchemaField('ano','INTEGER',description='Ano de referência da observação'),
    bigquery.SchemaField('cod_uf','INTEGER',description='Código do IBGE da UF'),
    bigquery.SchemaField('sigla_uf','STRING',description='Sigla da Unidade da Federação'),
    bigquery.SchemaField('existencia_legislacao_LAI','STRING',description='Existência de legislação estadual para garantir direito de acesso à informação pública em conformidade com a Lei de Acesso à Informação'),
]

In [ ]:
table_ref = dataset_ref.table('ESTADIC_acesso_informacao_LAI_v1')
job_config = bigquery.LoadJobConfig(schema=schema)
job = client.load_table_from_dataframe(df_final,table_ref, job_config=job_config)
job.result()

LoadJob<project=repositoriodedadosgpsp, location=US, id=b7db3d5c-bff3-4581-a37e-ed15e2dca406>