In [ ]:
!pip install gcloud
!gcloud auth application-default login

Collecting gcloud
  Downloading gcloud-0.18.3.tar.gz (454 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 454.4/454.4 kB 4.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: httplib2>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from gcloud) (0.32.0)
Requirement already satisfied: googleapis-common-protos in /usr/local/lib/python3.12/dist-packages (from gcloud) (1.75.0)
Requirement already satisfied: oauth2client>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from gcloud) (4.1.3)
Requirement already satisfied: protobuf!=3.0.0.b2.post1,>=3.0.0b2 in /usr/local/lib/python3.12/dist-packages (from gcloud) (5.29.6)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from gcloud) (1.17.0)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2>=0.9.1->gcloud) (3.3.2)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (0.6.4)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (0.4.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (4.9.1)
Building wheels for collected packages: gcloud
  Building wheel for gcloud (setup.py) ... done
  Created wheel for gcloud: filename=gcloud-0.18.3-py3-none-any.whl size=602927 sha256=a61d2f3be530d309c7f67910300c0a3569ef19b026587c55e8b0d9ff28999797
  Stored in directory: /root/.cache/pip/wheels/2a/62/75/3d74209bfebb8805823ae74afa28653aa1ea76d8b5a9d741ff
Successfully built gcloud
Installing collected packages: gcloud
Successfully installed gcloud-0.18.3
Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fapplicationdefaultauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=1yaDBxrAOmf3j7NjpN6gh1fxjTUp9P&prompt=consent&token_usage=remote&access_type=offline&code_challenge=P1yupQucrZBSSpJ7LpnX02AGJKqmI-fqF8oqlrQspUM&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0AXEQxICmeBxaGXE1eeeNkx_j0o5aIXMgnJHFhPat9UiRetS2Hq0FTQSHSpk8OvRUHyV-cQ

Credentials saved to file: [/content/.config/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.


To take a quick anonymous survey, run:
  $ gcloud survey

In [ ]:
import pandas as pd
import numpy as np
import os
import pandas_gbq
from google.cloud import bigquery
import glob
import openpyxl

# Ano de 2024

In [ ]:
df = pd.read_excel('/content/Base_Estadic_2024.xlsx', sheet_name='Informática e comunicação')
df

,Cod UF,Sigla UF,Nome UF,PopUF,Região,Etic011,Etic012,Etic013,Etic014,Etic015,...,Etic347,Etic348,Etic35,Etic361,Etic362,Etic363,Etic364,Etic365,Etic366,Etic367
0,11,RO,RONDÔNIA,1746227,1 - Norte,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Não,Não,Não,Não
1,12,AC,ACRE,880631,1 - Norte,Não,Não,Sim,Não,Sim,...,Não,Não,Sim,Sim,Não,Não,Não,Não,Não,Não
2,13,AM,AMAZONAS,4281209,1 - Norte,Não,Não,Sim,Sim,Não,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
3,14,RR,RORAIMA,716793,1 - Norte,Sim,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
4,15,PA,PARÁ,8664306,1 - Norte,Não,Não,Não,Sim,Sim,...,Não,Não,Sim,Sim,Sim,Não,Sim,Não,Não,Não
5,16,AP,AMAPÁ,802837,1 - Norte,Sim,Sim,Sim,Não,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Sim,Não,Não,Não
6,17,TO,TOCANTINS,1577342,1 - Norte,Não,Não,Sim,Não,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Não,Não,Não,Não
7,21,MA,MARANHÃO,7010960,2 - Nordeste,Não,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
8,22,PI,PIAUÍ,3375646,2 - Nordeste,Sim,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Sim,Não,Não,Não
9,23,CE,CEARÁ,9233656,2 - Nordeste,Sim,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Sim,Não,Sim,Não,Não,Não
10,24,RN,RIO GRANDE DO NORTE,3446071,2 - Nordeste,Não,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
11,25,PB,PARAÍBA,4145040,2 - Nordeste,Não,Não,Não,Sim,Não,...,-,-,Sim,Não,Não,Não,Não,Sim,Não,Não
12,26,PE,PERNAMBUCO,9539029,2 - Nordeste,Não,Não,Sim,Não,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Sim,Não,Não,Não
13,27,AL,ALAGOAS,3220104,2 - Nordeste,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Não,Não,Não,Não,Não
14,28,SE,SERGIPE,2291077,2 - Nordeste,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Não,Sim,Sim,Sim,Não,Não,Não
15,29,BA,BAHIA,14850513,2 - Nordeste,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
16,31,MG,MINAS GERAIS,21322691,3 - Sudeste,Não,Não,Sim,Sim,Não,...,Não,Não,Sim,Sim,Não,Sim,Não,Não,Não,Não
17,32,ES,ESPÍRITO SANTO,4102129,3 - Sudeste,Não,Não,Sim,Não,Sim,...,Não,Não,Sim,Sim,Sim,Não,Não,Não,Não,Não
18,33,RJ,RIO DE JANEIRO,17219679,3 - Sudeste,Sim,Não,Sim,Não,Não,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
19,35,SP,SÃO PAULO,45973194,3 - Sudeste,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Sim,Não,Não,Não
20,41,PR,PARANÁ,11824665,4 - Sul,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Não,Não,Não,Não
21,42,SC,SANTA CATARINA,8058441,4 - Sul,Não,Não,Sim,Não,Sim,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
22,43,RS,RIO GRANDE DO SUL,11229915,4 - Sul,Sim,Não,Não,Não,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Não,Não,Não,Não
23,50,MS,MATO GROSSO DO SUL,2901895,5 - Centro-Oeste,Sim,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Não,Não,Não,Não
24,51,MT,MATO GROSSO,3836399,5 - Centro-Oeste,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Não,Não,Não,Não
25,52,GO,GOIÁS,7350483,5 - Centro-Oeste,Não,Não,Sim,Sim,Não,...,Não,Não,Sim,Sim,Não,Sim,Não,Não,Não,Não
26,53,DF,DISTRITO FEDERAL,2982818,5 - Centro-Oeste,Sim,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Sim,Não,Não,Não

In [ ]:
df = df[['Cod UF','Etic231', 'Etic232', 'Etic234', 'Etic233']]

In [ ]:
cod_uf = pd.read_csv('/content/ESTADIC_2019 - Variáveis externas.csv', sep=',')[['UF','COD_UF']]

In [ ]:
cod_uf = cod_uf.rename(columns={'COD_UF':'Cod UF'})

In [ ]:
x= cod_uf.pivot_table(columns=('UF','Cod UF'), aggfunc='size')

In [ ]:
cod_uf = pd.DataFrame(x).reset_index()[['UF','Cod UF']]

In [ ]:
df = df.merge(cod_uf, right_on='Cod UF',left_on='Cod UF')
df

    Cod UF Etic231 Etic232 Etic234 Etic233  UF
0       11     Sim     Não     Não     Não  RO
1       12     Sim     Sim     Não     Não  AC
2       13     Sim     Não     Sim     Não  AM
3       14     Não     Sim     Não     Sim  RR
4       15     Sim     Não     Não     Não  PA
5       16     Sim     Sim     Sim     Sim  AP
6       17     Não     Não     Não     Não  TO
7       21     Sim     Sim     Sim     Sim  MA
8       22     Sim     Sim     Sim     Sim  PI
9       23     Sim     Não     Não     Sim  CE
10      24     Sim     Sim     Sim     Sim  RN
11      25     Não     Não     Não     Não  PB
12      26     Sim     Não     Sim     Não  PE
13      27     Sim     Sim     Não     Sim  AL
14      28     Sim     Sim     Sim     Sim  SE
15      29     Sim     Não     Não     Não  BA
16      31     Sim     Não     Não     Sim  MG
17      32     Sim     Não     Não     Sim  ES
18      33     Não     Não     Não     Sim  RJ
19      35     Sim     Sim     Sim     Sim  SP
20      41     Não     Não     Sim     Não  PR
21      42     Não     Não     Não     Não  SC
22      43     Sim     Não     Não     Sim  RS
23      50     Sim     Sim     Sim     Sim  MS
24      51     Sim     Não     Sim     Não  MT
25      52     Sim     Não     Não     Não  GO
26      53     Sim     Sim     Sim     Sim  DF

In [ ]:
df.columns

Index(['Cod UF', 'Etic231', 'Etic232', 'Etic234', 'Etic233', 'UF'], dtype='object')

In [ ]:
df['ano']=2024

In [ ]:
df = df.rename(columns={'Cod UF': 'cod_uf',
                        'UF':'sigla_uf',
                        'Etic231':'consulta_publica_cidadaos',
                        'Etic232':'grupos_discussao_foruns',
                        'Etic234':'votacao_orientar_decisoes',
                        'Etic233':'enquete_interesse_governo_estadual'})

In [ ]:
df = df[['ano','cod_uf','sigla_uf', 'consulta_publica_cidadaos', 'grupos_discussao_foruns','votacao_orientar_decisoes', 'enquete_interesse_governo_estadual']]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ano                                 27 non-null     int64
 1   cod_uf                              27 non-null     int64
 2   sigla_uf                            27 non-null     object
 3   consulta_publica_cidadaos           27 non-null     object
 4   grupos_discussao_foruns             27 non-null     object
 5   votacao_orientar_decisoes           27 non-null     object
 6   enquete_interesse_governo_estadual  27 non-null     object
dtypes: int64(2), object(5)
memory usage: 1.6+ KB

In [ ]:
df['ano'].unique()

array([2024])

# Ano de 2024

In [ ]:
df = pd.read_excel('/content/Base_Estadic_2024.xlsx', sheet_name='Informática e comunicação')
df

,Cod UF,Sigla UF,Nome UF,PopUF,Região,Etic011,Etic012,Etic013,Etic014,Etic015,...,Etic347,Etic348,Etic35,Etic361,Etic362,Etic363,Etic364,Etic365,Etic366,Etic367
0,11,RO,RONDÔNIA,1746227,1 - Norte,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Não,Não,Não,Não
1,12,AC,ACRE,880631,1 - Norte,Não,Não,Sim,Não,Sim,...,Não,Não,Sim,Sim,Não,Não,Não,Não,Não,Não
2,13,AM,AMAZONAS,4281209,1 - Norte,Não,Não,Sim,Sim,Não,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
3,14,RR,RORAIMA,716793,1 - Norte,Sim,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
4,15,PA,PARÁ,8664306,1 - Norte,Não,Não,Não,Sim,Sim,...,Não,Não,Sim,Sim,Sim,Não,Sim,Não,Não,Não
5,16,AP,AMAPÁ,802837,1 - Norte,Sim,Sim,Sim,Não,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Sim,Não,Não,Não
6,17,TO,TOCANTINS,1577342,1 - Norte,Não,Não,Sim,Não,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Não,Não,Não,Não
7,21,MA,MARANHÃO,7010960,2 - Nordeste,Não,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
8,22,PI,PIAUÍ,3375646,2 - Nordeste,Sim,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Sim,Não,Não,Não
9,23,CE,CEARÁ,9233656,2 - Nordeste,Sim,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Sim,Não,Sim,Não,Não,Não
10,24,RN,RIO GRANDE DO NORTE,3446071,2 - Nordeste,Não,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
11,25,PB,PARAÍBA,4145040,2 - Nordeste,Não,Não,Não,Sim,Não,...,-,-,Sim,Não,Não,Não,Não,Sim,Não,Não
12,26,PE,PERNAMBUCO,9539029,2 - Nordeste,Não,Não,Sim,Não,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Sim,Não,Não,Não
13,27,AL,ALAGOAS,3220104,2 - Nordeste,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Não,Não,Não,Não,Não
14,28,SE,SERGIPE,2291077,2 - Nordeste,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Não,Sim,Sim,Sim,Não,Não,Não
15,29,BA,BAHIA,14850513,2 - Nordeste,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
16,31,MG,MINAS GERAIS,21322691,3 - Sudeste,Não,Não,Sim,Sim,Não,...,Não,Não,Sim,Sim,Não,Sim,Não,Não,Não,Não
17,32,ES,ESPÍRITO SANTO,4102129,3 - Sudeste,Não,Não,Sim,Não,Sim,...,Não,Não,Sim,Sim,Sim,Não,Não,Não,Não,Não
18,33,RJ,RIO DE JANEIRO,17219679,3 - Sudeste,Sim,Não,Sim,Não,Não,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
19,35,SP,SÃO PAULO,45973194,3 - Sudeste,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Sim,Não,Não,Não
20,41,PR,PARANÁ,11824665,4 - Sul,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Não,Não,Não,Não
21,42,SC,SANTA CATARINA,8058441,4 - Sul,Não,Não,Sim,Não,Sim,...,Não,Não,Sim,Sim,Não,Sim,Sim,Não,Não,Não
22,43,RS,RIO GRANDE DO SUL,11229915,4 - Sul,Sim,Não,Não,Não,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Não,Não,Não,Não
23,50,MS,MATO GROSSO DO SUL,2901895,5 - Centro-Oeste,Sim,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Não,Não,Não,Não
24,51,MT,MATO GROSSO,3836399,5 - Centro-Oeste,Não,Não,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Não,Sim,Não,Não,Não,Não
25,52,GO,GOIÁS,7350483,5 - Centro-Oeste,Não,Não,Sim,Sim,Não,...,Não,Não,Sim,Sim,Não,Sim,Não,Não,Não,Não
26,53,DF,DISTRITO FEDERAL,2982818,5 - Centro-Oeste,Sim,Sim,Sim,Sim,Sim,...,Não,Não,Sim,Sim,Sim,Sim,Sim,Não,Não,Não

In [ ]:
df = df[['Cod UF','Etic231', 'Etic232', 'Etic234', 'Etic233']]

In [ ]:
cod_uf = pd.read_csv('/content/ESTADIC_2019 - Variáveis externas.csv', sep=',')[['UF','COD_UF']]

In [ ]:
cod_uf = cod_uf.rename(columns={'COD_UF':'Cod UF'})

In [ ]:
x= cod_uf.pivot_table(columns=('UF','Cod UF'), aggfunc='size')

In [ ]:
cod_uf = pd.DataFrame(x).reset_index()[['UF','Cod UF']]

In [ ]:
df = df.merge(cod_uf, right_on='Cod UF',left_on='Cod UF')
df

    Cod UF Etic231 Etic232 Etic234 Etic233  UF
0       11     Sim     Não     Não     Não  RO
1       12     Sim     Sim     Não     Não  AC
2       13     Sim     Não     Sim     Não  AM
3       14     Não     Sim     Não     Sim  RR
4       15     Sim     Não     Não     Não  PA
5       16     Sim     Sim     Sim     Sim  AP
6       17     Não     Não     Não     Não  TO
7       21     Sim     Sim     Sim     Sim  MA
8       22     Sim     Sim     Sim     Sim  PI
9       23     Sim     Não     Não     Sim  CE
10      24     Sim     Sim     Sim     Sim  RN
11      25     Não     Não     Não     Não  PB
12      26     Sim     Não     Sim     Não  PE
13      27     Sim     Sim     Não     Sim  AL
14      28     Sim     Sim     Sim     Sim  SE
15      29     Sim     Não     Não     Não  BA
16      31     Sim     Não     Não     Sim  MG
17      32     Sim     Não     Não     Sim  ES
18      33     Não     Não     Não     Sim  RJ
19      35     Sim     Sim     Sim     Sim  SP
20      41     Não     Não     Sim     Não  PR
21      42     Não     Não     Não     Não  SC
22      43     Sim     Não     Não     Sim  RS
23      50     Sim     Sim     Sim     Sim  MS
24      51     Sim     Não     Sim     Não  MT
25      52     Sim     Não     Não     Não  GO
26      53     Sim     Sim     Sim     Sim  DF

In [ ]:
df.columns

Index(['Cod UF', 'Etic231', 'Etic232', 'Etic234', 'Etic233', 'UF'], dtype='object')

In [ ]:
df['ano']=2024

In [ ]:
df = df.rename(columns={'Cod UF': 'cod_uf',
                        'UF':'sigla_uf',
                        'Etic231':'consulta_publica_cidadaos',
                        'Etic232':'grupos_discussao_foruns',
                        'Etic234':'votacao_orientar_decisoes',
                        'Etic233':'enquete_interesse_governo_estadual'})

In [ ]:
df = df[['ano','cod_uf','sigla_uf', 'consulta_publica_cidadaos', 'grupos_discussao_foruns','votacao_orientar_decisoes', 'enquete_interesse_governo_estadual']]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ano                                 27 non-null     int64
 1   cod_uf                              27 non-null     int64
 2   sigla_uf                            27 non-null     object
 3   consulta_publica_cidadaos           27 non-null     object
 4   grupos_discussao_foruns             27 non-null     object
 5   votacao_orientar_decisoes           27 non-null     object
 6   enquete_interesse_governo_estadual  27 non-null     object
dtypes: int64(2), object(5)
memory usage: 1.6+ KB

In [ ]:
df['ano'].unique()

array([2024])

# Consumindo o ano de 2019 através do GBQ

In [ ]:


query = """SELECT * FROM `repositoriodedadosgpsp.participacao_transparencia.ESTADIC_formas_participacao_cidadao_internet` WHERE ano = 2019"""
# Execute the query using pandas_gbq.read_gbq and load the result into a pandas DataFrame called 'df'.
# The 'project_id' specifies the Google Cloud Project to use.
df_2019 = pandas_gbq.read_gbq(query, project_id='repositoriodedadosgpsp')

Downloading: 100%|██████████|

In [ ]:
df_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ano                                 27 non-null     Int64
 1   cod_uf                              27 non-null     Int64
 2   sigla_uf                            27 non-null     object
 3   consulta_publica_cidadaos           27 non-null     object
 4   grupos_discussao_foruns             27 non-null     object
 5   votacao_orientar_decisoes           27 non-null     object
 6   enquete_interesse_governo_estadual  27 non-null     object
dtypes: Int64(2), object(5)
memory usage: 1.7+ KB

In [ ]:
df_2019['ano'].unique()

<IntegerArray>
[2019]
Length: 1, dtype: Int64

# Agregando os anos

In [ ]:
df_final = pd.concat([df, df_2019], ignore_index=True)

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 7 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ano                                 54 non-null     Int64
 1   cod_uf                              54 non-null     Int64
 2   sigla_uf                            54 non-null     object
 3   consulta_publica_cidadaos           54 non-null     object
 4   grupos_discussao_foruns             54 non-null     object
 5   votacao_orientar_decisoes           54 non-null     object
 6   enquete_interesse_governo_estadual  54 non-null     object
dtypes: Int64(2), object(5)
memory usage: 3.2+ KB

In [ ]:
df_final['ano'].unique()

<IntegerArray>
[2024, 2019]
Length: 2, dtype: Int64

In [ ]:
df_final.head(54)

,ano,cod_uf,sigla_uf,consulta_publica_cidadaos,grupos_discussao_foruns,votacao_orientar_decisoes,enquete_interesse_governo_estadual
0,2024,11,RO,Sim,Não,Não,Não
1,2024,12,AC,Sim,Sim,Não,Não
2,2024,13,AM,Sim,Não,Sim,Não
3,2024,14,RR,Não,Sim,Não,Sim
4,2024,15,PA,Sim,Não,Não,Não
5,2024,16,AP,Sim,Sim,Sim,Sim
6,2024,17,TO,Não,Não,Não,Não
7,2024,21,MA,Sim,Sim,Sim,Sim
8,2024,22,PI,Sim,Sim,Sim,Sim
9,2024,23,CE,Sim,Não,Não,Sim
10,2024,24,RN,Sim,Sim,Sim,Sim
11,2024,25,PB,Não,Não,Não,Não
12,2024,26,PE,Sim,Não,Sim,Não
13,2024,27,AL,Sim,Sim,Não,Sim
14,2024,28,SE,Sim,Sim,Sim,Sim
15,2024,29,BA,Sim,Não,Não,Não
16,2024,31,MG,Sim,Não,Não,Sim
17,2024,32,ES,Sim,Não,Não,Sim
18,2024,33,RJ,Não,Não,Não,Sim
19,2024,35,SP,Sim,Sim,Sim,Sim
20,2024,41,PR,Não,Não,Sim,Não
21,2024,42,SC,Não,Não,Não,Não
22,2024,43,RS,Sim,Não,Não,Sim
23,2024,50,MS,Sim,Sim,Sim,Sim
24,2024,51,MT,Sim,Não,Sim,Não
25,2024,52,GO,Sim,Não,Não,Não
26,2024,53,DF,Sim,Sim,Sim,Sim
27,2019,17,TO,Sim,Sim,Sim,Sim
28,2019,21,MA,Sim,Não,Sim,Sim
29,2019,24,RN,Sim,Não,Não,Sim
30,2019,25,PB,Sim,Sim,Sim,Sim
31,2019,27,AL,Sim,Sim,Sim,Sim
32,2019,31,MG,Sim,Sim,Não,Sim
33,2019,50,MS,Sim,Não,Sim,Sim
34,2019,53,DF,Sim,Sim,Sim,Sim
35,2019,11,RO,Sim,Não,Sim,Não
36,2019,15,PA,Sim,Não,Não,Não
37,2019,26,PE,Sim,Não,Sim,Não
38,2019,32,ES,Sim,Não,Não,Não
39,2019,43,RS,Sim,Sim,Sim,Não
40,2019,16,AP,Não,Não,Não,Sim
41,2019,28,SE,Não,Sim,Sim,Sim
42,2019,29,BA,Não,Sim,Não,Sim
43,2019,51,MT,Não,Sim,Não,Sim
44,2019,12,AC,Não,Não,Não,Não
45,2019,13,AM,Não,Não,Não,Não
46,2019,14,RR,Não,Não,Não,Não
47,2019,22,PI,Não,Não,Não,Não
48,2019,23,CE,Não,Não,Não,Não
49,2019,33,RJ,Não,Não,Não,Não
50,2019,35,SP,Não,Não,Não,Não
51,2019,41,PR,Não,Não,Não,Não
52,2019,42,SC,Não,Não,Não,Não
53,2019,52,GO,Não,Não,Não,Não

Subindo para o GBQ

In [ ]:
# Import the bigquery library from google.cloud
from google.cloud import bigquery

# Initialize the BigQuery client, specifying the Google Cloud project ID.
# This client object is used to interact with the BigQuery API.
client = bigquery.Client(project='repositoriodedadosgpsp')
dataset_ref = client.dataset('participacao_transparencia')

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

In [ ]:
schema=[bigquery.SchemaField('ano','INTEGER',description='Ano de referência da observação'),
    bigquery.SchemaField('cod_uf','INTEGER',description='Código do IBGE da UF'),
    bigquery.SchemaField('sigla_uf','STRING',description='Sigla da Unidade da Federação'),
    bigquery.SchemaField('consulta_publica_cidadaos','STRING',description='Consulta pública on line para que cidadãos possam enviar'),
    bigquery.SchemaField('grupos_discussao_foruns','STRING',description='Grupos de discussão como fóruns ou comunidades pela internet'),
    bigquery.SchemaField('votacao_orientar_decisoes','STRING',description='Votação on line para orientar a tomada de decisão sobre  políticas públicas, orçamento, etc.'),
    bigquery.SchemaField('enquete_interesse_governo_estadual','STRING',description='Enquete on line sobre assuntos de interesse do governo estadual'),
]

In [ ]:
table_ref = dataset_ref.table('ESTADIC_formas_participacao_cidadao_internet_v2')
job_config = bigquery.LoadJobConfig(schema=schema)
job = client.load_table_from_dataframe(df_final,table_ref, job_config=job_config)
job.result()

LoadJob<project=repositoriodedadosgpsp, location=US, id=f30cab06-5155-4550-850c-6e1475129c66>