# Dependendências

In [1]:
# Install required Google Cloud packages (commented out as these are typically one-time setup commands)
#!pip install gcloud
#!gcloud auth application-default login

# Import necessary Python libraries
import pandas as pd                # Data manipulation and analysis
import numpy as np                 # Numerical computing
import time                        # Time-related functions
import os                          # Operating system interfaces
import pandas_gbq                  # Pandas integration with BigQuery
from google.cloud import bigquery  # BigQuery client library
import glob                        # File path pattern matching
import openpyxl                    # Excel file handling
import csv                         # CSV file handling
import re                          # Regular expressions

# Note: The actual imports remain exactly as in the original code

c:\Users\ana.sales_republica\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

# Tratamentos

In [15]:
# Define the SQL query to be executed in Google BigQuery.
# This query selects all columns from the `CNES_profissionais_saude_ocupacao_publico` table,
# ordering the results by the 'ano' column in descending order.
query = """SELECT ano, tipo_ocupacao,sigla_uf,id_municipio, sum(n_profissionais) as quantidade_vinculos  
        FROM `repositoriodedadosgpsp.Datalake.CNES_vinculo_saude_tipo_ocupacao` where publico_privado='Público' group by ano, tipo_ocupacao, sigla_uf,id_municipio"""
# Execute the query using pandas_gbq.read_gbq and load the result into a pandas DataFrame called 'df'.
# The 'project_id' specifies the Google Cloud Project to use.
df= pandas_gbq.read_gbq(query, project_id='repositoriodedadosgpsp')

Downloading: 100%|██████████|

In [3]:
df

,ano,tipo_ocupacao,sigla_uf,id_municipio,quantidade_vinculos,tipo_2
79,2025,Psicólogos e psicanalistas,RR,1400407,4,Psicólogos e psicanalistas
137,2023,Psicólogos e psicanalistas,AP,1600279,12,Psicólogos e psicanalistas
142,2023,Psicólogos e psicanalistas,AP,1600253,1,Psicólogos e psicanalistas
179,2020,Psicólogos e psicanalistas,RR,1400506,1,Psicólogos e psicanalistas
218,2019,Psicólogos e psicanalistas,AP,1600600,21,Psicólogos e psicanalistas
...,...,...,...,...,...,...
2044061,2022,Psicólogos e psicanalistas,TO,1709005,1,Psicólogos e psicanalistas
2044099,2018,Psicólogos e psicanalistas,TO,1711100,1,Psicólogos e psicanalistas
2044103,2018,Psicólogos e psicanalistas,TO,1711803,1,Psicólogos e psicanalistas
2044116,2018,Psicólogos e psicanalistas,TO,1702307,1,Psicólogos e psicanalistas
2044125,2018,Psicólogos e psicanalistas,TO,1718709,1,Psicólogos e psicanalistas

In [16]:
df['tipo_2'] = np.where(df['tipo_ocupacao'].str.contains('Psicólogos e psicanalistas'),'Psicólogos e psicanalistas',df['tipo_ocupacao'])

In [ ]:
df = df[(df['tipo_2']=='Psicólogos e psicanalistas') & (df['ano']>2017)]

In [18]:
df['tipo_2'] = np.where(df['tipo_ocupacao'].str.contains('Psicólogos e psicanalistas'),'Psicólogos e psicanalistas',df['tipo_ocupacao'])

# Filter the DataFrame 'df'.
# It keeps only the rows where the 'tipo_2' column is 'Psicólogos e psicanalistas' AND the 'ano' is greater than 2017.
df = df[(df['tipo_2']=='Psicólogos e psicanalistas') & (df['ano']>2017)]

In [21]:
df

,ano,tipo_ocupacao,sigla_uf,id_municipio,quantidade_vinculos,tipo_2
79,2025,Psicólogos e psicanalistas,RR,1400407.0,4,Psicólogos e psicanalistas
137,2023,Psicólogos e psicanalistas,AP,1600279.0,12,Psicólogos e psicanalistas
142,2023,Psicólogos e psicanalistas,AP,1600253.0,1,Psicólogos e psicanalistas
179,2020,Psicólogos e psicanalistas,RR,1400506.0,1,Psicólogos e psicanalistas
218,2019,Psicólogos e psicanalistas,AP,1600600.0,21,Psicólogos e psicanalistas
...,...,...,...,...,...,...
2044061,2022,Psicólogos e psicanalistas,TO,1709005.0,1,Psicólogos e psicanalistas
2044099,2018,Psicólogos e psicanalistas,TO,1711100.0,1,Psicólogos e psicanalistas
2044103,2018,Psicólogos e psicanalistas,TO,1711803.0,1,Psicólogos e psicanalistas
2044116,2018,Psicólogos e psicanalistas,TO,1702307.0,1,Psicólogos e psicanalistas
2044125,2018,Psicólogos e psicanalistas,TO,1718709.0,1,Psicólogos e psicanalistas

In [22]:
pop = pd.read_excel(
    r"G:\Drives compartilhados\República.org\4. Equipes\Dados e Comunicação\DADOS E CONHECIMENTO\415 - Repositório de Dados\Repositório Local\CNES\POP2022_Municipios_20230622.xlsx")
pop

      UF  COD. UF  id_municipio      NOME DO MUNICÍPIO POPULAÇÃO
0     RO       11            15  Alta Floresta D'Oeste     21558
1     RO       11            23              Ariquemes    100896
2     RO       11            31                 Cabixi      5107
3     RO       11            49                 Cacoal     92202
4     RO       11            56             Cerejeiras     15237
...   ..      ...           ...                    ...       ...
5565  GO       52         22005             Vianópolis     14046
5566  GO       52         22054         Vicentinópolis      8776
5567  GO       52         22203               Vila Boa      3686
5568  GO       52         22302          Vila Propício      5646
5569  DF       53           108               Brasília   2923369

[5570 rows x 5 columns]

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42367 entries, 0 to 42366
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ano                  42367 non-null  Int64
 1   sigla_uf             42367 non-null  object
 2   id_municipio         42367 non-null  float64
 3   tipo_2               42367 non-null  object
 4   quantidade_vinculos  42367 non-null  Int64
dtypes: Int64(2), float64(1), object(2)
memory usage: 1.7+ MB

In [ ]:
df['id_municipio'] = pd.to_numeric(df['id_municipio'])

In [25]:
x=df.pivot_table(index=['ano','sigla_uf','id_municipio','tipo_2'], values='quantidade_vinculos',aggfunc=np.sum)
y = pd.DataFrame(x)
# Reset the index of DataFrame 'y' to turn the index levels into columns. The result is assigned back to 'df'.
df = y.reset_index()

C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_20136\2062207271.py:1: FutureWarning: The provided callable <function sum at 0x0000020D868CE2A0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  x=df.pivot_table(index=['ano','sigla_uf','id_municipio','tipo_2'], values='quantidade_vinculos',aggfunc=np.sum)

In [29]:
pop

      UF  COD. UF  id_municipio      NOME DO MUNICÍPIO POPULAÇÃO
0     RO       11            15  Alta Floresta D'Oeste     21558
1     RO       11            23              Ariquemes    100896
2     RO       11            31                 Cabixi      5107
3     RO       11            49                 Cacoal     92202
4     RO       11            56             Cerejeiras     15237
...   ..      ...           ...                    ...       ...
5565  GO       52         22005             Vianópolis     14046
5566  GO       52         22054         Vicentinópolis      8776
5567  GO       52         22203               Vila Boa      3686
5568  GO       52         22302          Vila Propício      5646
5569  DF       53           108               Brasília   2923369

[5570 rows x 5 columns]

In [27]:
df

,ano,sigla_uf,id_municipio,tipo_2,quantidade_vinculos
0,2018,AC,1200013.0,Psicólogos e psicanalistas,2
1,2018,AC,1200054.0,Psicólogos e psicanalistas,2
2,2018,AC,1200104.0,Psicólogos e psicanalistas,6
3,2018,AC,1200138.0,Psicólogos e psicanalistas,1
4,2018,AC,1200179.0,Psicólogos e psicanalistas,2
...,...,...,...,...,...
42362,2025,TO,1721109.0,Psicólogos e psicanalistas,2
42363,2025,TO,1721208.0,Psicólogos e psicanalistas,4
42364,2025,TO,1721307.0,Psicólogos e psicanalistas,2
42365,2025,TO,1722081.0,Psicólogos e psicanalistas,1
42366,2025,TO,1722107.0,Psicólogos e psicanalistas,2

In [28]:
df1= df.merge(pop[['UF','NOME DO MUNICÍPIO','id_municipio','POPULAÇÃO']], left_on='id_municipio',right_on='id_municipio').sort_values('quantidade_vinculos', ascending=False)
df1

Empty DataFrame
Columns: [ano, sigla_uf, id_municipio, tipo_2, quantidade_vinculos, UF, NOME DO MUNICÍPIO, POPULAÇÃO]
Index: []

In [11]:
# Create a new column 'tipo_2'.
# If the 'tipo_ocupacao' contains 'Psicólogos e psicanalistas', the value in 'tipo_2' becomes 'Psicólogos e psicanalistas'.
# Otherwise, it keeps the original 'tipo_ocupacao' value.
df['tipo_2'] = np.where(df['tipo_ocupacao'].str.contains('Psicólogos e psicanalistas'),'Psicólogos e psicanalistas',df['tipo_ocupacao'])

# Filter the DataFrame 'df'.
# It keeps only the rows where the 'tipo_2' column is 'Psicólogos e psicanalistas' AND the 'ano' is greater than 2017.
df = df[(df['tipo_2']=='Psicólogos e psicanalistas') & (df['ano']>2017)]

## Calling the population quantity.
# The line above is a comment in Portuguese.

# Read population data from a local CSV file named "Censo_previa_pop.csv" into a new DataFrame called 'pop'.
pop = pd.read_excel(
    r"G:\Drives compartilhados\República.org\4. Equipes\Dados e Comunicação\DADOS E CONHECIMENTO\415 - Repositório de Dados\Repositório Local\CNES\POP2022_Municipios_20230622.xlsx")

# Convert the 'id_municipio' column in the 'df' DataFrame to a numeric data type to ensure proper merging.
df['id_municipio'] = pd.to_numeric(df['id_municipio'])

# Create a pivot table 'x' from the 'df' DataFrame.
# This aggregates (sums) the 'quantidade_vinculos' (number of employment links)
# for each unique combination of 'ano', 'sigla_uf', 'id_municipio', and 'tipo_2'.
x=df.pivot_table(index=['ano','sigla_uf','id_municipio','tipo_2'], values='quantidade_vinculos',aggfunc=np.sum)

# Convert the pivot table 'x' into a DataFrame 'y'.
y = pd.DataFrame(x)

# Reset the index of DataFrame 'y' to turn the index levels into columns. The result is assigned back to 'df'.
df = y.reset_index()


# Merge the 'df' DataFrame with a selection of columns from the 'pop' DataFrame.
# The merge is performed on the 'id_municipio' column.
# The result is stored in a new DataFrame 'df1' and sorted by 'quantidade_vinculos' in descending order.
df1= df.merge(pop[['UF','NOME DO MUNICÍPIO','id_municipio','POPULAÇÃO']], left_on='id_municipio',right_on='id_municipio').sort_values('quantidade_vinculos', ascending=False)

# Calculate the rate of professionals per 1,000 people and create a new column 'taxa'.
# This is done by dividing the 'quantidade_vinculos' by the 'POPULAÇÃO' and multiplying by 1000.
df1['taxa'] = df1['quantidade_vinculos']/df1['POPULAÇÃO']*1000

## Rename columns
# The line above is a comment in Portuguese.

# Select a subset of columns from 'df1' and rename them for the final DataFrame structure.
# The result is assigned back to 'df'.
df = df1[['ano', 'sigla_uf', 'id_municipio', 'tipo_2', 'quantidade_vinculos',
        'NOME DO MUNICÍPIO', 'POPULAÇÃO', 'taxa']].rename(columns={'tipo_2':'tipo_ocupacao','UF':'sigla_uf', 'NOME DO MUNICÍPIO':'nome_municipio','POPULAÇÃO':'populacao_domiciliada' })

# Reorder the columns in the final DataFrame 'df' to a specific desired order.
df= df[['ano', 'sigla_uf', 'nome_municipio','id_municipio','populacao_domiciliada', 'tipo_ocupacao',
       'quantidade_vinculos',
       'taxa']]

C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_20136\874786456.py:23: FutureWarning: The provided callable <function sum at 0x0000020D868CE2A0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  x=df.pivot_table(index=['ano','sigla_uf','id_municipio','tipo_2'], values='quantidade_vinculos',aggfunc=np.sum)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ano                    0 non-null      Int64
 1   sigla_uf               0 non-null      object
 2   nome_municipio         0 non-null      object
 3   id_municipio           0 non-null      float64
 4   populacao_domiciliada  0 non-null      object
 5   tipo_ocupacao          0 non-null      object
 6   quantidade_vinculos    0 non-null      Int64
 7   taxa                   0 non-null      object
dtypes: Int64(2), float64(1), object(5)
memory usage: 132.0+ bytes

In [14]:
df

Empty DataFrame
Columns: [ano, sigla_uf, nome_municipio, id_municipio, populacao_domiciliada, tipo_ocupacao, quantidade_vinculos, taxa]
Index: []

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36535 entries, 4816 to 36514
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ano                    36535 non-null  Int64
 1   sigla_uf               36535 non-null  object
 2   nome_municipio         36535 non-null  object
 3   id_municipio           36535 non-null  int64
 4   populacao_domiciliada  36535 non-null  int64
 5   tipo_ocupacao          36535 non-null  object
 6   quantidade_vinculos    36535 non-null  Int64
 7   taxa                   36535 non-null  Float64
dtypes: Float64(1), Int64(2), int64(2), object(3)
memory usage: 2.6+ MB

Subindo para o GBQ

# Upload

In [ ]:
# Import the bigquery library from google.cloud
from google.cloud import bigquery

# Initialize the BigQuery client, specifying the Google Cloud project ID.
# This client object is the main entry point for interacting with the BigQuery API.
client = bigquery.Client(project='repositoriodedadosgpsp')

# Create a reference to the BigQuery dataset named 'perfil_remuneracao'.
# This object points to the dataset where the table will be created or updated.
dataset_ref = client.dataset('perfil_remuneracao')

# Define the schema for the destination BigQuery table.
# The schema is a list of SchemaField objects, where each object defines a column's:
# 1. Name (e.g., 'ano')
# 2. Data type (e.g., 'INTEGER')
# 3. Description (e.g., 'Ano de referencia da informacao')
schema=[bigquery.SchemaField('ano','INTEGER',description='Ano de referencia da informacao'),
 bigquery.SchemaField('sigla_uf','STRING',description='Sigla da Unidade da Federação.'),
 bigquery.SchemaField('nome_municipio','STRING',description='Nome do município da observação'),
 bigquery.SchemaField('id_municipio','FLOAT',description='Identificador do município pelo IBGE'),
 bigquery.SchemaField('populacao_domiciliada','FLOAT',description='População domiciliada (prévia do Censo 2022)'),
 bigquery.SchemaField('tipo_ocupacao','STRING',description='Qual a ocupação daquele vínculo'),
 bigquery.SchemaField('quantidade_vinculos','INTEGER',description='Quantidade de vinculos'),
 bigquery.SchemaField('taxa','FLOAT',description='Taxa de psicólogos e psicanalistas por 1000 habitantes')
 ]

# Create a reference to the target table within the dataset specified earlier.
# The table will be named 'CNES_psicologos_mil_habitantes_v2'.
table_ref = dataset_ref.table('CNES_psicologos_mil_habitantes_v2') # table name in the format SOURCE_intuitive_data_name

# Configure the load job by creating a LoadJobConfig object.
# Here, we specify the schema that BigQuery should use for the table. This ensures
# that the columns in BigQuery have the correct data types and descriptions.
job_config = bigquery.LoadJobConfig(schema=schema)

# Start the job to load data from the pandas DataFrame 'df' into the specified BigQuery table ('table_ref').
# The job is configured with the previously defined 'job_config'. This command sends the data to BigQuery.
job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)

# Wait for the load job to complete and retrieve its result.
# This line is blocking and will pause the script's execution until the data upload is finished.
# It's crucial for ensuring the data is fully loaded before the script ends or proceeds.
job.result()