In [ ]:
# Install required Google Cloud packages (commented out as these are typically one-time setup commands)
!pip install gcloud
!gcloud auth application-default login

# Import necessary Python libraries
import pandas as pd                # Data manipulation and analysis
import numpy as np                 # Numerical computing
import time                        # Time-related functions
import os                          # Operating system interfaces
import pandas_gbq                  # Pandas integration with BigQuery
from google.cloud import bigquery  # BigQuery client library
import glob                        # File path pattern matching
import openpyxl                    # Excel file handling
import csv                         # CSV file handling
import re                          # Regular expressions

# Note: The actual imports remain exactly as in the original code

Collecting gcloud
  Downloading gcloud-0.18.3.tar.gz (454 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 454.4/454.4 kB 2.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: httplib2>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from gcloud) (0.32.0)
Requirement already satisfied: googleapis-common-protos in /usr/local/lib/python3.12/dist-packages (from gcloud) (1.75.0)
Requirement already satisfied: oauth2client>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from gcloud) (4.1.3)
Requirement already satisfied: protobuf!=3.0.0.b2.post1,>=3.0.0b2 in /usr/local/lib/python3.12/dist-packages (from gcloud) (5.29.6)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from gcloud) (1.17.0)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2>=0.9.1->gcloud) (3.3.2)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (0.6.4)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (0.4.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (4.9.1)
Building wheels for collected packages: gcloud
  Building wheel for gcloud (setup.py) ... done
  Created wheel for gcloud: filename=gcloud-0.18.3-py3-none-any.whl size=602927 sha256=e48fd19055709cbf2968fb9cf55d967e757c770553f6f76f1087d503af388a77
  Stored in directory: /root/.cache/pip/wheels/2a/62/75/3d74209bfebb8805823ae74afa28653aa1ea76d8b5a9d741ff
Successfully built gcloud
Installing collected packages: gcloud
Successfully installed gcloud-0.18.3
Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fapplicationdefaultauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=IwrbMaw09aPDOsr8QeaK80TZAcldsw&prompt=consent&token_usage=remote&access_type=offline&code_challenge=DZplAKy6LgfCh-BHLuyJjkOtPo55BgFHg9H3az73QWE&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0AXEQxICuYnDOXRAxp2TGievdKv5eFyAuEGoGVYShT4XpqM1y2oVOpL_kYpwB0LFuiBHR6A

Credentials saved to file: [/content/.config/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.


To take a quick anonymous survey, run:
  $ gcloud survey

# Tratamento

In [ ]:
# Set Google Cloud project ID
project_id = "repositoriodedadosgpsp"

# SQL query to fetch all data from the ESTADIC_quantidade_vinculos_v1 table
query = """
SELECT * FROM `repositoriodedadosgpsp.perfil_remuneracao.ESTADIC_quantidade_vinculos_v3`
"""

In [ ]:
df = pandas_gbq.read_gbq(query, project_id=project_id)
df

Downloading: 100%|██████████|

      ano           tipo_vinculo sigla_uf  quantidade_vinculos
0    2024             Celetistas       AC                  532
1    2024             Celetistas       AL                    1
2    2024             Celetistas       AM                  286
3    2024             Celetistas       AP                    0
4    2024             Celetistas       BA                 2279
..    ...                    ...      ...                  ...
130  2024  Somente comissionados       RS                 2412
131  2024  Somente comissionados       SC                  789
132  2024  Somente comissionados       SE                 3108
133  2024  Somente comissionados       SP                 7305
134  2024  Somente comissionados       TO                32231

[135 rows x 4 columns]

In [ ]:
print(df.head())

    ano tipo_vinculo sigla_uf  quantidade_vinculos
0  2024   Celetistas       AC                  532
1  2024   Celetistas       AL                    1
2  2024   Celetistas       AM                  286
3  2024   Celetistas       AP                    0
4  2024   Celetistas       BA                 2279

In [ ]:
y = df.pivot_table(
    index={'sigla_uf'},  # Group by state abbreviation
    values='quantidade_vinculos',  # Aggregate employment numbers
    aggfunc=np.sum  # Sum all employment types
)

/tmp/ipykernel_3819/263602715.py:1: FutureWarning: The provided callable <function sum at 0x7da3c31fd3a0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  y = df.pivot_table(

In [ ]:
# Convert pivot table to DataFrame and reset index
y = pd.DataFrame(y)
total = y.reset_index()

In [ ]:
total = total.rename(columns={'quantidade_vinculos': 'total_estado'})

In [ ]:
# Merge totals back with original data
df1 = df.merge(
    total,
    right_on='sigla_uf',
    left_on='sigla_uf'
)

In [ ]:
df1[df1['sigla_uf'] == "RJ"]

      ano            tipo_vinculo sigla_uf  quantidade_vinculos  total_estado
18   2024              Celetistas       RJ                 3646        178216
45   2024             Estagiários       RJ                    0        178216
72   2024            Estatutários       RJ               155872        178216
99   2024  Sem vínculo permanente       RJ                 6671        178216
126  2024   Somente comissionados       RJ                12027        178216

In [ ]:
df = df1
df

      ano           tipo_vinculo sigla_uf  quantidade_vinculos  total_estado
0    2024             Celetistas       AC                  532         36545
1    2024             Celetistas       AL                    1         81267
2    2024             Celetistas       AM                  286         84629
3    2024             Celetistas       AP                    0         35683
4    2024             Celetistas       BA                 2279        151882
..    ...                    ...      ...                  ...           ...
130  2024  Somente comissionados       RS                 2412        127932
131  2024  Somente comissionados       SC                  789         96101
132  2024  Somente comissionados       SE                 3108         46162
133  2024  Somente comissionados       SP                 7305        553494
134  2024  Somente comissionados       TO                32231         63845

[135 rows x 5 columns]

# Agregando com os dados anteriores

In [ ]:


query = """SELECT * FROM `repositoriodedadosgpsp.perfil_remuneracao.ESTADIC_quantidade_vinculos_mapa`"""
# Execute the query using pandas_gbq.read_gbq and load the result into a pandas DataFrame called 'df'.
# The 'project_id' specifies the Google Cloud Project to use.
df_old = pandas_gbq.read_gbq(query, project_id='repositoriodedadosgpsp')

Downloading: 100%|██████████|

In [ ]:
df_final = pd.concat([df, df_old], ignore_index=True)

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405 entries, 0 to 404
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ano                  405 non-null    Int64
 1   tipo_vinculo         405 non-null    object
 2   sigla_uf             405 non-null    object
 3   quantidade_vinculos  405 non-null    Int64
 4   total_estado         405 non-null    Int64
dtypes: Int64(3), object(2)
memory usage: 17.1+ KB

# Upload

In [ ]:
# Define the BigQuery table schema with Portuguese descriptions
schema = [
    bigquery.SchemaField('ano', 'INTEGER', description='Ano de referencia da informacao'),
    bigquery.SchemaField('tipo_vinculo', 'STRING', description='Tipo de vinculo.'),
    bigquery.SchemaField('sigla_uf', 'STRING', description='Sigla da Unidade da Federação.'),
    bigquery.SchemaField('quantidade_vinculos', 'INTEGER', description='Quantidade de vinculos'),
    bigquery.SchemaField('total_estado', 'INTEGER', description='Total de vínculos daquela UF')
]

# Initialize BigQuery client connection
client = bigquery.Client(project='repositoriodedadosgpsp')

# Create reference to target dataset
dataset_ref = client.dataset('perfil_remuneracao')

# Create reference to target table with standardized naming convention:
# FONTE_algo_intuitivo_dado (ESTADIC_quantidade_vinculos_mapa_v2)
table_ref = dataset_ref.table('ESTADIC_quantidade_vinculos_mapa_v4')

# Configure the load job with our schema definition
job_config = bigquery.LoadJobConfig(
    schema=schema,
    # Optional parameters (commented out):
    # write_disposition="WRITE_TRUNCATE",  # Overwrites table if exists
    # create_disposition="CREATE_IF_NEEDED"  # Default behavior
)

# Execute the load job to upload DataFrame to BigQuery
job = client.load_table_from_dataframe(
    dataframe=df_final,
    destination=table_ref,
    job_config=job_config
)

# Wait for the job to complete
job.result()

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

LoadJob<project=repositoriodedadosgpsp, location=US, id=5330e441-2091-43e6-bd1e-312f6a5bceb5>