In [1]:
# Install required Google Cloud packages (commented out as these are typically one-time setup commands)
!pip install gcloud
!gcloud auth application-default login

# Import necessary Python libraries
import pandas as pd                # Data manipulation and analysis
import numpy as np                 # Numerical computing
import time                        # Time-related functions
import os                          # Operating system interfaces
import pandas_gbq                  # Pandas integration with BigQuery
from google.cloud import bigquery  # BigQuery client library
import glob                        # File path pattern matching
import openpyxl                    # Excel file handling
import csv                         # CSV file handling
import re                          # Regular expressions

# Note: The actual imports remain exactly as in the original code

Collecting gcloud
  Downloading gcloud-0.18.3.tar.gz (454 kB)
     ---------------------------------------- 0.0/454.4 kB ? eta -:--:--
     ----------------------------------- - 430.1/454.4 kB 13.5 MB/s eta 0:00:01
     -------------------------------------- 454.4/454.4 kB 7.0 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting httplib2>=0.9.1 (from gcloud)
  Obtaining dependency information for httplib2>=0.9.1 from https://files.pythonhosted.org/packages/8c/a2/0d269db0f6163be503775dc8b6a6fa15820cc9fdc866f6ba608d86b721f2/httplib2-0.31.0-py3-none-any.whl.metadata
  Downloading httplib2-0.31.0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: googleapis-common-protos in c:\users\ana.sales_republica\anaconda3\lib\site-packages (from gcloud) (1.60.0)
Collecting oauth2client>=2.0.1 (from gcloud)
  Obtaining dependency information for oauth2client>=2.0.1 from https://files.pythonhosted.org/packages/95/a9/4f25a14d23f0786b64875b91784607c2277eff25d48f915e39ff0cff505a/oauth2client-4.1.3-py2.py3-none-any.whl.metadata
  Downloading oauth2client-4.1.3-py2.py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: protobuf!=3.0.0.b2.post1,>=3.0.0b2 in c:\users\ana.sales_republica\anaconda3\lib\site-packages (from gcloud) (4.24.0)
Requirement already satisfied: six in c:\users\ana.sales_republica\appdata\roaming\python\python311\site-packages (from gcloud) (1.16.0)
Requirement already satisfied: pyparsing<4,>=3.0.4 in c:\users\ana.sales_republica\anaconda3\lib\site-packages (from httplib2>=0.9.1->gcloud) (3.0.9)
Requirement already satisfied: pyasn1>=0.1.7 in c:\users\ana.sales_republica\anaconda3\lib\site-packages (from oauth2client>=2.0.1->gcloud) (0.4.8)
Requirement already satisfied: pyasn1-modules>=0.0.5 in c:\users\ana.sales_republica\anaconda3\lib\site-packages (from oauth2client>=2.0.1->gcloud) (0.2.8)
Requirement already satisfied: rsa>=3.1.4 in c:\users\ana.sales_republica\anaconda3\lib\site-packages (from oauth2client>=2.0.1->gcloud) (4.9)
Downloading httplib2-0.31.0-py3-none-any.whl (91 kB)
   ---------------------------------------- 0.0/91.1 kB ? eta -:--:--
   ---------------------------------------- 91.1/91.1 kB 2.6 MB/s eta 0:00:00
Downloading oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)
   ---------------------------------------- 0.0/98.2 kB ? eta -:--:--
   ---------------------------------------- 98.2/98.2 kB 5.5 MB/s eta 0:00:00
Building wheels for collected packages: gcloud
  Building wheel for gcloud (setup.py): started
  Building wheel for gcloud (setup.py): finished with status 'done'
  Created wheel for gcloud: filename=gcloud-0.18.3-py3-none-any.whl size=602982 sha256=2ea94ba99ee6b725ac809f2d3081ecb2478f273c0e675550fe941bab1c1d91c8
  Stored in directory: c:\users\ana.sales_republica\appdata\local\pip\cache\wheels\3c\e8\d1\cb82a63f69083ea485de71d14248b8d145f1af46a41578be9c
Successfully built gcloud
Installing collected packages: httplib2, oauth2client, gcloud
Successfully installed gcloud-0.18.3 httplib2-0.31.0 oauth2client-4.1.3

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8085%2F&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=h9qL1fYJSNXpYRWSLPiXCLxcZZVLjz&access_type=offline&code_challenge=3jC9TK_-VMCBtlPjOrfRHukyl7jFHJkJsm54jnDC0hc&code_challenge_method=S256


Credentials saved to file: [C:\Users\ana.sales_republica\AppData\Roaming\gcloud\application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).

Quota project "repositoriodedadosgpsp" was added to ADC which can be used by Google client libraries for billing and quota. Note that some services may still bill the project owning the resource.
c:\Users\ana.sales_republica\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

# Tratamento

In [ ]:
# Set Google Cloud project ID
project_id = "repositoriodedadosgpsp"

# SQL query to fetch all data from the ESTADIC_quantidade_vinculos_v1 table
query = """
SELECT * FROM `repositoriodedadosgpsp.perfil_remuneracao.ESTADIC_quantidade_vinculos`
"""

In [5]:
df = pandas_gbq.read_gbq(query, project_id=project_id)
df

Downloading: 100%|██████████|

      ano           tipo_vinculo sigla_uf  quantidade_vinculos
0    2019             Celetistas       AC                  655
1    2019             Celetistas       AM                  377
2    2019             Celetistas       PA                 1711
3    2019             Celetistas       TO                  300
4    2019             Celetistas       MA                  628
..    ...                    ...      ...                  ...
535  2023  Somente comissionados       RS                 2479
536  2023  Somente comissionados       SC                  764
537  2023  Somente comissionados       SE                 2798
538  2023  Somente comissionados       SP                 7117
539  2023  Somente comissionados       TO                21476

[540 rows x 4 columns]

In [6]:
print(df.head())

    ano tipo_vinculo sigla_uf  quantidade_vinculos
0  2019   Celetistas       AC                  655
1  2019   Celetistas       AM                  377
2  2019   Celetistas       PA                 1711
3  2019   Celetistas       TO                  300
4  2019   Celetistas       MA                  628

In [8]:
y = df.pivot_table(
    index={'sigla_uf'},  # Group by state abbreviation
    values='quantidade_vinculos',  # Aggregate employment numbers
    aggfunc=np.sum  # Sum all employment types
)

C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_22804\263602715.py:1: FutureWarning: The provided callable <function sum at 0x0000025BA3B82480> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  y = df.pivot_table(

In [9]:
# Convert pivot table to DataFrame and reset index
y = pd.DataFrame(y)
total = y.reset_index()

In [ ]:
total = total.rename(columns={'quantidade_vinculos': 'total_estado'})

In [15]:
# Merge totals back with original data
df1 = df.merge(
    total,
    right_on='sigla_uf',
    left_on='sigla_uf'
)

In [14]:
df1[df1['sigla_uf'] == "RJ"]

      ano            tipo_vinculo sigla_uf  quantidade_vinculos  total_estado
13   2019              Celetistas       RJ                 5624        753788
33   2020              Celetistas       RJ                 4777        753788
57   2021              Celetistas       RJ                 4359        753788
142  2019             Estagiários       RJ                    0        753788
149  2020             Estagiários       RJ                    0        753788
156  2021             Estagiários       RJ                    0        753788
180  2019            Estatutários       RJ               182753        753788
206  2020            Estatutários       RJ               168590        753788
232  2021            Estatutários       RJ               164016        753788
261  2019   Somente comissionados       RJ                 8712        753788
285  2020   Somente comissionados       RJ                 9429        753788
310  2021   Somente comissionados       RJ                10003        753788
342  2019  Sem vínculo permanente       RJ                 5956        753788
367  2020  Sem vínculo permanente       RJ                 5029        753788
392  2021  Sem vínculo permanente       RJ                 5370        753788
423  2023              Celetistas       RJ                 3968        753788
450  2023             Estagiários       RJ                    0        753788
477  2023            Estatutários       RJ               156625        753788
504  2023  Sem vínculo permanente       RJ                 7676        753788
531  2023   Somente comissionados       RJ                10901        753788

In [16]:
df1.loc[df1['sigla_uf'] == 'RO', 'total_estado'] = 1

In [ ]:
df1[df1['sigla_uf'] == 'RO'] # Special handling for Rondônia state (setting total to 1)

      ano            tipo_vinculo sigla_uf  quantidade_vinculos  total_estado
20   2020              Celetistas       RO                  753             1
40   2021              Celetistas       RO                 7278             1
77   2019              Celetistas       RO                  870             1
81   2019             Estagiários       RO                  487             1
98   2020             Estagiários       RO                  472             1
116  2021             Estagiários       RO                  210             1
162  2019            Estatutários       RO                41306             1
188  2020            Estatutários       RO                38641             1
214  2021            Estatutários       RO                35789             1
243  2019   Somente comissionados       RO                 3328             1
269  2020   Somente comissionados       RO                 3722             1
293  2021   Somente comissionados       RO                 3023             1
324  2019  Sem vínculo permanente       RO                 7052             1
350  2020  Sem vínculo permanente       RO                 4298             1
375  2021  Sem vínculo permanente       RO                 1853             1
425  2023              Celetistas       RO                    0             1
452  2023             Estagiários       RO                    0             1
479  2023            Estatutários       RO                    0             1
506  2023  Sem vínculo permanente       RO                    0             1
533  2023   Somente comissionados       RO                    0             1

In [19]:
df = df1
df

      ano           tipo_vinculo sigla_uf  quantidade_vinculos  total_estado
0    2019             Celetistas       AC                  655        134574
1    2019             Celetistas       AM                  377        301320
2    2019             Celetistas       PA                 1711        435082
3    2019             Celetistas       TO                  300        191546
4    2019             Celetistas       MA                  628        269972
..    ...                    ...      ...                  ...           ...
535  2023  Somente comissionados       RS                 2479        506214
536  2023  Somente comissionados       SC                  764        351336
537  2023  Somente comissionados       SE                 2798        163628
538  2023  Somente comissionados       SP                 7117       2315114
539  2023  Somente comissionados       TO                21476        191546

[540 rows x 5 columns]

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 540 entries, 0 to 539
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ano                  540 non-null    Int64
 1   tipo_vinculo         540 non-null    object
 2   sigla_uf             540 non-null    object
 3   quantidade_vinculos  535 non-null    Int64
 4   total_estado         540 non-null    Int64
dtypes: Int64(3), object(2)
memory usage: 22.8+ KB

# Upload

In [ ]:
# Define the BigQuery table schema with Portuguese descriptions
schema = [
    bigquery.SchemaField('ano', 'INTEGER', description='Ano de referencia da informacao'),
    bigquery.SchemaField('tipo_vinculo', 'STRING', description='Tipo de vinculo.'),
    bigquery.SchemaField('sigla_uf', 'STRING', description='Sigla da Unidade da Federação.'),
    bigquery.SchemaField('quantidade_vinculos', 'INTEGER', description='Quantidade de vinculos'),
    bigquery.SchemaField('total_estado', 'INTEGER', description='Total de vínculos daquela UF')
]

# Initialize BigQuery client connection
client = bigquery.Client(project='repositoriodedadosgpsp')

# Create reference to target dataset
dataset_ref = client.dataset('perfil_remuneracao')

# Create reference to target table with standardized naming convention:
# FONTE_algo_intuitivo_dado (ESTADIC_quantidade_vinculos_mapa_v2)
table_ref = dataset_ref.table('ESTADIC_quantidade_vinculos_mapa_v2')

# Configure the load job with our schema definition
job_config = bigquery.LoadJobConfig(
    schema=schema,
    # Optional parameters (commented out):
    # write_disposition="WRITE_TRUNCATE",  # Overwrites table if exists
    # create_disposition="CREATE_IF_NEEDED"  # Default behavior
)

# Execute the load job to upload DataFrame to BigQuery
job = client.load_table_from_dataframe(
    dataframe=df,
    destination=table_ref,
    job_config=job_config
)

# Wait for the job to complete
job.result()