In [1]:
import numpy as np
import pandas as pd
import numpy as np
import os
import time
from google.cloud import bigquery

c:\Users\ana.sales_republica\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
os.chdir('G:\\Drives compartilhados\\República.org\\4. Equipes\\Dados e Comunicação\\DADOS E CONHECIMENTO\\415 - Repositório de Dados\\Repositório Local\\RAIS')

In [ ]:
os.listdir()

In [ ]:
# 2022 df = pd.read_excel('indicador_salarios_rais2022.xlsx', usecols="A:C")

       Medida      Valor              categoria
0    1º Decil   1300.000   Legislativo Estadual
1    1º Decil   1300.876  Legislativo Municipal
2    1º Decil   1313.000              Municipal
3    1º Decil   1313.000    Executivo Municipal
4    1º Decil   1328.410            Legislativo
..        ...        ...                    ...
160  9º Decil  25332.020   Legislativo Estadual
161  9º Decil  25971.110             Judiciário
162  9º Decil  26430.576     Judiciário Federal
163  8º Decil  31428.930    Legislativo Federal
164  9º Decil  36164.800    Legislativo Federal

[165 rows x 3 columns]

In [49]:
df1 = pd.read_excel('out_renda_2023.xlsx', usecols="A:C")
df1

         medida      valor              categoria
0      1º Decil   1400.000  Legislativo Municipal
1      1º Decil   1460.470              Municipal
2      1º Decil   1474.780    Executivo Municipal
3      1º Decil   1542.070              Executivo
4      1º Decil   1560.170            Legislativo
..          ...        ...                    ...
160    9º Decil  29372.812   Legislativo Estadual
161    9º Decil  29557.279    Judiciário Estadual
162  3º Quartil  29719.050    Legislativo Federal
163    8º Decil  34868.192    Legislativo Federal
164    9º Decil  40494.612    Legislativo Federal

[165 rows x 3 columns]

In [50]:
df1 = df1[df1['medida']=='Mediana']
df1

      medida      valor              categoria
35   Mediana   3255.140              Municipal
37   Mediana   3280.370    Executivo Municipal
42   Mediana   3569.440  Legislativo Municipal
45   Mediana   3780.580              Executivo
49   Mediana   4034.600                Público
59   Mediana   4780.250     Executivo Estadual
60   Mediana   4844.555            Legislativo
65   Mediana   5250.000               Estadual
91   Mediana   7549.820   Legislativo Estadual
109  Mediana  10092.860    Legislativo Federal
116  Mediana  11186.210      Executivo Federal
119  Mediana  12531.360                Federal
120  Mediana  12902.685    Judiciário Estadual
129  Mediana  14967.560             Judiciário
137  Mediana  17332.430     Judiciário Federal

In [51]:
def agrupamento (df1):
    if df1['categoria'] in ['Executivo Municipal', 'Legislativo Municipal', 'Executivo Estadual', 'Legislativo Estadual', 'Executivo Federal', 'Legislativo Federal', 'Judiciário Estadual', 'Judiciário Federal']:
        return 'Esfera e Poder'
    elif df1['categoria'] in ['Municipal', 'Federal', 'Estadual', 'Público']:
        return 'Esfera'
    elif df1['categoria'] in ['Executivo', 'Legislativo', 'Judiciário']:
        return 'Poder'

In [52]:
df1['grupo'] = df1.apply(agrupamento, axis=1) #incluindo a função acima na coluna denominada "grupo"

C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_13388\2381318492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['grupo'] = df1.apply(agrupamento, axis=1) #incluindo a função acima na coluna denominada "grupo"

In [53]:
df1['grupo_ordenado'] = pd.factorize(df1['grupo'])[0]  
df1['ano'] = 2023
df1

C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_13388\3548725666.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['grupo_ordenado'] = pd.factorize(df1['grupo'])[0]
C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_13388\3548725666.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ano'] = 2023

,medida,valor,categoria,grupo,grupo_ordenado,ano
35,Mediana,3255.140,Municipal,Esfera,0,2023
37,Mediana,3280.370,Executivo Municipal,Esfera e Poder,1,2023
42,Mediana,3569.440,Legislativo Municipal,Esfera e Poder,1,2023
45,Mediana,3780.580,Executivo,Poder,2,2023
49,Mediana,4034.600,Público,Esfera,0,2023
59,Mediana,4780.250,Executivo Estadual,Esfera e Poder,1,2023
60,Mediana,4844.555,Legislativo,Poder,2,2023
65,Mediana,5250.000,Estadual,Esfera,0,2023
91,Mediana,7549.820,Legislativo Estadual,Esfera e Poder,1,2023
109,Mediana,10092.860,Legislativo Federal,Esfera e Poder,1,2023
116,Mediana,11186.210,Executivo Federal,Esfera e Poder,1,2023
119,Mediana,12531.360,Federal,Esfera,0,2023
120,Mediana,12902.685,Judiciário Estadual,Esfera e Poder,1,2023
129,Mediana,14967.560,Judiciário,Poder,2,2023
137,Mediana,17332.430,Judiciário Federal,Esfera e Poder,1,2023

In [54]:
df1['grupo_ordenado'] = pd.factorize(df['grupo'])[0]  
df1

C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_13388\385831595.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['grupo_ordenado'] = pd.factorize(df['grupo'])[0]

,medida,valor,categoria,grupo,grupo_ordenado,ano
35,Mediana,3255.140,Municipal,Esfera,0,2023
37,Mediana,3280.370,Executivo Municipal,Esfera e Poder,1,2023
42,Mediana,3569.440,Legislativo Municipal,Esfera e Poder,0,2023
45,Mediana,3780.580,Executivo,Poder,2,2023
49,Mediana,4034.600,Público,Esfera,1,2023
59,Mediana,4780.250,Executivo Estadual,Esfera e Poder,2,2023
60,Mediana,4844.555,Legislativo,Poder,0,2023
65,Mediana,5250.000,Estadual,Esfera,1,2023
91,Mediana,7549.820,Legislativo Estadual,Esfera e Poder,0,2023
109,Mediana,10092.860,Legislativo Federal,Esfera e Poder,0,2023
116,Mediana,11186.210,Executivo Federal,Esfera e Poder,0,2023
119,Mediana,12531.360,Federal,Esfera,1,2023
120,Mediana,12902.685,Judiciário Estadual,Esfera e Poder,0,2023
129,Mediana,14967.560,Judiciário,Poder,2,2023
137,Mediana,17332.430,Judiciário Federal,Esfera e Poder,0,2023

In [55]:
df1_ordenado = df1.sort_values(by='grupo_ordenado').drop(columns=['grupo_ordenado', 'medida']).reset_index(drop=True)
df1_ordenado

        valor              categoria           grupo   ano
0    3255.140              Municipal          Esfera  2023
1    3569.440  Legislativo Municipal  Esfera e Poder  2023
2    4844.555            Legislativo           Poder  2023
3    7549.820   Legislativo Estadual  Esfera e Poder  2023
4   10092.860    Legislativo Federal  Esfera e Poder  2023
5   11186.210      Executivo Federal  Esfera e Poder  2023
6   12902.685    Judiciário Estadual  Esfera e Poder  2023
7   17332.430     Judiciário Federal  Esfera e Poder  2023
8    3280.370    Executivo Municipal  Esfera e Poder  2023
9    4034.600                Público          Esfera  2023
10   5250.000               Estadual          Esfera  2023
11  12531.360                Federal          Esfera  2023
12   3780.580              Executivo           Poder  2023
13   4780.250     Executivo Estadual  Esfera e Poder  2023
14  14967.560             Judiciário           Poder  2023

In [56]:
df1_ordenado = df1_ordenado.rename(columns={'valor':'mediana', 'categoria':'poder_esfera'})

In [57]:
df1_ordenado

      mediana           poder_esfera           grupo   ano
0    3255.140              Municipal          Esfera  2023
1    3569.440  Legislativo Municipal  Esfera e Poder  2023
2    4844.555            Legislativo           Poder  2023
3    7549.820   Legislativo Estadual  Esfera e Poder  2023
4   10092.860    Legislativo Federal  Esfera e Poder  2023
5   11186.210      Executivo Federal  Esfera e Poder  2023
6   12902.685    Judiciário Estadual  Esfera e Poder  2023
7   17332.430     Judiciário Federal  Esfera e Poder  2023
8    3280.370    Executivo Municipal  Esfera e Poder  2023
9    4034.600                Público          Esfera  2023
10   5250.000               Estadual          Esfera  2023
11  12531.360                Federal          Esfera  2023
12   3780.580              Executivo           Poder  2023
13   4780.250     Executivo Estadual  Esfera e Poder  2023
14  14967.560             Judiciário           Poder  2023

Subindo para o GBQ

In [58]:
client = bigquery.Client()
dataset_ref = client.dataset('perfil_remuneracao')

In [59]:
df1_ordenado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mediana       15 non-null     float64
 1   poder_esfera  15 non-null     object
 2   grupo         15 non-null     object
 3   ano           15 non-null     int64
dtypes: float64(1), int64(1), object(2)
memory usage: 612.0+ bytes

In [60]:
schema = [bigquery.SchemaField('poder_esfera', 'STRING', description= 'Nível da esfera e poder de governo'),
          bigquery.SchemaField('grupo', 'STRING', description= 'Se é esfera, poder ou esfera e poder'),
          bigquery.SchemaField('mediana', 'FLOAT', description= 'Mediana da remuneração por grupo'),
          bigquery.SchemaField('ano', 'FLOAT', description= 'Ano de referência')]

In [61]:
table_ref = dataset_ref.table('RAIS_remuneracao_poder_esfera')
job_config = bigquery.LoadJobConfig(schema=schema)
job = client.load_table_from_dataframe(df1_ordenado, table_ref, job_config=job_config)
job.result()

LoadJob<project=repositoriodedadosgpsp, location=US, id=da120ee9-7637-472d-9800-a7c84dd7eb25>