In [ ]:
# Install required Google Cloud packages (commented out as these are typically one-time setup commands)
!pip install gcloud
!gcloud auth application-default login

# Import necessary Python libraries
import pandas as pd                # Data manipulation and analysis
import numpy as np                 # Numerical computing
import time                        # Time-related functions
import os                          # Operating system interfaces
import pandas_gbq                  # Pandas integration with BigQuery
from google.cloud import bigquery  # BigQuery client library
import glob                        # File path pattern matching
import openpyxl                    # Excel file handling
import csv                         # CSV file handling
import re                          # Regular expressions

# Note: The actual imports remain exactly as in the original code

Collecting gcloud
  Downloading gcloud-0.18.3.tar.gz (454 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 454.4/454.4 kB 2.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: httplib2>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from gcloud) (0.32.0)
Requirement already satisfied: googleapis-common-protos in /usr/local/lib/python3.12/dist-packages (from gcloud) (1.75.0)
Requirement already satisfied: oauth2client>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from gcloud) (4.1.3)
Requirement already satisfied: protobuf!=3.0.0.b2.post1,>=3.0.0b2 in /usr/local/lib/python3.12/dist-packages (from gcloud) (5.29.6)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from gcloud) (1.17.0)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2>=0.9.1->gcloud) (3.3.2)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (0.6.4)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (0.4.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (4.9.1)
Building wheels for collected packages: gcloud
  Building wheel for gcloud (setup.py) ... done
  Created wheel for gcloud: filename=gcloud-0.18.3-py3-none-any.whl size=602927 sha256=43cbdc05aad1c54316d43f3eb847187ce8b54d9006d3ba0f9e7b56ff820df6c3
  Stored in directory: /root/.cache/pip/wheels/2a/62/75/3d74209bfebb8805823ae74afa28653aa1ea76d8b5a9d741ff
Successfully built gcloud
Installing collected packages: gcloud
Successfully installed gcloud-0.18.3
Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fapplicationdefaultauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=It92eCnQn7s5yx5noHfuasFTaJiBwx&prompt=consent&token_usage=remote&access_type=offline&code_challenge=PKHQ6wY3k9ETBmGyvdOzPQcqj2j-RZyY6ZhXMfye6Nw&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0AXEQxIANdcjhj5c1xtECq3paEm9M2fUnUGC6yBhj2bDwBOXG08KDdJ2-Mw6hvDsGf8OTjQ

Credentials saved to file: [/content/.config/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.


To take a quick anonymous survey, run:
  $ gcloud survey

In [ ]:
diretorio = 'G:\\Drives compartilhados\\República.org\\4. Equipes\\Dados e Comunicação\\DADOS E CONHECIMENTO\\460 - Estudos e Infográficos\\20 - Sistema prisional\\bases de dados'

In [ ]:
os.chdir(diretorio)

In [ ]:
os.listdir(diretorio)

['15o-ciclo-base-de-dados-2023-2-semestre-1.csv',
 '3o-ciclo-base-de-dados-2017-2-semestre.csv',
 '5o-ciclo-base-de-dados-2018-2-semestre.csv',
 '7o-ciclo-base-de-dados-2019-2-semestre.csv',
 '11o-ciclo-base-de-dados-2021-2-semestre.csv',
 '17o-ciclo-base-de-dados-2024-2-semestre.csv',
 'sistema_prisional.ipynb',
 '13o-ciclo-base-de-dados-2022-2-semestre.csv',
 'notas.md',
 '1º semestre',
 'infopen_2014.csv',
 'infopen_2015.csv',
 '1o-ciclo-base-de-dados-2016-2-semestre.csv',
 '9o-ciclo-base-de-dados-2020-2-semestre (1).csv',
 '17o-ciclo-base-de-dados-2024-2-semestre - Copia.csv',
 'qtd_total_epor_1000_por_profissao_saude.csv',
 'consolidado_geral_pop_profissoes.csv',
 'cnes-assistentes-sociais-mil-habitantes-g0B7UJeVYo6Vk4w7y.csv',
 'pop_por_cor_total_pct.xlsx',
 'saude_profissoes_ano.xlsx',
 'areas_por_pop_ano.xlsx',
 'saude_fisica.xlsx',
 'saude_mental_ano.xlsx',
 'saude_2024_profissao.xlsx',
 'mental_pop.xlsx']

In [ ]:
df24 = pd.read_csv('/content/17o-ciclo-base-de-dados-2024-2-semestre.csv', encoding= 'utf8', sep=';')
df25 = pd.read_csv('/content/19o-ciclo-base-de-dados-2025-2-semestre.csv', encoding= 'utf8', sep=';')

/tmp/ipykernel_3577/861533416.py:1: DtypeWarning: Columns (7,36,118,121,128,130,147,389,395) have mixed types. Specify dtype option on import or set low_memory=False.
  df24 = pd.read_csv('/content/17o-ciclo-base-de-dados-2024-2-semestre.csv', encoding= 'utf8', sep=';')
/tmp/ipykernel_3577/861533416.py:2: DtypeWarning: Columns (389) have mixed types. Specify dtype option on import or set low_memory=False.
  df25 = pd.read_csv('/content/19o-ciclo-base-de-dados-2025-2-semestre.csv', encoding= 'utf8', sep=';')

In [ ]:
dfs = {
    2025: df25
}

In [ ]:
df_todos = df25

In [ ]:
col_masc = [
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Estadual Masculino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Federal Masculino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Estadual Masculino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Federal Masculino',
    '4.1 População prisional | Medida de segurança - internação | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Estadual Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Federal Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Outros(Just. Trab., cível) Masculino'
]

col_fem = [
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Estadual Feminino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Federal Feminino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Estadual Feminino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Federal Feminino',
    '4.1 População prisional | Medida de segurança - internação | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Estadual Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Federal Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Outros(Just. Trab., cível) Feminino'
]

In [ ]:
enf = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total'].sum()
aux_enf= df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total'].sum()
psi = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total'].sum()
dent = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Total'].sum()
tec_dent = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Total'].sum()
assits = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Assistentes sociais | Total'].sum()
adv = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Advogados | Total'].sum()
med_geral = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total'].sum()
med_gineco = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total'].sum()
med_psiq = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – psiquiatras | Total'].sum()
med_outros = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total'].sum()
ped = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Pedagogos | Total'].sum()
prof= df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Professores | Total'].sum()
terapeuta_ocup = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Terapeuta/ terapeuta ocupacional | Total'].sum()

In [ ]:
col_enfs = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total',
             '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total']

col_medicos_fisica = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total',
                        '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total',
                       '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total']

col_medicos_mental = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total',
                    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – psiquiatras | Total',
                    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Terapeuta/ terapeuta ocupacional | Total']
col_assits = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Assistentes sociais | Total']

col_pop = ['4.1 População prisional | Total']

In [ ]:
resultados= []
dfs = [df25]
anos = list(range(2025,2026))  # de 2016 a 2024

In [ ]:
for df, ano in zip(dfs, anos):
    df = df[df['Tipo do Estabelecimento'] == 'Cela física'].copy()

    for col_group in [col_medicos_fisica, col_medicos_mental, col_enfs, col_assits, col_masc, col_fem]:
        for col in col_group:
            df[col] = pd.to_numeric(df[col], errors='coerce')

    # Soma populacional por sexo
    df['pop_masc'] = df[col_masc].sum(axis=1)
    df['pop_fem'] = df[col_fem].sum(axis=1)
    df['pop_total'] = df['pop_masc'] + df['pop_fem']

    df['total_medicos_fisica'] = df[col_medicos_fisica].sum(axis=1)
    df['total_medicos_mental'] = df[col_medicos_mental].sum(axis=1)
    df['total_enfs'] = df[col_enfs].sum(axis=1)
    df['total_assistentes_sociais'] = df[col_assits].sum(axis=1)
    df['ano'] = ano

    grupo = df.groupby(['UF', 'ano'])[
        ['total_medicos_fisica', 'total_medicos_mental', 'total_enfs', 'total_assistentes_sociais',
         'pop_masc', 'pop_fem', 'pop_total']
    ].sum().reset_index()

    resultados.append(grupo)

# DataFrame final unificado
saude_area_populacao_ano_uf = pd.concat(resultados, ignore_index=True)

In [ ]:
saude_area_populacao_ano_uf

,UF,ano,total_medicos_fisica,total_medicos_mental,total_enfs,total_assistentes_sociais,pop_masc,pop_fem,pop_total
0,AC,2025,5.0,12.0,12.0,19.0,5225.0,213.0,5438.0
1,AL,2025,21.0,36.0,131.0,26.0,5731.0,191.0,5922.0
2,AM,2025,14.0,34.0,70.0,25.0,5767.0,216.0,5983.0
3,AP,2025,5.0,8.0,24.0,5.0,3836.0,149.0,3985.0
4,BA,2025,65.0,109.0,286.0,73.0,16126.0,598.0,16724.0
5,CE,2025,50.0,40.0,131.0,41.0,24186.0,1227.0,25413.0
6,DF,2025,34.0,23.0,60.0,7.0,16360.0,661.0,17021.0
7,ES,2025,107.0,114.0,128.0,84.0,24201.0,1120.0,25321.0
8,GO,2025,67.0,58.0,138.0,42.0,18448.0,896.0,19344.0
9,MA,2025,77.0,69.0,380.0,69.0,12513.0,419.0,12932.0
10,MG,2025,194.0,311.0,551.0,275.0,70297.0,3135.0,73432.0
11,MS,2025,55.0,37.0,88.0,43.0,17198.0,1039.0,18237.0
12,MT,2025,25.0,38.0,118.0,41.0,14732.0,1000.0,15732.0
13,PA,2025,25.0,82.0,225.0,84.0,15907.0,701.0,16608.0
14,PB,2025,25.0,39.0,52.0,24.0,12591.0,710.0,13301.0
15,PE,2025,42.0,79.0,114.0,101.0,29913.0,997.0,30910.0
16,PI,2025,42.0,43.0,102.0,58.0,7678.0,306.0,7984.0
17,PR,2025,103.0,71.0,170.0,54.0,41239.0,2449.0,43688.0
18,RJ,2025,102.0,113.0,427.0,59.0,44844.0,1801.0,46645.0
19,RN,2025,33.0,24.0,65.0,14.0,7639.0,365.0,8004.0
20,RO,2025,31.0,16.0,136.0,25.0,7972.0,431.0,8403.0
21,RR,2025,8.0,7.0,35.0,3.0,2969.0,159.0,3128.0
22,RS,2025,81.0,162.0,220.0,168.0,38883.0,2172.0,41055.0
23,SC,2025,68.0,101.0,177.0,66.0,28893.0,1620.0,30513.0
24,SE,2025,12.0,23.0,91.0,21.0,6193.0,257.0,6450.0
25,SP,2025,160.0,176.0,787.0,185.0,210752.0,10468.0,221220.0
26,TO,2025,13.0,15.0,39.0,15.0,4314.0,188.0,4502.0

In [ ]:
saude_area_populacao_ano_uf['medicos_fisica_por_1000'] = (
    saude_area_populacao_ano_uf['total_medicos_fisica'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000

saude_area_populacao_ano_uf['medicos_mental_por_1000'] = (
    saude_area_populacao_ano_uf['total_medicos_mental'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000

saude_area_populacao_ano_uf['total_enfs_por_1000'] = (
    saude_area_populacao_ano_uf['total_enfs'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000
saude_area_populacao_ano_uf['total_assists_por_1000'] = (
    saude_area_populacao_ano_uf['total_assistentes_sociais'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000
saude_area_populacao_ano_uf

,UF,ano,total_medicos_fisica,total_medicos_mental,total_enfs,total_assistentes_sociais,pop_masc,pop_fem,pop_total,medicos_fisica_por_1000,medicos_mental_por_1000,total_enfs_por_1000,total_assists_por_1000
0,AC,2025,5.0,12.0,12.0,19.0,5225.0,213.0,5438.0,0.919456,2.206694,2.206694,3.493932
1,AL,2025,21.0,36.0,131.0,26.0,5731.0,191.0,5922.0,3.546099,6.079027,22.120905,4.390409
2,AM,2025,14.0,34.0,70.0,25.0,5767.0,216.0,5983.0,2.339963,5.682768,11.699816,4.178506
3,AP,2025,5.0,8.0,24.0,5.0,3836.0,149.0,3985.0,1.254705,2.007528,6.022585,1.254705
4,BA,2025,65.0,109.0,286.0,73.0,16126.0,598.0,16724.0,3.886630,6.517580,17.101172,4.364984
5,CE,2025,50.0,40.0,131.0,41.0,24186.0,1227.0,25413.0,1.967497,1.573998,5.154842,1.613347
6,DF,2025,34.0,23.0,60.0,7.0,16360.0,661.0,17021.0,1.997532,1.351272,3.525057,0.411257
7,ES,2025,107.0,114.0,128.0,84.0,24201.0,1120.0,25321.0,4.225741,4.502192,5.055093,3.317405
8,GO,2025,67.0,58.0,138.0,42.0,18448.0,896.0,19344.0,3.463606,2.998346,7.133995,2.171216
9,MA,2025,77.0,69.0,380.0,69.0,12513.0,419.0,12932.0,5.954222,5.335602,29.384473,5.335602
10,MG,2025,194.0,311.0,551.0,275.0,70297.0,3135.0,73432.0,2.641900,4.235211,7.503541,3.744961
11,MS,2025,55.0,37.0,88.0,43.0,17198.0,1039.0,18237.0,3.015847,2.028842,4.825355,2.357844
12,MT,2025,25.0,38.0,118.0,41.0,14732.0,1000.0,15732.0,1.589118,2.415459,7.500636,2.606153
13,PA,2025,25.0,82.0,225.0,84.0,15907.0,701.0,16608.0,1.505299,4.937380,13.547688,5.057803
14,PB,2025,25.0,39.0,52.0,24.0,12591.0,710.0,13301.0,1.879558,2.932110,3.909480,1.804376
15,PE,2025,42.0,79.0,114.0,101.0,29913.0,997.0,30910.0,1.358784,2.555807,3.688127,3.267551
16,PI,2025,42.0,43.0,102.0,58.0,7678.0,306.0,7984.0,5.260521,5.385772,12.775551,7.264529
17,PR,2025,103.0,71.0,170.0,54.0,41239.0,2449.0,43688.0,2.357627,1.625160,3.891229,1.236037
18,RJ,2025,102.0,113.0,427.0,59.0,44844.0,1801.0,46645.0,2.186730,2.422553,9.154250,1.264873
19,RN,2025,33.0,24.0,65.0,14.0,7639.0,365.0,8004.0,4.122939,2.998501,8.120940,1.749125
20,RO,2025,31.0,16.0,136.0,25.0,7972.0,431.0,8403.0,3.689159,1.904082,16.184696,2.975128
21,RR,2025,8.0,7.0,35.0,3.0,2969.0,159.0,3128.0,2.557545,2.237852,11.189258,0.959079
22,RS,2025,81.0,162.0,220.0,168.0,38883.0,2172.0,41055.0,1.972963,3.945926,5.358665,4.092072
23,SC,2025,68.0,101.0,177.0,66.0,28893.0,1620.0,30513.0,2.228558,3.310065,5.800806,2.163012
24,SE,2025,12.0,23.0,91.0,21.0,6193.0,257.0,6450.0,1.860465,3.565891,14.108527,3.255814
25,SP,2025,160.0,176.0,787.0,185.0,210752.0,10468.0,221220.0,0.723262,0.795588,3.557545,0.836272
26,TO,2025,13.0,15.0,39.0,15.0,4314.0,188.0,4502.0,2.887606,3.331853,8.662817,3.331853

In [ ]:
total_enfs_pop = saude_area_populacao_ano_uf[['ano','UF','total_enfs', 'pop_total', 'total_enfs_por_1000']]
total_enfs_pop

     ano  UF  total_enfs  pop_total  total_enfs_por_1000
0   2025  AC        12.0     5438.0             2.206694
1   2025  AL       131.0     5922.0            22.120905
2   2025  AM        70.0     5983.0            11.699816
3   2025  AP        24.0     3985.0             6.022585
4   2025  BA       286.0    16724.0            17.101172
5   2025  CE       131.0    25413.0             5.154842
6   2025  DF        60.0    17021.0             3.525057
7   2025  ES       128.0    25321.0             5.055093
8   2025  GO       138.0    19344.0             7.133995
9   2025  MA       380.0    12932.0            29.384473
10  2025  MG       551.0    73432.0             7.503541
11  2025  MS        88.0    18237.0             4.825355
12  2025  MT       118.0    15732.0             7.500636
13  2025  PA       225.0    16608.0            13.547688
14  2025  PB        52.0    13301.0             3.909480
15  2025  PE       114.0    30910.0             3.688127
16  2025  PI       102.0     7984.0            12.775551
17  2025  PR       170.0    43688.0             3.891229
18  2025  RJ       427.0    46645.0             9.154250
19  2025  RN        65.0     8004.0             8.120940
20  2025  RO       136.0     8403.0            16.184696
21  2025  RR        35.0     3128.0            11.189258
22  2025  RS       220.0    41055.0             5.358665
23  2025  SC       177.0    30513.0             5.800806
24  2025  SE        91.0     6450.0            14.108527
25  2025  SP       787.0   221220.0             3.557545
26  2025  TO        39.0     4502.0             8.662817

In [ ]:
total_enfs_pop['profissao'] = 'Enfermeiros, técnicos e auxiliares da enfermagem'

/tmp/ipykernel_3577/983763041.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  total_enfs_pop['profissao'] = 'Enfermeiros, técnicos e auxiliares da enfermagem'

In [ ]:
total_enfs_pop.columns

Index(['ano', 'UF', 'total_enfs', 'pop_total', 'total_enfs_por_1000',
       'profissao'],
      dtype='object')

In [ ]:
total_enfs_pop = total_enfs_pop[['ano', 'UF', 'profissao', 'total_enfs', 'pop_total',
       'total_enfs_por_1000']]
total_enfs_pop

,ano,UF,profissao,total_enfs,pop_total,total_enfs_por_1000
0,2025,AC,"Enfermeiros, técnicos e auxiliares da enfermagem",12.0,5438.0,2.206694
1,2025,AL,"Enfermeiros, técnicos e auxiliares da enfermagem",131.0,5922.0,22.120905
2,2025,AM,"Enfermeiros, técnicos e auxiliares da enfermagem",70.0,5983.0,11.699816
3,2025,AP,"Enfermeiros, técnicos e auxiliares da enfermagem",24.0,3985.0,6.022585
4,2025,BA,"Enfermeiros, técnicos e auxiliares da enfermagem",286.0,16724.0,17.101172
5,2025,CE,"Enfermeiros, técnicos e auxiliares da enfermagem",131.0,25413.0,5.154842
6,2025,DF,"Enfermeiros, técnicos e auxiliares da enfermagem",60.0,17021.0,3.525057
7,2025,ES,"Enfermeiros, técnicos e auxiliares da enfermagem",128.0,25321.0,5.055093
8,2025,GO,"Enfermeiros, técnicos e auxiliares da enfermagem",138.0,19344.0,7.133995
9,2025,MA,"Enfermeiros, técnicos e auxiliares da enfermagem",380.0,12932.0,29.384473
10,2025,MG,"Enfermeiros, técnicos e auxiliares da enfermagem",551.0,73432.0,7.503541
11,2025,MS,"Enfermeiros, técnicos e auxiliares da enfermagem",88.0,18237.0,4.825355
12,2025,MT,"Enfermeiros, técnicos e auxiliares da enfermagem",118.0,15732.0,7.500636
13,2025,PA,"Enfermeiros, técnicos e auxiliares da enfermagem",225.0,16608.0,13.547688
14,2025,PB,"Enfermeiros, técnicos e auxiliares da enfermagem",52.0,13301.0,3.909480
15,2025,PE,"Enfermeiros, técnicos e auxiliares da enfermagem",114.0,30910.0,3.688127
16,2025,PI,"Enfermeiros, técnicos e auxiliares da enfermagem",102.0,7984.0,12.775551
17,2025,PR,"Enfermeiros, técnicos e auxiliares da enfermagem",170.0,43688.0,3.891229
18,2025,RJ,"Enfermeiros, técnicos e auxiliares da enfermagem",427.0,46645.0,9.154250
19,2025,RN,"Enfermeiros, técnicos e auxiliares da enfermagem",65.0,8004.0,8.120940
20,2025,RO,"Enfermeiros, técnicos e auxiliares da enfermagem",136.0,8403.0,16.184696
21,2025,RR,"Enfermeiros, técnicos e auxiliares da enfermagem",35.0,3128.0,11.189258
22,2025,RS,"Enfermeiros, técnicos e auxiliares da enfermagem",220.0,41055.0,5.358665
23,2025,SC,"Enfermeiros, técnicos e auxiliares da enfermagem",177.0,30513.0,5.800806
24,2025,SE,"Enfermeiros, técnicos e auxiliares da enfermagem",91.0,6450.0,14.108527
25,2025,SP,"Enfermeiros, técnicos e auxiliares da enfermagem",787.0,221220.0,3.557545
26,2025,TO,"Enfermeiros, técnicos e auxiliares da enfermagem",39.0,4502.0,8.662817

In [ ]:
total_enfs_pop = total_enfs_pop.rename(
                                            columns={'UF':'sigla_uf'
                                            })
total_enfs_pop

,ano,sigla_uf,profissao,total_enfs,pop_total,total_enfs_por_1000
0,2025,AC,"Enfermeiros, técnicos e auxiliares da enfermagem",12.0,5438.0,2.206694
1,2025,AL,"Enfermeiros, técnicos e auxiliares da enfermagem",131.0,5922.0,22.120905
2,2025,AM,"Enfermeiros, técnicos e auxiliares da enfermagem",70.0,5983.0,11.699816
3,2025,AP,"Enfermeiros, técnicos e auxiliares da enfermagem",24.0,3985.0,6.022585
4,2025,BA,"Enfermeiros, técnicos e auxiliares da enfermagem",286.0,16724.0,17.101172
5,2025,CE,"Enfermeiros, técnicos e auxiliares da enfermagem",131.0,25413.0,5.154842
6,2025,DF,"Enfermeiros, técnicos e auxiliares da enfermagem",60.0,17021.0,3.525057
7,2025,ES,"Enfermeiros, técnicos e auxiliares da enfermagem",128.0,25321.0,5.055093
8,2025,GO,"Enfermeiros, técnicos e auxiliares da enfermagem",138.0,19344.0,7.133995
9,2025,MA,"Enfermeiros, técnicos e auxiliares da enfermagem",380.0,12932.0,29.384473
10,2025,MG,"Enfermeiros, técnicos e auxiliares da enfermagem",551.0,73432.0,7.503541
11,2025,MS,"Enfermeiros, técnicos e auxiliares da enfermagem",88.0,18237.0,4.825355
12,2025,MT,"Enfermeiros, técnicos e auxiliares da enfermagem",118.0,15732.0,7.500636
13,2025,PA,"Enfermeiros, técnicos e auxiliares da enfermagem",225.0,16608.0,13.547688
14,2025,PB,"Enfermeiros, técnicos e auxiliares da enfermagem",52.0,13301.0,3.909480
15,2025,PE,"Enfermeiros, técnicos e auxiliares da enfermagem",114.0,30910.0,3.688127
16,2025,PI,"Enfermeiros, técnicos e auxiliares da enfermagem",102.0,7984.0,12.775551
17,2025,PR,"Enfermeiros, técnicos e auxiliares da enfermagem",170.0,43688.0,3.891229
18,2025,RJ,"Enfermeiros, técnicos e auxiliares da enfermagem",427.0,46645.0,9.154250
19,2025,RN,"Enfermeiros, técnicos e auxiliares da enfermagem",65.0,8004.0,8.120940
20,2025,RO,"Enfermeiros, técnicos e auxiliares da enfermagem",136.0,8403.0,16.184696
21,2025,RR,"Enfermeiros, técnicos e auxiliares da enfermagem",35.0,3128.0,11.189258
22,2025,RS,"Enfermeiros, técnicos e auxiliares da enfermagem",220.0,41055.0,5.358665
23,2025,SC,"Enfermeiros, técnicos e auxiliares da enfermagem",177.0,30513.0,5.800806
24,2025,SE,"Enfermeiros, técnicos e auxiliares da enfermagem",91.0,6450.0,14.108527
25,2025,SP,"Enfermeiros, técnicos e auxiliares da enfermagem",787.0,221220.0,3.557545
26,2025,TO,"Enfermeiros, técnicos e auxiliares da enfermagem",39.0,4502.0,8.662817

In [ ]:
total_enfs_pop['total_enfs_por_1000']= total_enfs_pop['total_enfs_por_1000'].round(2)
total_enfs_pop

,ano,sigla_uf,profissao,total_enfs,pop_total,total_enfs_por_1000
0,2025,AC,"Enfermeiros, técnicos e auxiliares da enfermagem",12.0,5438.0,2.21
1,2025,AL,"Enfermeiros, técnicos e auxiliares da enfermagem",131.0,5922.0,22.12
2,2025,AM,"Enfermeiros, técnicos e auxiliares da enfermagem",70.0,5983.0,11.70
3,2025,AP,"Enfermeiros, técnicos e auxiliares da enfermagem",24.0,3985.0,6.02
4,2025,BA,"Enfermeiros, técnicos e auxiliares da enfermagem",286.0,16724.0,17.10
5,2025,CE,"Enfermeiros, técnicos e auxiliares da enfermagem",131.0,25413.0,5.15
6,2025,DF,"Enfermeiros, técnicos e auxiliares da enfermagem",60.0,17021.0,3.53
7,2025,ES,"Enfermeiros, técnicos e auxiliares da enfermagem",128.0,25321.0,5.06
8,2025,GO,"Enfermeiros, técnicos e auxiliares da enfermagem",138.0,19344.0,7.13
9,2025,MA,"Enfermeiros, técnicos e auxiliares da enfermagem",380.0,12932.0,29.38
10,2025,MG,"Enfermeiros, técnicos e auxiliares da enfermagem",551.0,73432.0,7.50
11,2025,MS,"Enfermeiros, técnicos e auxiliares da enfermagem",88.0,18237.0,4.83
12,2025,MT,"Enfermeiros, técnicos e auxiliares da enfermagem",118.0,15732.0,7.50
13,2025,PA,"Enfermeiros, técnicos e auxiliares da enfermagem",225.0,16608.0,13.55
14,2025,PB,"Enfermeiros, técnicos e auxiliares da enfermagem",52.0,13301.0,3.91
15,2025,PE,"Enfermeiros, técnicos e auxiliares da enfermagem",114.0,30910.0,3.69
16,2025,PI,"Enfermeiros, técnicos e auxiliares da enfermagem",102.0,7984.0,12.78
17,2025,PR,"Enfermeiros, técnicos e auxiliares da enfermagem",170.0,43688.0,3.89
18,2025,RJ,"Enfermeiros, técnicos e auxiliares da enfermagem",427.0,46645.0,9.15
19,2025,RN,"Enfermeiros, técnicos e auxiliares da enfermagem",65.0,8004.0,8.12
20,2025,RO,"Enfermeiros, técnicos e auxiliares da enfermagem",136.0,8403.0,16.18
21,2025,RR,"Enfermeiros, técnicos e auxiliares da enfermagem",35.0,3128.0,11.19
22,2025,RS,"Enfermeiros, técnicos e auxiliares da enfermagem",220.0,41055.0,5.36
23,2025,SC,"Enfermeiros, técnicos e auxiliares da enfermagem",177.0,30513.0,5.80
24,2025,SE,"Enfermeiros, técnicos e auxiliares da enfermagem",91.0,6450.0,14.11
25,2025,SP,"Enfermeiros, técnicos e auxiliares da enfermagem",787.0,221220.0,3.56
26,2025,TO,"Enfermeiros, técnicos e auxiliares da enfermagem",39.0,4502.0,8.66

In [ ]:
total_enfs_pop[total_enfs_pop['ano']==2025]['total_enfs'].sum()

np.float64(4757.0)

In [ ]:
total_enfs_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ano                  27 non-null     int64
 1   sigla_uf             27 non-null     object
 2   profissao            27 non-null     object
 3   total_enfs           27 non-null     float64
 4   pop_total            27 non-null     float64
 5   total_enfs_por_1000  27 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 1.4+ KB

In [ ]:
total_enfs_pop[total_enfs_pop['ano']==2025].sort_values(by='total_enfs_por_1000', ascending=False)

,ano,sigla_uf,profissao,total_enfs,pop_total,total_enfs_por_1000
9,2025,MA,"Enfermeiros, técnicos e auxiliares da enfermagem",380.0,12932.0,29.38
1,2025,AL,"Enfermeiros, técnicos e auxiliares da enfermagem",131.0,5922.0,22.12
4,2025,BA,"Enfermeiros, técnicos e auxiliares da enfermagem",286.0,16724.0,17.10
20,2025,RO,"Enfermeiros, técnicos e auxiliares da enfermagem",136.0,8403.0,16.18
24,2025,SE,"Enfermeiros, técnicos e auxiliares da enfermagem",91.0,6450.0,14.11
13,2025,PA,"Enfermeiros, técnicos e auxiliares da enfermagem",225.0,16608.0,13.55
16,2025,PI,"Enfermeiros, técnicos e auxiliares da enfermagem",102.0,7984.0,12.78
2,2025,AM,"Enfermeiros, técnicos e auxiliares da enfermagem",70.0,5983.0,11.70
21,2025,RR,"Enfermeiros, técnicos e auxiliares da enfermagem",35.0,3128.0,11.19
18,2025,RJ,"Enfermeiros, técnicos e auxiliares da enfermagem",427.0,46645.0,9.15
26,2025,TO,"Enfermeiros, técnicos e auxiliares da enfermagem",39.0,4502.0,8.66
19,2025,RN,"Enfermeiros, técnicos e auxiliares da enfermagem",65.0,8004.0,8.12
12,2025,MT,"Enfermeiros, técnicos e auxiliares da enfermagem",118.0,15732.0,7.50
10,2025,MG,"Enfermeiros, técnicos e auxiliares da enfermagem",551.0,73432.0,7.50
8,2025,GO,"Enfermeiros, técnicos e auxiliares da enfermagem",138.0,19344.0,7.13
3,2025,AP,"Enfermeiros, técnicos e auxiliares da enfermagem",24.0,3985.0,6.02
23,2025,SC,"Enfermeiros, técnicos e auxiliares da enfermagem",177.0,30513.0,5.80
22,2025,RS,"Enfermeiros, técnicos e auxiliares da enfermagem",220.0,41055.0,5.36
5,2025,CE,"Enfermeiros, técnicos e auxiliares da enfermagem",131.0,25413.0,5.15
7,2025,ES,"Enfermeiros, técnicos e auxiliares da enfermagem",128.0,25321.0,5.06
11,2025,MS,"Enfermeiros, técnicos e auxiliares da enfermagem",88.0,18237.0,4.83
14,2025,PB,"Enfermeiros, técnicos e auxiliares da enfermagem",52.0,13301.0,3.91
17,2025,PR,"Enfermeiros, técnicos e auxiliares da enfermagem",170.0,43688.0,3.89
15,2025,PE,"Enfermeiros, técnicos e auxiliares da enfermagem",114.0,30910.0,3.69
25,2025,SP,"Enfermeiros, técnicos e auxiliares da enfermagem",787.0,221220.0,3.56
6,2025,DF,"Enfermeiros, técnicos e auxiliares da enfermagem",60.0,17021.0,3.53
0,2025,AC,"Enfermeiros, técnicos e auxiliares da enfermagem",12.0,5438.0,2.21

# Agregando dados de anos anteriores

In [ ]:
total_enfs_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ano                  27 non-null     int64
 1   sigla_uf             27 non-null     object
 2   profissao            27 non-null     object
 3   total_enfs           27 non-null     float64
 4   pop_total            27 non-null     float64
 5   total_enfs_por_1000  27 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 1.4+ KB

In [ ]:
query = """SELECT * FROM `repositoriodedadosgpsp.perfil_remuneracao.SENAPPEN_profissionais_enfermagem_mil_presos`"""
# Execute the query using pandas_gbq.read_gbq and load the result into a pandas DataFrame called 'df'.
# The 'project_id' specifies the Google Cloud Project to use.
df_old = pandas_gbq.read_gbq(query, project_id='repositoriodedadosgpsp')

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

Downloading: 100%|██████████|

In [ ]:
df_old.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ano                  243 non-null    Int64
 1   sigla_uf             243 non-null    object
 2   profissao            243 non-null    object
 3   total_enfs           243 non-null    float64
 4   pop_total            243 non-null    float64
 5   total_enfs_por_1000  243 non-null    float64
dtypes: Int64(1), float64(3), object(2)
memory usage: 11.8+ KB

In [ ]:
df_final = pd.concat([total_enfs_pop, df_old], ignore_index=True)

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ano                  270 non-null    Int64
 1   sigla_uf             270 non-null    object
 2   profissao            270 non-null    object
 3   total_enfs           270 non-null    float64
 4   pop_total            270 non-null    float64
 5   total_enfs_por_1000  270 non-null    float64
dtypes: Int64(1), float64(3), object(2)
memory usage: 13.0+ KB

# Subindo no GBQ

In [ ]:
# Define the BigQuery table schema with Portuguese descriptions
schema=[bigquery.SchemaField('ano','INTEGER',description='Ano de referencia'),
 bigquery.SchemaField('sigla_uf','STRING',description='Sigla da Unidade da Federação'),
 bigquery.SchemaField('profissao','STRING',description='Profissional'),
 bigquery.SchemaField('total_enfs','FLOAT',description='Quantidade de enfermeiros, tecnicos e auxiliares da enfermagem'),
 bigquery.SchemaField('pop_total','FLOAT',description='Total da população prisional'),
 bigquery.SchemaField('total_enfs_por_1000','FLOAT',description='Taxa de profissionais da enfermagem por 1000 presos')
 ]


# Initialize BigQuery client connection
client = bigquery.Client(project='repositoriodedadosgpsp')

# Create reference to target dataset
dataset_ref = client.dataset('perfil_remuneracao')

# Create reference to target table with standardized naming convention:
# FONTE_algo_intuitivo_dado (INEP_esforco_docente_temporal_v2)
table_ref = dataset_ref.table('SENAPPEN_profissionais_enfermagem_mil_presos_v1')

# Configure the load job with our schema definition
job_config = bigquery.LoadJobConfig(schema=schema)

# Execute the load job to upload DataFrame to BigQuery
job = client.load_table_from_dataframe(
    dataframe=df_final,
    destination=table_ref,
    job_config=job_config
)

# Wait for the job to complete
job.result()

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

LoadJob<project=repositoriodedadosgpsp, location=US, id=a9933e39-5d68-428e-a972-da165cd3382c>