In [2]:
import pandas as pd
import numpy as np
import time
import os
import zipfile
import pandas_gbq
import unidecode
from google.cloud import bigquery
import re

c:\Users\ana.sales_republica\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
client = bigquery.Client()

In [7]:
diretorio = 'G:\\Drives compartilhados\\República.org\\4. Equipes\\Dados e Comunicação\\DADOS E CONHECIMENTO\\460 - Estudos e Infográficos\\20 - Sistema prisional\\bases de dados'

In [8]:
os.chdir(diretorio)

In [9]:
os.listdir(diretorio)

['15o-ciclo-base-de-dados-2023-2-semestre-1.csv',
 '3o-ciclo-base-de-dados-2017-2-semestre.csv',
 '5o-ciclo-base-de-dados-2018-2-semestre.csv',
 '7o-ciclo-base-de-dados-2019-2-semestre.csv',
 '11o-ciclo-base-de-dados-2021-2-semestre.csv',
 '17o-ciclo-base-de-dados-2024-2-semestre.csv',
 'sistema_prisional.ipynb',
 '13o-ciclo-base-de-dados-2022-2-semestre.csv',
 'notas.md',
 '1º semestre',
 'infopen_2014.csv',
 'infopen_2015.csv',
 '1o-ciclo-base-de-dados-2016-2-semestre.csv',
 '9o-ciclo-base-de-dados-2020-2-semestre (1).csv',
 '17o-ciclo-base-de-dados-2024-2-semestre - Copia.csv',
 'qtd_total_epor_1000_por_profissao_saude.csv',
 'consolidado_geral_pop_profissoes.csv',
 'cnes-assistentes-sociais-mil-habitantes-g0B7UJeVYo6Vk4w7y.csv',
 'pop_por_cor_total_pct.xlsx',
 'saude_profissoes_ano.xlsx',
 'areas_por_pop_ano.xlsx',
 'saude_fisica.xlsx',
 'saude_mental_ano.xlsx',
 'saude_2024_profissao.xlsx',
 'mental_pop.xlsx']

In [10]:
df16 = pd.read_csv('1o-ciclo-base-de-dados-2016-2-semestre.csv', encoding= 'utf8', sep=';')
df17 = pd.read_csv('3o-ciclo-base-de-dados-2017-2-semestre.csv', encoding= 'utf8', sep=';')
df18 = pd.read_csv('5o-ciclo-base-de-dados-2018-2-semestre.csv', encoding= 'utf8', sep=';')
df19 = pd.read_csv('7o-ciclo-base-de-dados-2019-2-semestre.csv', encoding= 'utf8', sep=';')
df20 = pd.read_csv('9o-ciclo-base-de-dados-2020-2-semestre (1).csv', encoding= 'utf8', sep=';')
df21 = pd.read_csv('11o-ciclo-base-de-dados-2021-2-semestre.csv', encoding= 'utf8', sep=';')
df22 = pd.read_csv('13o-ciclo-base-de-dados-2022-2-semestre.csv', encoding= 'utf8', sep=';')
df23 = pd.read_csv('15o-ciclo-base-de-dados-2023-2-semestre-1.csv', encoding= 'utf8', sep=';')
df24 = pd.read_csv('17o-ciclo-base-de-dados-2024-2-semestre.csv', encoding= 'utf8', sep=';')

C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_12032\1506389750.py:2: DtypeWarning: Columns (128,130) have mixed types. Specify dtype option on import or set low_memory=False.
  df17 = pd.read_csv('3o-ciclo-base-de-dados-2017-2-semestre.csv', encoding= 'utf8', sep=';')
C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_12032\1506389750.py:3: DtypeWarning: Columns (128,130) have mixed types. Specify dtype option on import or set low_memory=False.
  df18 = pd.read_csv('5o-ciclo-base-de-dados-2018-2-semestre.csv', encoding= 'utf8', sep=';')
C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_12032\1506389750.py:4: DtypeWarning: Columns (128,130) have mixed types. Specify dtype option on import or set low_memory=False.
  df19 = pd.read_csv('7o-ciclo-base-de-dados-2019-2-semestre.csv', encoding= 'utf8', sep=';')
C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_12032\1506389750.py:6: DtypeWarning: Columns (7,128,130,389) have mixed types. Specify dtype option on import or set low_memory=False.
  df21 = pd.read_csv('11o-ciclo-base-de-dados-2021-2-semestre.csv', encoding= 'utf8', sep=';')
C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_12032\1506389750.py:9: DtypeWarning: Columns (7,36,118,121,128,130,147,389,395) have mixed types. Specify dtype option on import or set low_memory=False.
  df24 = pd.read_csv('17o-ciclo-base-de-dados-2024-2-semestre.csv', encoding= 'utf8', sep=';')

In [11]:
df_todos = pd.concat([df16, df17, df18, df19, df20, df21, df22, df23, df24])
df_todos

,ciclo,Ano,Referência,Tipo do Estabelecimento,Situação de Preenchimento,Nome do Estabelecimento,Situação do Estabelecimento,Outras Denominações,Endereço,Bairro,...,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tonga | Masculino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tonga | Feminino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tonga | Total,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tuvalu | Masculino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tuvalu | Feminino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tuvalu | Total,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Vanuatu | Masculino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Vanuatu | Feminino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Vanuatu | Total,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Outros países do continente Oceania | Total
0,1,2016,2016/2,Domiciliar com monitoramento eletrônico,Validado,UNIDADE DE MONITORAMENTO ELETRONICO DE PRESOS,Ativo,NaN,"Av Getúlio Vargas, 1203",Bosque,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2016,2016/2,Cela física,Validado,UNIDADE DE RECOLHIMENTO PROVISORIO,Ativo,NaN,Estrada do Barro Vermelho km 3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO FEMININO,Ativo,NaN,ESTRADA DO BARRO VERMELHO KM03,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N1,Ativo,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N2,Ativo,NaN,ESTRADA DO BARRO VERMELHO - KM 03,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1558,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Brasília,Ativo,NaN,Rod DF-465 KM 01 - Complexo Penitenciário da P...,Setor Habitacional Jardim Botânico,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1559,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Campo Grande,Ativo,NaN,AVENIDA HENRIQUE BERTIN S/N JARDIM LOS ANGELES,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1560,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Catanduvas,Ativo,NaN,"Rodovia PR 471, Km 15, s/n",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1561,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Mossoró,Ativo,NaN,"RN 15, Km 13, Estrada Mossoró/Baraúnas - Mosso...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1562,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Porto Velho,Ativo,NaN,"SÍTIO DA BOA ESPERANÇA, LOTE 13, GLEBA 13 ""A"" ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_todos.columns.to_list()

['ciclo',
 'Ano',
 'Referência',
 'Tipo do Estabelecimento',
 'Situação de Preenchimento',
 'Nome do Estabelecimento',
 'Situação do Estabelecimento',
 'Outras Denominações',
 'Endereço',
 'Bairro',
 'CEP',
 'Âmbito',
 'UF',
 'Município',
 'Código IBGE',
 'Telefone Principal',
 '1.1 Estabelecimento originalmente destinado a pessoa privadas de liberdade do sexo',
 '1.2 Tipo de estabelecimento - originalmente destinado',
 '1.3 Capacidade do estabelecimento | Presos provisórios | Masculino',
 '1.3 Capacidade do estabelecimento | Presos provisórios | Feminino',
 '1.3 Capacidade do estabelecimento | Presos provisórios | Total',
 '1.3 Capacidade do estabelecimento | Regime fechado | Masculino',
 '1.3 Capacidade do estabelecimento | Regime fechado | Feminino',
 '1.3 Capacidade do estabelecimento | Regime fechado | Total',
 '1.3 Capacidade do estabelecimento | Regime semiaberto | Masculino',
 '1.3 Capacidade do estabelecimento | Regime semiaberto | Feminino',
 '1.3 Capacidade do estabelecimento | Regime semiaberto | Total',
 '1.3 Capacidade do estabelecimento | Regime aberto | Masculino',
 '1.3 Capacidade do estabelecimento | Regime aberto | Feminino',
 '1.3 Capacidade do estabelecimento | Regime aberto | Total',
 '1.3 Capacidade do estabelecimento | Regime Disciplinar Diferenciado (RDD) | Masculino',
 '1.3 Capacidade do estabelecimento | Regime Disciplinar Diferenciado (RDD) | Feminino',
 '1.3 Capacidade do estabelecimento | Regime Disciplinar Diferenciado (RDD) | Total',
 '1.3 Capacidade do estabelecimento | Medidas de segurança de internação | Masculino',
 '1.3 Capacidade do estabelecimento | Medidas de segurança de internação | Feminino',
 '1.3 Capacidade do estabelecimento | Medidas de segurança de internação | Total',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)?',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)? | Masculino',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)? | Feminino',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)? | Total',
 '1.3 Capacidade do estabelecimento | Masculino | Total',
 '1.3 Capacidade do estabelecimento | Feminino | Total',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Celas não aptas',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Vagas desativadas - Masculino',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Vagas desativadas - Feminino',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Total de vagas desativadas',
 '1.4 Gestão do estabelecimento',
 '1.5 Quais serviços são terceirizados? | Nenhum',
 '1.5 Quais serviços são terceirizados? | Alimentação',
 '1.5 Quais serviços são terceirizados? | Limpeza',
 '1.5 Quais serviços são terceirizados? | Lavanderia',
 '1.5 Quais serviços são terceirizados? | Saúde',
 '1.5 Quais serviços são terceirizados? | Segurança',
 '1.5 Quais serviços são terceirizados? | Assistência educacional',
 '1.5 Quais serviços são terceirizados? | Assistência laboral',
 '1.5 Quais serviços são terceirizados? | Assistência social',
 '1.5 Quais serviços são terceirizados? | Assistência jurídica',
 '1.5 Quais serviços são terceirizados? | Serviços administrativos',
 '1.5 Quais serviços são terceirizados? | Outro',
 '1.6 Data de inauguração do estabelecimento',
 '1.7 O estabelecimento foi concebido como estabelecimento penal ou foi construído para outra utilização e foi adaptado?',
 '1.8 Possui regimento interno?',
 '1.9 O regimento interno é específico para este estabelecimento ou se aplica aos demais estabelecimentos do Estado?',
 '2.1 Há cela adequada/ dormitório para gestantes? (apenas para estabelecimentos com vagas para mulheres)',
 '2.2 Possui berçário e/ou centro de referência materno-infantil? (apenas para estabelecimentos com vagas para mulheres)',
 '2.2 Possui berçário e/ou centro de referência materno-infantil? (apenas para estabelecimentos com vagas para mulheres) | Sim. Capacidade de bebês: | Quantidade',
 '2.3 Possui creche? (apenas para estabelecimentos com vagas para mulheres)',
 '2.3 Possui creche? (apenas para estabelecimentos com vagas para mulheres) | Sim. Capacidade de crianças: | Quantidade',
 '2.4 Módulo de saúde | Consultório médico',
 '2.4 Módulo de saúde | Consultório médico | Quantidade',
 '2.4 Módulo de saúde | Consultório médico | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Consultório odontológico',
 '2.4 Módulo de saúde | Consultório odontológico | Quantidade',
 '2.4 Módulo de saúde | Consultório odontológico | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de coleta de material para laboratório',
 '2.4 Módulo de saúde | Sala de coleta de material para laboratório | Quantidade',
 '2.4 Módulo de saúde | Sala de coleta de material para laboratório | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de curativos, suturas, vacinas e posto de enfermagem',
 '2.4 Módulo de saúde | Sala de curativos, suturas, vacinas e posto de enfermagem | Quantidade',
 '2.4 Módulo de saúde | Sala de curativos, suturas, vacinas e posto de enfermagem | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Cela de observação',
 '2.4 Módulo de saúde | Cela de observação | Quantidade',
 '2.4 Módulo de saúde | Cela de observação | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Cela de enfermaria com solário',
 '2.4 Módulo de saúde | Cela de enfermaria com solário | Quantidade',
 '2.4 Módulo de saúde | Cela de enfermaria com solário | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sanitário para pacientes',
 '2.4 Módulo de saúde | Sanitário para pacientes | Quantidade',
 '2.4 Módulo de saúde | Sanitário para pacientes | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sanitários para equipe de saúde',
 '2.4 Módulo de saúde | Sanitários para equipe de saúde | Quantidade',
 '2.4 Módulo de saúde | Sanitários para equipe de saúde | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Farmácia ou sala de estoque/ dispensação de medicamentos',
 '2.4 Módulo de saúde | Farmácia ou sala de estoque/ dispensação de medicamentos | Quantidade',
 '2.4 Módulo de saúde | Farmácia ou sala de estoque/ dispensação de medicamentos | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Central de material esterilizado/ expurgo',
 '2.4 Módulo de saúde | Central de material esterilizado/ expurgo | Quantidade',
 '2.4 Módulo de saúde | Central de material esterilizado/ expurgo | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de lavagem e descontaminação',
 '2.4 Módulo de saúde | Sala de lavagem e descontaminação | Quantidade',
 '2.4 Módulo de saúde | Sala de lavagem e descontaminação | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de esterilização',
 '2.4 Módulo de saúde | Sala de esterilização | Quantidade',
 '2.4 Módulo de saúde | Sala de esterilização | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Vestiário',
 '2.4 Módulo de saúde | Vestiário | Quantidade',
 '2.4 Módulo de saúde | Vestiário | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Depósito de material de limpeza - DML',
 '2.4 Módulo de saúde | Depósito de material de limpeza - DML | Quantidade',
 '2.4 Módulo de saúde | Depósito de material de limpeza - DML | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de atendimento clínico multiprofissional',
 '2.4 Módulo de saúde | Sala de atendimento clínico multiprofissional | Quantidade',
 '2.4 Módulo de saúde | Sala de atendimento clínico multiprofissional | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de procedimentos',
 '2.4 Módulo de saúde | Sala de procedimentos | Quantidade',
 '2.4 Módulo de saúde | Sala de procedimentos | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de raio x',
 '2.4 Módulo de saúde | Sala de raio x | Quantidade',
 '2.4 Módulo de saúde | Sala de raio x | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Laboratório de diagnóstico',
 '2.4 Módulo de saúde | Laboratório de diagnóstico | Quantidade',
 '2.4 Módulo de saúde | Laboratório de diagnóstico | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Cela de espera',
 '2.4 Módulo de saúde | Cela de espera | Quantidade',
 '2.4 Módulo de saúde | Cela de espera | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Solário para pacientes',
 '2.4 Módulo de saúde | Solário para pacientes | Quantidade',
 '2.4 Módulo de saúde | Solário para pacientes | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Outro(s). Qual(is)?',
 '2.4 Módulo de saúde | Outro(s). Qual(is)? | Quantidade',
 '2.4 Módulo de saúde | Outro(s). Qual(is)? | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Não possui módulo de saúde',
 '2.5 Módulo de educação | Sala de aula',
 '2.5 Módulo de educação | Sala de aula | Quantidade de salas',
 '2.5 Módulo de educação | Sala de aula | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Sala de informática',
 '2.5 Módulo de educação | Sala de informática | Quantidade de salas',
 '2.5 Módulo de educação | Sala de informática | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Sala de encontros com a sociedade/ sala de reuniões',
 '2.5 Módulo de educação | Sala de encontros com a sociedade/ sala de reuniões | Quantidade de salas',
 '2.5 Módulo de educação | Sala de encontros com a sociedade/ sala de reuniões | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Biblioteca',
 '2.5 Módulo de educação | Biblioteca | Quantidade de salas',
 '2.5 Módulo de educação | Biblioteca | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Sala de professores',
 '2.5 Módulo de educação | Sala de professores | Quantidade de salas',
 '2.5 Módulo de educação | Sala de professores | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Outro(s). Qual(is)?',
 '2.5 Módulo de educação | Outro(s). Qual(is)? | Quantidade de salas',
 '2.5 Módulo de educação | Outro(s). Qual(is)? | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Não possui',
 '2.5.1 Há local específico para biblioteca?',
 '2.5.2 Há acervo de obras na biblioteca?',
 '2.5.2 Há acervo de obras na biblioteca? | Sim. Quantidade de obras: | Quantidade',
 '2.5.3 A origem do acervo da biblioteca?',
 '2.5.4 Há controle do acervo bibliotecário do estabelecimento?',
 '2.5.5 Há manutenção permanente do acervo bibliotecário do estabelecimento?',
 '2.5.5 Há manutenção permanente do acervo bibliotecário do estabelecimento? | Caso o estabelecimento possua manutenção permanente do acervo bibliotecário, qual a periodicidade de manutenção do acervo?',
 '2.6 Módulo de oficinas | Não possui',
 '2.6 Módulo de oficinas | Sala de produção',
 '2.6 Módulo de oficinas | Sala de controle/ supervisão',
 '2.6 Módulo de oficinas | Sanitários',
 '2.6 Módulo de oficinas | Estoque',
 '2.6 Módulo de oficinas | Carga/ descarga',
 '2.6 Módulo de oficinas | Outro(s). Qual(is)?',
 '2.6 Módulo de oficinas | Artefatos de concreto',
 '2.6 Módulo de oficinas | Artefatos de concreto | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Blocos e tijolos',
 '2.6 Módulo de oficinas | Blocos e tijolos | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Padaria e panificação',
 '2.6 Módulo de oficinas | Padaria e panificação | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Corte e costura industrial',
 '2.6 Módulo de oficinas | Corte e costura industrial | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Artesanato',
 '2.6 Módulo de oficinas | Artesanato | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Marcenaria',
 '2.6 Módulo de oficinas | Marcenaria | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Serralheria',
 '2.6 Módulo de oficinas | Serralheria | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Outro(s). Qual(is)? | Espaços complementares',
 '2.6 Módulo de oficinas | Outro(s). Qual(is)? | Espaços complementares | Capacidade para quantas pessoas',
 '2.7 Há local específico para visitação?',
 '2.8 Há local específico para visita íntima?',
 '2.9 Há sala de atendimento para serviço social?',
 '2.10 Há sala de atendimento para psicologia?',
 '2.11 Há local destinado ao atendimento jurídico gratuito no estabelecimento?',
 '2.12 Possui sala de videoconferência?',
 '2.13 Há cela(s)-seguro"?"',
 '2.14 Há ala ou cela destinadas exclusivamente às pessoas privadas de liberdade que se declarem lésbicas, gays, bissexuais, travestis e transexuais (LGBT)?',
 '2.14 Há ala ou cela destinadas exclusivamente às pessoas privadas de liberdade que se declarem lésbicas, gays, bissexuais, travestis e transexuais (LGBT)? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.14 Há ala ou cela destinadas exclusivamente às pessoas privadas de liberdade que se declarem lésbicas, gays, bissexuais, travestis e transexuais (LGBT)? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.15 Há ala ou cela destinada exclusivamente para idosos?',
 '2.15 Há ala ou cela destinada exclusivamente para idosos? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.15 Há ala ou cela destinada exclusivamente para idosos? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.16 Há ala ou cela destinada exclusivamente para indígenas?',
 '2.16 Há ala ou cela destinada exclusivamente para indígenas? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.16 Há ala ou cela destinada exclusivamente para indígenas? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.17 Há ala ou cela destinada exclusivamente para pessoas estrangeiras?',
 '2.17 Há ala ou cela destinada exclusivamente para pessoas estrangeiras? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.17 Há ala ou cela destinada exclusivamente para pessoas estrangeiras? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.18 Há acessibilidade para pessoas com deficiência?',
 '2.18 Há acessibilidade para pessoas com deficiência? | Sim, módulos/alas/celas adaptados em conformidade com a Norma Brasileira ABNT n. 9050, de 2004. Indique o número de vagas: | Quantidade',
 '2.18 Há acessibilidade para pessoas com deficiência? | Sim, módulos/alas/celas adaptados, não observando todos os requisitos da Norma Brasileira ABNT n. 9050, de 2004. Indique o número de vagas: | Quantidade',
 '2.19 Há terreno/ espaço disponível para construção de novos módulos?',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Terceirizado Masculino',

In [13]:
dfs = {
    2016: df16,
    2017: df17,
    2018: df18,
    2019: df19,
    2020: df20,
    2021: df21,
    2022: df22,
    2023: df23,
    2024: df24
}

In [12]:
for ano, df in dfs.items():
    print(f"{ano}: {len(df.columns)} colunas")

2016: 1327 colunas
2017: 1333 colunas
2018: 1333 colunas
2019: 1333 colunas
2020: 1333 colunas
2021: 1334 colunas
2022: 1334 colunas
2023: 1737 colunas
2024: 1737 colunas

In [11]:
colunas_por_ano = {ano: set(df.columns) for ano, df in dfs.items()}

# Mostra as diferenças ano a ano em relação ao anterior
for ano_atual in sorted(dfs.keys())[1:]:
    ano_anterior = ano_atual - 1
    colunas_atuais = colunas_por_ano[ano_atual]
    colunas_anteriores = colunas_por_ano[ano_anterior]
    
    adicionadas = colunas_atuais - colunas_anteriores
    removidas = colunas_anteriores - colunas_atuais
    
    print(f"\n {ano_atual}:")
    if adicionadas:
        print(f"Colunas adicionadas em relação a {ano_anterior}: {sorted(adicionadas)}")
    if removidas:
        print(f"Colunas removidas em relação a {ano_anterior}: {sorted(removidas)}")
    if not adicionadas and not removidas:
        print("Nenhuma mudança nas colunas.")

 2017:
Colunas adicionadas em relação a 2016: ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Comissionado Feminino', '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Comissionado Masculino', '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Efetivo Feminino', '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Efetivo Masculino', '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Temporário Feminino', '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Temporário Masculino', '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Terceirizado Feminino', '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Terceirizado Masculino', '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Órgão de lotação originária (para efetivos e comissionados)']
Colunas removidas em relação a 2016: ['5.2 Quantidade de pessoas privadas de liberdade por cor de pele/raça/etnia | Outras | Feminino', '5.2 Quantidade de pessoas privadas de liberdade por cor de pele/raça/etnia | Outras | Masculino', '5.2 Quantidade de pessoas privadas de liberdade por cor de pele/raça/etnia | Outras | Total']

 2018:
Nenhuma mudança nas colunas.

 2019:
Nenhuma mudança nas colunas.

 2020:
Nenhuma mudança nas colunas.

 2021:
Colunas adicionadas em relação a 2020: ['2.13 Há "cela(s)-seguro"?', '5.14 Quantidade de incidências por tipo penal |  GRUPO: LEGISLAÇÃO ESPECÍFICA | Grupo: Legislação específica - outros | Estatuto da Criança e do Adolescente (Lei 8.069, de 13/01/1990) | Feminino', '5.14 Quantidade de incidências por tipo penal |  GRUPO: LEGISLAÇÃO ESPECÍFICA | Grupo: Legislação específica - outros | Estatuto da Criança e do Adolescente (Lei 8.069, de 13/01/1990) | Masculino', '5.14 Quantidade de incidências por tipo penal |  GRUPO: LEGISLAÇÃO ESPECÍFICA | Grupo: Legislação específica - outros | Estatuto da Criança e do Adolescente (Lei 8.069, de 13/01/1990) | Total', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com a iniciativa privada | Setor primário - rural, agrícola e artesanato | Trabalho externo Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com a iniciativa privada | Setor primário - rural, agrícola e artesanato | Trabalho externo Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com a iniciativa privada | Setor primário - rural, agrícola e artesanato | Trabalho interno Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com a iniciativa privada | Setor primário - rural, agrícola e artesanato | Trabalho interno Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com a iniciativa privada | Setor secundário - industrial e contrução civil | Trabalho externo Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com a iniciativa privada | Setor secundário - industrial e contrução civil | Trabalho externo Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com a iniciativa privada | Setor secundário - industrial e contrução civil | Trabalho interno Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com a iniciativa privada | Setor secundário - industrial e contrução civil | Trabalho interno Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor primário - rural, agrícola e artesanato | Total', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor primário - rural, agrícola e artesanato | Trabalho externo Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor primário - rural, agrícola e artesanato | Trabalho externo Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor primário - rural, agrícola e artesanato | Trabalho interno Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor primário - rural, agrícola e artesanato | Trabalho interno Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor secundário - industrial e contrução civil | Total', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor secundário - industrial e contrução civil | Trabalho externo Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor secundário - industrial e contrução civil | Trabalho externo Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor secundário - industrial e contrução civil | Trabalho interno Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor secundário - industrial e contrução civil | Trabalho interno Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor terciário - serviços | Total', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor terciário - serviços | Trabalho externo Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor terciário - serviços | Trabalho externo Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor terciário - serviços | Trabalho interno Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor terciário - serviços | Trabalho interno Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com outros órgãos públicos | Setor primário - rural, agrícola e artesanato | Trabalho externo Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com outros órgãos públicos | Setor primário - rural, agrícola e artesanato | Trabalho externo Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com outros órgãos públicos | Setor primário - rural, agrícola e artesanato | Trabalho interno Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com outros órgãos públicos | Setor primário - rural, agrícola e artesanato | Trabalho interno Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com outros órgãos públicos | Setor secundário - industrial e contrução civil | Trabalho externo Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com outros órgãos públicos | Setor secundário - industrial e contrução civil | Trabalho externo Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com outros órgãos públicos | Setor secundário - industrial e contrução civil | Trabalho interno Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com outros órgãos públicos | Setor secundário - industrial e contrução civil | Trabalho interno Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas obtidas por meios próprios e/ou sem intervenção do sistema prisional | Setor secundário - industrial e contrução civil | Trabalho externo Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas obtidas por meios próprios e/ou sem intervenção do sistema prisional | Setor secundário - industrial e contrução civil | Trabalho externo Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas obtidas por meios próprios e/ou sem intervenção do sistema prisional | Setor secundário - industrial e contrução civil | Trabalho interno Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas obtidas por meios próprios e/ou sem intervenção do sistema prisional | Setor secundário - industrial e contrução civil | Trabalho interno Masculino', '7.5 Foi realizada visita(s) de inspeção no período de referência? | Outro(s). Qual?']

In [14]:
df_todos = df_todos[df_todos['Tipo do Estabelecimento']=='Cela física']
df_todos

,ciclo,Ano,Referência,Tipo do Estabelecimento,Situação de Preenchimento,Nome do Estabelecimento,Situação do Estabelecimento,Outras Denominações,Endereço,Bairro,...,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tonga | Masculino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tonga | Feminino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tonga | Total,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tuvalu | Masculino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tuvalu | Feminino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tuvalu | Total,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Vanuatu | Masculino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Vanuatu | Feminino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Vanuatu | Total,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Outros países do continente Oceania | Total
1,1,2016,2016/2,Cela física,Validado,UNIDADE DE RECOLHIMENTO PROVISORIO,Ativo,NaN,Estrada do Barro Vermelho km 3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO FEMININO,Ativo,NaN,ESTRADA DO BARRO VERMELHO KM03,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N1,Ativo,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N2,Ativo,NaN,ESTRADA DO BARRO VERMELHO - KM 03,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N3,Ativo,NaN,ESTRADA DIAS MARTINS KM 05 S/N ATRÁS DO BOPE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1558,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Brasília,Ativo,NaN,Rod DF-465 KM 01 - Complexo Penitenciário da P...,Setor Habitacional Jardim Botânico,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1559,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Campo Grande,Ativo,NaN,AVENIDA HENRIQUE BERTIN S/N JARDIM LOS ANGELES,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1560,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Catanduvas,Ativo,NaN,"Rodovia PR 471, Km 15, s/n",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1561,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Mossoró,Ativo,NaN,"RN 15, Km 13, Estrada Mossoró/Baraúnas - Mosso...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1562,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Porto Velho,Ativo,NaN,"SÍTIO DA BOA ESPERANÇA, LOTE 13, GLEBA 13 ""A"" ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df_todos.columns.to_list()

['ciclo',
 'Ano',
 'Referência',
 'Tipo do Estabelecimento',
 'Situação de Preenchimento',
 'Nome do Estabelecimento',
 'Situação do Estabelecimento',
 'Outras Denominações',
 'Endereço',
 'Bairro',
 'CEP',
 'Âmbito',
 'UF',
 'Município',
 'Código IBGE',
 'Telefone Principal',
 '1.1 Estabelecimento originalmente destinado a pessoa privadas de liberdade do sexo',
 '1.2 Tipo de estabelecimento - originalmente destinado',
 '1.3 Capacidade do estabelecimento | Presos provisórios | Masculino',
 '1.3 Capacidade do estabelecimento | Presos provisórios | Feminino',
 '1.3 Capacidade do estabelecimento | Presos provisórios | Total',
 '1.3 Capacidade do estabelecimento | Regime fechado | Masculino',
 '1.3 Capacidade do estabelecimento | Regime fechado | Feminino',
 '1.3 Capacidade do estabelecimento | Regime fechado | Total',
 '1.3 Capacidade do estabelecimento | Regime semiaberto | Masculino',
 '1.3 Capacidade do estabelecimento | Regime semiaberto | Feminino',
 '1.3 Capacidade do estabelecimento | Regime semiaberto | Total',
 '1.3 Capacidade do estabelecimento | Regime aberto | Masculino',
 '1.3 Capacidade do estabelecimento | Regime aberto | Feminino',
 '1.3 Capacidade do estabelecimento | Regime aberto | Total',
 '1.3 Capacidade do estabelecimento | Regime Disciplinar Diferenciado (RDD) | Masculino',
 '1.3 Capacidade do estabelecimento | Regime Disciplinar Diferenciado (RDD) | Feminino',
 '1.3 Capacidade do estabelecimento | Regime Disciplinar Diferenciado (RDD) | Total',
 '1.3 Capacidade do estabelecimento | Medidas de segurança de internação | Masculino',
 '1.3 Capacidade do estabelecimento | Medidas de segurança de internação | Feminino',
 '1.3 Capacidade do estabelecimento | Medidas de segurança de internação | Total',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)?',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)? | Masculino',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)? | Feminino',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)? | Total',
 '1.3 Capacidade do estabelecimento | Masculino | Total',
 '1.3 Capacidade do estabelecimento | Feminino | Total',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Celas não aptas',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Vagas desativadas - Masculino',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Vagas desativadas - Feminino',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Total de vagas desativadas',
 '1.4 Gestão do estabelecimento',
 '1.5 Quais serviços são terceirizados? | Nenhum',
 '1.5 Quais serviços são terceirizados? | Alimentação',
 '1.5 Quais serviços são terceirizados? | Limpeza',
 '1.5 Quais serviços são terceirizados? | Lavanderia',
 '1.5 Quais serviços são terceirizados? | Saúde',
 '1.5 Quais serviços são terceirizados? | Segurança',
 '1.5 Quais serviços são terceirizados? | Assistência educacional',
 '1.5 Quais serviços são terceirizados? | Assistência laboral',
 '1.5 Quais serviços são terceirizados? | Assistência social',
 '1.5 Quais serviços são terceirizados? | Assistência jurídica',
 '1.5 Quais serviços são terceirizados? | Serviços administrativos',
 '1.5 Quais serviços são terceirizados? | Outro',
 '1.6 Data de inauguração do estabelecimento',
 '1.7 O estabelecimento foi concebido como estabelecimento penal ou foi construído para outra utilização e foi adaptado?',
 '1.8 Possui regimento interno?',
 '1.9 O regimento interno é específico para este estabelecimento ou se aplica aos demais estabelecimentos do Estado?',
 '2.1 Há cela adequada/ dormitório para gestantes? (apenas para estabelecimentos com vagas para mulheres)',
 '2.2 Possui berçário e/ou centro de referência materno-infantil? (apenas para estabelecimentos com vagas para mulheres)',
 '2.2 Possui berçário e/ou centro de referência materno-infantil? (apenas para estabelecimentos com vagas para mulheres) | Sim. Capacidade de bebês: | Quantidade',
 '2.3 Possui creche? (apenas para estabelecimentos com vagas para mulheres)',
 '2.3 Possui creche? (apenas para estabelecimentos com vagas para mulheres) | Sim. Capacidade de crianças: | Quantidade',
 '2.4 Módulo de saúde | Consultório médico',
 '2.4 Módulo de saúde | Consultório médico | Quantidade',
 '2.4 Módulo de saúde | Consultório médico | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Consultório odontológico',
 '2.4 Módulo de saúde | Consultório odontológico | Quantidade',
 '2.4 Módulo de saúde | Consultório odontológico | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de coleta de material para laboratório',
 '2.4 Módulo de saúde | Sala de coleta de material para laboratório | Quantidade',
 '2.4 Módulo de saúde | Sala de coleta de material para laboratório | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de curativos, suturas, vacinas e posto de enfermagem',
 '2.4 Módulo de saúde | Sala de curativos, suturas, vacinas e posto de enfermagem | Quantidade',
 '2.4 Módulo de saúde | Sala de curativos, suturas, vacinas e posto de enfermagem | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Cela de observação',
 '2.4 Módulo de saúde | Cela de observação | Quantidade',
 '2.4 Módulo de saúde | Cela de observação | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Cela de enfermaria com solário',
 '2.4 Módulo de saúde | Cela de enfermaria com solário | Quantidade',
 '2.4 Módulo de saúde | Cela de enfermaria com solário | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sanitário para pacientes',
 '2.4 Módulo de saúde | Sanitário para pacientes | Quantidade',
 '2.4 Módulo de saúde | Sanitário para pacientes | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sanitários para equipe de saúde',
 '2.4 Módulo de saúde | Sanitários para equipe de saúde | Quantidade',
 '2.4 Módulo de saúde | Sanitários para equipe de saúde | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Farmácia ou sala de estoque/ dispensação de medicamentos',
 '2.4 Módulo de saúde | Farmácia ou sala de estoque/ dispensação de medicamentos | Quantidade',
 '2.4 Módulo de saúde | Farmácia ou sala de estoque/ dispensação de medicamentos | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Central de material esterilizado/ expurgo',
 '2.4 Módulo de saúde | Central de material esterilizado/ expurgo | Quantidade',
 '2.4 Módulo de saúde | Central de material esterilizado/ expurgo | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de lavagem e descontaminação',
 '2.4 Módulo de saúde | Sala de lavagem e descontaminação | Quantidade',
 '2.4 Módulo de saúde | Sala de lavagem e descontaminação | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de esterilização',
 '2.4 Módulo de saúde | Sala de esterilização | Quantidade',
 '2.4 Módulo de saúde | Sala de esterilização | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Vestiário',
 '2.4 Módulo de saúde | Vestiário | Quantidade',
 '2.4 Módulo de saúde | Vestiário | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Depósito de material de limpeza - DML',
 '2.4 Módulo de saúde | Depósito de material de limpeza - DML | Quantidade',
 '2.4 Módulo de saúde | Depósito de material de limpeza - DML | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de atendimento clínico multiprofissional',
 '2.4 Módulo de saúde | Sala de atendimento clínico multiprofissional | Quantidade',
 '2.4 Módulo de saúde | Sala de atendimento clínico multiprofissional | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de procedimentos',
 '2.4 Módulo de saúde | Sala de procedimentos | Quantidade',
 '2.4 Módulo de saúde | Sala de procedimentos | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de raio x',
 '2.4 Módulo de saúde | Sala de raio x | Quantidade',
 '2.4 Módulo de saúde | Sala de raio x | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Laboratório de diagnóstico',
 '2.4 Módulo de saúde | Laboratório de diagnóstico | Quantidade',
 '2.4 Módulo de saúde | Laboratório de diagnóstico | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Cela de espera',
 '2.4 Módulo de saúde | Cela de espera | Quantidade',
 '2.4 Módulo de saúde | Cela de espera | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Solário para pacientes',
 '2.4 Módulo de saúde | Solário para pacientes | Quantidade',
 '2.4 Módulo de saúde | Solário para pacientes | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Outro(s). Qual(is)?',
 '2.4 Módulo de saúde | Outro(s). Qual(is)? | Quantidade',
 '2.4 Módulo de saúde | Outro(s). Qual(is)? | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Não possui módulo de saúde',
 '2.5 Módulo de educação | Sala de aula',
 '2.5 Módulo de educação | Sala de aula | Quantidade de salas',
 '2.5 Módulo de educação | Sala de aula | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Sala de informática',
 '2.5 Módulo de educação | Sala de informática | Quantidade de salas',
 '2.5 Módulo de educação | Sala de informática | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Sala de encontros com a sociedade/ sala de reuniões',
 '2.5 Módulo de educação | Sala de encontros com a sociedade/ sala de reuniões | Quantidade de salas',
 '2.5 Módulo de educação | Sala de encontros com a sociedade/ sala de reuniões | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Biblioteca',
 '2.5 Módulo de educação | Biblioteca | Quantidade de salas',
 '2.5 Módulo de educação | Biblioteca | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Sala de professores',
 '2.5 Módulo de educação | Sala de professores | Quantidade de salas',
 '2.5 Módulo de educação | Sala de professores | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Outro(s). Qual(is)?',
 '2.5 Módulo de educação | Outro(s). Qual(is)? | Quantidade de salas',
 '2.5 Módulo de educação | Outro(s). Qual(is)? | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Não possui',
 '2.5.1 Há local específico para biblioteca?',
 '2.5.2 Há acervo de obras na biblioteca?',
 '2.5.2 Há acervo de obras na biblioteca? | Sim. Quantidade de obras: | Quantidade',
 '2.5.3 A origem do acervo da biblioteca?',
 '2.5.4 Há controle do acervo bibliotecário do estabelecimento?',
 '2.5.5 Há manutenção permanente do acervo bibliotecário do estabelecimento?',
 '2.5.5 Há manutenção permanente do acervo bibliotecário do estabelecimento? | Caso o estabelecimento possua manutenção permanente do acervo bibliotecário, qual a periodicidade de manutenção do acervo?',
 '2.6 Módulo de oficinas | Não possui',
 '2.6 Módulo de oficinas | Sala de produção',
 '2.6 Módulo de oficinas | Sala de controle/ supervisão',
 '2.6 Módulo de oficinas | Sanitários',
 '2.6 Módulo de oficinas | Estoque',
 '2.6 Módulo de oficinas | Carga/ descarga',
 '2.6 Módulo de oficinas | Outro(s). Qual(is)?',
 '2.6 Módulo de oficinas | Artefatos de concreto',
 '2.6 Módulo de oficinas | Artefatos de concreto | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Blocos e tijolos',
 '2.6 Módulo de oficinas | Blocos e tijolos | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Padaria e panificação',
 '2.6 Módulo de oficinas | Padaria e panificação | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Corte e costura industrial',
 '2.6 Módulo de oficinas | Corte e costura industrial | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Artesanato',
 '2.6 Módulo de oficinas | Artesanato | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Marcenaria',
 '2.6 Módulo de oficinas | Marcenaria | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Serralheria',
 '2.6 Módulo de oficinas | Serralheria | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Outro(s). Qual(is)? | Espaços complementares',
 '2.6 Módulo de oficinas | Outro(s). Qual(is)? | Espaços complementares | Capacidade para quantas pessoas',
 '2.7 Há local específico para visitação?',
 '2.8 Há local específico para visita íntima?',
 '2.9 Há sala de atendimento para serviço social?',
 '2.10 Há sala de atendimento para psicologia?',
 '2.11 Há local destinado ao atendimento jurídico gratuito no estabelecimento?',
 '2.12 Possui sala de videoconferência?',
 '2.13 Há cela(s)-seguro"?"',
 '2.14 Há ala ou cela destinadas exclusivamente às pessoas privadas de liberdade que se declarem lésbicas, gays, bissexuais, travestis e transexuais (LGBT)?',
 '2.14 Há ala ou cela destinadas exclusivamente às pessoas privadas de liberdade que se declarem lésbicas, gays, bissexuais, travestis e transexuais (LGBT)? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.14 Há ala ou cela destinadas exclusivamente às pessoas privadas de liberdade que se declarem lésbicas, gays, bissexuais, travestis e transexuais (LGBT)? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.15 Há ala ou cela destinada exclusivamente para idosos?',
 '2.15 Há ala ou cela destinada exclusivamente para idosos? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.15 Há ala ou cela destinada exclusivamente para idosos? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.16 Há ala ou cela destinada exclusivamente para indígenas?',
 '2.16 Há ala ou cela destinada exclusivamente para indígenas? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.16 Há ala ou cela destinada exclusivamente para indígenas? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.17 Há ala ou cela destinada exclusivamente para pessoas estrangeiras?',
 '2.17 Há ala ou cela destinada exclusivamente para pessoas estrangeiras? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.17 Há ala ou cela destinada exclusivamente para pessoas estrangeiras? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.18 Há acessibilidade para pessoas com deficiência?',
 '2.18 Há acessibilidade para pessoas com deficiência? | Sim, módulos/alas/celas adaptados em conformidade com a Norma Brasileira ABNT n. 9050, de 2004. Indique o número de vagas: | Quantidade',
 '2.18 Há acessibilidade para pessoas com deficiência? | Sim, módulos/alas/celas adaptados, não observando todos os requisitos da Norma Brasileira ABNT n. 9050, de 2004. Indique o número de vagas: | Quantidade',
 '2.19 Há terreno/ espaço disponível para construção de novos módulos?',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Terceirizado Masculino',

In [15]:
df_todos['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Outros. Especificar:'].str.lower().unique()

array([nan, 'farmacêutico', 'serviços gerais / agente de portaria',
       'nutricionista', 'cinofilos',
       'agente de postaria / motorista / sergiços gerais', 'adhoc',
       'adhocs e desvio de função', 'desvio de função',
       'adhocs e cozinheiras', '2 cozinheiras e 1 serviços gerais',
       '3 ad hoc e 1 cozinheira', '1 cozinheira', 'serviços gerais',
       'ad hoc', '1 desvio de função e 2 ad hoc', '2 ad hoc',
       'cozinheira', 'ad-hoc', 'adhoc e cozinheira', 'cozinheiro',
       'ad-hoc e desvio de função', 'ad hoc, desvio de função',
       'ah doc e desvio de função', 'operador rx e auxiliar de farmácia',
       'bombeiro militar', 'farmaceutico, delegada de policia, limpeza',
       'auxiliar de serviços gerais', 'assistente administrativo',
       'á disposição', 'municipio',
       'encarregado de segurança e disciplina e encarregada de tesouraria',
       'técnico em contabilidade (01)', '01- especialista juridica',
       'datilografo', 'auxiliar de segurança penitenciaria',
       'funcionários e estagiarios contratados', 'estagiarios',
       'condutor de segurança',
       'nutricionista, instrutor de mecânica, tratador de animais, marceneiro, motorista, supervisor de atividades agrícolas',
       'inspetoras de segurança', 'tesouraria',
       'analista técnico jurídico', 'gerente de trabalho  eprodução',
       'diretor de atendimento e ressocialização (comissionado)',
       'oficial de serviços gerais', 'farmacêutica', 'administrador',
       'nutricionista / farmaceutica',
       'nutricionista, farmacêuticos, educador físico', 'educador físico',
       'auxiliar operacional', 'coordenador de segurança', 'motorista',
       'auxiliar operacional 03 e tecnico agricola 01',
       '3 agentes de portaria, 2 agentes operacionas, 1 auxiliar de serviços operacioais',
       '2 funcionários em desvio de função.', 'chefe de farmácia',
       'assistente de ressocialização', 'auxiliar de serviços diversos',
       'serviços diversos', 'agente de apoio',
       '03 auxiliar de manutenção, 03 auxiliar operacional, 01 telefonista',
       'farmaceutico',
       'agente penitenciário em atividade exclusiva no patronato',
       'oficial de manutenção',
       'técnica de raio x/bioquimica/nutricionista/farmaceutico',
       'monitor penitenciário (cargo extinto)',
       'pessoas da instituição, mas não lotadas na casa',
       'secretaria de escola',
       '03 - pm rr convocados (cetisp -sc) e 01 - operador maquinas',
       'oficial operacional motorista e serviços gerais',
       'auxiliar serviços gerais e oficial operacional',
       'oficial operacional',
       'oficial operacional, auxiliar de serviços e atendente à saúde',
       'nuticionista, farmacêutica e oficial operacional', 'aevp',
       'oficial operacional / auxiliar de serviçoes gerais',
       'auxiliar de serviços gerais, oficial operacional, tec. laborátorio, aux. laboratório',
       'auxiliar de laboratório',
       'técnico de laboratório, auxiliar de serviços gerais, oficial operacional',
       '3 motoritas e 1 mestre de oficio',
       'oficial operacional- motorista - 03,  oficial operacional - barbeiro - 01,  oficial operacional -cozinheiro(a) - 02,  oficial operacional - mecânico - 01,  oficial operacional - pedreiro - 02',
       '05 motorista masc., 05 aux. serv. gerais masc, 03 aux. serv. geriais fem, 01 cozinhiero masc.,01 cozinheiros fem, 01 serralheiro.',
       'oficial operacional encanador', 'auxiliar de manutenção',
       '01 farmacêutico masculino / 01 aux. de laboratório feminino / 05 oficiais operacionais masculinos / 01 oficial operacional feminino / 02 aux. de serviços gerais masculinos',
       'enfermeiros',
       'oficial operacional/auxiliar serviços gerais/farmaceutica',
       'oficial operacional (motorista)',
       'farmacêutica, técnico de laboratório',
       '02 farmacêutico f/02 of. operaconal, sendo 01 cabelereiro-m e 01 motorista-m',
       'auxiliar de laborátório',
       'policial militar do efetivo do bope que fazem guarda e segurança da unidade em regime de escala de 24x72h',
       'educador social', 'estagiários', 'servidores terceirizados',
       'vigilantes', 'ad hoc / cozinheira', 'serv. gerais e conzinheiro',
       'desvio da função', 'desvio de função e ad hoc',
       'ad hoc e desvio de função', 'ad hoc e desviod de função',
       'desfio de func + ad hoc',
       'tec. telep 1 + encarregado alm 1 +bomb. hidra. 1 + eletricista 1 + motorista 2',
       'auxiliar de serviços hospitalares', 'fisioterapeuta',
       '- especialista juridica', 'padeiro/oficinas',
       'condutor de segurança e administrativo, inspetor de segurança',
       'inspetor de segurança -', 'técnico em informática', 'diretores',
       'nutricionista / educador fisico / farmaceutico', 'motoristas',
       'limpeza', 'fonoaudiológa', 'cargo de direção',
       '02- auxiliar de manutenção, 02- auxiliar operacional, 01- telefonista,02 técnicos administrativos pertencentes a seed, 01 auxiliar operacional da seed.',
       'técnica de raio x/bioquimica~/nutricionista/farmaceutica/secretário neeja',
       'farmaceuticos', 'farmaceutica', 'farmaceútica/auxiliar de saúde',
       'auxiliar de serviços gerais/',
       'auxiliar de serviços gerais e oficial operacional',
       'oficial operacional, auxiliar de serviços',
       'auxiliar de laboratório, auxiliar de serviços gerais, farmacêutica, nutricionista, oficial operacional, auxiliar de saúde',
       'auxiliar e técnico de laboratório',
       'oficial operacional e auxiliar de serviços gerais',
       'oficial operacional  - motorista 03, oficial operacional - barbeiro 01, oficial operacional cozinheiro(a) 02, oficial operacional - mecânico 01, oficial operacional - pedreiro 02, auxiliar de serviços gerais 01, auxiliar de laboratório 01',
       'auxiliar de serviços gerais (1 masc. 1 fem.) oficial operacional (1 masc. 2 fem.)',
       'ofic.oper../ téc.labor./aux.labor./aux.serv. gerais',
       'farmacêutico/oficial operacional/auxiliar de serviços geraisl',
       'asg', 'auxiliares de serviços gerais', 'vigia e educador social',
       'motorista/nutricionista', 'vigilantes/ motoristas',
       'motorista/agente portaria/nutricionista',
       'nutricionista/motorista', 'motorista / nutricionista',
       'adhoc/desvio de função', 'serv. gerais', 'adhocs', 'outros',
       'desvio de finção', 'desvio de função/adhoc', 'desvio função',
       'ad hoc / desvio de função', 'desvio função  + ad hoc',
       'operador de raio x, auxiliar de farmácia e desvio de função',
       'desvio de funçao',
       'tec. teleprocessamento + almoxarife + bomb, hidraulico +eletricista + motorista = aux. farmácia',
       'auxiliar de farmácia', 'farmacêutico e delegada de polícia',
       'farmaceutico e auxiliar de farmacia',
       'farmacêutico, auxiliar farmácia e nutricionista',
       'cartório unidade prisional', 'professora educação física',
       'voluntário',
       'funcionários, estagiários e técnicos contratados pela associação',
       'inspetores de segurança',
       'nutricionista, instrutor de mecânica, tratador de animais, marceneiro, motorista, supervisor de atividades agrícolas e serralheiro',
       'professora', 'estagiários de direito', 'atj', 'capelão',
       'enfermeira, nutrucionista fisioterapelta, farmaceutico',
       'auxiliar operacional e motorista',
       'assistente agrícola e socióloga', 'guarda patrimonial',
       'nutricionista/fisioterapeuta',
       'ha 03 prestadores de serviços 01 na limpeza e 02 na cozinha.',
       'fisioterapeuta 01 / fonoaudióloga 02',
       '01 farmacêutico - 01 nutricionista',
       '02 - auxiliar de manutenção, 02 auxiliar operacional, 02 técnicos administrativos pertencentes a seed, 01 - auxiliar operacional da seed, central de transporte - 06 motoristas,  - 12 agentes penitenciários.',
       'conselheiro da comunidade',
       'supervisores, coordenador administrativo e operacional, motorista,  técnico em informática,, oficial de manutenção, manutenção, eletrecista, copeira, auxiliar de serviços gerais, secretária, coordenadora adm e pessoa, encarregada do setor de prontuários, almoxarife, técnico em segurança do trabalho, telefonista. gerente operacional, farmacêutico.',
       'agentes de escolta e vigilância penitenciária 40 + oficial operacional 01',
       'advogado da fundação "prof dr manoel pedro pimentel" funap',
       'oficial operacional / auxiliar de serviços',
       'farmacêutica, auxiliar de saúde, nutricionista e técnico de laboratório',
       'oficial operacional, auxiliar de serviços, técnico laboratório',
       'farmacêutico - assessor i',
       'outros. especificar: oficial operacional ¿ motorista 03, oficial operacional barbeiro 01, oficial operacional cozinheiro (a) 02, oficial operacional mecânico 01, oficial operacional pedreiro 02, auxiliar de serviços gerais 01, auxiliar de laboratório 01',
       'aux. serviços gerais 1 masc. 1 fem. e oficial operacional 1masc. 2 fem.',
       'oficial operacional,  auxiliar serviços gerais, farmaceutica',
       'oficial operacional/auxiliar serviços gerais/farmaceutico',
       'operador de microssistema e auxiliar de serviços gerais',
       '1 assistente administrativo,  1 motorista, 1 auxiliar de serviços gerais',
       'monitores de ressocialização prisional',
       'técnico em laboratório/motorista/vigilantes',
       'motoristas/ portaria', 'vigilantes/motorista',
       'motoristas/ag. portaria/nutricionista', 'cinófilos, motoristas',
       'nutricionistas',
       'nutricionista / tec de nutriçaõ/motorista/tec de odontologia/motorista/limpeza/portaria',
       'nutricionista e motorista',
       'divisão de prontuários / identificação / sistemas',
       'téc. em teleprocessamento de dados + enc. de almoxarifado + bomb. hidráulico + eletricista + motorista + aux. de farmácia + aux. de serviços gerais',
       'aux. farmácia', 'motorista/administrativo/limpeza',
       'auxiliar administrativo setor de saúde',
       'estagiário/ auxiliar administrativo',
       'auxiliar de farmacia e farmaceutica',
       'farmaceutica/ auxiliar de famarcia', 'psicologa',
       'nutricionista / farmaceutica / ed. fisico',
       'nutricionista e auxiliar operacional', 'diretor',
       'socióloga, assistente agropecuária, auxiliar agropecuário e auxiliar operacional',
       'prestador de serviços', 'agente de segurança',
       'defensora pública, educadora física, fisioterapeuta',
       '04 prestadores de serviço / 01 auxiliar de limpeza / 03 cozinheiras',
       '1 farmacêutico e 2 nutricionistas', 'estagiário',
       'agentes penitenciarios',
       '02 - auxiliar de manutenção. 01 - auxiliar operacional. 02 - técnicos administrativos da escola. 01 - auxiliar operacional da escola, 05 - motoristas e 12 agentes penitenciários da central de transporte, 32 - agentes penitenciários que atuam do grupo soe (seção de operações especiais,orgão que atende unidades penais e delegacias da região.',
       'advogado', 'técnico em radiologia',
       'farmacêutico 01, técnico de segurança do trabalho 01, gerente administrativo 01, almoxarife 02, auxiliares de serviços gerais 04, coordenador de rh 01, copeira 01, eletricista 01, encarregada do setor de prontuários 01, motorista 03, oficialde manutenção 01, pedreiro 03, secretária 01, técnico em informática 01, telefonista 02, coordenador administrativo 01, coordenador operacional 01, supervisor operacional 04.',
       'motorista/porteiro', 'aux de saúde e farmacêutica',
       'oficial operacional -motorista/ auxiliar de serviços gerais',
       'advogados da funap',
       'aux. de serviços gerais e oficial operacional',
       'farmacêutico, nutricionista e tec. laboratório',
       'auxiliar laboratório', 'técnico/auxiliar laboratório',
       'técnico de laboratório', 'farmacêuticos e acessor i',
       'oficial operacional - motorista 03, oficial operacional - barbeiro 01, oficial operacional - cozinheiro(a)  02, oficial operacional - mecânico 01, oficial operacional - pedreiro 02, auxililar de serviçõs gerais - 01 auxiliar de laboratório  - 01',
       '1 masc: motorista, 1 fem: assistente técnica de saúde farmacêutica',
       'aux.serv.gerais, auxil. laboratório,ofic. operac. e técn. laboratório',
       'técnico/auxiliar de laboratório',
       'oficial operacional /  auxiliar serviços gerais /   farmaceutica',
       'auxiliar de laboratório, nutricionista', 'auxiliar ii',
       'portaria e motorista', 'farcacêutica/ nutricionista / motorista',
       'servidor administrativo', 'atribuição administrativa',
       'auxiliar de farmácia: 1 feminino terceirizado, auxiliar de serviços gerais: 1 feminino terceirizado, 4 masculino terceirizado, bombeiro hidráulico: 1 masculino terceirizado, eletricista: 1 masculino terceirizado, encarregado de almoxarifado: 1 masculino terceirizado, motorista: 2 masculino terceirizado, técnico em teleprocessamento de dados: 1 masculino terceirizado',
       'auxiliar administrativo',
       'auxiliar administrativo e farmaceutico',
       'fisioterapeuta e nutricionista', 'direção',
       'farmaceutico/bioiquimica', 'manutenção predial',
       'agente de portaria e auxiliar', 'gerente administrativo',
       'secretaria', 'farmacêutico/fisioterapeuta/nutricionista',
       '03- agentes de apoio, 01- diretora da  escola,02 técnicos administrativos da escola, 01- auxiliar operacional da escola,05- motoristas, 12- agentes penitenciários da central de transportes,33- agentes penitenciários que atuam no soe(sessão de operações especiais,órgão que atende unidades penais e delegacias da região.',
       'agente comunitária', 'auxilliar de serviços gerais',
       'oficial de manutençao', 'policial penal',
       'auxiliar de saude / famaceutico',
       'advogado fundação pedro pimentel - funap',
       'farmacêutico/auxiliar de saúde/nutricionista/auxiliar de laboratório',
       'técnico / auxiliar de laboratório',
       'técnico de laboratório e farmacêutico', 'técnico em laboratório',
       'agente técnico de de assistência a saúde - farmacêutico',
       'ag. tec. de assit.  a saúde (farmacêutico)',
       'técnico e auxiliar de laboratório', '1 farmacêutica fem.',
       'auxiliar de laboratório e técnico de laboratório',
       'farmacêutico e nutricionista',
       'oficial operacional/auxiliar de serviços',
       'farmacêutico e técnico lab.', 'farmaceuticas',
       'oficial operacional, auxiliar de serviços gerais, auxiliar de laboratório e farmacêutica.',
       'operador de cftv', 'auxiliar 02',
       'especificar: os servidores que atendem na upmns são os mesmos que atendem na guimarães lima',
       'motorista/higienização/fisio', 'educador fisico', 'cinófilos',
       'cozinha', 'servente e motorista',
       'farmaceutica / nutricionista / motorista / administrativo',
       'educador físico, desvio de função, t.i, aux. de farmácia, psicólogo, serviços gerais e eletricista.',
       'auxiliar de serviços gerais: 4 masculinos terceirizados, 1 feminino terceirizado, auxiliar técnico: 1 masculino terceirizado, bombeiro hidráulico: 1 masculino terceirizado, eletricista: 1 masculino terceirizado, encarregado de almoxarifado: 1 masculino terceirizado, motorista: 2 masculinos terceirizados, técnico em teleprocessamento de dados: 2 masculinos terceirizados',
       'bombeiro', 'farmaceutico/auxiliar de farmacia', 'diretora',
       'equipe epmc atua na duas unidades',
       'grupo de escolta penitenciário',
       'cope - guarda das muralhas externas', 'famaceutico',
       'outras funções/afastados diversos',
       'agente de portaria e auxiliar de serv. operacionais',
       'aux. operacional',
       'técnico em agropecuária, motoristas, ag de portaria e artes práticas',
       'aux. operacional e assist. agropecuário', 'secretária',
       'farmaceutico/fisioterapeuta/nutricionista', 'cozinheiros',
       '01-diretora da escola, 02 - técnicoa administrativos da escola, 01- auxiliar operacional da escola, 03- motoristas, 20 - policiais penais da central de transportes, 38 - policiais penais que atuam no soe (setor de operações especiais orgão que atende unidades penais e delegacias da região.',
       'agente de saúde', 'farmacêutica e nutricionista',
       'agente de segurança socioeducativo',
       '03 auxiliar operacional de serviços diversos', 'farmárcia',
       'vigilante', 'farmacêutico/nutricionista',
       'policial militar da reserva ctisp', 'serviço de portaria',
       'oficial operacional - motorista',
       'fundação "dr manoel pedro pimentel" funap',
       'nutricionista / tec. laboratório', 'técnico em laborátório',
       'ag. téc. de assist. a saúde (farmacêutico)',
       'auxiliar de laboratório, técnico de laratório',
       'oficial operacional/auxiliar de serviços gerais',
       'oficial operacional, aux. de serviços gerais',
       'operador de cftv (monitoramento)',
       '01 farmacêutico e 29 agentes penitenciários estaduais (ftip)',
       'os servidores que atendem na upmns são os mesmos que atendem na guimarães lima',
       'grupo de intervenção', 'niutricionaistas',
       'nutricionista/serviços gerais/tecnico de laboratório',
       'motorista e servente',
       'nutricionista/fisioterapeuta/farmacêutico/tec.laboratório',
       'jovem aprendiz',
       'farmaceutica, nutricionista, motoriista, adm e fisioterapia',
       'serviços gerais (limpeza)', 'tecnico farmacia',
       'assistente administrativa',
       'nutricionista/aux adm/aux de farmácia',
       'padeiro, estagiário jurídico, contadora', 'segurança',
       '2 supervisora de oficina/ cozinheira',
       '1 estagiário jurídico, 1 estagiária em serviço social e 1 estagiária em pedagogia',
       '1 cozinheira, 2 supervisores de oficina e 2 estagiários de direito',
       '1 terceirizado masculino',
       '7 (sendo duas supervisoras de oficinas, dois padeiro, dois estágiarios de direito, uma estágiaria de comunicação)',
       '6 (sendo duas supervisoras de oficina, uma cozinheiro e três estágiarios)',
       '1 motorista, 2 padeiros 1 cozinheira',
       'supervisores de oficinas 02,  secretárias 02, auxiliares administrativos 03, encarregados 03, gerentes-geral 01, dentista 01, condutor de segurança 03, estagiários 03, psicólogo 01, assistente social 01, auxiliar de serviços gerais 02',
       '4 administrativo, 2 finaceiro, 2 estagiárias jurídicas, 2 supervisores',
       'estagiárias', 'cozinheira 1,', '1',
       'servidores das carreiras de analista e de assistente de especialidades não listadas acima',
       '"servidores das carreiras de analista e de assistente de especialidades não listadas acima."',
       'servidores das carreiras de analista e de assistente de especialidades não listadas acima.',
       'servidores efetivos das carreiras de analista e de assistente de especialidades não listadas acima',
       'https://twitter.com/juliorochareal/status/1614340393989963777?s=20&t=-pe9jr9v8z3k_mfyhsbdcg',
       'servidores efetivos das carreiras de analista e de assistente de especialidades não listadas acima.',
       '0',
       '"servidores efetivos das carreiras de analista e de assistente de especialidades não listadas acima."',
       '2', 'são domingos goiás',
       'educado fisico / nuticionista / farmaceutica',
       'assistente agropecuário e auxiliar operacional',
       'assistente administrativa e auxiliar operacional',
       'auxiliar operacional e assistente de agropecuária',
       'farmacêuticos', 'ceasa',
       '01- dentista voluntário 01- diretora da escola 02- agentes de apoio 02- téc. adm da escola 01- auxiliar de apoio da escola 03- motoristas 42- sse (policial penal transporte) 34- policiais penais (soe) orgão que atende as unidades penais e delegacias da região.',
       'farmácia',

In [15]:
df_todos = pd.concat(dfs, ignore_index=True)
df_todos = df_todos[df_todos['Tipo do Estabelecimento']=='Cela física']
df_todos

,ciclo,Ano,Referência,Tipo do Estabelecimento,Situação de Preenchimento,Nome do Estabelecimento,Situação do Estabelecimento,Outras Denominações,Endereço,Bairro,...,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tonga | Masculino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tonga | Feminino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tonga | Total,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tuvalu | Masculino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tuvalu | Feminino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tuvalu | Total,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Vanuatu | Masculino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Vanuatu | Feminino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Vanuatu | Total,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Outros países do continente Oceania | Total
1,1,2016,2016/2,Cela física,Validado,UNIDADE DE RECOLHIMENTO PROVISORIO,Ativo,NaN,Estrada do Barro Vermelho km 3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO FEMININO,Ativo,NaN,ESTRADA DO BARRO VERMELHO KM03,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N1,Ativo,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N2,Ativo,NaN,ESTRADA DO BARRO VERMELHO - KM 03,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N3,Ativo,NaN,ESTRADA DIAS MARTINS KM 05 S/N ATRÁS DO BOPE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13666,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Brasília,Ativo,NaN,Rod DF-465 KM 01 - Complexo Penitenciário da P...,Setor Habitacional Jardim Botânico,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13667,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Campo Grande,Ativo,NaN,AVENIDA HENRIQUE BERTIN S/N JARDIM LOS ANGELES,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13668,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Catanduvas,Ativo,NaN,"Rodovia PR 471, Km 15, s/n",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13669,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Mossoró,Ativo,NaN,"RN 15, Km 13, Estrada Mossoró/Baraúnas - Mosso...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13670,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Porto Velho,Ativo,NaN,"SÍTIO DA BOA ESPERANÇA, LOTE 13, GLEBA 13 ""A"" ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
col_masc = [
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Estadual Masculino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Federal Masculino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Estadual Masculino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Federal Masculino',
    '4.1 População prisional | Medida de segurança - internação | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Estadual Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Federal Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Outros(Just. Trab., cível) Masculino'
]

col_fem = [
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Estadual Feminino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Federal Feminino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Estadual Feminino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Federal Feminino',
    '4.1 População prisional | Medida de segurança - internação | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Estadual Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Federal Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Outros(Just. Trab., cível) Feminino'
]

In [15]:
medicos_total = df_todos[['Ano',
            'Nome do Estabelecimento',
            'Âmbito','UF', 'Município', 'Código IBGE',
            '1.1 Estabelecimento originalmente destinado a pessoa privadas de liberdade do sexo',
            '1.2 Tipo de estabelecimento - originalmente destinado',
            '1.3 Capacidade do estabelecimento | Masculino | Total',
            '1.3 Capacidade do estabelecimento | Feminino | Total',
            '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total',
            '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total',
            '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total',
            '4.1 População prisional | Total'
            ]]
medicos_total # sem psiquiatras

,Ano,Nome do Estabelecimento,Âmbito,UF,Município,Código IBGE,1.1 Estabelecimento originalmente destinado a pessoa privadas de liberdade do sexo,1.2 Tipo de estabelecimento - originalmente destinado,1.3 Capacidade do estabelecimento | Masculino | Total,1.3 Capacidade do estabelecimento | Feminino | Total,3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total,3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total,3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total,4.1 População prisional | Total
1,2016,UNIDADE DE RECOLHIMENTO PROVISORIO,Estadual,AC,Rio Branco,1200401.0,Masculino,Estabelecimento destinado ao recolhimento de p...,200.0,NaN,5.0,1.0,NaN,1102.0
2,2016,UNIDADE DE REGIME FECHADO FEMININO,Estadual,AC,Rio Branco,1200401.0,Feminino,Estabelecimento destinado ao cumprimento de pe...,0.0,80.0,NaN,NaN,NaN,241.0
3,2016,UNIDADE DE REGIME FECHADO N1,Estadual,AC,Rio Branco,1200401.0,Masculino,Estabelecimento destinado ao cumprimento de pe...,1584.0,NaN,3.0,1.0,NaN,1985.0
4,2016,UNIDADE DE REGIME FECHADO N2,Estadual,AC,Rio Branco,1200401.0,Masculino,Estabelecimento destinado ao cumprimento de pe...,77.0,0.0,1.0,0.0,0.0,61.0
5,2016,UNIDADE DE REGIME FECHADO N3,Estadual,AC,Rio Branco,1200401.0,Misto,Estabelecimento destinado ao cumprimento de pe...,81.0,9.0,1.0,NaN,NaN,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13666,2024,Penitenciária Federal em Brasília,Federal,DF,Brasília,5300108.0,Masculino,Estabelecimento destinado ao cumprimento de pe...,208.0,NaN,1.0,NaN,13.0,72.0
13667,2024,Penitenciária Federal em Campo Grande,Federal,MS,Campo Grande,5002704.0,Masculino,Estabelecimento destinado ao cumprimento de pe...,208.0,NaN,1.0,NaN,13.0,129.0
13668,2024,Penitenciária Federal em Catanduvas,Federal,PR,Catanduvas,4105003.0,Masculino,Estabelecimento destinado ao cumprimento de pe...,208.0,NaN,1.0,0.0,13.0,125.0
13669,2024,Penitenciária Federal em Mossoró,Federal,RN,Mossoró,2408003.0,Masculino,Estabelecimento destinado ao cumprimento de pe...,208.0,NaN,1.0,NaN,13.0,79.0
13670,2024,Penitenciária Federal em Porto Velho,Federal,RO,Porto Velho,1100205.0,Masculino,Estabelecimento destinado ao cumprimento de pe...,208.0,0.0,1.0,0.0,13.0,122.0

In [ ]:
df_todos['Tipo do Estabelecimento'].unique()

In [41]:
enf = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total'].sum()
aux_enf= df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total'].sum()
psi = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total'].sum()
dent = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Total'].sum()
tec_dent = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Total'].sum()
assits = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Assistentes sociais | Total'].sum()
adv = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Advogados | Total'].sum()
med_geral = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total'].sum()
med_gineco = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total'].sum()
med_psiq = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – psiquiatras | Total'].sum()
med_outros = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total'].sum()
ped = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Pedagogos | Total'].sum()
prof= df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Professores | Total'].sum()
terapeuta_ocup = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Terapeuta/ terapeuta ocupacional | Total'].sum()

In [42]:
enf = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total'].sum()
aux_enf= df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total'].sum()
psi = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total'].sum()
dent = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Total'].sum()
tec_dent = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Total'].sum()
assits = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Assistentes sociais | Total'].sum()
adv = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Advogados | Total'].sum()
med_geral = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total'].sum()
med_gineco = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total'].sum()
med_psiq = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – psiquiatras | Total'].sum()
med_outros = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total'].sum()
ped = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Pedagogos | Total'].sum()
prof= df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Professores | Total'].sum()
terapeuta_ocup = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Terapeuta/ terapeuta ocupacional | Total'].sum()

In [9]:
col_medicos_fisica = [
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total',
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total',
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total'
]

col_medicos_mental = [
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total',
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – psiquiatras | Total',
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Terapeuta/ terapeuta ocupacional | Total'
]

col_enfs = [
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total',
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total'
]

col_assits = [
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Assistentes sociais | Total'
]

col_odonto = [
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Total',
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Total'
]

col_pop = '4.1 População prisional | Total'

col_gineco = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total']

In [10]:
resultados = []
dfs = [df16, df17, df18, df19, df20, df21, df22, df23, df24]
anos = list(range(2016, 2025))  # de 2016 a 2024

In [18]:
for df, ano in zip(dfs, anos):
    # Filtrando apenas celas físicas
    df = df[df['Tipo do Estabelecimento'] == 'Cela física'].copy()  # .copy() evita avisos de atribuição encadeada

    # Conversão para numérico
    for col_group in [col_medicos_fisica, col_medicos_mental, col_enfs, col_assits, col_masc, col_fem]:
        for col in col_group:
            df.loc[:, col] = pd.to_numeric(df[col], errors='coerce')

    df.loc[:, col_pop] = pd.to_numeric(df[col_pop], errors='coerce')

    # Cálculo de totais por linha com .loc
    df.loc[:, 'total_medicos_fisica'] = df[col_medicos_fisica].sum(axis=1)
    df.loc[:, 'total_medicos_mental'] = df[col_medicos_mental].sum(axis=1)
    df.loc[:, 'total_enfs'] = df[col_enfs].sum(axis=1)
    df.loc[:, 'total_assits'] = df[col_assits].sum(axis=1)
    df.loc[:, 'pop_masc'] = df[col_masc].sum(axis=1)
    df.loc[:, 'pop_fem'] = df[col_fem].sum(axis=1)
    df.loc[:, 'pop_total'] = df[col_pop]
    df.loc[:, 'ano'] = ano


    # Agrupamento por UF e ano
    grupo = df.groupby(['UF', 'ano'])[
        ['total_medicos_fisica', 'total_medicos_mental', 'total_enfs', 'total_assits',
         'pop_masc', 'pop_fem', 'pop_total']
    ].sum().reset_index()

    resultados.append(grupo)

# Concatenação dos resultados
saude_area_populacao_ano_uf = pd.concat(resultados, ignore_index=True)

In [19]:
saude_area_populacao_ano_uf

,UF,ano,total_medicos_fisica,total_medicos_mental,total_enfs,total_assits,pop_masc,pop_fem,pop_total
0,AC,2016,14.0,15.0,33.0,21.0,4955.0,330.0,5285.0
1,AL,2016,4.0,20.0,70.0,15.0,6700.0,411.0,7111.0
2,AM,2016,13.0,25.0,62.0,25.0,8510.0,1731.0,10241.0
3,AP,2016,3.0,21.0,15.0,11.0,2831.0,106.0,2937.0
4,BA,2016,29.0,84.0,173.0,50.0,13088.0,508.0,13596.0
...,...,...,...,...,...,...,...,...,...
238,RS,2024,71.0,161.0,158.0,167.0,34443.0,1714.0,36157.0
239,SC,2024,62.0,76.0,188.0,65.0,25901.0,1448.0,27349.0
240,SE,2024,13.0,24.0,104.0,21.0,5801.0,233.0,6034.0
241,SP,2024,173.0,204.0,791.0,196.0,196839.0,9145.0,205984.0
242,TO,2024,10.0,13.0,37.0,19.0,3734.0,154.0,3888.0

In [33]:
saude_area_populacao_ano_uf['medicos_fisica_por_1000'] = (
    saude_area_populacao_ano_uf['total_medicos_fisica'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000

saude_area_populacao_ano_uf['medicos_mental_por_1000'] = (
    saude_area_populacao_ano_uf['total_medicos_mental'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000

saude_area_populacao_ano_uf['total_enfs_por_1000'] = (
    saude_area_populacao_ano_uf['total_enfs'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000
saude_area_populacao_ano_uf['total_assits_por_1000'] = (
    saude_area_populacao_ano_uf['total_assits'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000
saude_area_populacao_ano_uf

,UF,ano,total_medicos_fisica,total_medicos_mental,total_enfs,total_assits,pop_masc,pop_fem,pop_total,medicos_fisica_por_1000,medicos_mental_por_1000,total_enfs_por_1000,total_assits_por_1000
0,AC,2016,14.0,15.0,33.0,21.0,4955.0,330.0,5285.0,2.649007,2.838221,6.244087,3.973510
1,AL,2016,4.0,20.0,70.0,15.0,6700.0,411.0,7111.0,0.562509,2.812544,9.843904,2.109408
2,AM,2016,13.0,25.0,62.0,25.0,8510.0,1731.0,10241.0,1.269407,2.441168,6.054096,2.441168
3,AP,2016,3.0,21.0,15.0,11.0,2831.0,106.0,2937.0,1.021450,7.150153,5.107252,3.745318
4,BA,2016,29.0,84.0,173.0,50.0,13088.0,508.0,13596.0,2.132980,6.178288,12.724331,3.677552
...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,RS,2024,71.0,161.0,158.0,167.0,34443.0,1714.0,36157.0,1.963658,4.452803,4.369832,4.618746
239,SC,2024,62.0,76.0,188.0,65.0,25901.0,1448.0,27349.0,2.266993,2.778895,6.874109,2.376687
240,SE,2024,13.0,24.0,104.0,21.0,5801.0,233.0,6034.0,2.154458,3.977461,17.235665,3.480278
241,SP,2024,173.0,204.0,791.0,196.0,196839.0,9145.0,205984.0,0.839871,0.990368,3.840104,0.951530
242,TO,2024,10.0,13.0,37.0,19.0,3734.0,154.0,3888.0,2.572016,3.343621,9.516461,4.886831

In [34]:
medicos_fisica_pop = saude_area_populacao_ano_uf[['ano','UF','total_medicos_fisica', 'pop_total', 'medicos_fisica_por_1000']]
medicos_fisica_pop

      ano  UF  total_medicos_fisica  pop_total  medicos_fisica_por_1000
0    2016  AC                  14.0     5285.0                 2.649007
1    2016  AL                   4.0     7111.0                 0.562509
2    2016  AM                  13.0    10241.0                 1.269407
3    2016  AP                   3.0     2937.0                 1.021450
4    2016  BA                  29.0    13596.0                 2.132980
..    ...  ..                   ...        ...                      ...
238  2024  RS                  71.0    36157.0                 1.963658
239  2024  SC                  62.0    27349.0                 2.266993
240  2024  SE                  13.0     6034.0                 2.154458
241  2024  SP                 173.0   205984.0                 0.839871
242  2024  TO                  10.0     3888.0                 2.572016

[243 rows x 5 columns]

In [36]:
medicos_fisica_pop['profissao'] = 'Médicos (Clinicos gerais, ginecologistas e outras especialidades)'

C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_2264\835226405.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  medicos_fisica_pop['profissao'] = 'Médicos (Clinicos gerais, ginecologistas e outras especialidades)'

In [38]:
medicos_fisica_pop.columns

Index(['ano', 'UF', 'total_medicos_fisica', 'pop_total',
       'medicos_fisica_por_1000', 'profissao'],
      dtype='object')

In [39]:
medicos_fisica_pop = medicos_fisica_pop[['ano', 'UF', 'profissao', 'total_medicos_fisica', 'pop_total',
       'medicos_fisica_por_1000']]
medicos_fisica_pop

,ano,UF,profissao,total_medicos_fisica,pop_total,medicos_fisica_por_1000
0,2016,AC,"Médicos (Clinicos gerais, ginecologistas e out...",14.0,5285.0,2.649007
1,2016,AL,"Médicos (Clinicos gerais, ginecologistas e out...",4.0,7111.0,0.562509
2,2016,AM,"Médicos (Clinicos gerais, ginecologistas e out...",13.0,10241.0,1.269407
3,2016,AP,"Médicos (Clinicos gerais, ginecologistas e out...",3.0,2937.0,1.021450
4,2016,BA,"Médicos (Clinicos gerais, ginecologistas e out...",29.0,13596.0,2.132980
...,...,...,...,...,...,...
238,2024,RS,"Médicos (Clinicos gerais, ginecologistas e out...",71.0,36157.0,1.963658
239,2024,SC,"Médicos (Clinicos gerais, ginecologistas e out...",62.0,27349.0,2.266993
240,2024,SE,"Médicos (Clinicos gerais, ginecologistas e out...",13.0,6034.0,2.154458
241,2024,SP,"Médicos (Clinicos gerais, ginecologistas e out...",173.0,205984.0,0.839871
242,2024,TO,"Médicos (Clinicos gerais, ginecologistas e out...",10.0,3888.0,2.572016

In [11]:
resultado_gineco = []

In [12]:
for df, ano in zip(dfs, anos):
    # Filtrando apenas celas físicas
    df = df[df['Tipo do Estabelecimento'] == 'Cela física'].copy()  # .copy() evita avisos de atribuição encadeada

    # Conversão para numérico
    for col_group in [col_medicos_fisica, col_gineco]:
        for col in col_group:
            df.loc[:, col] = pd.to_numeric(df[col], errors='coerce')

    df.loc[:, col_pop] = pd.to_numeric(df[col_pop], errors='coerce')

    # Cálculo de totais por linha com .loc
    df.loc[:, 'total_medicos_fisica'] = df[col_medicos_fisica].sum(axis=1)
    df.loc[:, 'total_ginecologistas'] = df[col_gineco].sum(axis=1)
    df.loc[:, 'pop_fem'] = df[col_fem].sum(axis=1)
    df.loc[:, 'pop_total'] = df[col_pop]
    df.loc[:, 'ano'] = ano


    # Agrupamento por UF e ano
    grupo = df.groupby(['UF', 'ano'])[
        ['total_medicos_fisica','total_ginecologistas', 'pop_fem', 'pop_total']
    ].sum().reset_index()

    resultado_gineco.append(grupo)

# Concatenação dos resultados
gineco_area_populacao_ano_uf = pd.concat(resultado_gineco, ignore_index=True)

In [ ]:
medicos_fisica_pop.info()

In [13]:
gineco_area_populacao_ano_uf

     UF   ano  total_medicos_fisica  total_ginecologistas  pop_fem  pop_total
0    AC  2016                  14.0                   2.0    330.0     5285.0
1    AL  2016                   4.0                   0.0    411.0     7111.0
2    AM  2016                  13.0                   0.0   1731.0    10241.0
3    AP  2016                   3.0                   2.0    106.0     2937.0
4    BA  2016                  29.0                   3.0    508.0    13596.0
..   ..   ...                   ...                   ...      ...        ...
238  RS  2024                  71.0                   0.0   1714.0    36157.0
239  SC  2024                  62.0                   0.0   1448.0    27349.0
240  SE  2024                  13.0                   0.0    233.0     6034.0
241  SP  2024                 173.0                   7.0   9145.0   205984.0
242  TO  2024                  10.0                   0.0    154.0     3888.0

[243 rows x 6 columns]

In [15]:
df24_gineco = gineco_area_populacao_ano_uf[gineco_area_populacao_ano_uf['ano']==2024]
df24_gineco['total_ginecologistas'].value_counts()

total_ginecologistas
0.0    19
2.0     4
1.0     1
3.0     1
5.0     1
7.0     1
Name: count, dtype: int64

In [20]:
df24_gineco.sort_values(by='total_ginecologistas', ascending= False )

     UF   ano  total_medicos_fisica  total_ginecologistas  pop_fem  pop_total
241  SP  2024                 173.0                   7.0   9145.0   205984.0
234  RJ  2024                 129.0                   5.0   1668.0    46115.0
232  PI  2024                  36.0                   3.0    258.0     7198.0
218  AM  2024                  16.0                   2.0    172.0     5111.0
220  BA  2024                  59.0                   2.0    392.0    13721.0
221  CE  2024                  40.0                   2.0    913.0    22296.0
228  MT  2024                  25.0                   2.0    825.0    13735.0
225  MA  2024                  77.0                   1.0    375.0    11743.0
216  AC  2024                   6.0                   0.0    205.0     5401.0
240  SE  2024                  13.0                   0.0    233.0     6034.0
239  SC  2024                  62.0                   0.0   1448.0    27349.0
238  RS  2024                  71.0                   0.0   1714.0    36157.0
237  RR  2024                   9.0                   0.0    160.0     3258.0
236  RO  2024                  38.0                   0.0    336.0     7466.0
235  RN  2024                  34.0                   0.0    356.0     7499.0
233  PR  2024                  76.0                   0.0   2378.0    40699.0
229  PA  2024                  26.0                   0.0    631.0    15498.0
231  PE  2024                  53.0                   0.0    924.0    28983.0
230  PB  2024                  28.0                   0.0    618.0    12410.0
217  AL  2024                  18.0                   0.0    150.0     5240.0
227  MS  2024                  58.0                   0.0    962.0    16662.0
226  MG  2024                 175.0                   0.0   2628.0    66282.0
224  GO  2024                  60.0                   0.0    805.0    18489.0
223  ES  2024                  83.0                   0.0   1019.0    24117.0
222  DF  2024                  32.0                   0.0    559.0    16200.0
219  AP  2024                   9.0                   0.0    109.0     3257.0
242  TO  2024                  10.0                   0.0    154.0     3888.0

In [25]:
gineco_area_populacao_ano_uf = gineco_area_populacao_ano_uf.rename(
                                            columns={'UF':'sigla_uf'                                  
                                            })
gineco_area_populacao_ano_uf

,sigla_uf,ano,total_medicos_fisica,total_ginecologistas,pop_fem,pop_total
0,AC,2016,14.0,2.0,330.0,5285.0
1,AL,2016,4.0,0.0,411.0,7111.0
2,AM,2016,13.0,0.0,1731.0,10241.0
3,AP,2016,3.0,2.0,106.0,2937.0
4,BA,2016,29.0,3.0,508.0,13596.0
...,...,...,...,...,...,...
238,RS,2024,71.0,0.0,1714.0,36157.0
239,SC,2024,62.0,0.0,1448.0,27349.0
240,SE,2024,13.0,0.0,233.0,6034.0
241,SP,2024,173.0,7.0,9145.0,205984.0
242,TO,2024,10.0,0.0,154.0,3888.0

In [41]:
medicos_fisica_pop = medicos_fisica_pop.rename(
                                            columns={'UF':'sigla_uf'                                  
                                            })
medicos_fisica_pop

,ano,sigla_uf,profissao,total_medicos_fisica,pop_total,medicos_fisica_por_1000
0,2016,AC,"Médicos (Clinicos gerais, ginecologistas e out...",14.0,5285.0,2.649007
1,2016,AL,"Médicos (Clinicos gerais, ginecologistas e out...",4.0,7111.0,0.562509
2,2016,AM,"Médicos (Clinicos gerais, ginecologistas e out...",13.0,10241.0,1.269407
3,2016,AP,"Médicos (Clinicos gerais, ginecologistas e out...",3.0,2937.0,1.021450
4,2016,BA,"Médicos (Clinicos gerais, ginecologistas e out...",29.0,13596.0,2.132980
...,...,...,...,...,...,...
238,2024,RS,"Médicos (Clinicos gerais, ginecologistas e out...",71.0,36157.0,1.963658
239,2024,SC,"Médicos (Clinicos gerais, ginecologistas e out...",62.0,27349.0,2.266993
240,2024,SE,"Médicos (Clinicos gerais, ginecologistas e out...",13.0,6034.0,2.154458
241,2024,SP,"Médicos (Clinicos gerais, ginecologistas e out...",173.0,205984.0,0.839871
242,2024,TO,"Médicos (Clinicos gerais, ginecologistas e out...",10.0,3888.0,2.572016

In [42]:
medicos_fisica_pop['medicos_fisica_por_1000_1']= medicos_fisica_pop['medicos_fisica_por_1000'].round(2)
medicos_fisica_pop

,ano,sigla_uf,profissao,total_medicos_fisica,pop_total,medicos_fisica_por_1000,medicos_fisica_por_1000_1
0,2016,AC,"Médicos (Clinicos gerais, ginecologistas e out...",14.0,5285.0,2.649007,2.65
1,2016,AL,"Médicos (Clinicos gerais, ginecologistas e out...",4.0,7111.0,0.562509,0.56
2,2016,AM,"Médicos (Clinicos gerais, ginecologistas e out...",13.0,10241.0,1.269407,1.27
3,2016,AP,"Médicos (Clinicos gerais, ginecologistas e out...",3.0,2937.0,1.021450,1.02
4,2016,BA,"Médicos (Clinicos gerais, ginecologistas e out...",29.0,13596.0,2.132980,2.13
...,...,...,...,...,...,...,...
238,2024,RS,"Médicos (Clinicos gerais, ginecologistas e out...",71.0,36157.0,1.963658,1.96
239,2024,SC,"Médicos (Clinicos gerais, ginecologistas e out...",62.0,27349.0,2.266993,2.27
240,2024,SE,"Médicos (Clinicos gerais, ginecologistas e out...",13.0,6034.0,2.154458,2.15
241,2024,SP,"Médicos (Clinicos gerais, ginecologistas e out...",173.0,205984.0,0.839871,0.84
242,2024,TO,"Médicos (Clinicos gerais, ginecologistas e out...",10.0,3888.0,2.572016,2.57

In [44]:
medicos_fisica_pop[medicos_fisica_pop['ano']==2024]

,ano,sigla_uf,profissao,total_medicos_fisica,pop_total,medicos_fisica_por_1000,medicos_fisica_por_1000_1
216,2024,AC,"Médicos (Clinicos gerais, ginecologistas e out...",6.0,5401.0,1.110905,1.11
217,2024,AL,"Médicos (Clinicos gerais, ginecologistas e out...",18.0,5240.0,3.435115,3.44
218,2024,AM,"Médicos (Clinicos gerais, ginecologistas e out...",16.0,5111.0,3.130503,3.13
219,2024,AP,"Médicos (Clinicos gerais, ginecologistas e out...",9.0,3257.0,2.763279,2.76
220,2024,BA,"Médicos (Clinicos gerais, ginecologistas e out...",59.0,13721.0,4.299978,4.30
221,2024,CE,"Médicos (Clinicos gerais, ginecologistas e out...",40.0,22296.0,1.794044,1.79
222,2024,DF,"Médicos (Clinicos gerais, ginecologistas e out...",32.0,16200.0,1.975309,1.98
223,2024,ES,"Médicos (Clinicos gerais, ginecologistas e out...",83.0,24117.0,3.441556,3.44
224,2024,GO,"Médicos (Clinicos gerais, ginecologistas e out...",60.0,18489.0,3.245173,3.25
225,2024,MA,"Médicos (Clinicos gerais, ginecologistas e out...",77.0,11743.0,6.557098,6.56
226,2024,MG,"Médicos (Clinicos gerais, ginecologistas e out...",175.0,66282.0,2.640234,2.64
227,2024,MS,"Médicos (Clinicos gerais, ginecologistas e out...",58.0,16662.0,3.480975,3.48
228,2024,MT,"Médicos (Clinicos gerais, ginecologistas e out...",25.0,13735.0,1.820167,1.82
229,2024,PA,"Médicos (Clinicos gerais, ginecologistas e out...",26.0,15498.0,1.677636,1.68
230,2024,PB,"Médicos (Clinicos gerais, ginecologistas e out...",28.0,12410.0,2.256245,2.26
231,2024,PE,"Médicos (Clinicos gerais, ginecologistas e out...",53.0,28983.0,1.828658,1.83
232,2024,PI,"Médicos (Clinicos gerais, ginecologistas e out...",36.0,7198.0,5.001389,5.00
233,2024,PR,"Médicos (Clinicos gerais, ginecologistas e out...",76.0,40699.0,1.867368,1.87
234,2024,RJ,"Médicos (Clinicos gerais, ginecologistas e out...",129.0,46115.0,2.797354,2.80
235,2024,RN,"Médicos (Clinicos gerais, ginecologistas e out...",34.0,7499.0,4.533938,4.53
236,2024,RO,"Médicos (Clinicos gerais, ginecologistas e out...",38.0,7466.0,5.089740,5.09
237,2024,RR,"Médicos (Clinicos gerais, ginecologistas e out...",9.0,3258.0,2.762431,2.76
238,2024,RS,"Médicos (Clinicos gerais, ginecologistas e out...",71.0,36157.0,1.963658,1.96
239,2024,SC,"Médicos (Clinicos gerais, ginecologistas e out...",62.0,27349.0,2.266993,2.27
240,2024,SE,"Médicos (Clinicos gerais, ginecologistas e out...",13.0,6034.0,2.154458,2.15
241,2024,SP,"Médicos (Clinicos gerais, ginecologistas e out...",173.0,205984.0,0.839871,0.84
242,2024,TO,"Médicos (Clinicos gerais, ginecologistas e out...",10.0,3888.0,2.572016,2.57

In [57]:
a = medicos_fisica_pop[medicos_fisica_pop['ano']==2024]
a.sort_values(by='medicos_fisica_por_1000_1', ascending=True)

,ano,sigla_uf,profissao,total_medicos_fisica,pop_total,medicos_fisica_por_1000,medicos_fisica_por_1000_1
241,2024,SP,"Médicos (Clinicos gerais, ginecologistas e out...",173.0,205984.0,0.839871,0.84
216,2024,AC,"Médicos (Clinicos gerais, ginecologistas e out...",6.0,5401.0,1.110905,1.11
229,2024,PA,"Médicos (Clinicos gerais, ginecologistas e out...",26.0,15498.0,1.677636,1.68
221,2024,CE,"Médicos (Clinicos gerais, ginecologistas e out...",40.0,22296.0,1.794044,1.79
228,2024,MT,"Médicos (Clinicos gerais, ginecologistas e out...",25.0,13735.0,1.820167,1.82
231,2024,PE,"Médicos (Clinicos gerais, ginecologistas e out...",53.0,28983.0,1.828658,1.83
233,2024,PR,"Médicos (Clinicos gerais, ginecologistas e out...",76.0,40699.0,1.867368,1.87
238,2024,RS,"Médicos (Clinicos gerais, ginecologistas e out...",71.0,36157.0,1.963658,1.96
222,2024,DF,"Médicos (Clinicos gerais, ginecologistas e out...",32.0,16200.0,1.975309,1.98
240,2024,SE,"Médicos (Clinicos gerais, ginecologistas e out...",13.0,6034.0,2.154458,2.15
230,2024,PB,"Médicos (Clinicos gerais, ginecologistas e out...",28.0,12410.0,2.256245,2.26
239,2024,SC,"Médicos (Clinicos gerais, ginecologistas e out...",62.0,27349.0,2.266993,2.27
242,2024,TO,"Médicos (Clinicos gerais, ginecologistas e out...",10.0,3888.0,2.572016,2.57
226,2024,MG,"Médicos (Clinicos gerais, ginecologistas e out...",175.0,66282.0,2.640234,2.64
237,2024,RR,"Médicos (Clinicos gerais, ginecologistas e out...",9.0,3258.0,2.762431,2.76
219,2024,AP,"Médicos (Clinicos gerais, ginecologistas e out...",9.0,3257.0,2.763279,2.76
234,2024,RJ,"Médicos (Clinicos gerais, ginecologistas e out...",129.0,46115.0,2.797354,2.80
218,2024,AM,"Médicos (Clinicos gerais, ginecologistas e out...",16.0,5111.0,3.130503,3.13
224,2024,GO,"Médicos (Clinicos gerais, ginecologistas e out...",60.0,18489.0,3.245173,3.25
217,2024,AL,"Médicos (Clinicos gerais, ginecologistas e out...",18.0,5240.0,3.435115,3.44
223,2024,ES,"Médicos (Clinicos gerais, ginecologistas e out...",83.0,24117.0,3.441556,3.44
227,2024,MS,"Médicos (Clinicos gerais, ginecologistas e out...",58.0,16662.0,3.480975,3.48
220,2024,BA,"Médicos (Clinicos gerais, ginecologistas e out...",59.0,13721.0,4.299978,4.30
235,2024,RN,"Médicos (Clinicos gerais, ginecologistas e out...",34.0,7499.0,4.533938,4.53
232,2024,PI,"Médicos (Clinicos gerais, ginecologistas e out...",36.0,7198.0,5.001389,5.00
236,2024,RO,"Médicos (Clinicos gerais, ginecologistas e out...",38.0,7466.0,5.089740,5.09
225,2024,MA,"Médicos (Clinicos gerais, ginecologistas e out...",77.0,11743.0,6.557098,6.56

In [66]:
medicos_fisica_pop.columns

Index(['ano', 'sigla_uf', 'profissao', 'total_medicos_fisica', 'pop_total',
       'medicos_fisica_por_1000', 'medicos_fisica_por_1000_1'],
      dtype='object')

In [65]:
a.sort_values(by='medicos_fisica_por_1000_1', ascending=True)

,ano,sigla_uf,profissao,total_medicos_fisica,pop_total,medicos_fisica_por_1000,medicos_fisica_por_1000_1
241,2024,SP,"Médicos (Clinicos gerais, ginecologistas e out...",173.0,205984.0,0.839871,0.84
216,2024,AC,"Médicos (Clinicos gerais, ginecologistas e out...",6.0,5401.0,1.110905,1.11
229,2024,PA,"Médicos (Clinicos gerais, ginecologistas e out...",26.0,15498.0,1.677636,1.68
221,2024,CE,"Médicos (Clinicos gerais, ginecologistas e out...",40.0,22296.0,1.794044,1.79
228,2024,MT,"Médicos (Clinicos gerais, ginecologistas e out...",25.0,13735.0,1.820167,1.82
231,2024,PE,"Médicos (Clinicos gerais, ginecologistas e out...",53.0,28983.0,1.828658,1.83
233,2024,PR,"Médicos (Clinicos gerais, ginecologistas e out...",76.0,40699.0,1.867368,1.87
238,2024,RS,"Médicos (Clinicos gerais, ginecologistas e out...",71.0,36157.0,1.963658,1.96
222,2024,DF,"Médicos (Clinicos gerais, ginecologistas e out...",32.0,16200.0,1.975309,1.98
240,2024,SE,"Médicos (Clinicos gerais, ginecologistas e out...",13.0,6034.0,2.154458,2.15
230,2024,PB,"Médicos (Clinicos gerais, ginecologistas e out...",28.0,12410.0,2.256245,2.26
239,2024,SC,"Médicos (Clinicos gerais, ginecologistas e out...",62.0,27349.0,2.266993,2.27
242,2024,TO,"Médicos (Clinicos gerais, ginecologistas e out...",10.0,3888.0,2.572016,2.57
226,2024,MG,"Médicos (Clinicos gerais, ginecologistas e out...",175.0,66282.0,2.640234,2.64
237,2024,RR,"Médicos (Clinicos gerais, ginecologistas e out...",9.0,3258.0,2.762431,2.76
219,2024,AP,"Médicos (Clinicos gerais, ginecologistas e out...",9.0,3257.0,2.763279,2.76
234,2024,RJ,"Médicos (Clinicos gerais, ginecologistas e out...",129.0,46115.0,2.797354,2.80
218,2024,AM,"Médicos (Clinicos gerais, ginecologistas e out...",16.0,5111.0,3.130503,3.13
224,2024,GO,"Médicos (Clinicos gerais, ginecologistas e out...",60.0,18489.0,3.245173,3.25
217,2024,AL,"Médicos (Clinicos gerais, ginecologistas e out...",18.0,5240.0,3.435115,3.44
223,2024,ES,"Médicos (Clinicos gerais, ginecologistas e out...",83.0,24117.0,3.441556,3.44
227,2024,MS,"Médicos (Clinicos gerais, ginecologistas e out...",58.0,16662.0,3.480975,3.48
220,2024,BA,"Médicos (Clinicos gerais, ginecologistas e out...",59.0,13721.0,4.299978,4.30
235,2024,RN,"Médicos (Clinicos gerais, ginecologistas e out...",34.0,7499.0,4.533938,4.53
232,2024,PI,"Médicos (Clinicos gerais, ginecologistas e out...",36.0,7198.0,5.001389,5.00
236,2024,RO,"Médicos (Clinicos gerais, ginecologistas e out...",38.0,7466.0,5.089740,5.09
225,2024,MA,"Médicos (Clinicos gerais, ginecologistas e out...",77.0,11743.0,6.557098,6.56

In [26]:
client = bigquery.Client()
dataset_ref = client.dataset('perfil_remuneracao')

In [36]:
df_2024 = gineco_area_populacao_ano_uf[gineco_area_populacao_ano_uf['ano']==2024]

In [40]:
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt

# Carregar GeoJSON dos estados do Brasil
url = "https://raw.githubusercontent.com/codeforamerica/click_that_hood/master/public/data/brazil-states.geojson"
mapa_estados = gpd.read_file(url)

In [ ]:
gineco_area_populacao_ano_uf[gineco_area_populacao_ano_uf['ano']==2024].sum()

670792.0

In [29]:
gineco_area_populacao_ano_uf.columns

Index(['sigla_uf', 'ano', 'total_medicos_fisica', 'total_ginecologistas',
       'pop_fem', 'pop_total'],
      dtype='object')

In [46]:

schema=[bigquery.SchemaField('ano','INTEGER',description='Ano de referencia'),
 bigquery.SchemaField('sigla_uf','STRING',description='Sigla da Unidade da Federação.'),
 bigquery.SchemaField('profissao','STRING',description='Profissional'),
 bigquery.SchemaField('total_medicos_fisica','FLOAT',description='Quantidade de médicos responsáveis pela saúde física'),
 bigquery.SchemaField('pop_total','FLOAT',description='Total da população prisional'),
 bigquery.SchemaField('medicos_fisica_por_1000','FLOAT',description='Taxa de médicos por 1000 presos')
 ]

In [47]:
table_ref = dataset_ref.table('SENAPPEN_medico_saude_fisica_mil_presos') 
job_config = bigquery.LoadJobConfig(schema=schema)
job = client.load_table_from_dataframe(medicos_fisica_pop, table_ref, job_config=job_config)
job.result()

LoadJob<project=repositoriodedadosgpsp, location=US, id=477b810e-427c-401a-8b65-dc079d6b5e46>