In [ ]:
# Install required Google Cloud packages (commented out as these are typically one-time setup commands)
!pip install gcloud
!gcloud auth application-default login

# Import necessary Python libraries
import pandas as pd                # Data manipulation and analysis
import numpy as np                 # Numerical computing
import time                        # Time-related functions
import os                          # Operating system interfaces
import pandas_gbq                  # Pandas integration with BigQuery
from google.cloud import bigquery  # BigQuery client library
import glob                        # File path pattern matching
import openpyxl                    # Excel file handling
import csv                         # CSV file handling
import re                          # Regular expressions

# Note: The actual imports remain exactly as in the original code

In [ ]:
df = pd.read_csv('/content/19o-ciclo-base-de-dados-2025-2-semestre.csv', encoding= 'utf8', sep=';')

/tmp/ipykernel_2633/1061426035.py:1: DtypeWarning: Columns (389) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/19o-ciclo-base-de-dados-2025-2-semestre.csv', encoding= 'utf8', sep=';')

In [ ]:
diretorio = 'G:\\Drives compartilhados\\República.org\\4. Equipes\\Dados e Comunicação\\DADOS E CONHECIMENTO\\460 - Estudos e Infográficos\\20 - Sistema prisional\\bases de dados'

In [ ]:
os.chdir(diretorio)

In [ ]:
df16 = pd.read_csv('1o-ciclo-base-de-dados-2016-2-semestre.csv', encoding= 'utf8', sep=';')
df17 = pd.read_csv('3o-ciclo-base-de-dados-2017-2-semestre.csv', encoding= 'utf8', sep=';')
df18 = pd.read_csv('5o-ciclo-base-de-dados-2018-2-semestre.csv', encoding= 'utf8', sep=';')
df19 = pd.read_csv('7o-ciclo-base-de-dados-2019-2-semestre.csv', encoding= 'utf8', sep=';')
df20 = pd.read_csv('9o-ciclo-base-de-dados-2020-2-semestre (1).csv', encoding= 'utf8', sep=';')
df21 = pd.read_csv('11o-ciclo-base-de-dados-2021-2-semestre.csv', encoding= 'utf8', sep=';')
df22 = pd.read_csv('13o-ciclo-base-de-dados-2022-2-semestre.csv', encoding= 'utf8', sep=';')
df23 = pd.read_csv('15o-ciclo-base-de-dados-2023-2-semestre-1.csv', encoding= 'utf8', sep=';')
df24 = pd.read_csv('17o-ciclo-base-de-dados-2024-2-semestre.csv', encoding= 'utf8', sep=';')

In [ ]:
df_todos = df
df_todos

,ciclo,Ano,Referência,Tipo do Estabelecimento,Situação de Preenchimento,Nome do Estabelecimento,Situação do Estabelecimento,Outras Denominações,Endereço,Bairro,...,7.3 Quantidade de visitas registradas no período de referência | Quantidade de presos que receberam visita no período de referência | Feminino,7.5 Foi realizada visita(s) de inspeção no período de referência?,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho Nacional de Política Criminal e Penitenciária - CNPCP,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho Estadual de Política Criminal e Penitenciária/ Conselho Penitenciário,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho da Comunidade,7.5 Foi realizada visita(s) de inspeção no período de referência? | Ouvidoria do sistema prisional - estadual ou nacional,7.5 Foi realizada visita(s) de inspeção no período de referência? | Defensoria Pública,7.5 Foi realizada visita(s) de inspeção no período de referência? | Judiciário,7.5 Foi realizada visita(s) de inspeção no período de referência? | Ministério Público,7.5 Foi realizada visita(s) de inspeção no período de referência? | Outro(s). Qual?
0,19,2025,2025/2,Domiciliar com monitoramento eletrônico,Validado,NÚCLEO DE MONITORAMENTO ELETRÔNICO DOMICILIAR ...,Ativo,NaN,"Travessa Santos Dumond, 2",Centro,...,0.0,Não,Não,Não,Não,Não,Não,Não,Não,NaN
1,19,2025,2025/2,Domiciliar com monitoramento eletrônico,Validado,NÚCLEO DE MONITORAMENTO ELETRÔNICO DOMICILIAR ...,Ativo,NaN,"Av. 25 de Agosto, 1923",Bairro 25 de Agosto,...,0.0,Não,Não,Não,Não,Não,Não,Não,Não,NaN
2,19,2025,2025/2,Domiciliar com monitoramento eletrônico,Validado,NÚCLEO DE MONITORAMENTO ELETRÔNICO DOMICILIAR ...,Ativo,NaN,"Avenida Marechal Deodoro, Setor 02 Q 20",Centro,...,NaN,Não,Não,Não,Não,Não,Não,Não,Não,NaN
3,19,2025,2025/2,Domiciliar com monitoramento eletrônico,Validado,NÚCLEO DE MONITORAMENTO ELETRONICO DOMICILIAR ...,Ativo,NaN,"Rodovia BR-364, KM 01",Triângulo,...,0.0,Não,Não,Não,Não,Não,Não,Não,Não,NaN
4,19,2025,2025/2,Domiciliar com monitoramento eletrônico,Validado,UNIDADE DE MONITORAMENTO ELETRÔNICO DOMICILIAR...,Ativo,NaN,"Av Getúlio Vargas, 1203",Bosque,...,NaN,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1527,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Brasília,Ativo,NaN,Rod DF-465 KM 01 - Complexo Penitenciário da P...,Setor Habitacional Jardim Botânico,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN
1528,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Campo Grande,Ativo,NaN,AVENIDA HENRIQUE BERTIN S/N JARDIM LOS ANGELES,NaN,...,0.0,Sim,Não,Não,Não,Não,Não,Sim,Sim,NaN
1529,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Catanduvas,Ativo,NaN,"Rodovia PR 471, Km 15, s/n",NaN,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN
1530,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Mossoró,Ativo,NaN,"RN 15, Km 13, Estrada Mossoró/Baraúnas - Mosso...",NaN,...,0.0,Sim,Não,Não,Sim,Não,Sim,Sim,Sim,NaN
1531,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Porto Velho,Ativo,NaN,"SÍTIO DA BOA ESPERANÇA, LOTE 13, GLEBA 13 ""A"" ...",NaN,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN

In [ ]:
df_todos.columns.to_list()

['ciclo',
 'Ano',
 'Referência',
 'Tipo do Estabelecimento',
 'Situação de Preenchimento',
 'Nome do Estabelecimento',
 'Situação do Estabelecimento',
 'Outras Denominações',
 'Endereço',
 'Bairro',
 'CEP',
 'Âmbito',
 'UF',
 'Município',
 'Código IBGE',
 'Telefone Principal',
 '1.1 Estabelecimento originalmente destinado a pessoa privadas de liberdade do sexo',
 '1.2 Tipo de estabelecimento - originalmente destinado',
 '1.3 Capacidade do estabelecimento | Presos provisórios | Masculino',
 '1.3 Capacidade do estabelecimento | Presos provisórios | Feminino',
 '1.3 Capacidade do estabelecimento | Presos provisórios | Total',
 '1.3 Capacidade do estabelecimento | Regime fechado | Masculino',
 '1.3 Capacidade do estabelecimento | Regime fechado | Feminino',
 '1.3 Capacidade do estabelecimento | Regime fechado | Total',
 '1.3 Capacidade do estabelecimento | Regime semiaberto | Masculino',
 '1.3 Capacidade do estabelecimento | Regime semiaberto | Feminino',
 '1.3 Capacidade do estabelecimento | Regime semiaberto | Total',
 '1.3 Capacidade do estabelecimento | Regime aberto | Masculino',
 '1.3 Capacidade do estabelecimento | Regime aberto | Feminino',
 '1.3 Capacidade do estabelecimento | Regime aberto | Total',
 '1.3 Capacidade do estabelecimento | Regime Disciplinar Diferenciado (RDD) | Masculino',
 '1.3 Capacidade do estabelecimento | Regime Disciplinar Diferenciado (RDD) | Feminino',
 '1.3 Capacidade do estabelecimento | Regime Disciplinar Diferenciado (RDD) | Total',
 '1.3 Capacidade do estabelecimento | Medidas de segurança de internação | Masculino',
 '1.3 Capacidade do estabelecimento | Medidas de segurança de internação | Feminino',
 '1.3 Capacidade do estabelecimento | Medidas de segurança de internação | Total',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)?',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)? | Masculino',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)? | Feminino',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)? | Total',
 '1.3 Capacidade do estabelecimento | Masculino | Total',
 '1.3 Capacidade do estabelecimento | Feminino | Total',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Celas não aptas',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Vagas desativadas - Masculino',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Vagas desativadas - Feminino',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Total de vagas desativadas',
 '1.4 Gestão do estabelecimento',
 '1.5 Quais serviços são terceirizados? | Nenhum',
 '1.5 Quais serviços são terceirizados? | Alimentação',
 '1.5 Quais serviços são terceirizados? | Limpeza',
 '1.5 Quais serviços são terceirizados? | Lavanderia',
 '1.5 Quais serviços são terceirizados? | Saúde',
 '1.5 Quais serviços são terceirizados? | Segurança',
 '1.5 Quais serviços são terceirizados? | Assistência educacional',
 '1.5 Quais serviços são terceirizados? | Assistência laboral',
 '1.5 Quais serviços são terceirizados? | Assistência social',
 '1.5 Quais serviços são terceirizados? | Assistência jurídica',
 '1.5 Quais serviços são terceirizados? | Serviços administrativos',
 '1.5 Quais serviços são terceirizados? | Outro',
 '1.6 Data de inauguração do estabelecimento',
 '1.7 O estabelecimento foi concebido como estabelecimento penal ou foi construído para outra utilização e foi adaptado?',
 '1.8 Possui regimento interno?',
 '1.9 O regimento interno é específico para este estabelecimento ou se aplica aos demais estabelecimentos do Estado?',
 '2.1 Há cela adequada/ dormitório para gestantes? (apenas para estabelecimentos com vagas para mulheres)',
 '2.2 Possui berçário e/ou centro de referência materno-infantil? (apenas para estabelecimentos com vagas para mulheres)',
 '2.2 Possui berçário e/ou centro de referência materno-infantil? (apenas para estabelecimentos com vagas para mulheres) | Sim. Capacidade de bebês: | Quantidade',
 '2.3 Possui creche? (apenas para estabelecimentos com vagas para mulheres)',
 '2.3 Possui creche? (apenas para estabelecimentos com vagas para mulheres) | Sim. Capacidade de crianças: | Quantidade',
 '2.4 Módulo de saúde | Consultório médico',
 '2.4 Módulo de saúde | Consultório médico | Quantidade',
 '2.4 Módulo de saúde | Consultório médico | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Consultório odontológico',
 '2.4 Módulo de saúde | Consultório odontológico | Quantidade',
 '2.4 Módulo de saúde | Consultório odontológico | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de coleta de material para laboratório',
 '2.4 Módulo de saúde | Sala de coleta de material para laboratório | Quantidade',
 '2.4 Módulo de saúde | Sala de coleta de material para laboratório | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de curativos, suturas, vacinas e posto de enfermagem',
 '2.4 Módulo de saúde | Sala de curativos, suturas, vacinas e posto de enfermagem | Quantidade',
 '2.4 Módulo de saúde | Sala de curativos, suturas, vacinas e posto de enfermagem | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Cela de observação',
 '2.4 Módulo de saúde | Cela de observação | Quantidade',
 '2.4 Módulo de saúde | Cela de observação | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Cela de enfermaria com solário',
 '2.4 Módulo de saúde | Cela de enfermaria com solário | Quantidade',
 '2.4 Módulo de saúde | Cela de enfermaria com solário | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sanitário para pacientes',
 '2.4 Módulo de saúde | Sanitário para pacientes | Quantidade',
 '2.4 Módulo de saúde | Sanitário para pacientes | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sanitários para equipe de saúde',
 '2.4 Módulo de saúde | Sanitários para equipe de saúde | Quantidade',
 '2.4 Módulo de saúde | Sanitários para equipe de saúde | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Farmácia ou sala de estoque/ dispensação de medicamentos',
 '2.4 Módulo de saúde | Farmácia ou sala de estoque/ dispensação de medicamentos | Quantidade',
 '2.4 Módulo de saúde | Farmácia ou sala de estoque/ dispensação de medicamentos | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Central de material esterilizado/ expurgo',
 '2.4 Módulo de saúde | Central de material esterilizado/ expurgo | Quantidade',
 '2.4 Módulo de saúde | Central de material esterilizado/ expurgo | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de lavagem e descontaminação',
 '2.4 Módulo de saúde | Sala de lavagem e descontaminação | Quantidade',
 '2.4 Módulo de saúde | Sala de lavagem e descontaminação | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de esterilização',
 '2.4 Módulo de saúde | Sala de esterilização | Quantidade',
 '2.4 Módulo de saúde | Sala de esterilização | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Vestiário',
 '2.4 Módulo de saúde | Vestiário | Quantidade',
 '2.4 Módulo de saúde | Vestiário | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Depósito de material de limpeza - DML',
 '2.4 Módulo de saúde | Depósito de material de limpeza - DML | Quantidade',
 '2.4 Módulo de saúde | Depósito de material de limpeza - DML | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de atendimento clínico multiprofissional',
 '2.4 Módulo de saúde | Sala de atendimento clínico multiprofissional | Quantidade',
 '2.4 Módulo de saúde | Sala de atendimento clínico multiprofissional | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de procedimentos',
 '2.4 Módulo de saúde | Sala de procedimentos | Quantidade',
 '2.4 Módulo de saúde | Sala de procedimentos | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de raio x',
 '2.4 Módulo de saúde | Sala de raio x | Quantidade',
 '2.4 Módulo de saúde | Sala de raio x | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Laboratório de diagnóstico',
 '2.4 Módulo de saúde | Laboratório de diagnóstico | Quantidade',
 '2.4 Módulo de saúde | Laboratório de diagnóstico | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Cela de espera',
 '2.4 Módulo de saúde | Cela de espera | Quantidade',
 '2.4 Módulo de saúde | Cela de espera | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Solário para pacientes',
 '2.4 Módulo de saúde | Solário para pacientes | Quantidade',
 '2.4 Módulo de saúde | Solário para pacientes | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Outro(s). Qual(is)?',
 '2.4 Módulo de saúde | Outro(s). Qual(is)? | Quantidade',
 '2.4 Módulo de saúde | Outro(s). Qual(is)? | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Não possui módulo de saúde',
 '2.5 Módulo de educação | Sala de aula',
 '2.5 Módulo de educação | Sala de aula | Quantidade de salas',
 '2.5 Módulo de educação | Sala de aula | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Sala de informática',
 '2.5 Módulo de educação | Sala de informática | Quantidade de salas',
 '2.5 Módulo de educação | Sala de informática | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Sala de encontros com a sociedade/ sala de reuniões',
 '2.5 Módulo de educação | Sala de encontros com a sociedade/ sala de reuniões | Quantidade de salas',
 '2.5 Módulo de educação | Sala de encontros com a sociedade/ sala de reuniões | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Biblioteca',
 '2.5 Módulo de educação | Biblioteca | Quantidade de salas',
 '2.5 Módulo de educação | Biblioteca | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Sala de professores',
 '2.5 Módulo de educação | Sala de professores | Quantidade de salas',
 '2.5 Módulo de educação | Sala de professores | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Outro(s). Qual(is)?',
 '2.5 Módulo de educação | Outro(s). Qual(is)? | Quantidade de salas',
 '2.5 Módulo de educação | Outro(s). Qual(is)? | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Não possui',
 '2.5.1 Há local específico para biblioteca?',
 '2.5.2 Há acervo de obras na biblioteca?',
 '2.5.2 Há acervo de obras na biblioteca? | Sim. Quantidade de obras: | Quantidade',
 '2.5.3 A origem do acervo da biblioteca?',
 '2.5.4 Há controle do acervo bibliotecário do estabelecimento?',
 '2.5.5 Há manutenção permanente do acervo bibliotecário do estabelecimento?',
 '2.5.5 Há manutenção permanente do acervo bibliotecário do estabelecimento? | Caso o estabelecimento possua manutenção permanente do acervo bibliotecário, qual a periodicidade de manutenção do acervo?',
 '2.6 Módulo de oficinas | Não possui',
 '2.6 Módulo de oficinas | Sala de produção',
 '2.6 Módulo de oficinas | Sala de controle/ supervisão',
 '2.6 Módulo de oficinas | Sanitários',
 '2.6 Módulo de oficinas | Estoque',
 '2.6 Módulo de oficinas | Carga/ descarga',
 '2.6 Módulo de oficinas | Outro(s). Qual(is)?',
 '2.6 Módulo de oficinas | Artefatos de concreto',
 '2.6 Módulo de oficinas | Artefatos de concreto | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Blocos e tijolos',
 '2.6 Módulo de oficinas | Blocos e tijolos | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Padaria e panificação',
 '2.6 Módulo de oficinas | Padaria e panificação | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Corte e costura industrial',
 '2.6 Módulo de oficinas | Corte e costura industrial | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Artesanato',
 '2.6 Módulo de oficinas | Artesanato | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Marcenaria',
 '2.6 Módulo de oficinas | Marcenaria | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Serralheria',
 '2.6 Módulo de oficinas | Serralheria | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Outro(s). Qual(is)? | Espaços complementares',
 '2.6 Módulo de oficinas | Outro(s). Qual(is)? | Espaços complementares | Capacidade para quantas pessoas',
 '2.7 Há local específico para visitação?',
 '2.8 Há local específico para visita íntima?',
 '2.9 Há sala de atendimento para serviço social?',
 '2.10 Há sala de atendimento para psicologia?',
 '2.11 Há local destinado ao atendimento jurídico gratuito no estabelecimento?',
 '2.12 Possui sala de videoconferência?',
 '2.13 Há "cela(s)-seguro"?',
 '2.14 Há ala ou cela destinadas exclusivamente às pessoas privadas de liberdade que se declarem lésbicas, gays, bissexuais, travestis e transexuais (LGBT)?',
 '2.14 Há ala ou cela destinadas exclusivamente às pessoas privadas de liberdade que se declarem lésbicas, gays, bissexuais, travestis e transexuais (LGBT)? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.14 Há ala ou cela destinadas exclusivamente às pessoas privadas de liberdade que se declarem lésbicas, gays, bissexuais, travestis e transexuais (LGBT)? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.15 Há ala ou cela destinada exclusivamente para idosos?',
 '2.15 Há ala ou cela destinada exclusivamente para idosos? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.15 Há ala ou cela destinada exclusivamente para idosos? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.16 Há ala ou cela destinada exclusivamente para indígenas?',
 '2.16 Há ala ou cela destinada exclusivamente para indígenas? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.16 Há ala ou cela destinada exclusivamente para indígenas? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.17 Há ala ou cela destinada exclusivamente para pessoas estrangeiras?',
 '2.17 Há ala ou cela destinada exclusivamente para pessoas estrangeiras? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.17 Há ala ou cela destinada exclusivamente para pessoas estrangeiras? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.18 Há acessibilidade para pessoas com deficiência?',
 '2.18 Há acessibilidade para pessoas com deficiência? | Sim, módulos/alas/celas adaptados em conformidade com a Norma Brasileira ABNT n. 9050, de 2004. Indique o número de vagas: | Quantidade',
 '2.18 Há acessibilidade para pessoas com deficiência? | Sim, módulos/alas/celas adaptados, não observando todos os requisitos da Norma Brasileira ABNT n. 9050, de 2004. Indique o número de vagas: | Quantidade',
 '2.19 Há terreno/ espaço disponível para construção de novos módulos?',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Temporário Masculino',

In [ ]:
dfs = {
    2025: df25
}

In [ ]:
for ano, df in dfs.items():
    print(f"{ano}: {len(df.columns)} colunas")

2025: 1737 colunas

In [ ]:
colunas_por_ano = {ano: set(df.columns) for ano, df in dfs.items()}

# Mostra as diferenças ano a ano em relação ao anterior
for ano_atual in sorted(dfs.keys())[1:]:
    ano_anterior = ano_atual - 1
    colunas_atuais = colunas_por_ano[ano_atual]
    colunas_anteriores = colunas_por_ano[ano_anterior]

    adicionadas = colunas_atuais - colunas_anteriores
    removidas = colunas_anteriores - colunas_atuais

    print(f"\n {ano_atual}:")
    if adicionadas:
        print(f"Colunas adicionadas em relação a {ano_anterior}: {sorted(adicionadas)}")
    if removidas:
        print(f"Colunas removidas em relação a {ano_anterior}: {sorted(removidas)}")
    if not adicionadas and not removidas:
        print("Nenhuma mudança nas colunas.")

In [ ]:
df_todos = df_todos[df_todos['Tipo do Estabelecimento']=='Cela física']
df_todos

,ciclo,Ano,Referência,Tipo do Estabelecimento,Situação de Preenchimento,Nome do Estabelecimento,Situação do Estabelecimento,Outras Denominações,Endereço,Bairro,...,7.3 Quantidade de visitas registradas no período de referência | Quantidade de presos que receberam visita no período de referência | Feminino,7.5 Foi realizada visita(s) de inspeção no período de referência?,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho Nacional de Política Criminal e Penitenciária - CNPCP,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho Estadual de Política Criminal e Penitenciária/ Conselho Penitenciário,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho da Comunidade,7.5 Foi realizada visita(s) de inspeção no período de referência? | Ouvidoria do sistema prisional - estadual ou nacional,7.5 Foi realizada visita(s) de inspeção no período de referência? | Defensoria Pública,7.5 Foi realizada visita(s) de inspeção no período de referência? | Judiciário,7.5 Foi realizada visita(s) de inspeção no período de referência? | Ministério Público,7.5 Foi realizada visita(s) de inspeção no período de referência? | Outro(s). Qual?
5,19,2025,2025/2,Cela física,Validado,UNIDADE DE RECOLHIMENTO PROVISÓRIO,Ativo,NaN,Estrada do Barro Vermelho km 3,DISTRITO INDUSTRIAL,...,NaN,Sim,Não,Não,Não,Sim,Sim,Sim,Sim,NaN
6,19,2025,2025/2,Cela física,Validado,UNIDADE DE REGIME FECHADO FEMININO,Ativo,NaN,ESTRADA DO BARRO VERMELHO KM03,DISTRITO INDUSTRIAL,...,NaN,Sim,Não,Não,Não,Sim,Sim,Sim,Sim,NaN
7,19,2025,2025/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N1,Ativo,NaN,"Estrada do Barro Vermelho, km 03",Distrito Industrial,...,NaN,Sim,Não,Sim,Sim,Sim,Sim,Sim,Sim,NaN
8,19,2025,2025/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N2,Ativo,NaN,ESTRADA DO BARRO VERMELHO - KM 03,DISTRITO INDUSTRIAL,...,0.0,Sim,Não,Não,Não,Não,Sim,Não,Sim,NaN
9,19,2025,2025/2,Cela física,Validado,UNIDADE PENITENCIARIA DO QUINARI,Ativo,NaN,Rodovia BR - 317 - KM 11,Zona rural,...,0.0,Sim,Não,Sim,Sim,Sim,Sim,Sim,Sim,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1527,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Brasília,Ativo,NaN,Rod DF-465 KM 01 - Complexo Penitenciário da P...,Setor Habitacional Jardim Botânico,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN
1528,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Campo Grande,Ativo,NaN,AVENIDA HENRIQUE BERTIN S/N JARDIM LOS ANGELES,NaN,...,0.0,Sim,Não,Não,Não,Não,Não,Sim,Sim,NaN
1529,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Catanduvas,Ativo,NaN,"Rodovia PR 471, Km 15, s/n",NaN,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN
1530,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Mossoró,Ativo,NaN,"RN 15, Km 13, Estrada Mossoró/Baraúnas - Mosso...",NaN,...,0.0,Sim,Não,Não,Sim,Não,Sim,Sim,Sim,NaN
1531,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Porto Velho,Ativo,NaN,"SÍTIO DA BOA ESPERANÇA, LOTE 13, GLEBA 13 ""A"" ...",NaN,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN

In [ ]:
df_todos.columns.to_list()

['ciclo',
 'Ano',
 'Referência',
 'Tipo do Estabelecimento',
 'Situação de Preenchimento',
 'Nome do Estabelecimento',
 'Situação do Estabelecimento',
 'Outras Denominações',
 'Endereço',
 'Bairro',
 'CEP',
 'Âmbito',
 'UF',
 'Município',
 'Código IBGE',
 'Telefone Principal',
 '1.1 Estabelecimento originalmente destinado a pessoa privadas de liberdade do sexo',
 '1.2 Tipo de estabelecimento - originalmente destinado',
 '1.3 Capacidade do estabelecimento | Presos provisórios | Masculino',
 '1.3 Capacidade do estabelecimento | Presos provisórios | Feminino',
 '1.3 Capacidade do estabelecimento | Presos provisórios | Total',
 '1.3 Capacidade do estabelecimento | Regime fechado | Masculino',
 '1.3 Capacidade do estabelecimento | Regime fechado | Feminino',
 '1.3 Capacidade do estabelecimento | Regime fechado | Total',
 '1.3 Capacidade do estabelecimento | Regime semiaberto | Masculino',
 '1.3 Capacidade do estabelecimento | Regime semiaberto | Feminino',
 '1.3 Capacidade do estabelecimento | Regime semiaberto | Total',
 '1.3 Capacidade do estabelecimento | Regime aberto | Masculino',
 '1.3 Capacidade do estabelecimento | Regime aberto | Feminino',
 '1.3 Capacidade do estabelecimento | Regime aberto | Total',
 '1.3 Capacidade do estabelecimento | Regime Disciplinar Diferenciado (RDD) | Masculino',
 '1.3 Capacidade do estabelecimento | Regime Disciplinar Diferenciado (RDD) | Feminino',
 '1.3 Capacidade do estabelecimento | Regime Disciplinar Diferenciado (RDD) | Total',
 '1.3 Capacidade do estabelecimento | Medidas de segurança de internação | Masculino',
 '1.3 Capacidade do estabelecimento | Medidas de segurança de internação | Feminino',
 '1.3 Capacidade do estabelecimento | Medidas de segurança de internação | Total',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)?',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)? | Masculino',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)? | Feminino',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)? | Total',
 '1.3 Capacidade do estabelecimento | Masculino | Total',
 '1.3 Capacidade do estabelecimento | Feminino | Total',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Celas não aptas',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Vagas desativadas - Masculino',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Vagas desativadas - Feminino',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Total de vagas desativadas',
 '1.4 Gestão do estabelecimento',
 '1.5 Quais serviços são terceirizados? | Nenhum',
 '1.5 Quais serviços são terceirizados? | Alimentação',
 '1.5 Quais serviços são terceirizados? | Limpeza',
 '1.5 Quais serviços são terceirizados? | Lavanderia',
 '1.5 Quais serviços são terceirizados? | Saúde',
 '1.5 Quais serviços são terceirizados? | Segurança',
 '1.5 Quais serviços são terceirizados? | Assistência educacional',
 '1.5 Quais serviços são terceirizados? | Assistência laboral',
 '1.5 Quais serviços são terceirizados? | Assistência social',
 '1.5 Quais serviços são terceirizados? | Assistência jurídica',
 '1.5 Quais serviços são terceirizados? | Serviços administrativos',
 '1.5 Quais serviços são terceirizados? | Outro',
 '1.6 Data de inauguração do estabelecimento',
 '1.7 O estabelecimento foi concebido como estabelecimento penal ou foi construído para outra utilização e foi adaptado?',
 '1.8 Possui regimento interno?',
 '1.9 O regimento interno é específico para este estabelecimento ou se aplica aos demais estabelecimentos do Estado?',
 '2.1 Há cela adequada/ dormitório para gestantes? (apenas para estabelecimentos com vagas para mulheres)',
 '2.2 Possui berçário e/ou centro de referência materno-infantil? (apenas para estabelecimentos com vagas para mulheres)',
 '2.2 Possui berçário e/ou centro de referência materno-infantil? (apenas para estabelecimentos com vagas para mulheres) | Sim. Capacidade de bebês: | Quantidade',
 '2.3 Possui creche? (apenas para estabelecimentos com vagas para mulheres)',
 '2.3 Possui creche? (apenas para estabelecimentos com vagas para mulheres) | Sim. Capacidade de crianças: | Quantidade',
 '2.4 Módulo de saúde | Consultório médico',
 '2.4 Módulo de saúde | Consultório médico | Quantidade',
 '2.4 Módulo de saúde | Consultório médico | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Consultório odontológico',
 '2.4 Módulo de saúde | Consultório odontológico | Quantidade',
 '2.4 Módulo de saúde | Consultório odontológico | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de coleta de material para laboratório',
 '2.4 Módulo de saúde | Sala de coleta de material para laboratório | Quantidade',
 '2.4 Módulo de saúde | Sala de coleta de material para laboratório | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de curativos, suturas, vacinas e posto de enfermagem',
 '2.4 Módulo de saúde | Sala de curativos, suturas, vacinas e posto de enfermagem | Quantidade',
 '2.4 Módulo de saúde | Sala de curativos, suturas, vacinas e posto de enfermagem | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Cela de observação',
 '2.4 Módulo de saúde | Cela de observação | Quantidade',
 '2.4 Módulo de saúde | Cela de observação | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Cela de enfermaria com solário',
 '2.4 Módulo de saúde | Cela de enfermaria com solário | Quantidade',
 '2.4 Módulo de saúde | Cela de enfermaria com solário | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sanitário para pacientes',
 '2.4 Módulo de saúde | Sanitário para pacientes | Quantidade',
 '2.4 Módulo de saúde | Sanitário para pacientes | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sanitários para equipe de saúde',
 '2.4 Módulo de saúde | Sanitários para equipe de saúde | Quantidade',
 '2.4 Módulo de saúde | Sanitários para equipe de saúde | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Farmácia ou sala de estoque/ dispensação de medicamentos',
 '2.4 Módulo de saúde | Farmácia ou sala de estoque/ dispensação de medicamentos | Quantidade',
 '2.4 Módulo de saúde | Farmácia ou sala de estoque/ dispensação de medicamentos | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Central de material esterilizado/ expurgo',
 '2.4 Módulo de saúde | Central de material esterilizado/ expurgo | Quantidade',
 '2.4 Módulo de saúde | Central de material esterilizado/ expurgo | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de lavagem e descontaminação',
 '2.4 Módulo de saúde | Sala de lavagem e descontaminação | Quantidade',
 '2.4 Módulo de saúde | Sala de lavagem e descontaminação | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de esterilização',
 '2.4 Módulo de saúde | Sala de esterilização | Quantidade',
 '2.4 Módulo de saúde | Sala de esterilização | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Vestiário',
 '2.4 Módulo de saúde | Vestiário | Quantidade',
 '2.4 Módulo de saúde | Vestiário | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Depósito de material de limpeza - DML',
 '2.4 Módulo de saúde | Depósito de material de limpeza - DML | Quantidade',
 '2.4 Módulo de saúde | Depósito de material de limpeza - DML | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de atendimento clínico multiprofissional',
 '2.4 Módulo de saúde | Sala de atendimento clínico multiprofissional | Quantidade',
 '2.4 Módulo de saúde | Sala de atendimento clínico multiprofissional | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de procedimentos',
 '2.4 Módulo de saúde | Sala de procedimentos | Quantidade',
 '2.4 Módulo de saúde | Sala de procedimentos | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de raio x',
 '2.4 Módulo de saúde | Sala de raio x | Quantidade',
 '2.4 Módulo de saúde | Sala de raio x | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Laboratório de diagnóstico',
 '2.4 Módulo de saúde | Laboratório de diagnóstico | Quantidade',
 '2.4 Módulo de saúde | Laboratório de diagnóstico | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Cela de espera',
 '2.4 Módulo de saúde | Cela de espera | Quantidade',
 '2.4 Módulo de saúde | Cela de espera | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Solário para pacientes',
 '2.4 Módulo de saúde | Solário para pacientes | Quantidade',
 '2.4 Módulo de saúde | Solário para pacientes | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Outro(s). Qual(is)?',
 '2.4 Módulo de saúde | Outro(s). Qual(is)? | Quantidade',
 '2.4 Módulo de saúde | Outro(s). Qual(is)? | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Não possui módulo de saúde',
 '2.5 Módulo de educação | Sala de aula',
 '2.5 Módulo de educação | Sala de aula | Quantidade de salas',
 '2.5 Módulo de educação | Sala de aula | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Sala de informática',
 '2.5 Módulo de educação | Sala de informática | Quantidade de salas',
 '2.5 Módulo de educação | Sala de informática | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Sala de encontros com a sociedade/ sala de reuniões',
 '2.5 Módulo de educação | Sala de encontros com a sociedade/ sala de reuniões | Quantidade de salas',
 '2.5 Módulo de educação | Sala de encontros com a sociedade/ sala de reuniões | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Biblioteca',
 '2.5 Módulo de educação | Biblioteca | Quantidade de salas',
 '2.5 Módulo de educação | Biblioteca | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Sala de professores',
 '2.5 Módulo de educação | Sala de professores | Quantidade de salas',
 '2.5 Módulo de educação | Sala de professores | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Outro(s). Qual(is)?',
 '2.5 Módulo de educação | Outro(s). Qual(is)? | Quantidade de salas',
 '2.5 Módulo de educação | Outro(s). Qual(is)? | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Não possui',
 '2.5.1 Há local específico para biblioteca?',
 '2.5.2 Há acervo de obras na biblioteca?',
 '2.5.2 Há acervo de obras na biblioteca? | Sim. Quantidade de obras: | Quantidade',
 '2.5.3 A origem do acervo da biblioteca?',
 '2.5.4 Há controle do acervo bibliotecário do estabelecimento?',
 '2.5.5 Há manutenção permanente do acervo bibliotecário do estabelecimento?',
 '2.5.5 Há manutenção permanente do acervo bibliotecário do estabelecimento? | Caso o estabelecimento possua manutenção permanente do acervo bibliotecário, qual a periodicidade de manutenção do acervo?',
 '2.6 Módulo de oficinas | Não possui',
 '2.6 Módulo de oficinas | Sala de produção',
 '2.6 Módulo de oficinas | Sala de controle/ supervisão',
 '2.6 Módulo de oficinas | Sanitários',
 '2.6 Módulo de oficinas | Estoque',
 '2.6 Módulo de oficinas | Carga/ descarga',
 '2.6 Módulo de oficinas | Outro(s). Qual(is)?',
 '2.6 Módulo de oficinas | Artefatos de concreto',
 '2.6 Módulo de oficinas | Artefatos de concreto | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Blocos e tijolos',
 '2.6 Módulo de oficinas | Blocos e tijolos | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Padaria e panificação',
 '2.6 Módulo de oficinas | Padaria e panificação | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Corte e costura industrial',
 '2.6 Módulo de oficinas | Corte e costura industrial | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Artesanato',
 '2.6 Módulo de oficinas | Artesanato | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Marcenaria',
 '2.6 Módulo de oficinas | Marcenaria | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Serralheria',
 '2.6 Módulo de oficinas | Serralheria | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Outro(s). Qual(is)? | Espaços complementares',
 '2.6 Módulo de oficinas | Outro(s). Qual(is)? | Espaços complementares | Capacidade para quantas pessoas',
 '2.7 Há local específico para visitação?',
 '2.8 Há local específico para visita íntima?',
 '2.9 Há sala de atendimento para serviço social?',
 '2.10 Há sala de atendimento para psicologia?',
 '2.11 Há local destinado ao atendimento jurídico gratuito no estabelecimento?',
 '2.12 Possui sala de videoconferência?',
 '2.13 Há "cela(s)-seguro"?',
 '2.14 Há ala ou cela destinadas exclusivamente às pessoas privadas de liberdade que se declarem lésbicas, gays, bissexuais, travestis e transexuais (LGBT)?',
 '2.14 Há ala ou cela destinadas exclusivamente às pessoas privadas de liberdade que se declarem lésbicas, gays, bissexuais, travestis e transexuais (LGBT)? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.14 Há ala ou cela destinadas exclusivamente às pessoas privadas de liberdade que se declarem lésbicas, gays, bissexuais, travestis e transexuais (LGBT)? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.15 Há ala ou cela destinada exclusivamente para idosos?',
 '2.15 Há ala ou cela destinada exclusivamente para idosos? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.15 Há ala ou cela destinada exclusivamente para idosos? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.16 Há ala ou cela destinada exclusivamente para indígenas?',
 '2.16 Há ala ou cela destinada exclusivamente para indígenas? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.16 Há ala ou cela destinada exclusivamente para indígenas? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.17 Há ala ou cela destinada exclusivamente para pessoas estrangeiras?',
 '2.17 Há ala ou cela destinada exclusivamente para pessoas estrangeiras? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.17 Há ala ou cela destinada exclusivamente para pessoas estrangeiras? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.18 Há acessibilidade para pessoas com deficiência?',
 '2.18 Há acessibilidade para pessoas com deficiência? | Sim, módulos/alas/celas adaptados em conformidade com a Norma Brasileira ABNT n. 9050, de 2004. Indique o número de vagas: | Quantidade',
 '2.18 Há acessibilidade para pessoas com deficiência? | Sim, módulos/alas/celas adaptados, não observando todos os requisitos da Norma Brasileira ABNT n. 9050, de 2004. Indique o número de vagas: | Quantidade',
 '2.19 Há terreno/ espaço disponível para construção de novos módulos?',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Temporário Masculino',

In [ ]:
df_todos['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Outros. Especificar:'].str.lower().unique()

array([nan, 'fisioterapeuta', 'apoio jurídico e administrativo',
       'auxiliares de administração',
       'grupo de intervenção penitenciária', 'estagiário',
       'técnico em execução penal', 'farmacêutico', 'limpeza',
       'nutricionistas',
       'almoxarife, artifice, asg,ti,motorista,pedreiro,auxiliar de cozinha,conzinheira,magarefe, e pedreiro',
       'cozinha / asg / estagiários',
       'cinofilo/nutricionista/farmaceutica',
       'nutricionista e auxiliares de cozinha',
       'jovem aprendiz, estagiário, manutenção, auxiliar de serviços gerais e mmotoristas',
       'farmaceutico / fisioterapeuta e nutricionista',
       'fisioterapeuta/nutricionista/cozinha', 'serviços gerais',
       'auxiliar de serviços gerais',
       'serviços gerais e tecnico eletronico e tecnico informatica',
       'educador físico/ seriços gerais', 'nutricionista',
       'auxiliar serv gerais', 'bombeiro', 'farmacêutica', '0',
       'farmaceutico', 'comissionado cedido',
       'estagiários em enfermagem / direito e pedagogia', 'estagiários',
       'estagiario de pedagogia / cozinheira /estagiaria serviço social',
       'seguranças', 'cozinheira', 'padeiros',
       '4 (médico, enfermeiro, dentista e farmacêutica)',
       'estagiário jurídico', 'estagiárias',
       'estagiária jurídica estagiária pscicologia',
       'estagiário  pedagogia /  estagiário  pedagogia /  estagiária jurídica',
       'gerente de produção', 'analista técnico jurídico', 'farmaceutivo',
       'educador fisico / nutircionista / farmaceutica',
       'nutricionista e farmaceuticos', 'agente de segurança',
       'desvio de função', 'cozinheiras', 'cedidos de outras secretaria',
       'ceasa', 'nutricionista/auxiliar de farmacia',
       'nutricionista/cozinheiras',
       'nutricionistas/cozinheiras/serviços gerais',
       'nutricionista/cozinheira',
       'nutricionista/ cozinheira/ farmacêutica',
       'cozinheira / nutricionista / aux. de almoxarifado',
       'nutricionista/cozinheira/auxiliar de serviços gerais',
       'nutricionistas / cozinheiras', 'nutricionista/cozinheiro',
       'cozinheiras / nutricionista', 'nutricionistas/cozinheiras',
       'assistente administrativo', 'agente de saúde',
       'monitores de ressoacialização',
       'apoio masculino 02, motoristas 04, dentista voluntário 01, sot 76 masculinos,04 femininos, soe 34 masculinos,01 feminino, administrativos da escola 01, masculino, 01 feminino, 01 apoio feminino,',
       '1 - manutenção / 1 - médico - cmp, atendimento virtual',
       'cargos administrativos/escola', 'auxiliar de farmácia',
       'diretora da ubs prisional - esf',
       'socios educadores em atividade exclusiva no estabelecimento prisional',
       'farmaceutica', 'nutricionista e farmaceutico',
       'nutricionista e farmacêutico',
       'motorista (2m efetivos), agente de serviços gerais (1m efetivo), artífice i (1m efetivo), farmacêutico (1m temporário), técnico em atividades de saúde (1m efetivo)',
       'farmacêuticos', 'policial penal (aposentado)',
       'farmacêutica e técnica em farmácia', 'analista administrativo',
       'oficial operacional', '01 - operacional - 02 serviços gerais',
       'oficial operacional e auxiliar de serviços gerais',
       'farmaceutico / of. saude / nutricionista / aux. laboratorio',
       'analisa adm', '01 oficial operacional', 'auxiliar de laboratorio',
       'oficial operacional, auxiliar de serviços gerais',
       'agente técnico de assistência à saúde - famacêutico',
       'agente técnico de assistência a saúde (farmacêutica)',
       'técnico de laboratório/auxiliar de laboratório',
       'oficial operacional - motorista', 'auxiliar de manutenção',
       '02 oficial operacional, 01 aux. de laboratorio',
       'auxiliar de laboratório / oficial operacional',
       'comissionado integral',
       'oficiais operacionais (5), auxiliar de serviços gerais (1).',
       'aux. laboratorio', 'operador de cftv', 'socio educativo',
       'motorista', 'farmacêutico(a)'], dtype=object)

In [ ]:
df_todos = pd.concat(dfs, ignore_index=True)
df_todos = df_todos[df_todos['Tipo do Estabelecimento']=='Cela física']
df_todos

,ciclo,Ano,Referência,Tipo do Estabelecimento,Situação de Preenchimento,Nome do Estabelecimento,Situação do Estabelecimento,Outras Denominações,Endereço,Bairro,...,7.3 Quantidade de visitas registradas no período de referência | Quantidade de presos que receberam visita no período de referência | Feminino,7.5 Foi realizada visita(s) de inspeção no período de referência?,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho Nacional de Política Criminal e Penitenciária - CNPCP,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho Estadual de Política Criminal e Penitenciária/ Conselho Penitenciário,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho da Comunidade,7.5 Foi realizada visita(s) de inspeção no período de referência? | Ouvidoria do sistema prisional - estadual ou nacional,7.5 Foi realizada visita(s) de inspeção no período de referência? | Defensoria Pública,7.5 Foi realizada visita(s) de inspeção no período de referência? | Judiciário,7.5 Foi realizada visita(s) de inspeção no período de referência? | Ministério Público,7.5 Foi realizada visita(s) de inspeção no período de referência? | Outro(s). Qual?
5,19,2025,2025/2,Cela física,Validado,UNIDADE DE RECOLHIMENTO PROVISÓRIO,Ativo,NaN,Estrada do Barro Vermelho km 3,DISTRITO INDUSTRIAL,...,NaN,Sim,Não,Não,Não,Sim,Sim,Sim,Sim,NaN
6,19,2025,2025/2,Cela física,Validado,UNIDADE DE REGIME FECHADO FEMININO,Ativo,NaN,ESTRADA DO BARRO VERMELHO KM03,DISTRITO INDUSTRIAL,...,NaN,Sim,Não,Não,Não,Sim,Sim,Sim,Sim,NaN
7,19,2025,2025/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N1,Ativo,NaN,"Estrada do Barro Vermelho, km 03",Distrito Industrial,...,NaN,Sim,Não,Sim,Sim,Sim,Sim,Sim,Sim,NaN
8,19,2025,2025/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N2,Ativo,NaN,ESTRADA DO BARRO VERMELHO - KM 03,DISTRITO INDUSTRIAL,...,0.0,Sim,Não,Não,Não,Não,Sim,Não,Sim,NaN
9,19,2025,2025/2,Cela física,Validado,UNIDADE PENITENCIARIA DO QUINARI,Ativo,NaN,Rodovia BR - 317 - KM 11,Zona rural,...,0.0,Sim,Não,Sim,Sim,Sim,Sim,Sim,Sim,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1527,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Brasília,Ativo,NaN,Rod DF-465 KM 01 - Complexo Penitenciário da P...,Setor Habitacional Jardim Botânico,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN
1528,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Campo Grande,Ativo,NaN,AVENIDA HENRIQUE BERTIN S/N JARDIM LOS ANGELES,NaN,...,0.0,Sim,Não,Não,Não,Não,Não,Sim,Sim,NaN
1529,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Catanduvas,Ativo,NaN,"Rodovia PR 471, Km 15, s/n",NaN,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN
1530,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Mossoró,Ativo,NaN,"RN 15, Km 13, Estrada Mossoró/Baraúnas - Mosso...",NaN,...,0.0,Sim,Não,Não,Sim,Não,Sim,Sim,Sim,NaN
1531,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Porto Velho,Ativo,NaN,"SÍTIO DA BOA ESPERANÇA, LOTE 13, GLEBA 13 ""A"" ...",NaN,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN

In [ ]:
col_masc = [
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Estadual Masculino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Federal Masculino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Estadual Masculino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Federal Masculino',
    '4.1 População prisional | Medida de segurança - internação | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Estadual Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Federal Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Outros(Just. Trab., cível) Masculino'
]

col_fem = [
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Estadual Feminino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Federal Feminino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Estadual Feminino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Federal Feminino',
    '4.1 População prisional | Medida de segurança - internação | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Estadual Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Federal Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Outros(Just. Trab., cível) Feminino'
]

In [ ]:
medicos_total = df_todos[['Ano',
            'Nome do Estabelecimento',
            'Âmbito','UF', 'Município', 'Código IBGE',
            '1.1 Estabelecimento originalmente destinado a pessoa privadas de liberdade do sexo',
            '1.2 Tipo de estabelecimento - originalmente destinado',
            '1.3 Capacidade do estabelecimento | Masculino | Total',
            '1.3 Capacidade do estabelecimento | Feminino | Total',
            '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total',
            '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total',
            '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total',
            '4.1 População prisional | Total'
            ]]
medicos_total # sem psiquiatras

,Ano,Nome do Estabelecimento,Âmbito,UF,Município,Código IBGE,1.1 Estabelecimento originalmente destinado a pessoa privadas de liberdade do sexo,1.2 Tipo de estabelecimento - originalmente destinado,1.3 Capacidade do estabelecimento | Masculino | Total,1.3 Capacidade do estabelecimento | Feminino | Total,3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total,3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total,3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total,4.1 População prisional | Total
5,2025,UNIDADE DE RECOLHIMENTO PROVISÓRIO,Estadual,AC,Rio Branco,1200401.0,Masculino,Estabelecimento destinado ao recolhimento de p...,759.0,0.0,2.0,0.0,0.0,1858
6,2025,UNIDADE DE REGIME FECHADO FEMININO,Estadual,AC,Rio Branco,1200401.0,Feminino,Estabelecimento destinado ao cumprimento de pe...,0.0,178.0,0.0,0.0,0.0,184
7,2025,UNIDADE DE REGIME FECHADO N1,Estadual,AC,Rio Branco,1200401.0,Masculino,Estabelecimento destinado ao cumprimento de pe...,792.0,0.0,0.0,0.0,0.0,1034
8,2025,UNIDADE DE REGIME FECHADO N2,Estadual,AC,Rio Branco,1200401.0,Masculino,Estabelecimento destinado ao cumprimento de pe...,300.0,0.0,0.0,0.0,0.0,85
9,2025,UNIDADE PENITENCIARIA DO QUINARI,Estadual,AC,Senador Guiomard,1200450.0,Masculino,Estabelecimento destinado ao cumprimento de pe...,796.0,0.0,1.0,0.0,0.0,513
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1527,2025,Penitenciária Federal em Brasília,Federal,DF,Brasília,5300108.0,Masculino,Estabelecimento destinado ao cumprimento de pe...,208.0,0.0,1.0,NaN,13.0,78
1528,2025,Penitenciária Federal em Campo Grande,Federal,MS,Campo Grande,5002704.0,Masculino,Estabelecimento destinado ao cumprimento de pe...,208.0,0.0,1.0,NaN,13.0,127
1529,2025,Penitenciária Federal em Catanduvas,Federal,PR,Catanduvas,4105003.0,Masculino,Estabelecimento destinado ao cumprimento de pe...,208.0,0.0,1.0,0.0,13.0,135
1530,2025,Penitenciária Federal em Mossoró,Federal,RN,Mossoró,2408003.0,Masculino,Estabelecimento destinado ao cumprimento de pe...,208.0,0.0,1.0,0.0,13.0,107
1531,2025,Penitenciária Federal em Porto Velho,Federal,RO,Porto Velho,1100205.0,Masculino,Estabelecimento destinado ao cumprimento de pe...,208.0,0.0,0.0,0.0,13.0,147

In [ ]:
df_todos['Tipo do Estabelecimento'].unique()

array(['Cela física'], dtype=object)

In [ ]:
enf = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total'].sum()
aux_enf= df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total'].sum()
psi = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total'].sum()
dent = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Total'].sum()
tec_dent = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Total'].sum()
assits = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Assistentes sociais | Total'].sum()
adv = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Advogados | Total'].sum()
med_geral = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total'].sum()
med_gineco = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total'].sum()
med_psiq = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – psiquiatras | Total'].sum()
med_outros = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total'].sum()
ped = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Pedagogos | Total'].sum()
prof= df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Professores | Total'].sum()
terapeuta_ocup = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Terapeuta/ terapeuta ocupacional | Total'].sum()

In [ ]:
enf = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total'].sum()
aux_enf= df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total'].sum()
psi = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total'].sum()
dent = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Total'].sum()
tec_dent = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Total'].sum()
assits = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Assistentes sociais | Total'].sum()
adv = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Advogados | Total'].sum()
med_geral = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total'].sum()
med_gineco = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total'].sum()
med_psiq = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – psiquiatras | Total'].sum()
med_outros = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total'].sum()
ped = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Pedagogos | Total'].sum()
prof= df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Professores | Total'].sum()
terapeuta_ocup = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Terapeuta/ terapeuta ocupacional | Total'].sum()

In [ ]:
col_medicos_fisica = [
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total',
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total',
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total'
]

col_medicos_mental = [
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total',
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – psiquiatras | Total',
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Terapeuta/ terapeuta ocupacional | Total'
]

col_enfs = [
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total',
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total'
]

col_assits = [
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Assistentes sociais | Total'
]

col_odonto = [
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Total',
    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Total'
]

col_pop = '4.1 População prisional | Total'

col_gineco = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total']

In [ ]:
resultados = []
dfs = [df]
anos = list(range(2025,2026))  # de 2016 a 2024

In [ ]:
for df, ano in zip(dfs, anos):
    # Filtrando apenas celas físicas
    df = df[df['Tipo do Estabelecimento'] == 'Cela física'].copy()  # .copy() evita avisos de atribuição encadeada

    # Conversão para numérico
    for col_group in [col_medicos_fisica, col_medicos_mental, col_enfs, col_assits, col_masc, col_fem]:
        for col in col_group:
            df.loc[:, col] = pd.to_numeric(df[col], errors='coerce')

    df.loc[:, col_pop] = pd.to_numeric(df[col_pop], errors='coerce')

    # Cálculo de totais por linha com .loc
    df.loc[:, 'total_medicos_fisica'] = df[col_medicos_fisica].sum(axis=1)
    df.loc[:, 'total_medicos_mental'] = df[col_medicos_mental].sum(axis=1)
    df.loc[:, 'total_enfs'] = df[col_enfs].sum(axis=1)
    df.loc[:, 'total_assits'] = df[col_assits].sum(axis=1)
    df.loc[:, 'pop_masc'] = df[col_masc].sum(axis=1)
    df.loc[:, 'pop_fem'] = df[col_fem].sum(axis=1)
    df.loc[:, 'pop_total'] = df[col_pop]
    df.loc[:, 'ano'] = ano


    # Agrupamento por UF e ano
    grupo = df.groupby(['UF', 'ano'])[
        ['total_medicos_fisica', 'total_medicos_mental', 'total_enfs', 'total_assits',
         'pop_masc', 'pop_fem', 'pop_total']
    ].sum().reset_index()

    resultados.append(grupo)

# Concatenação dos resultados
saude_area_populacao_ano_uf = pd.concat(resultados, ignore_index=True)

In [ ]:
saude_area_populacao_ano_uf

,UF,ano,total_medicos_fisica,total_medicos_mental,total_enfs,total_assits,pop_masc,pop_fem,pop_total
0,AC,2025,5.0,12.0,12.0,19.0,5225.0,213.0,5438
1,AL,2025,21.0,36.0,131.0,26.0,5731.0,191.0,5922
2,AM,2025,14.0,34.0,70.0,25.0,5767.0,216.0,5983
3,AP,2025,5.0,8.0,24.0,5.0,3836.0,149.0,3985
4,BA,2025,65.0,109.0,286.0,73.0,16126.0,598.0,16724
5,CE,2025,50.0,40.0,131.0,41.0,24186.0,1227.0,25413
6,DF,2025,34.0,23.0,60.0,7.0,16360.0,661.0,17021
7,ES,2025,107.0,114.0,128.0,84.0,24201.0,1120.0,25321
8,GO,2025,67.0,58.0,138.0,42.0,18448.0,896.0,19344
9,MA,2025,77.0,69.0,380.0,69.0,12513.0,419.0,12932
10,MG,2025,194.0,311.0,551.0,275.0,70297.0,3135.0,73432
11,MS,2025,55.0,37.0,88.0,43.0,17198.0,1039.0,18237
12,MT,2025,25.0,38.0,118.0,41.0,14732.0,1000.0,15732
13,PA,2025,25.0,82.0,225.0,84.0,15907.0,701.0,16608
14,PB,2025,25.0,39.0,52.0,24.0,12591.0,710.0,13301
15,PE,2025,42.0,79.0,114.0,101.0,29913.0,997.0,30910
16,PI,2025,42.0,43.0,102.0,58.0,7678.0,306.0,7984
17,PR,2025,103.0,71.0,170.0,54.0,41239.0,2449.0,43688
18,RJ,2025,102.0,113.0,427.0,59.0,44844.0,1801.0,46645
19,RN,2025,33.0,24.0,65.0,14.0,7639.0,365.0,8004
20,RO,2025,31.0,16.0,136.0,25.0,7972.0,431.0,8403
21,RR,2025,8.0,7.0,35.0,3.0,2969.0,159.0,3128
22,RS,2025,81.0,162.0,220.0,168.0,38883.0,2172.0,41055
23,SC,2025,68.0,101.0,177.0,66.0,28893.0,1620.0,30513
24,SE,2025,12.0,23.0,91.0,21.0,6193.0,257.0,6450
25,SP,2025,160.0,176.0,787.0,185.0,210752.0,10468.0,221220
26,TO,2025,13.0,15.0,39.0,15.0,4314.0,188.0,4502

In [ ]:
saude_area_populacao_ano_uf['medicos_fisica_por_1000'] = (
    saude_area_populacao_ano_uf['total_medicos_fisica'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000

saude_area_populacao_ano_uf['medicos_mental_por_1000'] = (
    saude_area_populacao_ano_uf['total_medicos_mental'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000

saude_area_populacao_ano_uf['total_enfs_por_1000'] = (
    saude_area_populacao_ano_uf['total_enfs'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000
saude_area_populacao_ano_uf['total_assits_por_1000'] = (
    saude_area_populacao_ano_uf['total_assits'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000
saude_area_populacao_ano_uf

,UF,ano,total_medicos_fisica,total_medicos_mental,total_enfs,total_assits,pop_masc,pop_fem,pop_total,medicos_fisica_por_1000,medicos_mental_por_1000,total_enfs_por_1000,total_assits_por_1000
0,AC,2025,5.0,12.0,12.0,19.0,5225.0,213.0,5438,0.919456,2.206694,2.206694,3.493932
1,AL,2025,21.0,36.0,131.0,26.0,5731.0,191.0,5922,3.546099,6.079027,22.120905,4.390409
2,AM,2025,14.0,34.0,70.0,25.0,5767.0,216.0,5983,2.339963,5.682768,11.699816,4.178506
3,AP,2025,5.0,8.0,24.0,5.0,3836.0,149.0,3985,1.254705,2.007528,6.022585,1.254705
4,BA,2025,65.0,109.0,286.0,73.0,16126.0,598.0,16724,3.886630,6.517580,17.101172,4.364984
5,CE,2025,50.0,40.0,131.0,41.0,24186.0,1227.0,25413,1.967497,1.573998,5.154842,1.613347
6,DF,2025,34.0,23.0,60.0,7.0,16360.0,661.0,17021,1.997532,1.351272,3.525057,0.411257
7,ES,2025,107.0,114.0,128.0,84.0,24201.0,1120.0,25321,4.225741,4.502192,5.055093,3.317405
8,GO,2025,67.0,58.0,138.0,42.0,18448.0,896.0,19344,3.463606,2.998346,7.133995,2.171216
9,MA,2025,77.0,69.0,380.0,69.0,12513.0,419.0,12932,5.954222,5.335602,29.384473,5.335602
10,MG,2025,194.0,311.0,551.0,275.0,70297.0,3135.0,73432,2.641900,4.235211,7.503541,3.744961
11,MS,2025,55.0,37.0,88.0,43.0,17198.0,1039.0,18237,3.015847,2.028842,4.825355,2.357844
12,MT,2025,25.0,38.0,118.0,41.0,14732.0,1000.0,15732,1.589118,2.415459,7.500636,2.606153
13,PA,2025,25.0,82.0,225.0,84.0,15907.0,701.0,16608,1.505299,4.937380,13.547688,5.057803
14,PB,2025,25.0,39.0,52.0,24.0,12591.0,710.0,13301,1.879558,2.932110,3.909480,1.804376
15,PE,2025,42.0,79.0,114.0,101.0,29913.0,997.0,30910,1.358784,2.555807,3.688127,3.267551
16,PI,2025,42.0,43.0,102.0,58.0,7678.0,306.0,7984,5.260521,5.385772,12.775551,7.264529
17,PR,2025,103.0,71.0,170.0,54.0,41239.0,2449.0,43688,2.357627,1.625160,3.891229,1.236037
18,RJ,2025,102.0,113.0,427.0,59.0,44844.0,1801.0,46645,2.186730,2.422553,9.154250,1.264873
19,RN,2025,33.0,24.0,65.0,14.0,7639.0,365.0,8004,4.122939,2.998501,8.120940,1.749125
20,RO,2025,31.0,16.0,136.0,25.0,7972.0,431.0,8403,3.689159,1.904082,16.184696,2.975128
21,RR,2025,8.0,7.0,35.0,3.0,2969.0,159.0,3128,2.557545,2.237852,11.189258,0.959079
22,RS,2025,81.0,162.0,220.0,168.0,38883.0,2172.0,41055,1.972963,3.945926,5.358665,4.092072
23,SC,2025,68.0,101.0,177.0,66.0,28893.0,1620.0,30513,2.228558,3.310065,5.800806,2.163012
24,SE,2025,12.0,23.0,91.0,21.0,6193.0,257.0,6450,1.860465,3.565891,14.108527,3.255814
25,SP,2025,160.0,176.0,787.0,185.0,210752.0,10468.0,221220,0.723262,0.795588,3.557545,0.836272
26,TO,2025,13.0,15.0,39.0,15.0,4314.0,188.0,4502,2.887606,3.331853,8.662817,3.331853

In [ ]:
medicos_fisica_pop = saude_area_populacao_ano_uf[['ano','UF','total_medicos_fisica', 'pop_total', 'medicos_fisica_por_1000']]
medicos_fisica_pop

     ano  UF  total_medicos_fisica  pop_total  medicos_fisica_por_1000
0   2025  AC                   5.0       5438                 0.919456
1   2025  AL                  21.0       5922                 3.546099
2   2025  AM                  14.0       5983                 2.339963
3   2025  AP                   5.0       3985                 1.254705
4   2025  BA                  65.0      16724                 3.886630
5   2025  CE                  50.0      25413                 1.967497
6   2025  DF                  34.0      17021                 1.997532
7   2025  ES                 107.0      25321                 4.225741
8   2025  GO                  67.0      19344                 3.463606
9   2025  MA                  77.0      12932                 5.954222
10  2025  MG                 194.0      73432                 2.641900
11  2025  MS                  55.0      18237                 3.015847
12  2025  MT                  25.0      15732                 1.589118
13  2025  PA                  25.0      16608                 1.505299
14  2025  PB                  25.0      13301                 1.879558
15  2025  PE                  42.0      30910                 1.358784
16  2025  PI                  42.0       7984                 5.260521
17  2025  PR                 103.0      43688                 2.357627
18  2025  RJ                 102.0      46645                 2.186730
19  2025  RN                  33.0       8004                 4.122939
20  2025  RO                  31.0       8403                 3.689159
21  2025  RR                   8.0       3128                 2.557545
22  2025  RS                  81.0      41055                 1.972963
23  2025  SC                  68.0      30513                 2.228558
24  2025  SE                  12.0       6450                 1.860465
25  2025  SP                 160.0     221220                 0.723262
26  2025  TO                  13.0       4502                 2.887606

In [ ]:
medicos_fisica_pop['profissao'] = 'Médicos (Clinicos gerais, ginecologistas e outras especialidades)'

/tmp/ipykernel_2633/835226405.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  medicos_fisica_pop['profissao'] = 'Médicos (Clinicos gerais, ginecologistas e outras especialidades)'

In [ ]:
medicos_fisica_pop.columns

Index(['ano', 'UF', 'total_medicos_fisica', 'pop_total',
       'medicos_fisica_por_1000', 'profissao'],
      dtype='object')

In [ ]:
medicos_fisica_pop = medicos_fisica_pop[['ano', 'UF', 'profissao', 'total_medicos_fisica', 'pop_total',
       'medicos_fisica_por_1000']]
medicos_fisica_pop

,ano,UF,profissao,total_medicos_fisica,pop_total,medicos_fisica_por_1000
0,2025,AC,"Médicos (Clinicos gerais, ginecologistas e out...",5.0,5438,0.919456
1,2025,AL,"Médicos (Clinicos gerais, ginecologistas e out...",21.0,5922,3.546099
2,2025,AM,"Médicos (Clinicos gerais, ginecologistas e out...",14.0,5983,2.339963
3,2025,AP,"Médicos (Clinicos gerais, ginecologistas e out...",5.0,3985,1.254705
4,2025,BA,"Médicos (Clinicos gerais, ginecologistas e out...",65.0,16724,3.886630
5,2025,CE,"Médicos (Clinicos gerais, ginecologistas e out...",50.0,25413,1.967497
6,2025,DF,"Médicos (Clinicos gerais, ginecologistas e out...",34.0,17021,1.997532
7,2025,ES,"Médicos (Clinicos gerais, ginecologistas e out...",107.0,25321,4.225741
8,2025,GO,"Médicos (Clinicos gerais, ginecologistas e out...",67.0,19344,3.463606
9,2025,MA,"Médicos (Clinicos gerais, ginecologistas e out...",77.0,12932,5.954222
10,2025,MG,"Médicos (Clinicos gerais, ginecologistas e out...",194.0,73432,2.641900
11,2025,MS,"Médicos (Clinicos gerais, ginecologistas e out...",55.0,18237,3.015847
12,2025,MT,"Médicos (Clinicos gerais, ginecologistas e out...",25.0,15732,1.589118
13,2025,PA,"Médicos (Clinicos gerais, ginecologistas e out...",25.0,16608,1.505299
14,2025,PB,"Médicos (Clinicos gerais, ginecologistas e out...",25.0,13301,1.879558
15,2025,PE,"Médicos (Clinicos gerais, ginecologistas e out...",42.0,30910,1.358784
16,2025,PI,"Médicos (Clinicos gerais, ginecologistas e out...",42.0,7984,5.260521
17,2025,PR,"Médicos (Clinicos gerais, ginecologistas e out...",103.0,43688,2.357627
18,2025,RJ,"Médicos (Clinicos gerais, ginecologistas e out...",102.0,46645,2.186730
19,2025,RN,"Médicos (Clinicos gerais, ginecologistas e out...",33.0,8004,4.122939
20,2025,RO,"Médicos (Clinicos gerais, ginecologistas e out...",31.0,8403,3.689159
21,2025,RR,"Médicos (Clinicos gerais, ginecologistas e out...",8.0,3128,2.557545
22,2025,RS,"Médicos (Clinicos gerais, ginecologistas e out...",81.0,41055,1.972963
23,2025,SC,"Médicos (Clinicos gerais, ginecologistas e out...",68.0,30513,2.228558
24,2025,SE,"Médicos (Clinicos gerais, ginecologistas e out...",12.0,6450,1.860465
25,2025,SP,"Médicos (Clinicos gerais, ginecologistas e out...",160.0,221220,0.723262
26,2025,TO,"Médicos (Clinicos gerais, ginecologistas e out...",13.0,4502,2.887606

In [ ]:
resultado_gineco = []

In [ ]:
for df, ano in zip(dfs, anos):
    # Filtrando apenas celas físicas
    df = df[df['Tipo do Estabelecimento'] == 'Cela física'].copy()  # .copy() evita avisos de atribuição encadeada

    # Conversão para numérico
    for col_group in [col_medicos_fisica, col_gineco]:
        for col in col_group:
            df.loc[:, col] = pd.to_numeric(df[col], errors='coerce')

    df.loc[:, col_pop] = pd.to_numeric(df[col_pop], errors='coerce')

    # Cálculo de totais por linha com .loc
    df.loc[:, 'total_medicos_fisica'] = df[col_medicos_fisica].sum(axis=1)
    df.loc[:, 'total_ginecologistas'] = df[col_gineco].sum(axis=1)
    df.loc[:, 'pop_fem'] = df[col_fem].sum(axis=1)
    df.loc[:, 'pop_total'] = df[col_pop]
    df.loc[:, 'ano'] = ano


    # Agrupamento por UF e ano
    grupo = df.groupby(['UF', 'ano'])[
        ['total_medicos_fisica','total_ginecologistas', 'pop_fem', 'pop_total']
    ].sum().reset_index()

    resultado_gineco.append(grupo)

# Concatenação dos resultados
gineco_area_populacao_ano_uf = pd.concat(resultado_gineco, ignore_index=True)

In [ ]:
medicos_fisica_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ano                      27 non-null     int64
 1   UF                       27 non-null     object
 2   profissao                27 non-null     object
 3   total_medicos_fisica     27 non-null     float64
 4   pop_total                27 non-null     int64
 5   medicos_fisica_por_1000  27 non-null     float64
dtypes: float64(2), int64(2), object(2)
memory usage: 1.4+ KB

In [ ]:
gineco_area_populacao_ano_uf

    UF   ano  total_medicos_fisica  total_ginecologistas  pop_fem  pop_total
0   AC  2025                   5.0                   0.0    213.0       5438
1   AL  2025                  21.0                   0.0    191.0       5922
2   AM  2025                  14.0                   2.0    216.0       5983
3   AP  2025                   5.0                   0.0    149.0       3985
4   BA  2025                  65.0                   2.0    598.0      16724
5   CE  2025                  50.0                   3.0   1227.0      25413
6   DF  2025                  34.0                   0.0    661.0      17021
7   ES  2025                 107.0                   0.0   1120.0      25321
8   GO  2025                  67.0                   1.0    896.0      19344
9   MA  2025                  77.0                   1.0    419.0      12932
10  MG  2025                 194.0                   1.0   3135.0      73432
11  MS  2025                  55.0                   0.0   1039.0      18237
12  MT  2025                  25.0                   1.0   1000.0      15732
13  PA  2025                  25.0                   2.0    701.0      16608
14  PB  2025                  25.0                   0.0    710.0      13301
15  PE  2025                  42.0                   0.0    997.0      30910
16  PI  2025                  42.0                   3.0    306.0       7984
17  PR  2025                 103.0                   2.0   2449.0      43688
18  RJ  2025                 102.0                   5.0   1801.0      46645
19  RN  2025                  33.0                   0.0    365.0       8004
20  RO  2025                  31.0                   0.0    431.0       8403
21  RR  2025                   8.0                   0.0    159.0       3128
22  RS  2025                  81.0                   0.0   2172.0      41055
23  SC  2025                  68.0                   0.0   1620.0      30513
24  SE  2025                  12.0                   0.0    257.0       6450
25  SP  2025                 160.0                   7.0  10468.0     221220
26  TO  2025                  13.0                   0.0    188.0       4502

In [ ]:
df24_gineco = gineco_area_populacao_ano_uf[gineco_area_populacao_ano_uf['ano']==2024]
df24_gineco['total_ginecologistas'].value_counts()

total_ginecologistas
0.0    19
2.0     4
1.0     1
3.0     1
5.0     1
7.0     1
Name: count, dtype: int64

In [ ]:
df24_gineco.sort_values(by='total_ginecologistas', ascending= False )

     UF   ano  total_medicos_fisica  total_ginecologistas  pop_fem  pop_total
241  SP  2024                 173.0                   7.0   9145.0   205984.0
234  RJ  2024                 129.0                   5.0   1668.0    46115.0
232  PI  2024                  36.0                   3.0    258.0     7198.0
218  AM  2024                  16.0                   2.0    172.0     5111.0
220  BA  2024                  59.0                   2.0    392.0    13721.0
221  CE  2024                  40.0                   2.0    913.0    22296.0
228  MT  2024                  25.0                   2.0    825.0    13735.0
225  MA  2024                  77.0                   1.0    375.0    11743.0
216  AC  2024                   6.0                   0.0    205.0     5401.0
240  SE  2024                  13.0                   0.0    233.0     6034.0
239  SC  2024                  62.0                   0.0   1448.0    27349.0
238  RS  2024                  71.0                   0.0   1714.0    36157.0
237  RR  2024                   9.0                   0.0    160.0     3258.0
236  RO  2024                  38.0                   0.0    336.0     7466.0
235  RN  2024                  34.0                   0.0    356.0     7499.0
233  PR  2024                  76.0                   0.0   2378.0    40699.0
229  PA  2024                  26.0                   0.0    631.0    15498.0
231  PE  2024                  53.0                   0.0    924.0    28983.0
230  PB  2024                  28.0                   0.0    618.0    12410.0
217  AL  2024                  18.0                   0.0    150.0     5240.0
227  MS  2024                  58.0                   0.0    962.0    16662.0
226  MG  2024                 175.0                   0.0   2628.0    66282.0
224  GO  2024                  60.0                   0.0    805.0    18489.0
223  ES  2024                  83.0                   0.0   1019.0    24117.0
222  DF  2024                  32.0                   0.0    559.0    16200.0
219  AP  2024                   9.0                   0.0    109.0     3257.0
242  TO  2024                  10.0                   0.0    154.0     3888.0

In [ ]:
gineco_area_populacao_ano_uf = gineco_area_populacao_ano_uf.rename(
                                            columns={'UF':'sigla_uf'
                                            })
gineco_area_populacao_ano_uf

,sigla_uf,ano,total_medicos_fisica,total_ginecologistas,pop_fem,pop_total
0,AC,2025,5.0,0.0,213.0,5438
1,AL,2025,21.0,0.0,191.0,5922
2,AM,2025,14.0,2.0,216.0,5983
3,AP,2025,5.0,0.0,149.0,3985
4,BA,2025,65.0,2.0,598.0,16724
5,CE,2025,50.0,3.0,1227.0,25413
6,DF,2025,34.0,0.0,661.0,17021
7,ES,2025,107.0,0.0,1120.0,25321
8,GO,2025,67.0,1.0,896.0,19344
9,MA,2025,77.0,1.0,419.0,12932
10,MG,2025,194.0,1.0,3135.0,73432
11,MS,2025,55.0,0.0,1039.0,18237
12,MT,2025,25.0,1.0,1000.0,15732
13,PA,2025,25.0,2.0,701.0,16608
14,PB,2025,25.0,0.0,710.0,13301
15,PE,2025,42.0,0.0,997.0,30910
16,PI,2025,42.0,3.0,306.0,7984
17,PR,2025,103.0,2.0,2449.0,43688
18,RJ,2025,102.0,5.0,1801.0,46645
19,RN,2025,33.0,0.0,365.0,8004
20,RO,2025,31.0,0.0,431.0,8403
21,RR,2025,8.0,0.0,159.0,3128
22,RS,2025,81.0,0.0,2172.0,41055
23,SC,2025,68.0,0.0,1620.0,30513
24,SE,2025,12.0,0.0,257.0,6450
25,SP,2025,160.0,7.0,10468.0,221220
26,TO,2025,13.0,0.0,188.0,4502

In [ ]:
medicos_fisica_pop = medicos_fisica_pop.rename(
                                            columns={'UF':'sigla_uf'
                                            })
medicos_fisica_pop

,ano,sigla_uf,profissao,total_medicos_fisica,pop_total,medicos_fisica_por_1000
0,2025,AC,"Médicos (Clinicos gerais, ginecologistas e out...",5.0,5438,0.919456
1,2025,AL,"Médicos (Clinicos gerais, ginecologistas e out...",21.0,5922,3.546099
2,2025,AM,"Médicos (Clinicos gerais, ginecologistas e out...",14.0,5983,2.339963
3,2025,AP,"Médicos (Clinicos gerais, ginecologistas e out...",5.0,3985,1.254705
4,2025,BA,"Médicos (Clinicos gerais, ginecologistas e out...",65.0,16724,3.886630
5,2025,CE,"Médicos (Clinicos gerais, ginecologistas e out...",50.0,25413,1.967497
6,2025,DF,"Médicos (Clinicos gerais, ginecologistas e out...",34.0,17021,1.997532
7,2025,ES,"Médicos (Clinicos gerais, ginecologistas e out...",107.0,25321,4.225741
8,2025,GO,"Médicos (Clinicos gerais, ginecologistas e out...",67.0,19344,3.463606
9,2025,MA,"Médicos (Clinicos gerais, ginecologistas e out...",77.0,12932,5.954222
10,2025,MG,"Médicos (Clinicos gerais, ginecologistas e out...",194.0,73432,2.641900
11,2025,MS,"Médicos (Clinicos gerais, ginecologistas e out...",55.0,18237,3.015847
12,2025,MT,"Médicos (Clinicos gerais, ginecologistas e out...",25.0,15732,1.589118
13,2025,PA,"Médicos (Clinicos gerais, ginecologistas e out...",25.0,16608,1.505299
14,2025,PB,"Médicos (Clinicos gerais, ginecologistas e out...",25.0,13301,1.879558
15,2025,PE,"Médicos (Clinicos gerais, ginecologistas e out...",42.0,30910,1.358784
16,2025,PI,"Médicos (Clinicos gerais, ginecologistas e out...",42.0,7984,5.260521
17,2025,PR,"Médicos (Clinicos gerais, ginecologistas e out...",103.0,43688,2.357627
18,2025,RJ,"Médicos (Clinicos gerais, ginecologistas e out...",102.0,46645,2.186730
19,2025,RN,"Médicos (Clinicos gerais, ginecologistas e out...",33.0,8004,4.122939
20,2025,RO,"Médicos (Clinicos gerais, ginecologistas e out...",31.0,8403,3.689159
21,2025,RR,"Médicos (Clinicos gerais, ginecologistas e out...",8.0,3128,2.557545
22,2025,RS,"Médicos (Clinicos gerais, ginecologistas e out...",81.0,41055,1.972963
23,2025,SC,"Médicos (Clinicos gerais, ginecologistas e out...",68.0,30513,2.228558
24,2025,SE,"Médicos (Clinicos gerais, ginecologistas e out...",12.0,6450,1.860465
25,2025,SP,"Médicos (Clinicos gerais, ginecologistas e out...",160.0,221220,0.723262
26,2025,TO,"Médicos (Clinicos gerais, ginecologistas e out...",13.0,4502,2.887606

In [ ]:
medicos_fisica_pop['medicos_fisica_por_1000_1']= medicos_fisica_pop['medicos_fisica_por_1000'].round(2)
medicos_fisica_pop

,ano,sigla_uf,profissao,total_medicos_fisica,pop_total,medicos_fisica_por_1000,medicos_fisica_por_1000_1
0,2025,AC,"Médicos (Clinicos gerais, ginecologistas e out...",5.0,5438,0.919456,0.92
1,2025,AL,"Médicos (Clinicos gerais, ginecologistas e out...",21.0,5922,3.546099,3.55
2,2025,AM,"Médicos (Clinicos gerais, ginecologistas e out...",14.0,5983,2.339963,2.34
3,2025,AP,"Médicos (Clinicos gerais, ginecologistas e out...",5.0,3985,1.254705,1.25
4,2025,BA,"Médicos (Clinicos gerais, ginecologistas e out...",65.0,16724,3.886630,3.89
5,2025,CE,"Médicos (Clinicos gerais, ginecologistas e out...",50.0,25413,1.967497,1.97
6,2025,DF,"Médicos (Clinicos gerais, ginecologistas e out...",34.0,17021,1.997532,2.00
7,2025,ES,"Médicos (Clinicos gerais, ginecologistas e out...",107.0,25321,4.225741,4.23
8,2025,GO,"Médicos (Clinicos gerais, ginecologistas e out...",67.0,19344,3.463606,3.46
9,2025,MA,"Médicos (Clinicos gerais, ginecologistas e out...",77.0,12932,5.954222,5.95
10,2025,MG,"Médicos (Clinicos gerais, ginecologistas e out...",194.0,73432,2.641900,2.64
11,2025,MS,"Médicos (Clinicos gerais, ginecologistas e out...",55.0,18237,3.015847,3.02
12,2025,MT,"Médicos (Clinicos gerais, ginecologistas e out...",25.0,15732,1.589118,1.59
13,2025,PA,"Médicos (Clinicos gerais, ginecologistas e out...",25.0,16608,1.505299,1.51
14,2025,PB,"Médicos (Clinicos gerais, ginecologistas e out...",25.0,13301,1.879558,1.88
15,2025,PE,"Médicos (Clinicos gerais, ginecologistas e out...",42.0,30910,1.358784,1.36
16,2025,PI,"Médicos (Clinicos gerais, ginecologistas e out...",42.0,7984,5.260521,5.26
17,2025,PR,"Médicos (Clinicos gerais, ginecologistas e out...",103.0,43688,2.357627,2.36
18,2025,RJ,"Médicos (Clinicos gerais, ginecologistas e out...",102.0,46645,2.186730,2.19
19,2025,RN,"Médicos (Clinicos gerais, ginecologistas e out...",33.0,8004,4.122939,4.12
20,2025,RO,"Médicos (Clinicos gerais, ginecologistas e out...",31.0,8403,3.689159,3.69
21,2025,RR,"Médicos (Clinicos gerais, ginecologistas e out...",8.0,3128,2.557545,2.56
22,2025,RS,"Médicos (Clinicos gerais, ginecologistas e out...",81.0,41055,1.972963,1.97
23,2025,SC,"Médicos (Clinicos gerais, ginecologistas e out...",68.0,30513,2.228558,2.23
24,2025,SE,"Médicos (Clinicos gerais, ginecologistas e out...",12.0,6450,1.860465,1.86
25,2025,SP,"Médicos (Clinicos gerais, ginecologistas e out...",160.0,221220,0.723262,0.72
26,2025,TO,"Médicos (Clinicos gerais, ginecologistas e out...",13.0,4502,2.887606,2.89

In [ ]:
medicos_fisica_pop[medicos_fisica_pop['ano']==2024]

,ano,sigla_uf,profissao,total_medicos_fisica,pop_total,medicos_fisica_por_1000,medicos_fisica_por_1000_1
216,2024,AC,"Médicos (Clinicos gerais, ginecologistas e out...",6.0,5401.0,1.110905,1.11
217,2024,AL,"Médicos (Clinicos gerais, ginecologistas e out...",18.0,5240.0,3.435115,3.44
218,2024,AM,"Médicos (Clinicos gerais, ginecologistas e out...",16.0,5111.0,3.130503,3.13
219,2024,AP,"Médicos (Clinicos gerais, ginecologistas e out...",9.0,3257.0,2.763279,2.76
220,2024,BA,"Médicos (Clinicos gerais, ginecologistas e out...",59.0,13721.0,4.299978,4.30
221,2024,CE,"Médicos (Clinicos gerais, ginecologistas e out...",40.0,22296.0,1.794044,1.79
222,2024,DF,"Médicos (Clinicos gerais, ginecologistas e out...",32.0,16200.0,1.975309,1.98
223,2024,ES,"Médicos (Clinicos gerais, ginecologistas e out...",83.0,24117.0,3.441556,3.44
224,2024,GO,"Médicos (Clinicos gerais, ginecologistas e out...",60.0,18489.0,3.245173,3.25
225,2024,MA,"Médicos (Clinicos gerais, ginecologistas e out...",77.0,11743.0,6.557098,6.56
226,2024,MG,"Médicos (Clinicos gerais, ginecologistas e out...",175.0,66282.0,2.640234,2.64
227,2024,MS,"Médicos (Clinicos gerais, ginecologistas e out...",58.0,16662.0,3.480975,3.48
228,2024,MT,"Médicos (Clinicos gerais, ginecologistas e out...",25.0,13735.0,1.820167,1.82
229,2024,PA,"Médicos (Clinicos gerais, ginecologistas e out...",26.0,15498.0,1.677636,1.68
230,2024,PB,"Médicos (Clinicos gerais, ginecologistas e out...",28.0,12410.0,2.256245,2.26
231,2024,PE,"Médicos (Clinicos gerais, ginecologistas e out...",53.0,28983.0,1.828658,1.83
232,2024,PI,"Médicos (Clinicos gerais, ginecologistas e out...",36.0,7198.0,5.001389,5.00
233,2024,PR,"Médicos (Clinicos gerais, ginecologistas e out...",76.0,40699.0,1.867368,1.87
234,2024,RJ,"Médicos (Clinicos gerais, ginecologistas e out...",129.0,46115.0,2.797354,2.80
235,2024,RN,"Médicos (Clinicos gerais, ginecologistas e out...",34.0,7499.0,4.533938,4.53
236,2024,RO,"Médicos (Clinicos gerais, ginecologistas e out...",38.0,7466.0,5.089740,5.09
237,2024,RR,"Médicos (Clinicos gerais, ginecologistas e out...",9.0,3258.0,2.762431,2.76
238,2024,RS,"Médicos (Clinicos gerais, ginecologistas e out...",71.0,36157.0,1.963658,1.96
239,2024,SC,"Médicos (Clinicos gerais, ginecologistas e out...",62.0,27349.0,2.266993,2.27
240,2024,SE,"Médicos (Clinicos gerais, ginecologistas e out...",13.0,6034.0,2.154458,2.15
241,2024,SP,"Médicos (Clinicos gerais, ginecologistas e out...",173.0,205984.0,0.839871,0.84
242,2024,TO,"Médicos (Clinicos gerais, ginecologistas e out...",10.0,3888.0,2.572016,2.57

In [ ]:
a = medicos_fisica_pop[medicos_fisica_pop['ano']==2024]
a.sort_values(by='medicos_fisica_por_1000_1', ascending=True)

,ano,sigla_uf,profissao,total_medicos_fisica,pop_total,medicos_fisica_por_1000,medicos_fisica_por_1000_1
241,2024,SP,"Médicos (Clinicos gerais, ginecologistas e out...",173.0,205984.0,0.839871,0.84
216,2024,AC,"Médicos (Clinicos gerais, ginecologistas e out...",6.0,5401.0,1.110905,1.11
229,2024,PA,"Médicos (Clinicos gerais, ginecologistas e out...",26.0,15498.0,1.677636,1.68
221,2024,CE,"Médicos (Clinicos gerais, ginecologistas e out...",40.0,22296.0,1.794044,1.79
228,2024,MT,"Médicos (Clinicos gerais, ginecologistas e out...",25.0,13735.0,1.820167,1.82
231,2024,PE,"Médicos (Clinicos gerais, ginecologistas e out...",53.0,28983.0,1.828658,1.83
233,2024,PR,"Médicos (Clinicos gerais, ginecologistas e out...",76.0,40699.0,1.867368,1.87
238,2024,RS,"Médicos (Clinicos gerais, ginecologistas e out...",71.0,36157.0,1.963658,1.96
222,2024,DF,"Médicos (Clinicos gerais, ginecologistas e out...",32.0,16200.0,1.975309,1.98
240,2024,SE,"Médicos (Clinicos gerais, ginecologistas e out...",13.0,6034.0,2.154458,2.15
230,2024,PB,"Médicos (Clinicos gerais, ginecologistas e out...",28.0,12410.0,2.256245,2.26
239,2024,SC,"Médicos (Clinicos gerais, ginecologistas e out...",62.0,27349.0,2.266993,2.27
242,2024,TO,"Médicos (Clinicos gerais, ginecologistas e out...",10.0,3888.0,2.572016,2.57
226,2024,MG,"Médicos (Clinicos gerais, ginecologistas e out...",175.0,66282.0,2.640234,2.64
237,2024,RR,"Médicos (Clinicos gerais, ginecologistas e out...",9.0,3258.0,2.762431,2.76
219,2024,AP,"Médicos (Clinicos gerais, ginecologistas e out...",9.0,3257.0,2.763279,2.76
234,2024,RJ,"Médicos (Clinicos gerais, ginecologistas e out...",129.0,46115.0,2.797354,2.80
218,2024,AM,"Médicos (Clinicos gerais, ginecologistas e out...",16.0,5111.0,3.130503,3.13
224,2024,GO,"Médicos (Clinicos gerais, ginecologistas e out...",60.0,18489.0,3.245173,3.25
217,2024,AL,"Médicos (Clinicos gerais, ginecologistas e out...",18.0,5240.0,3.435115,3.44
223,2024,ES,"Médicos (Clinicos gerais, ginecologistas e out...",83.0,24117.0,3.441556,3.44
227,2024,MS,"Médicos (Clinicos gerais, ginecologistas e out...",58.0,16662.0,3.480975,3.48
220,2024,BA,"Médicos (Clinicos gerais, ginecologistas e out...",59.0,13721.0,4.299978,4.30
235,2024,RN,"Médicos (Clinicos gerais, ginecologistas e out...",34.0,7499.0,4.533938,4.53
232,2024,PI,"Médicos (Clinicos gerais, ginecologistas e out...",36.0,7198.0,5.001389,5.00
236,2024,RO,"Médicos (Clinicos gerais, ginecologistas e out...",38.0,7466.0,5.089740,5.09
225,2024,MA,"Médicos (Clinicos gerais, ginecologistas e out...",77.0,11743.0,6.557098,6.56

In [ ]:
medicos_fisica_pop.columns

Index(['ano', 'sigla_uf', 'profissao', 'total_medicos_fisica', 'pop_total',
       'medicos_fisica_por_1000', 'medicos_fisica_por_1000_1'],
      dtype='object')

In [ ]:
a.sort_values(by='medicos_fisica_por_1000_1', ascending=True)

,ano,sigla_uf,profissao,total_medicos_fisica,pop_total,medicos_fisica_por_1000,medicos_fisica_por_1000_1
241,2024,SP,"Médicos (Clinicos gerais, ginecologistas e out...",173.0,205984.0,0.839871,0.84
216,2024,AC,"Médicos (Clinicos gerais, ginecologistas e out...",6.0,5401.0,1.110905,1.11
229,2024,PA,"Médicos (Clinicos gerais, ginecologistas e out...",26.0,15498.0,1.677636,1.68
221,2024,CE,"Médicos (Clinicos gerais, ginecologistas e out...",40.0,22296.0,1.794044,1.79
228,2024,MT,"Médicos (Clinicos gerais, ginecologistas e out...",25.0,13735.0,1.820167,1.82
231,2024,PE,"Médicos (Clinicos gerais, ginecologistas e out...",53.0,28983.0,1.828658,1.83
233,2024,PR,"Médicos (Clinicos gerais, ginecologistas e out...",76.0,40699.0,1.867368,1.87
238,2024,RS,"Médicos (Clinicos gerais, ginecologistas e out...",71.0,36157.0,1.963658,1.96
222,2024,DF,"Médicos (Clinicos gerais, ginecologistas e out...",32.0,16200.0,1.975309,1.98
240,2024,SE,"Médicos (Clinicos gerais, ginecologistas e out...",13.0,6034.0,2.154458,2.15
230,2024,PB,"Médicos (Clinicos gerais, ginecologistas e out...",28.0,12410.0,2.256245,2.26
239,2024,SC,"Médicos (Clinicos gerais, ginecologistas e out...",62.0,27349.0,2.266993,2.27
242,2024,TO,"Médicos (Clinicos gerais, ginecologistas e out...",10.0,3888.0,2.572016,2.57
226,2024,MG,"Médicos (Clinicos gerais, ginecologistas e out...",175.0,66282.0,2.640234,2.64
237,2024,RR,"Médicos (Clinicos gerais, ginecologistas e out...",9.0,3258.0,2.762431,2.76
219,2024,AP,"Médicos (Clinicos gerais, ginecologistas e out...",9.0,3257.0,2.763279,2.76
234,2024,RJ,"Médicos (Clinicos gerais, ginecologistas e out...",129.0,46115.0,2.797354,2.80
218,2024,AM,"Médicos (Clinicos gerais, ginecologistas e out...",16.0,5111.0,3.130503,3.13
224,2024,GO,"Médicos (Clinicos gerais, ginecologistas e out...",60.0,18489.0,3.245173,3.25
217,2024,AL,"Médicos (Clinicos gerais, ginecologistas e out...",18.0,5240.0,3.435115,3.44
223,2024,ES,"Médicos (Clinicos gerais, ginecologistas e out...",83.0,24117.0,3.441556,3.44
227,2024,MS,"Médicos (Clinicos gerais, ginecologistas e out...",58.0,16662.0,3.480975,3.48
220,2024,BA,"Médicos (Clinicos gerais, ginecologistas e out...",59.0,13721.0,4.299978,4.30
235,2024,RN,"Médicos (Clinicos gerais, ginecologistas e out...",34.0,7499.0,4.533938,4.53
232,2024,PI,"Médicos (Clinicos gerais, ginecologistas e out...",36.0,7198.0,5.001389,5.00
236,2024,RO,"Médicos (Clinicos gerais, ginecologistas e out...",38.0,7466.0,5.089740,5.09
225,2024,MA,"Médicos (Clinicos gerais, ginecologistas e out...",77.0,11743.0,6.557098,6.56

# Agregando dados de anos anteriores

In [ ]:
medicos_fisica_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ano                        27 non-null     int64
 1   sigla_uf                   27 non-null     object
 2   profissao                  27 non-null     object
 3   total_medicos_fisica       27 non-null     float64
 4   pop_total                  27 non-null     int64
 5   medicos_fisica_por_1000    27 non-null     float64
 6   medicos_fisica_por_1000_1  27 non-null     float64
dtypes: float64(3), int64(2), object(2)
memory usage: 1.6+ KB

In [ ]:
query = """SELECT * FROM `repositoriodedadosgpsp.perfil_remuneracao.SENAPPEN_medico_saude_fisica_mil_presos`"""
# Execute the query using pandas_gbq.read_gbq and load the result into a pandas DataFrame called 'df'.
# The 'project_id' specifies the Google Cloud Project to use.
df_old = pandas_gbq.read_gbq(query, project_id='repositoriodedadosgpsp')

Downloading: 100%|██████████|

In [ ]:
df_old.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ano                        243 non-null    Int64
 1   sigla_uf                   243 non-null    object
 2   profissao                  243 non-null    object
 3   total_medicos_fisica       243 non-null    float64
 4   pop_total                  243 non-null    float64
 5   medicos_fisica_por_1000    243 non-null    float64
 6   medicos_fisica_por_1000_1  243 non-null    float64
dtypes: Int64(1), float64(4), object(2)
memory usage: 13.7+ KB

In [ ]:
df_final = pd.concat([medicos_fisica_pop, df_old], ignore_index=True)

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ano                        270 non-null    Int64
 1   sigla_uf                   270 non-null    object
 2   profissao                  270 non-null    object
 3   total_medicos_fisica       270 non-null    float64
 4   pop_total                  270 non-null    float64
 5   medicos_fisica_por_1000    270 non-null    float64
 6   medicos_fisica_por_1000_1  270 non-null    float64
dtypes: Int64(1), float64(4), object(2)
memory usage: 15.2+ KB

# Subindo no GBQ

In [ ]:
# Define the BigQuery table schema with Portuguese descriptions
schema=[bigquery.SchemaField('ano','INTEGER',description='Ano de referencia'),
 bigquery.SchemaField('sigla_uf','STRING',description='Sigla da Unidade da Federação.'),
 bigquery.SchemaField('profissao','STRING',description='Profissional'),
 bigquery.SchemaField('total_medicos_fisica','FLOAT',description='Quantidade de médicos responsáveis pela saúde física'),
 bigquery.SchemaField('pop_total','FLOAT',description='Total da população prisional'),
 bigquery.SchemaField('medicos_fisica_por_1000','FLOAT',description='Taxa de médicos por 1000 presos')
 ]


# Initialize BigQuery client connection
client = bigquery.Client(project='repositoriodedadosgpsp')

# Create reference to target dataset
dataset_ref = client.dataset('perfil_remuneracao')

# Create reference to target table with standardized naming convention:
# FONTE_algo_intuitivo_dado (INEP_esforco_docente_temporal_v2)
table_ref = dataset_ref.table('SENAPPEN_medico_saude_fisica_mil_presos_v1')

# Configure the load job with our schema definition
job_config = bigquery.LoadJobConfig(schema=schema)

# Execute the load job to upload DataFrame to BigQuery
job = client.load_table_from_dataframe(
    dataframe=df_final,
    destination=table_ref,
    job_config=job_config
)

# Wait for the job to complete
job.result()

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

LoadJob<project=repositoriodedadosgpsp, location=US, id=67eed406-c586-499d-ad4c-2496334975f2>