In [1]:
import pandas as pd
import numpy as np
import time
import os
import zipfile
import pandas_gbq
import unidecode
from google.cloud import bigquery
import re

c:\Users\ana.sales_republica\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
client = bigquery.Client()

In [3]:
diretorio = 'G:\\Drives compartilhados\\República.org\\4. Equipes\\Dados e Comunicação\\DADOS E CONHECIMENTO\\460 - Estudos e Infográficos\\20 - Sistema prisional\\bases de dados'

In [4]:
os.chdir(diretorio)

In [5]:
os.listdir(diretorio)

['15o-ciclo-base-de-dados-2023-2-semestre-1.csv',
 '3o-ciclo-base-de-dados-2017-2-semestre.csv',
 '5o-ciclo-base-de-dados-2018-2-semestre.csv',
 '7o-ciclo-base-de-dados-2019-2-semestre.csv',
 '11o-ciclo-base-de-dados-2021-2-semestre.csv',
 '17o-ciclo-base-de-dados-2024-2-semestre.csv',
 'sistema_prisional.ipynb',
 '13o-ciclo-base-de-dados-2022-2-semestre.csv',
 'notas.md',
 '1º semestre',
 'infopen_2014.csv',
 'infopen_2015.csv',
 '1o-ciclo-base-de-dados-2016-2-semestre.csv',
 '9o-ciclo-base-de-dados-2020-2-semestre (1).csv',
 '17o-ciclo-base-de-dados-2024-2-semestre - Copia.csv',
 'qtd_total_epor_1000_por_profissao_saude.csv',
 'consolidado_geral_pop_profissoes.csv',
 'cnes-assistentes-sociais-mil-habitantes-g0B7UJeVYo6Vk4w7y.csv',
 'pop_por_cor_total_pct.xlsx',
 'saude_profissoes_ano.xlsx',
 'areas_por_pop_ano.xlsx',
 'saude_fisica.xlsx',
 'saude_mental_ano.xlsx',
 'saude_2024_profissao.xlsx']

In [5]:
df16 = pd.read_csv('1o-ciclo-base-de-dados-2016-2-semestre.csv', encoding= 'utf8', sep=';')
df17 = pd.read_csv('3o-ciclo-base-de-dados-2017-2-semestre.csv', encoding= 'utf8', sep=';')
df18 = pd.read_csv('5o-ciclo-base-de-dados-2018-2-semestre.csv', encoding= 'utf8', sep=';')
df19 = pd.read_csv('7o-ciclo-base-de-dados-2019-2-semestre.csv', encoding= 'utf8', sep=';')
df20 = pd.read_csv('9o-ciclo-base-de-dados-2020-2-semestre (1).csv', encoding= 'utf8', sep=';')
df21 = pd.read_csv('11o-ciclo-base-de-dados-2021-2-semestre.csv', encoding= 'utf8', sep=';')
df22 = pd.read_csv('13o-ciclo-base-de-dados-2022-2-semestre.csv', encoding= 'utf8', sep=';')
df23 = pd.read_csv('15o-ciclo-base-de-dados-2023-2-semestre-1.csv', encoding= 'utf8', sep=';')
df24 = pd.read_csv('17o-ciclo-base-de-dados-2024-2-semestre.csv', encoding= 'utf8', sep=';')

C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_4608\1506389750.py:2: DtypeWarning: Columns (128,130) have mixed types. Specify dtype option on import or set low_memory=False.
  df17 = pd.read_csv('3o-ciclo-base-de-dados-2017-2-semestre.csv', encoding= 'utf8', sep=';')
C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_4608\1506389750.py:3: DtypeWarning: Columns (128,130) have mixed types. Specify dtype option on import or set low_memory=False.
  df18 = pd.read_csv('5o-ciclo-base-de-dados-2018-2-semestre.csv', encoding= 'utf8', sep=';')
C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_4608\1506389750.py:4: DtypeWarning: Columns (128,130) have mixed types. Specify dtype option on import or set low_memory=False.
  df19 = pd.read_csv('7o-ciclo-base-de-dados-2019-2-semestre.csv', encoding= 'utf8', sep=';')
C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_4608\1506389750.py:6: DtypeWarning: Columns (7,128,130,389) have mixed types. Specify dtype option on import or set low_memory=False.
  df21 = pd.read_csv('11o-ciclo-base-de-dados-2021-2-semestre.csv', encoding= 'utf8', sep=';')
C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_4608\1506389750.py:9: DtypeWarning: Columns (7,36,118,121,128,130,147,389,395) have mixed types. Specify dtype option on import or set low_memory=False.
  df24 = pd.read_csv('17o-ciclo-base-de-dados-2024-2-semestre.csv', encoding= 'utf8', sep=';')

In [6]:
df_todos = pd.concat([df16, df17, df18, df19, df20, df21, df22, df23, df24])
df_todos

,ciclo,Ano,Referência,Tipo do Estabelecimento,Situação de Preenchimento,Nome do Estabelecimento,Situação do Estabelecimento,Outras Denominações,Endereço,Bairro,...,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tonga | Masculino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tonga | Feminino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tonga | Total,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tuvalu | Masculino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tuvalu | Feminino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tuvalu | Total,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Vanuatu | Masculino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Vanuatu | Feminino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Vanuatu | Total,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Outros países do continente Oceania | Total
0,1,2016,2016/2,Domiciliar com monitoramento eletrônico,Validado,UNIDADE DE MONITORAMENTO ELETRONICO DE PRESOS,Ativo,NaN,"Av Getúlio Vargas, 1203",Bosque,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2016,2016/2,Cela física,Validado,UNIDADE DE RECOLHIMENTO PROVISORIO,Ativo,NaN,Estrada do Barro Vermelho km 3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO FEMININO,Ativo,NaN,ESTRADA DO BARRO VERMELHO KM03,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N1,Ativo,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N2,Ativo,NaN,ESTRADA DO BARRO VERMELHO - KM 03,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1558,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Brasília,Ativo,NaN,Rod DF-465 KM 01 - Complexo Penitenciário da P...,Setor Habitacional Jardim Botânico,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1559,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Campo Grande,Ativo,NaN,AVENIDA HENRIQUE BERTIN S/N JARDIM LOS ANGELES,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1560,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Catanduvas,Ativo,NaN,"Rodovia PR 471, Km 15, s/n",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1561,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Mossoró,Ativo,NaN,"RN 15, Km 13, Estrada Mossoró/Baraúnas - Mosso...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1562,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Porto Velho,Ativo,NaN,"SÍTIO DA BOA ESPERANÇA, LOTE 13, GLEBA 13 ""A"" ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
dfs = {
    2016: df16,
    2017: df17,
    2018: df18,
    2019: df19,
    2020: df20,
    2021: df21,
    2022: df22,
    2023: df23,
    2024: df24
}

In [8]:
colunas_por_ano = {ano: set(df.columns) for ano, df in dfs.items()}

# Mostra as diferenças ano a ano em relação ao anterior
for ano_atual in sorted(dfs.keys())[1:]:
    ano_anterior = ano_atual - 1
    colunas_atuais = colunas_por_ano[ano_atual]
    colunas_anteriores = colunas_por_ano[ano_anterior]
    
    adicionadas = colunas_atuais - colunas_anteriores
    removidas = colunas_anteriores - colunas_atuais
    
    print(f"\n {ano_atual}:")
    if adicionadas:
        print(f"Colunas adicionadas em relação a {ano_anterior}: {sorted(adicionadas)}")
    if removidas:
        print(f"Colunas removidas em relação a {ano_anterior}: {sorted(removidas)}")
    if not adicionadas and not removidas:
        print("Nenhuma mudança nas colunas.")

 2017:
Colunas adicionadas em relação a 2016: ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Comissionado Feminino', '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Comissionado Masculino', '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Efetivo Feminino', '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Efetivo Masculino', '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Temporário Feminino', '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Temporário Masculino', '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Terceirizado Feminino', '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Terceirizado Masculino', '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Órgão de lotação originária (para efetivos e comissionados)']
Colunas removidas em relação a 2016: ['5.2 Quantidade de pessoas privadas de liberdade por cor de pele/raça/etnia | Outras | Feminino', '5.2 Quantidade de pessoas privadas de liberdade por cor de pele/raça/etnia | Outras | Masculino', '5.2 Quantidade de pessoas privadas de liberdade por cor de pele/raça/etnia | Outras | Total']

 2018:
Nenhuma mudança nas colunas.

 2019:
Nenhuma mudança nas colunas.

 2020:
Nenhuma mudança nas colunas.

 2021:
Colunas adicionadas em relação a 2020: ['2.13 Há "cela(s)-seguro"?', '5.14 Quantidade de incidências por tipo penal |  GRUPO: LEGISLAÇÃO ESPECÍFICA | Grupo: Legislação específica - outros | Estatuto da Criança e do Adolescente (Lei 8.069, de 13/01/1990) | Feminino', '5.14 Quantidade de incidências por tipo penal |  GRUPO: LEGISLAÇÃO ESPECÍFICA | Grupo: Legislação específica - outros | Estatuto da Criança e do Adolescente (Lei 8.069, de 13/01/1990) | Masculino', '5.14 Quantidade de incidências por tipo penal |  GRUPO: LEGISLAÇÃO ESPECÍFICA | Grupo: Legislação específica - outros | Estatuto da Criança e do Adolescente (Lei 8.069, de 13/01/1990) | Total', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com a iniciativa privada | Setor primário - rural, agrícola e artesanato | Trabalho externo Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com a iniciativa privada | Setor primário - rural, agrícola e artesanato | Trabalho externo Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com a iniciativa privada | Setor primário - rural, agrícola e artesanato | Trabalho interno Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com a iniciativa privada | Setor primário - rural, agrícola e artesanato | Trabalho interno Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com a iniciativa privada | Setor secundário - industrial e contrução civil | Trabalho externo Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com a iniciativa privada | Setor secundário - industrial e contrução civil | Trabalho externo Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com a iniciativa privada | Setor secundário - industrial e contrução civil | Trabalho interno Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com a iniciativa privada | Setor secundário - industrial e contrução civil | Trabalho interno Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor primário - rural, agrícola e artesanato | Total', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor primário - rural, agrícola e artesanato | Trabalho externo Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor primário - rural, agrícola e artesanato | Trabalho externo Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor primário - rural, agrícola e artesanato | Trabalho interno Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor primário - rural, agrícola e artesanato | Trabalho interno Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor secundário - industrial e contrução civil | Total', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor secundário - industrial e contrução civil | Trabalho externo Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor secundário - industrial e contrução civil | Trabalho externo Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor secundário - industrial e contrução civil | Trabalho interno Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor secundário - industrial e contrução civil | Trabalho interno Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor terciário - serviços | Total', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor terciário - serviços | Trabalho externo Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor terciário - serviços | Trabalho externo Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor terciário - serviços | Trabalho interno Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com entidade ou organizações não governamentais sem fins lucrativos | Setor terciário - serviços | Trabalho interno Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com outros órgãos públicos | Setor primário - rural, agrícola e artesanato | Trabalho externo Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com outros órgãos públicos | Setor primário - rural, agrícola e artesanato | Trabalho externo Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com outros órgãos públicos | Setor primário - rural, agrícola e artesanato | Trabalho interno Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com outros órgãos públicos | Setor primário - rural, agrícola e artesanato | Trabalho interno Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com outros órgãos públicos | Setor secundário - industrial e contrução civil | Trabalho externo Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com outros órgãos públicos | Setor secundário - industrial e contrução civil | Trabalho externo Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com outros órgãos públicos | Setor secundário - industrial e contrução civil | Trabalho interno Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas disponibilizadas pela administração prisional em parceria com outros órgãos públicos | Setor secundário - industrial e contrução civil | Trabalho interno Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas obtidas por meios próprios e/ou sem intervenção do sistema prisional | Setor secundário - industrial e contrução civil | Trabalho externo Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas obtidas por meios próprios e/ou sem intervenção do sistema prisional | Setor secundário - industrial e contrução civil | Trabalho externo Masculino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas obtidas por meios próprios e/ou sem intervenção do sistema prisional | Setor secundário - industrial e contrução civil | Trabalho interno Feminino', '6.1 Quantidade de pessoas privadas de liberdade em programas de laborterapia | Quantidade de pessoas em vagas obtidas por meios próprios e/ou sem intervenção do sistema prisional | Setor secundário - industrial e contrução civil | Trabalho interno Masculino', '7.5 Foi realizada visita(s) de inspeção no período de referência? | Outro(s). Qual?']

In [9]:
df_todos = df_todos[df_todos['Tipo do Estabelecimento']=='Cela física']
df_todos

,ciclo,Ano,Referência,Tipo do Estabelecimento,Situação de Preenchimento,Nome do Estabelecimento,Situação do Estabelecimento,Outras Denominações,Endereço,Bairro,...,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tonga | Masculino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tonga | Feminino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tonga | Total,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tuvalu | Masculino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tuvalu | Feminino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Tuvalu | Total,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Vanuatu | Masculino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Vanuatu | Feminino,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Vanuatu | Total,5.8 Quantidade de pessoas privadas de liberdade por nacionalidade | Oceania | Outros países do continente Oceania | Total
1,1,2016,2016/2,Cela física,Validado,UNIDADE DE RECOLHIMENTO PROVISORIO,Ativo,NaN,Estrada do Barro Vermelho km 3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO FEMININO,Ativo,NaN,ESTRADA DO BARRO VERMELHO KM03,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N1,Ativo,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N2,Ativo,NaN,ESTRADA DO BARRO VERMELHO - KM 03,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,2016,2016/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N3,Ativo,NaN,ESTRADA DIAS MARTINS KM 05 S/N ATRÁS DO BOPE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1558,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Brasília,Ativo,NaN,Rod DF-465 KM 01 - Complexo Penitenciário da P...,Setor Habitacional Jardim Botânico,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1559,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Campo Grande,Ativo,NaN,AVENIDA HENRIQUE BERTIN S/N JARDIM LOS ANGELES,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1560,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Catanduvas,Ativo,NaN,"Rodovia PR 471, Km 15, s/n",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1561,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Mossoró,Ativo,NaN,"RN 15, Km 13, Estrada Mossoró/Baraúnas - Mosso...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1562,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Porto Velho,Ativo,NaN,"SÍTIO DA BOA ESPERANÇA, LOTE 13, GLEBA 13 ""A"" ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
col_masc = [
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Estadual Masculino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Federal Masculino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Estadual Masculino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Federal Masculino',
    '4.1 População prisional | Medida de segurança - internação | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Estadual Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Federal Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Outros(Just. Trab., cível) Masculino'
]

col_fem = [
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Estadual Feminino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Federal Feminino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Estadual Feminino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Federal Feminino',
    '4.1 População prisional | Medida de segurança - internação | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Estadual Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Federal Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Outros(Just. Trab., cível) Feminino'
]

In [41]:
enf = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total'].sum()
aux_enf= df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total'].sum()
psi = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total'].sum()
dent = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Total'].sum()
tec_dent = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Total'].sum()
assits = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Assistentes sociais | Total'].sum()
adv = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Advogados | Total'].sum()
med_geral = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total'].sum()
med_gineco = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total'].sum()
med_psiq = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – psiquiatras | Total'].sum()
med_outros = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total'].sum()
ped = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Pedagogos | Total'].sum()
prof= df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Professores | Total'].sum()
terapeuta_ocup = df['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Terapeuta/ terapeuta ocupacional | Total'].sum()

In [17]:
dfs = [df16, df17, df18, df19, df20, df21, df22, df23, df24]
anos = list(range(2016, 2025))  # de 2016 a 2024

In [21]:
resultados = []

In [22]:
col_enfs = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total',
             '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total']

col_medicos_fisica = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total',
                        '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total',
                       '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total']
                       
col_medicos_mental = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total',
                    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – psiquiatras | Total',
                    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Terapeuta/ terapeuta ocupacional | Total']
col_assits = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Assistentes sociais | Total']

col_pop = ['4.1 População prisional | Total']

In [23]:
for df, ano in zip(dfs, anos):
    # Filtrando apenas celas físicas
    df = df[df['Tipo do Estabelecimento'] == 'Cela física'].copy()  # .copy() evita avisos de atribuição encadeada

    # Conversão para numérico
    for col_group in [col_medicos_fisica, col_medicos_mental, col_enfs, col_assits, col_masc, col_fem]:
        for col in col_group:
            df.loc[:, col] = pd.to_numeric(df[col], errors='coerce')

    # Cálculo de totais por linha com .loc
    df.loc[:, 'total_medicos_fisica'] = df[col_medicos_fisica].sum(axis=1)
    df.loc[:, 'total_medicos_mental'] = df[col_medicos_mental].sum(axis=1)
    df.loc[:, 'total_enfs'] = df[col_enfs].sum(axis=1)
    df.loc[:, 'total_assits'] = df[col_assits].sum(axis=1)
    df.loc[:, 'pop_masc'] = df[col_masc].sum(axis=1)
    df.loc[:, 'pop_fem'] = df[col_fem].sum(axis=1)
    df.loc[:, 'pop_total'] = df[col_pop]
    df.loc[:, 'ano'] = ano

    # Agrupamento por UF e ano
    grupo = df.groupby(['UF', 'ano'])[
        ['total_medicos_fisica', 'total_medicos_mental', 'total_enfs', 'total_assits',
         'pop_masc', 'pop_fem', 'pop_total']
    ].sum().reset_index()

    resultados.append(grupo)

# Concatenação dos resultados
saude_area_populacao_ano_uf = pd.concat(resultados, ignore_index=True)

In [24]:
saude_area_populacao_ano_uf

,UF,ano,total_medicos_fisica,total_medicos_mental,total_enfs,total_assits,pop_masc,pop_fem,pop_total
0,AC,2016,14.0,15.0,33.0,21.0,4955.0,330.0,5285.0
1,AL,2016,4.0,20.0,70.0,15.0,6700.0,411.0,7111.0
2,AM,2016,13.0,25.0,62.0,25.0,8510.0,1731.0,10241.0
3,AP,2016,3.0,21.0,15.0,11.0,2831.0,106.0,2937.0
4,BA,2016,29.0,84.0,173.0,50.0,13088.0,508.0,13596.0
...,...,...,...,...,...,...,...,...,...
238,RS,2024,71.0,161.0,158.0,167.0,34443.0,1714.0,36157.0
239,SC,2024,62.0,76.0,188.0,65.0,25901.0,1448.0,27349.0
240,SE,2024,13.0,24.0,104.0,21.0,5801.0,233.0,6034.0
241,SP,2024,173.0,204.0,791.0,196.0,196839.0,9145.0,205984.0
242,TO,2024,10.0,13.0,37.0,19.0,3734.0,154.0,3888.0

In [25]:
saude_area_populacao_ano_uf['medicos_fisica_por_1000'] = (
    saude_area_populacao_ano_uf['total_medicos_fisica'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000

saude_area_populacao_ano_uf['medicos_mental_por_1000'] = (
    saude_area_populacao_ano_uf['total_medicos_mental'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000

saude_area_populacao_ano_uf['total_enfs_por_1000'] = (
    saude_area_populacao_ano_uf['total_enfs'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000
saude_area_populacao_ano_uf['total_assits_por_1000'] = (
    saude_area_populacao_ano_uf['total_assits'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000
saude_area_populacao_ano_uf

,UF,ano,total_medicos_fisica,total_medicos_mental,total_enfs,total_assits,pop_masc,pop_fem,pop_total,medicos_fisica_por_1000,medicos_mental_por_1000,total_enfs_por_1000,total_assits_por_1000
0,AC,2016,14.0,15.0,33.0,21.0,4955.0,330.0,5285.0,2.649007,2.838221,6.244087,3.973510
1,AL,2016,4.0,20.0,70.0,15.0,6700.0,411.0,7111.0,0.562509,2.812544,9.843904,2.109408
2,AM,2016,13.0,25.0,62.0,25.0,8510.0,1731.0,10241.0,1.269407,2.441168,6.054096,2.441168
3,AP,2016,3.0,21.0,15.0,11.0,2831.0,106.0,2937.0,1.021450,7.150153,5.107252,3.745318
4,BA,2016,29.0,84.0,173.0,50.0,13088.0,508.0,13596.0,2.132980,6.178288,12.724331,3.677552
...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,RS,2024,71.0,161.0,158.0,167.0,34443.0,1714.0,36157.0,1.963658,4.452803,4.369832,4.618746
239,SC,2024,62.0,76.0,188.0,65.0,25901.0,1448.0,27349.0,2.266993,2.778895,6.874109,2.376687
240,SE,2024,13.0,24.0,104.0,21.0,5801.0,233.0,6034.0,2.154458,3.977461,17.235665,3.480278
241,SP,2024,173.0,204.0,791.0,196.0,196839.0,9145.0,205984.0,0.839871,0.990368,3.840104,0.951530
242,TO,2024,10.0,13.0,37.0,19.0,3734.0,154.0,3888.0,2.572016,3.343621,9.516461,4.886831

In [26]:
medicos_mental_pop = saude_area_populacao_ano_uf[['ano','UF','total_medicos_mental', 'pop_total', 'medicos_mental_por_1000']]
medicos_mental_pop

      ano  UF  total_medicos_mental  pop_total  medicos_mental_por_1000
0    2016  AC                  15.0     5285.0                 2.838221
1    2016  AL                  20.0     7111.0                 2.812544
2    2016  AM                  25.0    10241.0                 2.441168
3    2016  AP                  21.0     2937.0                 7.150153
4    2016  BA                  84.0    13596.0                 6.178288
..    ...  ..                   ...        ...                      ...
238  2024  RS                 161.0    36157.0                 4.452803
239  2024  SC                  76.0    27349.0                 2.778895
240  2024  SE                  24.0     6034.0                 3.977461
241  2024  SP                 204.0   205984.0                 0.990368
242  2024  TO                  13.0     3888.0                 3.343621

[243 rows x 5 columns]

In [27]:
medicos_mental_pop['profissao'] = 'Psiquiatras/psicólogos/terapeutas'

C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_4608\2164045910.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  medicos_mental_pop['profissao'] = 'Psiquiatras/psicólogos/terapeutas'

In [28]:
medicos_mental_pop.columns

Index(['ano', 'UF', 'total_medicos_mental', 'pop_total',
       'medicos_mental_por_1000', 'profissao'],
      dtype='object')

In [29]:
a = medicos_mental_pop[medicos_mental_pop['ano']==2024]
a['total_medicos_mental'].sum()

1759.0

In [30]:
medicos_mental_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ano                      243 non-null    int64
 1   UF                       243 non-null    object
 2   total_medicos_mental     243 non-null    float64
 3   pop_total                243 non-null    float64
 4   medicos_mental_por_1000  243 non-null    float64
 5   profissao                243 non-null    object
dtypes: float64(3), int64(1), object(2)
memory usage: 11.5+ KB

In [31]:
medicos_mental_pop = medicos_mental_pop.rename(
                                            columns={'UF':'sigla_uf'                                  
                                            })
medicos_mental_pop

,ano,sigla_uf,total_medicos_mental,pop_total,medicos_mental_por_1000,profissao
0,2016,AC,15.0,5285.0,2.838221,Psiquiatras/psicólogos/terapeutas
1,2016,AL,20.0,7111.0,2.812544,Psiquiatras/psicólogos/terapeutas
2,2016,AM,25.0,10241.0,2.441168,Psiquiatras/psicólogos/terapeutas
3,2016,AP,21.0,2937.0,7.150153,Psiquiatras/psicólogos/terapeutas
4,2016,BA,84.0,13596.0,6.178288,Psiquiatras/psicólogos/terapeutas
...,...,...,...,...,...,...
238,2024,RS,161.0,36157.0,4.452803,Psiquiatras/psicólogos/terapeutas
239,2024,SC,76.0,27349.0,2.778895,Psiquiatras/psicólogos/terapeutas
240,2024,SE,24.0,6034.0,3.977461,Psiquiatras/psicólogos/terapeutas
241,2024,SP,204.0,205984.0,0.990368,Psiquiatras/psicólogos/terapeutas
242,2024,TO,13.0,3888.0,3.343621,Psiquiatras/psicólogos/terapeutas

In [32]:
medicos_mental_pop['medicos_mental_por_1000_1']= medicos_mental_pop['medicos_mental_por_1000'].round(2)
medicos_mental_pop

,ano,sigla_uf,total_medicos_mental,pop_total,medicos_mental_por_1000,profissao,medicos_mental_por_1000_1
0,2016,AC,15.0,5285.0,2.838221,Psiquiatras/psicólogos/terapeutas,2.84
1,2016,AL,20.0,7111.0,2.812544,Psiquiatras/psicólogos/terapeutas,2.81
2,2016,AM,25.0,10241.0,2.441168,Psiquiatras/psicólogos/terapeutas,2.44
3,2016,AP,21.0,2937.0,7.150153,Psiquiatras/psicólogos/terapeutas,7.15
4,2016,BA,84.0,13596.0,6.178288,Psiquiatras/psicólogos/terapeutas,6.18
...,...,...,...,...,...,...,...
238,2024,RS,161.0,36157.0,4.452803,Psiquiatras/psicólogos/terapeutas,4.45
239,2024,SC,76.0,27349.0,2.778895,Psiquiatras/psicólogos/terapeutas,2.78
240,2024,SE,24.0,6034.0,3.977461,Psiquiatras/psicólogos/terapeutas,3.98
241,2024,SP,204.0,205984.0,0.990368,Psiquiatras/psicólogos/terapeutas,0.99
242,2024,TO,13.0,3888.0,3.343621,Psiquiatras/psicólogos/terapeutas,3.34

In [47]:
medicos_mental_pop[medicos_mental_pop['ano']==2024]['total_medicos_mental'].sum()

1759.0

In [33]:
medicos_mental_pop.columns

Index(['ano', 'sigla_uf', 'total_medicos_mental', 'pop_total',
       'medicos_mental_por_1000', 'profissao', 'medicos_mental_por_1000_1'],
      dtype='object')

In [61]:
medicos_mental_pop[(medicos_mental_pop['ano'] == 2024) & (medicos_mental_pop['medicos_mental_por_1000_1'] < 2.62)].sort_values(by='medicos_mental_por_1000_1', ascending=True)

,ano,sigla_uf,total_medicos_mental,pop_total,medicos_mental_por_1000,profissao,medicos_mental_por_1000_1
241,2024,SP,204.0,205984.0,0.990368,Psiquiatras/psicólogos/terapeutas,0.99
222,2024,DF,18.0,16200.0,1.111111,Psiquiatras/psicólogos/terapeutas,1.11
233,2024,PR,57.0,40699.0,1.400526,Psiquiatras/psicólogos/terapeutas,1.40
221,2024,CE,37.0,22296.0,1.659490,Psiquiatras/psicólogos/terapeutas,1.66
216,2024,AC,9.0,5401.0,1.666358,Psiquiatras/psicólogos/terapeutas,1.67
227,2024,MS,38.0,16662.0,2.280639,Psiquiatras/psicólogos/terapeutas,2.28
234,2024,RJ,110.0,46115.0,2.385341,Psiquiatras/psicólogos/terapeutas,2.39
228,2024,MT,35.0,13735.0,2.548234,Psiquiatras/psicólogos/terapeutas,2.55

In [60]:
medicos_mental_pop[medicos_mental_pop['ano']==2024].sort_values(by='medicos_mental_por_1000', ascending=False)

,ano,sigla_uf,total_medicos_mental,pop_total,medicos_mental_por_1000,profissao,medicos_mental_por_1000_1
220,2024,BA,112.0,13721.0,8.162670,Psiquiatras/psicólogos/terapeutas,8.16
217,2024,AL,36.0,5240.0,6.870229,Psiquiatras/psicólogos/terapeutas,6.87
225,2024,MA,77.0,11743.0,6.557098,Psiquiatras/psicólogos/terapeutas,6.56
218,2024,AM,31.0,5111.0,6.065349,Psiquiatras/psicólogos/terapeutas,6.07
229,2024,PA,80.0,15498.0,5.161956,Psiquiatras/psicólogos/terapeutas,5.16
232,2024,PI,34.0,7198.0,4.723534,Psiquiatras/psicólogos/terapeutas,4.72
238,2024,RS,161.0,36157.0,4.452803,Psiquiatras/psicólogos/terapeutas,4.45
226,2024,MG,286.0,66282.0,4.314897,Psiquiatras/psicólogos/terapeutas,4.31
235,2024,RN,30.0,7499.0,4.000533,Psiquiatras/psicólogos/terapeutas,4.00
240,2024,SE,24.0,6034.0,3.977461,Psiquiatras/psicólogos/terapeutas,3.98
242,2024,TO,13.0,3888.0,3.343621,Psiquiatras/psicólogos/terapeutas,3.34
223,2024,ES,77.0,24117.0,3.192769,Psiquiatras/psicólogos/terapeutas,3.19
224,2024,GO,58.0,18489.0,3.137000,Psiquiatras/psicólogos/terapeutas,3.14
230,2024,PB,36.0,12410.0,2.900886,Psiquiatras/psicólogos/terapeutas,2.90
231,2024,PE,82.0,28983.0,2.829245,Psiquiatras/psicólogos/terapeutas,2.83
239,2024,SC,76.0,27349.0,2.778895,Psiquiatras/psicólogos/terapeutas,2.78
219,2024,AP,9.0,3257.0,2.763279,Psiquiatras/psicólogos/terapeutas,2.76
237,2024,RR,9.0,3258.0,2.762431,Psiquiatras/psicólogos/terapeutas,2.76
236,2024,RO,20.0,7466.0,2.678811,Psiquiatras/psicólogos/terapeutas,2.68
228,2024,MT,35.0,13735.0,2.548234,Psiquiatras/psicólogos/terapeutas,2.55
234,2024,RJ,110.0,46115.0,2.385341,Psiquiatras/psicólogos/terapeutas,2.39
227,2024,MS,38.0,16662.0,2.280639,Psiquiatras/psicólogos/terapeutas,2.28
216,2024,AC,9.0,5401.0,1.666358,Psiquiatras/psicólogos/terapeutas,1.67
221,2024,CE,37.0,22296.0,1.659490,Psiquiatras/psicólogos/terapeutas,1.66
233,2024,PR,57.0,40699.0,1.400526,Psiquiatras/psicólogos/terapeutas,1.40
222,2024,DF,18.0,16200.0,1.111111,Psiquiatras/psicólogos/terapeutas,1.11
241,2024,SP,204.0,205984.0,0.990368,Psiquiatras/psicólogos/terapeutas,0.99

In [35]:
medicos_mental_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ano                        243 non-null    int64
 1   sigla_uf                   243 non-null    object
 2   total_medicos_mental       243 non-null    float64
 3   pop_total                  243 non-null    float64
 4   medicos_mental_por_1000    243 non-null    float64
 5   profissao                  243 non-null    object
 6   medicos_mental_por_1000_1  243 non-null    float64
dtypes: float64(4), int64(1), object(2)
memory usage: 13.4+ KB

In [87]:
medicos_mental_pop.to_excel('mental_pop.xlsx', index=False)

In [62]:
client = bigquery.Client()
dataset_ref = client.dataset('perfil_remuneracao')

In [82]:

schema=[bigquery.SchemaField('ano','INTEGER',description='Ano de referencia'),
        bigquery.SchemaField('sigla_uf','STRING',description='Sigla da Unidade da Federação'),
        bigquery.SchemaField('profissao','STRING',description='Profissional'),
        bigquery.SchemaField('total_medicos_mental','FLOAT',description='Quantidade de médicos responsáveis pela saúde mental'),
        bigquery.SchemaField('pop_total','FLOAT',description='Total da população prisional'),
        bigquery.SchemaField('medicos_mental_por_1000','FLOAT',description='Taxa de médicos responsáveis pela saúde mental por 1000 presos'),
        bigquery.SchemaField('medicos_mental_por_1000_1','FLOAT',description='Taxa de médicos  responsáveis pela saúde mental por 1000 presos arredondado')
 ]

In [83]:
table_ref = dataset_ref.table('SENAPPEN_profissionais_saude_mental_mil_presos') 
job_config = bigquery.LoadJobConfig(schema=schema)
job = client.load_table_from_dataframe(medicos_mental_pop, table_ref, job_config=job_config)
job.result()

LoadJob<project=repositoriodedadosgpsp, location=US, id=b67f708a-bfa6-4473-9143-4d935656f5e5>