In [ ]:
# Install required Google Cloud packages (commented out as these are typically one-time setup commands)
!pip install gcloud
!gcloud auth application-default login

# Import necessary Python libraries
import pandas as pd                # Data manipulation and analysis
import numpy as np                 # Numerical computing
import time                        # Time-related functions
import os                          # Operating system interfaces
import pandas_gbq                  # Pandas integration with BigQuery
from google.cloud import bigquery  # BigQuery client library
import glob                        # File path pattern matching
import openpyxl                    # Excel file handling
import csv                         # CSV file handling
import re                          # Regular expressions

# Note: The actual imports remain exactly as in the original code

Collecting gcloud
  Downloading gcloud-0.18.3.tar.gz (454 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 454.4/454.4 kB 11.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: httplib2>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from gcloud) (0.32.0)
Requirement already satisfied: googleapis-common-protos in /usr/local/lib/python3.12/dist-packages (from gcloud) (1.75.0)
Requirement already satisfied: oauth2client>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from gcloud) (4.1.3)
Requirement already satisfied: protobuf!=3.0.0.b2.post1,>=3.0.0b2 in /usr/local/lib/python3.12/dist-packages (from gcloud) (5.29.6)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from gcloud) (1.17.0)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2>=0.9.1->gcloud) (3.3.2)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (0.6.4)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (0.4.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (4.9.1)
Building wheels for collected packages: gcloud
  Building wheel for gcloud (setup.py) ... done
  Created wheel for gcloud: filename=gcloud-0.18.3-py3-none-any.whl size=602927 sha256=e6bc10639facc6e911a376afec323c49444615ef26f4ca5e705f709e8bebdfc8
  Stored in directory: /root/.cache/pip/wheels/2a/62/75/3d74209bfebb8805823ae74afa28653aa1ea76d8b5a9d741ff
Successfully built gcloud
Installing collected packages: gcloud
Successfully installed gcloud-0.18.3
Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fapplicationdefaultauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=rdnYTokOR7OWGGKHciLR5iiHf1e4aC&prompt=consent&token_usage=remote&access_type=offline&code_challenge=hWhrYFFc1CLnJG1BKl4o5UhXd43C_uSbv9sRZauymXY&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0AXEQxICo6iWxnLva6cSNpMFSj45PHtwzDspcAZHIFGZI7A1WZxiJvTkmhg791h81leg1Wg

Credentials saved to file: [/content/.config/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.


To take a quick anonymous survey, run:
  $ gcloud survey

In [ ]:
df25 = pd.read_csv('/content/19o-ciclo-base-de-dados-2025-2-semestre.csv', encoding= 'utf8', sep=';')

/tmp/ipykernel_3772/338327083.py:1: DtypeWarning: Columns (389) have mixed types. Specify dtype option on import or set low_memory=False.
  df25 = pd.read_csv('/content/19o-ciclo-base-de-dados-2025-2-semestre.csv', encoding= 'utf8', sep=';')

In [ ]:
dfs = {
    2025: df25
}

In [ ]:
df_todos = pd.concat(dfs, ignore_index=True)
df_todos = df_todos[df_todos['Tipo do Estabelecimento']=='Cela física']
df_todos

,ciclo,Ano,Referência,Tipo do Estabelecimento,Situação de Preenchimento,Nome do Estabelecimento,Situação do Estabelecimento,Outras Denominações,Endereço,Bairro,...,7.3 Quantidade de visitas registradas no período de referência | Quantidade de presos que receberam visita no período de referência | Feminino,7.5 Foi realizada visita(s) de inspeção no período de referência?,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho Nacional de Política Criminal e Penitenciária - CNPCP,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho Estadual de Política Criminal e Penitenciária/ Conselho Penitenciário,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho da Comunidade,7.5 Foi realizada visita(s) de inspeção no período de referência? | Ouvidoria do sistema prisional - estadual ou nacional,7.5 Foi realizada visita(s) de inspeção no período de referência? | Defensoria Pública,7.5 Foi realizada visita(s) de inspeção no período de referência? | Judiciário,7.5 Foi realizada visita(s) de inspeção no período de referência? | Ministério Público,7.5 Foi realizada visita(s) de inspeção no período de referência? | Outro(s). Qual?
5,19,2025,2025/2,Cela física,Validado,UNIDADE DE RECOLHIMENTO PROVISÓRIO,Ativo,NaN,Estrada do Barro Vermelho km 3,DISTRITO INDUSTRIAL,...,NaN,Sim,Não,Não,Não,Sim,Sim,Sim,Sim,NaN
6,19,2025,2025/2,Cela física,Validado,UNIDADE DE REGIME FECHADO FEMININO,Ativo,NaN,ESTRADA DO BARRO VERMELHO KM03,DISTRITO INDUSTRIAL,...,NaN,Sim,Não,Não,Não,Sim,Sim,Sim,Sim,NaN
7,19,2025,2025/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N1,Ativo,NaN,"Estrada do Barro Vermelho, km 03",Distrito Industrial,...,NaN,Sim,Não,Sim,Sim,Sim,Sim,Sim,Sim,NaN
8,19,2025,2025/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N2,Ativo,NaN,ESTRADA DO BARRO VERMELHO - KM 03,DISTRITO INDUSTRIAL,...,0.0,Sim,Não,Não,Não,Não,Sim,Não,Sim,NaN
9,19,2025,2025/2,Cela física,Validado,UNIDADE PENITENCIARIA DO QUINARI,Ativo,NaN,Rodovia BR - 317 - KM 11,Zona rural,...,0.0,Sim,Não,Sim,Sim,Sim,Sim,Sim,Sim,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1527,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Brasília,Ativo,NaN,Rod DF-465 KM 01 - Complexo Penitenciário da P...,Setor Habitacional Jardim Botânico,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN
1528,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Campo Grande,Ativo,NaN,AVENIDA HENRIQUE BERTIN S/N JARDIM LOS ANGELES,NaN,...,0.0,Sim,Não,Não,Não,Não,Não,Sim,Sim,NaN
1529,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Catanduvas,Ativo,NaN,"Rodovia PR 471, Km 15, s/n",NaN,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN
1530,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Mossoró,Ativo,NaN,"RN 15, Km 13, Estrada Mossoró/Baraúnas - Mosso...",NaN,...,0.0,Sim,Não,Não,Sim,Não,Sim,Sim,Sim,NaN
1531,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Porto Velho,Ativo,NaN,"SÍTIO DA BOA ESPERANÇA, LOTE 13, GLEBA 13 ""A"" ...",NaN,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN

In [ ]:
col_masc = [
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Estadual Masculino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Federal Masculino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Estadual Masculino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Federal Masculino',
    '4.1 População prisional | Medida de segurança - internação | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Estadual Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Federal Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Outros(Just. Trab., cível) Masculino'
]

col_fem = [
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Estadual Feminino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Federal Feminino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Estadual Feminino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Federal Feminino',
    '4.1 População prisional | Medida de segurança - internação | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Estadual Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Federal Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Outros(Just. Trab., cível) Feminino'
]

In [ ]:
enf = df24['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total'].sum()
aux_enf= df24['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total'].sum()
psi = df24['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total'].sum()
dent = df24['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Total'].sum()
tec_dent = df24['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Total'].sum()
assits = df24['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Assistentes sociais | Total'].sum()
adv = df24['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Advogados | Total'].sum()
med_geral = df24['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total'].sum()
med_gineco = df24['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total'].sum()
med_psiq = df24['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – psiquiatras | Total'].sum()
med_outros = df24['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total'].sum()
ped = df24['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Pedagogos | Total'].sum()
prof= df24['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Professores | Total'].sum()
terapeuta_ocup = df24['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Terapeuta/ terapeuta ocupacional | Total'].sum()

In [ ]:
col_enfs = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total',
             '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total']

col_medicos_fisica = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total',
                        '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total',
                       '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total']

col_medicos_mental = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total',
                    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – psiquiatras | Total',
                    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Terapeuta/ terapeuta ocupacional | Total']
col_assits = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Assistentes sociais | Total']

col_pop = ['4.1 População prisional | Total']

In [ ]:
resultados= []
dfs = [df25]
anos = list(range(2025, 2026))  # de 2016 a 2024

In [ ]:
for df, ano in zip(dfs, anos):
    df = df[df['Tipo do Estabelecimento'] == 'Cela física'].copy()

    for col_group in [col_medicos_fisica, col_medicos_mental, col_enfs, col_assits, col_masc, col_fem]:
        for col in col_group:
            df[col] = pd.to_numeric(df[col], errors='coerce')

    # Soma populacional por sexo
    df['pop_masc'] = df[col_masc].sum(axis=1)
    df['pop_fem'] = df[col_fem].sum(axis=1)
    df['pop_total'] = df['pop_masc'] + df['pop_fem']

    df['total_medicos_fisica'] = df[col_medicos_fisica].sum(axis=1)
    df['total_medicos_mental'] = df[col_medicos_mental].sum(axis=1)
    df['total_enfs'] = df[col_enfs].sum(axis=1)
    df['total_assistentes_sociais'] = df[col_assits].sum(axis=1)
    df['ano'] = ano

    grupo = df.groupby(['UF', 'ano'])[
        ['total_medicos_fisica', 'total_medicos_mental', 'total_enfs', 'total_assistentes_sociais',
         'pop_masc', 'pop_fem', 'pop_total']
    ].sum().reset_index()

    resultados.append(grupo)

# DataFrame final unificado
saude_area_populacao_ano_uf = pd.concat(resultados, ignore_index=True)

In [ ]:
saude_area_populacao_ano_uf

,UF,ano,total_medicos_fisica,total_medicos_mental,total_enfs,total_assistentes_sociais,pop_masc,pop_fem,pop_total
0,AC,2025,5.0,12.0,12.0,19.0,5225.0,213.0,5438.0
1,AL,2025,21.0,36.0,131.0,26.0,5731.0,191.0,5922.0
2,AM,2025,14.0,34.0,70.0,25.0,5767.0,216.0,5983.0
3,AP,2025,5.0,8.0,24.0,5.0,3836.0,149.0,3985.0
4,BA,2025,65.0,109.0,286.0,73.0,16126.0,598.0,16724.0
5,CE,2025,50.0,40.0,131.0,41.0,24186.0,1227.0,25413.0
6,DF,2025,34.0,23.0,60.0,7.0,16360.0,661.0,17021.0
7,ES,2025,107.0,114.0,128.0,84.0,24201.0,1120.0,25321.0
8,GO,2025,67.0,58.0,138.0,42.0,18448.0,896.0,19344.0
9,MA,2025,77.0,69.0,380.0,69.0,12513.0,419.0,12932.0
10,MG,2025,194.0,311.0,551.0,275.0,70297.0,3135.0,73432.0
11,MS,2025,55.0,37.0,88.0,43.0,17198.0,1039.0,18237.0
12,MT,2025,25.0,38.0,118.0,41.0,14732.0,1000.0,15732.0
13,PA,2025,25.0,82.0,225.0,84.0,15907.0,701.0,16608.0
14,PB,2025,25.0,39.0,52.0,24.0,12591.0,710.0,13301.0
15,PE,2025,42.0,79.0,114.0,101.0,29913.0,997.0,30910.0
16,PI,2025,42.0,43.0,102.0,58.0,7678.0,306.0,7984.0
17,PR,2025,103.0,71.0,170.0,54.0,41239.0,2449.0,43688.0
18,RJ,2025,102.0,113.0,427.0,59.0,44844.0,1801.0,46645.0
19,RN,2025,33.0,24.0,65.0,14.0,7639.0,365.0,8004.0
20,RO,2025,31.0,16.0,136.0,25.0,7972.0,431.0,8403.0
21,RR,2025,8.0,7.0,35.0,3.0,2969.0,159.0,3128.0
22,RS,2025,81.0,162.0,220.0,168.0,38883.0,2172.0,41055.0
23,SC,2025,68.0,101.0,177.0,66.0,28893.0,1620.0,30513.0
24,SE,2025,12.0,23.0,91.0,21.0,6193.0,257.0,6450.0
25,SP,2025,160.0,176.0,787.0,185.0,210752.0,10468.0,221220.0
26,TO,2025,13.0,15.0,39.0,15.0,4314.0,188.0,4502.0

In [ ]:
saude_area_populacao_ano_uf['medicos_fisica_por_1000'] = (
    saude_area_populacao_ano_uf['total_medicos_fisica'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000

saude_area_populacao_ano_uf['medicos_mental_por_1000'] = (
    saude_area_populacao_ano_uf['total_medicos_mental'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000

saude_area_populacao_ano_uf['total_enfs_por_1000'] = (
    saude_area_populacao_ano_uf['total_enfs'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000
saude_area_populacao_ano_uf['total_assists_por_1000'] = (
    saude_area_populacao_ano_uf['total_assistentes_sociais'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000
saude_area_populacao_ano_uf

,UF,ano,total_medicos_fisica,total_medicos_mental,total_enfs,total_assistentes_sociais,pop_masc,pop_fem,pop_total,medicos_fisica_por_1000,medicos_mental_por_1000,total_enfs_por_1000,total_assists_por_1000
0,AC,2025,5.0,12.0,12.0,19.0,5225.0,213.0,5438.0,0.919456,2.206694,2.206694,3.493932
1,AL,2025,21.0,36.0,131.0,26.0,5731.0,191.0,5922.0,3.546099,6.079027,22.120905,4.390409
2,AM,2025,14.0,34.0,70.0,25.0,5767.0,216.0,5983.0,2.339963,5.682768,11.699816,4.178506
3,AP,2025,5.0,8.0,24.0,5.0,3836.0,149.0,3985.0,1.254705,2.007528,6.022585,1.254705
4,BA,2025,65.0,109.0,286.0,73.0,16126.0,598.0,16724.0,3.886630,6.517580,17.101172,4.364984
5,CE,2025,50.0,40.0,131.0,41.0,24186.0,1227.0,25413.0,1.967497,1.573998,5.154842,1.613347
6,DF,2025,34.0,23.0,60.0,7.0,16360.0,661.0,17021.0,1.997532,1.351272,3.525057,0.411257
7,ES,2025,107.0,114.0,128.0,84.0,24201.0,1120.0,25321.0,4.225741,4.502192,5.055093,3.317405
8,GO,2025,67.0,58.0,138.0,42.0,18448.0,896.0,19344.0,3.463606,2.998346,7.133995,2.171216
9,MA,2025,77.0,69.0,380.0,69.0,12513.0,419.0,12932.0,5.954222,5.335602,29.384473,5.335602
10,MG,2025,194.0,311.0,551.0,275.0,70297.0,3135.0,73432.0,2.641900,4.235211,7.503541,3.744961
11,MS,2025,55.0,37.0,88.0,43.0,17198.0,1039.0,18237.0,3.015847,2.028842,4.825355,2.357844
12,MT,2025,25.0,38.0,118.0,41.0,14732.0,1000.0,15732.0,1.589118,2.415459,7.500636,2.606153
13,PA,2025,25.0,82.0,225.0,84.0,15907.0,701.0,16608.0,1.505299,4.937380,13.547688,5.057803
14,PB,2025,25.0,39.0,52.0,24.0,12591.0,710.0,13301.0,1.879558,2.932110,3.909480,1.804376
15,PE,2025,42.0,79.0,114.0,101.0,29913.0,997.0,30910.0,1.358784,2.555807,3.688127,3.267551
16,PI,2025,42.0,43.0,102.0,58.0,7678.0,306.0,7984.0,5.260521,5.385772,12.775551,7.264529
17,PR,2025,103.0,71.0,170.0,54.0,41239.0,2449.0,43688.0,2.357627,1.625160,3.891229,1.236037
18,RJ,2025,102.0,113.0,427.0,59.0,44844.0,1801.0,46645.0,2.186730,2.422553,9.154250,1.264873
19,RN,2025,33.0,24.0,65.0,14.0,7639.0,365.0,8004.0,4.122939,2.998501,8.120940,1.749125
20,RO,2025,31.0,16.0,136.0,25.0,7972.0,431.0,8403.0,3.689159,1.904082,16.184696,2.975128
21,RR,2025,8.0,7.0,35.0,3.0,2969.0,159.0,3128.0,2.557545,2.237852,11.189258,0.959079
22,RS,2025,81.0,162.0,220.0,168.0,38883.0,2172.0,41055.0,1.972963,3.945926,5.358665,4.092072
23,SC,2025,68.0,101.0,177.0,66.0,28893.0,1620.0,30513.0,2.228558,3.310065,5.800806,2.163012
24,SE,2025,12.0,23.0,91.0,21.0,6193.0,257.0,6450.0,1.860465,3.565891,14.108527,3.255814
25,SP,2025,160.0,176.0,787.0,185.0,210752.0,10468.0,221220.0,0.723262,0.795588,3.557545,0.836272
26,TO,2025,13.0,15.0,39.0,15.0,4314.0,188.0,4502.0,2.887606,3.331853,8.662817,3.331853

In [ ]:
total_assistentes_sociais_pop = saude_area_populacao_ano_uf[['ano','UF','total_assistentes_sociais', 'pop_total', 'total_assists_por_1000']]
total_assistentes_sociais_pop

     ano  UF  total_assistentes_sociais  pop_total  total_assists_por_1000
0   2025  AC                       19.0     5438.0                3.493932
1   2025  AL                       26.0     5922.0                4.390409
2   2025  AM                       25.0     5983.0                4.178506
3   2025  AP                        5.0     3985.0                1.254705
4   2025  BA                       73.0    16724.0                4.364984
5   2025  CE                       41.0    25413.0                1.613347
6   2025  DF                        7.0    17021.0                0.411257
7   2025  ES                       84.0    25321.0                3.317405
8   2025  GO                       42.0    19344.0                2.171216
9   2025  MA                       69.0    12932.0                5.335602
10  2025  MG                      275.0    73432.0                3.744961
11  2025  MS                       43.0    18237.0                2.357844
12  2025  MT                       41.0    15732.0                2.606153
13  2025  PA                       84.0    16608.0                5.057803
14  2025  PB                       24.0    13301.0                1.804376
15  2025  PE                      101.0    30910.0                3.267551
16  2025  PI                       58.0     7984.0                7.264529
17  2025  PR                       54.0    43688.0                1.236037
18  2025  RJ                       59.0    46645.0                1.264873
19  2025  RN                       14.0     8004.0                1.749125
20  2025  RO                       25.0     8403.0                2.975128
21  2025  RR                        3.0     3128.0                0.959079
22  2025  RS                      168.0    41055.0                4.092072
23  2025  SC                       66.0    30513.0                2.163012
24  2025  SE                       21.0     6450.0                3.255814
25  2025  SP                      185.0   221220.0                0.836272
26  2025  TO                       15.0     4502.0                3.331853

In [ ]:
total_assistentes_sociais_pop[(total_assistentes_sociais_pop['ano'] == 2025) & (total_assistentes_sociais_pop['total_assists_por_1000'] < 2.37)].sort_values(by='total_assists_por_1000', ascending=True)

     ano  UF  total_assistentes_sociais  pop_total  total_assists_por_1000
6   2025  DF                        7.0    17021.0                0.411257
25  2025  SP                      185.0   221220.0                0.836272
21  2025  RR                        3.0     3128.0                0.959079
17  2025  PR                       54.0    43688.0                1.236037
3   2025  AP                        5.0     3985.0                1.254705
18  2025  RJ                       59.0    46645.0                1.264873
5   2025  CE                       41.0    25413.0                1.613347
19  2025  RN                       14.0     8004.0                1.749125
14  2025  PB                       24.0    13301.0                1.804376
23  2025  SC                       66.0    30513.0                2.163012
8   2025  GO                       42.0    19344.0                2.171216
11  2025  MS                       43.0    18237.0                2.357844

Maior quantidade de de profissionais
Minas Gerais: 264.0 profissionais, 66282 pessoas (3.98 por mil)
São Paulo: 167,, 205984 pessoas,  (0.95 por mil)
RS: 161, 36.157 pessoas, (4.62 por mil)

Menor proporção:
DF 7, 16.200 pessoas (0.43 por mil)
SP 196, 205,984 (0.95 por mil)
RJ 54.0 profissionais, 46115 pessoas (1.17 por mil)
Além desses, PR, RR, CE, AP, RN, GO, PB possuem a taxa abaixo da média nacional (2.37)

Maior proporção:
PI 49 profissionais, 7198 pessoas (6.81 por mil) e 5ª maior qtd de profissionais,
PA 91.0 profissionais, 15498 pessoas, (5.87 por mil)
BA 72 profissionais, 13721 pessoas (5.25 por mil)

In [ ]:
total_assistentes_sociais_pop[total_assistentes_sociais_pop['ano']==2025].sort_values(by='total_assists_por_1000', ascending=True)

     ano  UF  total_assistentes_sociais  pop_total  total_assists_por_1000
6   2025  DF                        7.0    17021.0                0.411257
25  2025  SP                      185.0   221220.0                0.836272
21  2025  RR                        3.0     3128.0                0.959079
17  2025  PR                       54.0    43688.0                1.236037
3   2025  AP                        5.0     3985.0                1.254705
18  2025  RJ                       59.0    46645.0                1.264873
5   2025  CE                       41.0    25413.0                1.613347
19  2025  RN                       14.0     8004.0                1.749125
14  2025  PB                       24.0    13301.0                1.804376
23  2025  SC                       66.0    30513.0                2.163012
8   2025  GO                       42.0    19344.0                2.171216
11  2025  MS                       43.0    18237.0                2.357844
12  2025  MT                       41.0    15732.0                2.606153
20  2025  RO                       25.0     8403.0                2.975128
24  2025  SE                       21.0     6450.0                3.255814
15  2025  PE                      101.0    30910.0                3.267551
7   2025  ES                       84.0    25321.0                3.317405
26  2025  TO                       15.0     4502.0                3.331853
0   2025  AC                       19.0     5438.0                3.493932
10  2025  MG                      275.0    73432.0                3.744961
22  2025  RS                      168.0    41055.0                4.092072
2   2025  AM                       25.0     5983.0                4.178506
4   2025  BA                       73.0    16724.0                4.364984
1   2025  AL                       26.0     5922.0                4.390409
13  2025  PA                       84.0    16608.0                5.057803
9   2025  MA                       69.0    12932.0                5.335602
16  2025  PI                       58.0     7984.0                7.264529

In [ ]:
total_assistentes_sociais_pop[total_assistentes_sociais_pop['ano']==2024]['pop_total'].sum()
total_assistentes_sociais

670792.0

In [ ]:
total_assistentes_sociais_pop[total_assistentes_sociais_pop['ano']==2024]['total_assistentes_sociais'].sum()

1589.0

In [ ]:
total_assistentes_sociais_pop['profissao'] = 'Assistentes sociais'

/tmp/ipykernel_3772/3309208839.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  total_assistentes_sociais_pop['profissao'] = 'Assistentes sociais'

In [ ]:
total_assistentes_sociais_pop.columns

Index(['ano', 'UF', 'total_assistentes_sociais', 'pop_total',
       'total_assists_por_1000', 'profissao'],
      dtype='object')

In [ ]:
total_assistentes_sociais_pop = total_assistentes_sociais_pop[['ano', 'UF', 'profissao', 'total_assistentes_sociais', 'pop_total',
       'total_assists_por_1000']]
total_assistentes_sociais_pop

,ano,UF,profissao,total_assistentes_sociais,pop_total,total_assists_por_1000
0,2025,AC,Assistentes sociais,19.0,5438.0,3.493932
1,2025,AL,Assistentes sociais,26.0,5922.0,4.390409
2,2025,AM,Assistentes sociais,25.0,5983.0,4.178506
3,2025,AP,Assistentes sociais,5.0,3985.0,1.254705
4,2025,BA,Assistentes sociais,73.0,16724.0,4.364984
5,2025,CE,Assistentes sociais,41.0,25413.0,1.613347
6,2025,DF,Assistentes sociais,7.0,17021.0,0.411257
7,2025,ES,Assistentes sociais,84.0,25321.0,3.317405
8,2025,GO,Assistentes sociais,42.0,19344.0,2.171216
9,2025,MA,Assistentes sociais,69.0,12932.0,5.335602
10,2025,MG,Assistentes sociais,275.0,73432.0,3.744961
11,2025,MS,Assistentes sociais,43.0,18237.0,2.357844
12,2025,MT,Assistentes sociais,41.0,15732.0,2.606153
13,2025,PA,Assistentes sociais,84.0,16608.0,5.057803
14,2025,PB,Assistentes sociais,24.0,13301.0,1.804376
15,2025,PE,Assistentes sociais,101.0,30910.0,3.267551
16,2025,PI,Assistentes sociais,58.0,7984.0,7.264529
17,2025,PR,Assistentes sociais,54.0,43688.0,1.236037
18,2025,RJ,Assistentes sociais,59.0,46645.0,1.264873
19,2025,RN,Assistentes sociais,14.0,8004.0,1.749125
20,2025,RO,Assistentes sociais,25.0,8403.0,2.975128
21,2025,RR,Assistentes sociais,3.0,3128.0,0.959079
22,2025,RS,Assistentes sociais,168.0,41055.0,4.092072
23,2025,SC,Assistentes sociais,66.0,30513.0,2.163012
24,2025,SE,Assistentes sociais,21.0,6450.0,3.255814
25,2025,SP,Assistentes sociais,185.0,221220.0,0.836272
26,2025,TO,Assistentes sociais,15.0,4502.0,3.331853

In [ ]:
total_assistentes_sociais_pop = total_assistentes_sociais_pop.rename(
                                            columns={'UF':'sigla_uf'
                                            })
total_assistentes_sociais_pop

,ano,sigla_uf,profissao,total_assistentes_sociais,pop_total,total_assists_por_1000
0,2025,AC,Assistentes sociais,19.0,5438.0,3.493932
1,2025,AL,Assistentes sociais,26.0,5922.0,4.390409
2,2025,AM,Assistentes sociais,25.0,5983.0,4.178506
3,2025,AP,Assistentes sociais,5.0,3985.0,1.254705
4,2025,BA,Assistentes sociais,73.0,16724.0,4.364984
5,2025,CE,Assistentes sociais,41.0,25413.0,1.613347
6,2025,DF,Assistentes sociais,7.0,17021.0,0.411257
7,2025,ES,Assistentes sociais,84.0,25321.0,3.317405
8,2025,GO,Assistentes sociais,42.0,19344.0,2.171216
9,2025,MA,Assistentes sociais,69.0,12932.0,5.335602
10,2025,MG,Assistentes sociais,275.0,73432.0,3.744961
11,2025,MS,Assistentes sociais,43.0,18237.0,2.357844
12,2025,MT,Assistentes sociais,41.0,15732.0,2.606153
13,2025,PA,Assistentes sociais,84.0,16608.0,5.057803
14,2025,PB,Assistentes sociais,24.0,13301.0,1.804376
15,2025,PE,Assistentes sociais,101.0,30910.0,3.267551
16,2025,PI,Assistentes sociais,58.0,7984.0,7.264529
17,2025,PR,Assistentes sociais,54.0,43688.0,1.236037
18,2025,RJ,Assistentes sociais,59.0,46645.0,1.264873
19,2025,RN,Assistentes sociais,14.0,8004.0,1.749125
20,2025,RO,Assistentes sociais,25.0,8403.0,2.975128
21,2025,RR,Assistentes sociais,3.0,3128.0,0.959079
22,2025,RS,Assistentes sociais,168.0,41055.0,4.092072
23,2025,SC,Assistentes sociais,66.0,30513.0,2.163012
24,2025,SE,Assistentes sociais,21.0,6450.0,3.255814
25,2025,SP,Assistentes sociais,185.0,221220.0,0.836272
26,2025,TO,Assistentes sociais,15.0,4502.0,3.331853

In [ ]:
total_assistentes_sociais_pop['total_assists_por_1000']= total_assistentes_sociais_pop['total_assists_por_1000'].round(2)
total_assistentes_sociais_pop

,ano,sigla_uf,profissao,total_assistentes_sociais,pop_total,total_assists_por_1000
0,2025,AC,Assistentes sociais,19.0,5438.0,3.49
1,2025,AL,Assistentes sociais,26.0,5922.0,4.39
2,2025,AM,Assistentes sociais,25.0,5983.0,4.18
3,2025,AP,Assistentes sociais,5.0,3985.0,1.25
4,2025,BA,Assistentes sociais,73.0,16724.0,4.36
5,2025,CE,Assistentes sociais,41.0,25413.0,1.61
6,2025,DF,Assistentes sociais,7.0,17021.0,0.41
7,2025,ES,Assistentes sociais,84.0,25321.0,3.32
8,2025,GO,Assistentes sociais,42.0,19344.0,2.17
9,2025,MA,Assistentes sociais,69.0,12932.0,5.34
10,2025,MG,Assistentes sociais,275.0,73432.0,3.74
11,2025,MS,Assistentes sociais,43.0,18237.0,2.36
12,2025,MT,Assistentes sociais,41.0,15732.0,2.61
13,2025,PA,Assistentes sociais,84.0,16608.0,5.06
14,2025,PB,Assistentes sociais,24.0,13301.0,1.80
15,2025,PE,Assistentes sociais,101.0,30910.0,3.27
16,2025,PI,Assistentes sociais,58.0,7984.0,7.26
17,2025,PR,Assistentes sociais,54.0,43688.0,1.24
18,2025,RJ,Assistentes sociais,59.0,46645.0,1.26
19,2025,RN,Assistentes sociais,14.0,8004.0,1.75
20,2025,RO,Assistentes sociais,25.0,8403.0,2.98
21,2025,RR,Assistentes sociais,3.0,3128.0,0.96
22,2025,RS,Assistentes sociais,168.0,41055.0,4.09
23,2025,SC,Assistentes sociais,66.0,30513.0,2.16
24,2025,SE,Assistentes sociais,21.0,6450.0,3.26
25,2025,SP,Assistentes sociais,185.0,221220.0,0.84
26,2025,TO,Assistentes sociais,15.0,4502.0,3.33

In [ ]:
total_assistentes_sociais_pop[total_assistentes_sociais_pop['ano']==2025]['total_assistentes_sociais'].sum()

np.float64(1627.0)

In [ ]:
total_assistentes_sociais_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ano                        27 non-null     int64
 1   sigla_uf                   27 non-null     object
 2   profissao                  27 non-null     object
 3   total_assistentes_sociais  27 non-null     float64
 4   pop_total                  27 non-null     float64
 5   total_assists_por_1000     27 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 1.4+ KB

In [ ]:
total_assistentes_sociais_pop[total_assistentes_sociais_pop['ano']==2025].sort_values(by='total_assists_por_1000', ascending=False)

,ano,sigla_uf,profissao,total_assistentes_sociais,pop_total,total_assists_por_1000
16,2025,PI,Assistentes sociais,58.0,7984.0,7.26
9,2025,MA,Assistentes sociais,69.0,12932.0,5.34
13,2025,PA,Assistentes sociais,84.0,16608.0,5.06
1,2025,AL,Assistentes sociais,26.0,5922.0,4.39
4,2025,BA,Assistentes sociais,73.0,16724.0,4.36
2,2025,AM,Assistentes sociais,25.0,5983.0,4.18
22,2025,RS,Assistentes sociais,168.0,41055.0,4.09
10,2025,MG,Assistentes sociais,275.0,73432.0,3.74
0,2025,AC,Assistentes sociais,19.0,5438.0,3.49
26,2025,TO,Assistentes sociais,15.0,4502.0,3.33
7,2025,ES,Assistentes sociais,84.0,25321.0,3.32
15,2025,PE,Assistentes sociais,101.0,30910.0,3.27
24,2025,SE,Assistentes sociais,21.0,6450.0,3.26
20,2025,RO,Assistentes sociais,25.0,8403.0,2.98
12,2025,MT,Assistentes sociais,41.0,15732.0,2.61
11,2025,MS,Assistentes sociais,43.0,18237.0,2.36
8,2025,GO,Assistentes sociais,42.0,19344.0,2.17
23,2025,SC,Assistentes sociais,66.0,30513.0,2.16
14,2025,PB,Assistentes sociais,24.0,13301.0,1.80
19,2025,RN,Assistentes sociais,14.0,8004.0,1.75
5,2025,CE,Assistentes sociais,41.0,25413.0,1.61
18,2025,RJ,Assistentes sociais,59.0,46645.0,1.26
3,2025,AP,Assistentes sociais,5.0,3985.0,1.25
17,2025,PR,Assistentes sociais,54.0,43688.0,1.24
21,2025,RR,Assistentes sociais,3.0,3128.0,0.96
25,2025,SP,Assistentes sociais,185.0,221220.0,0.84
6,2025,DF,Assistentes sociais,7.0,17021.0,0.41

# Agregando dados de anos anteriores

In [ ]:
total_assistentes_sociais_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ano                        27 non-null     int64
 1   sigla_uf                   27 non-null     object
 2   profissao                  27 non-null     object
 3   total_assistentes_sociais  27 non-null     float64
 4   pop_total                  27 non-null     float64
 5   total_assists_por_1000     27 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 1.4+ KB

In [ ]:
query = """SELECT * FROM `repositoriodedadosgpsp.perfil_remuneracao.SENAPPEN_assistentes_sociais_mil_presos`"""
# Execute the query using pandas_gbq.read_gbq and load the result into a pandas DataFrame called 'df'.
# The 'project_id' specifies the Google Cloud Project to use.
df_old = pandas_gbq.read_gbq(query, project_id='repositoriodedadosgpsp')

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

Downloading: 100%|██████████|

In [ ]:
df_old.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ano                        243 non-null    Int64
 1   sigla_uf                   243 non-null    object
 2   profissao                  243 non-null    object
 3   total_assistentes_sociais  243 non-null    float64
 4   pop_total                  243 non-null    float64
 5   total_assists_por_1000     243 non-null    float64
dtypes: Int64(1), float64(3), object(2)
memory usage: 11.8+ KB

In [ ]:
df_final = pd.concat([total_assistentes_sociais_pop, df_old], ignore_index=True)

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ano                        270 non-null    Int64
 1   sigla_uf                   270 non-null    object
 2   profissao                  270 non-null    object
 3   total_assistentes_sociais  270 non-null    float64
 4   pop_total                  270 non-null    float64
 5   total_assists_por_1000     270 non-null    float64
dtypes: Int64(1), float64(3), object(2)
memory usage: 13.0+ KB

# Subindo no GBQ

In [ ]:
# Define the BigQuery table schema with Portuguese descriptions

schema=[bigquery.SchemaField('ano','INTEGER',description='Ano de referencia'),
 bigquery.SchemaField('sigla_uf','STRING',description='Sigla da Unidade da Federação'),
 bigquery.SchemaField('profissao','STRING',description='Profissional'),
 bigquery.SchemaField('total_assistentes_sociais','FLOAT',description='Quantidade de assistentes sociais'),
 bigquery.SchemaField('pop_total','FLOAT',description='Total da população prisional'),
 bigquery.SchemaField('total_assists_por_1000','FLOAT',description='Taxa de assistentes sociais por 1000 presos')
 ]



# Initialize BigQuery client connection
client = bigquery.Client(project='repositoriodedadosgpsp')

# Create reference to target dataset
dataset_ref = client.dataset('perfil_remuneracao')

# Create reference to target table with standardized naming convention:
# FONTE_algo_intuitivo_dado (INEP_esforco_docente_temporal_v2)
table_ref = dataset_ref.table('SENAPPEN_assistentes_sociais_mil_presos_v1')

# Configure the load job with our schema definition
job_config = bigquery.LoadJobConfig(schema=schema)

# Execute the load job to upload DataFrame to BigQuery
job = client.load_table_from_dataframe(
    dataframe=df_final,
    destination=table_ref,
    job_config=job_config
)

# Wait for the job to complete
job.result()

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

LoadJob<project=repositoriodedadosgpsp, location=US, id=352139cb-c97a-4914-a6d8-aa82caa448c1>