In [ ]:
# Install required Google Cloud packages (commented out as these are typically one-time setup commands)
!pip install gcloud
!gcloud auth application-default login

# Import necessary Python libraries
import pandas as pd                # Data manipulation and analysis
import numpy as np                 # Numerical computing
import time                        # Time-related functions
import os                          # Operating system interfaces
import pandas_gbq                  # Pandas integration with BigQuery
from google.cloud import bigquery  # BigQuery client library
import glob                        # File path pattern matching
import openpyxl                    # Excel file handling
import csv                         # CSV file handling
import re                          # Regular expressions

# Note: The actual imports remain exactly as in the original code

Collecting gcloud
  Downloading gcloud-0.18.3.tar.gz (454 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 454.4/454.4 kB 10.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: httplib2>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from gcloud) (0.32.0)
Requirement already satisfied: googleapis-common-protos in /usr/local/lib/python3.12/dist-packages (from gcloud) (1.75.0)
Requirement already satisfied: oauth2client>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from gcloud) (4.1.3)
Requirement already satisfied: protobuf!=3.0.0.b2.post1,>=3.0.0b2 in /usr/local/lib/python3.12/dist-packages (from gcloud) (5.29.6)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from gcloud) (1.17.0)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2>=0.9.1->gcloud) (3.3.2)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (0.6.4)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (0.4.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (4.9.1)
Building wheels for collected packages: gcloud
  Building wheel for gcloud (setup.py) ... done
  Created wheel for gcloud: filename=gcloud-0.18.3-py3-none-any.whl size=602927 sha256=67f922ccc841d36a715128b0ef03afa14277df9cca28c872a58c14b0dfe61903
  Stored in directory: /root/.cache/pip/wheels/2a/62/75/3d74209bfebb8805823ae74afa28653aa1ea76d8b5a9d741ff
Successfully built gcloud
Installing collected packages: gcloud
Successfully installed gcloud-0.18.3
Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fapplicationdefaultauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=iVbm31n0OQ3kTIWaSOcmu4Z87AXTJ9&prompt=consent&token_usage=remote&access_type=offline&code_challenge=pEBEBfQfcDnxLsj3dyuvolWcgkxPDIKZcj-7ibsPqRw&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0AXEQxIDvOs7VqaY2cEI4AK0ATY7TU25zX6o_gxDesq2eM33aa7gWQ0_p383N7-QYT-0rWw

Credentials saved to file: [/content/.config/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.


To take a quick anonymous survey, run:
  $ gcloud survey

In [ ]:
df25 = pd.read_csv('/content/19o-ciclo-base-de-dados-2025-2-semestre.csv', encoding= 'utf8', sep=';')

/tmp/ipykernel_2662/338327083.py:1: DtypeWarning: Columns (389) have mixed types. Specify dtype option on import or set low_memory=False.
  df25 = pd.read_csv('/content/19o-ciclo-base-de-dados-2025-2-semestre.csv', encoding= 'utf8', sep=';')

In [ ]:
client = bigquery.Client()

In [ ]:
diretorio = 'G:\\Drives compartilhados\\República.org\\4. Equipes\\Dados e Comunicação\\DADOS E CONHECIMENTO\\460 - Estudos e Infográficos\\20 - Sistema prisional\\bases de dados'

In [ ]:
os.chdir(diretorio)

In [ ]:
os.listdir(diretorio)

['15o-ciclo-base-de-dados-2023-2-semestre-1.csv',
 '3o-ciclo-base-de-dados-2017-2-semestre.csv',
 '5o-ciclo-base-de-dados-2018-2-semestre.csv',
 '7o-ciclo-base-de-dados-2019-2-semestre.csv',
 '11o-ciclo-base-de-dados-2021-2-semestre.csv',
 '17o-ciclo-base-de-dados-2024-2-semestre.csv',
 'sistema_prisional.ipynb',
 '13o-ciclo-base-de-dados-2022-2-semestre.csv',
 'notas.md',
 '1º semestre',
 'infopen_2014.csv',
 'infopen_2015.csv',
 '1o-ciclo-base-de-dados-2016-2-semestre.csv',
 '9o-ciclo-base-de-dados-2020-2-semestre (1).csv',
 '17o-ciclo-base-de-dados-2024-2-semestre - Copia.csv',
 'qtd_total_epor_1000_por_profissao_saude.csv',
 'consolidado_geral_pop_profissoes.csv',
 'cnes-assistentes-sociais-mil-habitantes-g0B7UJeVYo6Vk4w7y.csv',
 'pop_por_cor_total_pct.xlsx',
 'saude_profissoes_ano.xlsx',
 'areas_por_pop_ano.xlsx',
 'saude_fisica.xlsx',
 'saude_mental_ano.xlsx',
 'saude_2024_profissao.xlsx',
 'mental_pop.xlsx',
 'sp_penintenciarias_fisicas.xlsx',
 'repasses_pnaisp.xlsx']

In [ ]:
df16 = pd.read_csv('1o-ciclo-base-de-dados-2016-2-semestre.csv', encoding= 'utf8', sep=';')
df17 = pd.read_csv('3o-ciclo-base-de-dados-2017-2-semestre.csv', encoding= 'utf8', sep=';')
df18 = pd.read_csv('5o-ciclo-base-de-dados-2018-2-semestre.csv', encoding= 'utf8', sep=';')
df19 = pd.read_csv('7o-ciclo-base-de-dados-2019-2-semestre.csv', encoding= 'utf8', sep=';')
df20 = pd.read_csv('9o-ciclo-base-de-dados-2020-2-semestre (1).csv', encoding= 'utf8', sep=';')
df21 = pd.read_csv('11o-ciclo-base-de-dados-2021-2-semestre.csv', encoding= 'utf8', sep=';')
df22 = pd.read_csv('13o-ciclo-base-de-dados-2022-2-semestre.csv', encoding= 'utf8', sep=';')
df23 = pd.read_csv('15o-ciclo-base-de-dados-2023-2-semestre-1.csv', encoding= 'utf8', sep=';')
df24 = pd.read_csv('17o-ciclo-base-de-dados-2024-2-semestre.csv', encoding= 'utf8', sep=';')

C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_23388\1506389750.py:2: DtypeWarning: Columns (128,130) have mixed types. Specify dtype option on import or set low_memory=False.
  df17 = pd.read_csv('3o-ciclo-base-de-dados-2017-2-semestre.csv', encoding= 'utf8', sep=';')
C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_23388\1506389750.py:3: DtypeWarning: Columns (128,130) have mixed types. Specify dtype option on import or set low_memory=False.
  df18 = pd.read_csv('5o-ciclo-base-de-dados-2018-2-semestre.csv', encoding= 'utf8', sep=';')
C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_23388\1506389750.py:4: DtypeWarning: Columns (128,130) have mixed types. Specify dtype option on import or set low_memory=False.
  df19 = pd.read_csv('7o-ciclo-base-de-dados-2019-2-semestre.csv', encoding= 'utf8', sep=';')
C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_23388\1506389750.py:6: DtypeWarning: Columns (7,128,130,389) have mixed types. Specify dtype option on import or set low_memory=False.
  df21 = pd.read_csv('11o-ciclo-base-de-dados-2021-2-semestre.csv', encoding= 'utf8', sep=';')
C:\Users\ana.sales_republica\AppData\Local\Temp\ipykernel_23388\1506389750.py:9: DtypeWarning: Columns (7,36,118,121,128,130,147,389,395) have mixed types. Specify dtype option on import or set low_memory=False.
  df24 = pd.read_csv('17o-ciclo-base-de-dados-2024-2-semestre.csv', encoding= 'utf8', sep=';')

In [ ]:
df_todos = df25
df_todos

,ciclo,Ano,Referência,Tipo do Estabelecimento,Situação de Preenchimento,Nome do Estabelecimento,Situação do Estabelecimento,Outras Denominações,Endereço,Bairro,...,7.3 Quantidade de visitas registradas no período de referência | Quantidade de presos que receberam visita no período de referência | Feminino,7.5 Foi realizada visita(s) de inspeção no período de referência?,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho Nacional de Política Criminal e Penitenciária - CNPCP,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho Estadual de Política Criminal e Penitenciária/ Conselho Penitenciário,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho da Comunidade,7.5 Foi realizada visita(s) de inspeção no período de referência? | Ouvidoria do sistema prisional - estadual ou nacional,7.5 Foi realizada visita(s) de inspeção no período de referência? | Defensoria Pública,7.5 Foi realizada visita(s) de inspeção no período de referência? | Judiciário,7.5 Foi realizada visita(s) de inspeção no período de referência? | Ministério Público,7.5 Foi realizada visita(s) de inspeção no período de referência? | Outro(s). Qual?
0,19,2025,2025/2,Domiciliar com monitoramento eletrônico,Validado,NÚCLEO DE MONITORAMENTO ELETRÔNICO DOMICILIAR ...,Ativo,NaN,"Travessa Santos Dumond, 2",Centro,...,0.0,Não,Não,Não,Não,Não,Não,Não,Não,NaN
1,19,2025,2025/2,Domiciliar com monitoramento eletrônico,Validado,NÚCLEO DE MONITORAMENTO ELETRÔNICO DOMICILIAR ...,Ativo,NaN,"Av. 25 de Agosto, 1923",Bairro 25 de Agosto,...,0.0,Não,Não,Não,Não,Não,Não,Não,Não,NaN
2,19,2025,2025/2,Domiciliar com monitoramento eletrônico,Validado,NÚCLEO DE MONITORAMENTO ELETRÔNICO DOMICILIAR ...,Ativo,NaN,"Avenida Marechal Deodoro, Setor 02 Q 20",Centro,...,NaN,Não,Não,Não,Não,Não,Não,Não,Não,NaN
3,19,2025,2025/2,Domiciliar com monitoramento eletrônico,Validado,NÚCLEO DE MONITORAMENTO ELETRONICO DOMICILIAR ...,Ativo,NaN,"Rodovia BR-364, KM 01",Triângulo,...,0.0,Não,Não,Não,Não,Não,Não,Não,Não,NaN
4,19,2025,2025/2,Domiciliar com monitoramento eletrônico,Validado,UNIDADE DE MONITORAMENTO ELETRÔNICO DOMICILIAR...,Ativo,NaN,"Av Getúlio Vargas, 1203",Bosque,...,NaN,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1527,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Brasília,Ativo,NaN,Rod DF-465 KM 01 - Complexo Penitenciário da P...,Setor Habitacional Jardim Botânico,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN
1528,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Campo Grande,Ativo,NaN,AVENIDA HENRIQUE BERTIN S/N JARDIM LOS ANGELES,NaN,...,0.0,Sim,Não,Não,Não,Não,Não,Sim,Sim,NaN
1529,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Catanduvas,Ativo,NaN,"Rodovia PR 471, Km 15, s/n",NaN,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN
1530,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Mossoró,Ativo,NaN,"RN 15, Km 13, Estrada Mossoró/Baraúnas - Mosso...",NaN,...,0.0,Sim,Não,Não,Sim,Não,Sim,Sim,Sim,NaN
1531,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Porto Velho,Ativo,NaN,"SÍTIO DA BOA ESPERANÇA, LOTE 13, GLEBA 13 ""A"" ...",NaN,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN

In [ ]:
dfs = {
    2025: df25
}

In [ ]:
colunas_por_ano = {ano: set(df.columns) for ano, df in dfs.items()}

# Mostra as diferenças ano a ano em relação ao anterior
for ano_atual in sorted(dfs.keys())[1:]:
    ano_anterior = ano_atual - 1
    colunas_atuais = colunas_por_ano[ano_atual]
    colunas_anteriores = colunas_por_ano[ano_anterior]

    adicionadas = colunas_atuais - colunas_anteriores
    removidas = colunas_anteriores - colunas_atuais

    print(f"\n {ano_atual}:")
    if adicionadas:
        print(f"Colunas adicionadas em relação a {ano_anterior}: {sorted(adicionadas)}")
    if removidas:
        print(f"Colunas removidas em relação a {ano_anterior}: {sorted(removidas)}")
    if not adicionadas and not removidas:
        print("Nenhuma mudança nas colunas.")

In [ ]:
df_todos = df_todos[df_todos['Tipo do Estabelecimento']=='Cela física']
df_todos

,ciclo,Ano,Referência,Tipo do Estabelecimento,Situação de Preenchimento,Nome do Estabelecimento,Situação do Estabelecimento,Outras Denominações,Endereço,Bairro,...,7.3 Quantidade de visitas registradas no período de referência | Quantidade de presos que receberam visita no período de referência | Feminino,7.5 Foi realizada visita(s) de inspeção no período de referência?,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho Nacional de Política Criminal e Penitenciária - CNPCP,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho Estadual de Política Criminal e Penitenciária/ Conselho Penitenciário,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho da Comunidade,7.5 Foi realizada visita(s) de inspeção no período de referência? | Ouvidoria do sistema prisional - estadual ou nacional,7.5 Foi realizada visita(s) de inspeção no período de referência? | Defensoria Pública,7.5 Foi realizada visita(s) de inspeção no período de referência? | Judiciário,7.5 Foi realizada visita(s) de inspeção no período de referência? | Ministério Público,7.5 Foi realizada visita(s) de inspeção no período de referência? | Outro(s). Qual?
5,19,2025,2025/2,Cela física,Validado,UNIDADE DE RECOLHIMENTO PROVISÓRIO,Ativo,NaN,Estrada do Barro Vermelho km 3,DISTRITO INDUSTRIAL,...,NaN,Sim,Não,Não,Não,Sim,Sim,Sim,Sim,NaN
6,19,2025,2025/2,Cela física,Validado,UNIDADE DE REGIME FECHADO FEMININO,Ativo,NaN,ESTRADA DO BARRO VERMELHO KM03,DISTRITO INDUSTRIAL,...,NaN,Sim,Não,Não,Não,Sim,Sim,Sim,Sim,NaN
7,19,2025,2025/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N1,Ativo,NaN,"Estrada do Barro Vermelho, km 03",Distrito Industrial,...,NaN,Sim,Não,Sim,Sim,Sim,Sim,Sim,Sim,NaN
8,19,2025,2025/2,Cela física,Validado,UNIDADE DE REGIME FECHADO N2,Ativo,NaN,ESTRADA DO BARRO VERMELHO - KM 03,DISTRITO INDUSTRIAL,...,0.0,Sim,Não,Não,Não,Não,Sim,Não,Sim,NaN
9,19,2025,2025/2,Cela física,Validado,UNIDADE PENITENCIARIA DO QUINARI,Ativo,NaN,Rodovia BR - 317 - KM 11,Zona rural,...,0.0,Sim,Não,Sim,Sim,Sim,Sim,Sim,Sim,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1527,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Brasília,Ativo,NaN,Rod DF-465 KM 01 - Complexo Penitenciário da P...,Setor Habitacional Jardim Botânico,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN
1528,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Campo Grande,Ativo,NaN,AVENIDA HENRIQUE BERTIN S/N JARDIM LOS ANGELES,NaN,...,0.0,Sim,Não,Não,Não,Não,Não,Sim,Sim,NaN
1529,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Catanduvas,Ativo,NaN,"Rodovia PR 471, Km 15, s/n",NaN,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN
1530,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Mossoró,Ativo,NaN,"RN 15, Km 13, Estrada Mossoró/Baraúnas - Mosso...",NaN,...,0.0,Sim,Não,Não,Sim,Não,Sim,Sim,Sim,NaN
1531,19,2025,2025/2,Cela física,Validado,Penitenciária Federal em Porto Velho,Ativo,NaN,"SÍTIO DA BOA ESPERANÇA, LOTE 13, GLEBA 13 ""A"" ...",NaN,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN

## Tratamento Adjacente

In [ ]:
df24 = df_todos[df_todos['Referência']=='2024/2']
df24

,ciclo,Ano,Referência,Tipo do Estabelecimento,Situação de Preenchimento,Nome do Estabelecimento,Situação do Estabelecimento,Outras Denominações,Endereço,Bairro,...,7.3 Quantidade de visitas registradas no período de referência | Quantidade de presos que receberam visita no período de referência | Feminino,7.5 Foi realizada visita(s) de inspeção no período de referência?,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho Nacional de Política Criminal e Penitenciária - CNPCP,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho Estadual de Política Criminal e Penitenciária/ Conselho Penitenciário,7.5 Foi realizada visita(s) de inspeção no período de referência? | Conselho da Comunidade,7.5 Foi realizada visita(s) de inspeção no período de referência? | Ouvidoria do sistema prisional - estadual ou nacional,7.5 Foi realizada visita(s) de inspeção no período de referência? | Defensoria Pública,7.5 Foi realizada visita(s) de inspeção no período de referência? | Judiciário,7.5 Foi realizada visita(s) de inspeção no período de referência? | Ministério Público,7.5 Foi realizada visita(s) de inspeção no período de referência? | Outro(s). Qual?
0,17,2024,2024/2,Domiciliar com monitoramento eletrônico,Validado,NÚCLEO DE MONITORAMENTO ELETRÔNICO DOMICILIAR ...,Ativo,NaN,"Travessa Santos Dumond, 2",Centro,...,0.0,Não,Não,Não,Não,Não,Não,Não,Não,NaN
1,17,2024,2024/2,Domiciliar com monitoramento eletrônico,Validado,NÚCLEO DE MONITORAMENTO ELETRÔNICO DOMICILIAR ...,Ativo,NaN,"Av. 25 de Agosto, 1923",Bairro 25 de Agosto,...,0.0,Não,Não,Não,Não,Não,Não,Não,Não,NaN
2,17,2024,2024/2,Domiciliar com monitoramento eletrônico,Validado,NÚCLEO DE MONITORAMENTO ELETRÔNICO DOMICILIAR ...,Ativo,NaN,"Avenida Marechal Deodoro, Setor 02 Q 20",Centro,...,0.0,Não,Não,Não,Não,Não,Não,Não,Não,NaN
3,17,2024,2024/2,Domiciliar com monitoramento eletrônico,Validado,NÚCLEO DE MONITORAMENTO ELETRONICO DOMICILIAR ...,Ativo,NaN,"Rodovia BR-364, KM 01",Triângulo,...,33.0,Não,Não,Não,Não,Não,Não,Não,Não,NaN
4,17,2024,2024/2,Domiciliar com monitoramento eletrônico,Validado,UNIDADE DE MONITORAMENTO ELETRÔNICO DOMICILIAR...,Ativo,NaN,"Av Getúlio Vargas, 1203",Bosque,...,0.0,Sim,Não,Não,Não,Não,Não,Sim,Sim,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1558,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Brasília,Ativo,NaN,Rod DF-465 KM 01 - Complexo Penitenciário da P...,Setor Habitacional Jardim Botânico,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN
1559,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Campo Grande,Ativo,NaN,AVENIDA HENRIQUE BERTIN S/N JARDIM LOS ANGELES,NaN,...,NaN,Sim,Não,Sim,Sim,Sim,Sim,Sim,Sim,Mecanismo Nacional de Prevenção e Combate a To...
1560,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Catanduvas,Ativo,NaN,"Rodovia PR 471, Km 15, s/n",NaN,...,0.0,Sim,Não,Não,Não,Não,Sim,Sim,Sim,NaN
1561,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Mossoró,Ativo,NaN,"RN 15, Km 13, Estrada Mossoró/Baraúnas - Mosso...",NaN,...,0.0,Sim,Não,Não,Sim,Sim,Sim,Sim,Sim,NaN
1562,17,2024,2024/2,Cela física,Validado,Penitenciária Federal em Porto Velho,Ativo,NaN,"SÍTIO DA BOA ESPERANÇA, LOTE 13, GLEBA 13 ""A"" ...",NaN,...,0.0,Sim,Não,Não,Não,Sim,Sim,Sim,Sim,NaN

In [ ]:
rj = df_todos[df_todos['UF']=='RJ']
rj['Município'].unique()

array(['Niterói', 'Japeri', 'Rio de Janeiro', 'Campos dos Goytacazes',
       'Volta Redonda', 'Magé', 'Resende', 'São Gonçalo', 'Itaperuna'],
      dtype=object)

In [ ]:
uf_mun = df24.groupby(["UF", "Município", "Código IBGE", "Nome do Estabelecimento"]).size().reset_index(name="n_estabelecimentos").sort_values(by=["UF", "n_estabelecimentos"], ascending=[True, False])
uf_mun.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1562 entries, 0 to 1561
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UF                       1562 non-null   object
 1   Município                1562 non-null   object
 2   Código IBGE              1562 non-null   float64
 3   Nome do Estabelecimento  1562 non-null   object
 4   n_estabelecimentos       1562 non-null   int64
dtypes: float64(1), int64(1), object(3)
memory usage: 61.1+ KB

In [ ]:
uf_mun['Município'].value_counts()

Município
Rio de Janeiro       35
Manaus               19
São Luís             16
Viana                15
Porto Velho          14
                     ..
Taquarituba           1
Taiúva                1
Girau do Ponciano     1
Arapiraca             1
Senador Guiomard      1
Name: count, Length: 878, dtype: int64

In [ ]:
pnaisp = pd.read_excel("repasses_pnaisp.xlsx")
pnaisp = pnaisp.rename(columns={'CO_MUNICIPIO_IBGE':'Código IBGE'})
pnaisp.columns

FileNotFoundError: [Errno 2] No such file or directory: 'repasses_pnaisp.xlsx'

In [ ]:
uf_mun[uf_mun['UF']=='AC']

,UF,Município,Código IBGE,Nome do Estabelecimento,n_estabelecimentos
0,AC,Cruzeiro do Sul,1200203,UNIDADE PENITENCIARIA MANOEL NERI DA SILVA,1
1,AC,Cruzeiro do Sul,1200203,UNIDADE PENITENCIÁRIA GUIMARÃES LIMA,1
2,AC,Rio Branco,1200401,UNIDADE DE RECOLHIMENTO PROVISÓRIO,1
3,AC,Rio Branco,1200401,UNIDADE DE REGIME FECHADO FEMININO,1
4,AC,Rio Branco,1200401,UNIDADE DE REGIME FECHADO N1,1
5,AC,Rio Branco,1200401,UNIDADE DE REGIME FECHADO N2,1
6,AC,Rio Branco,1200401,UNIDADE DE REGIME SEMIABERTO N1,1
7,AC,Sena Madureira,1200500,UNIDADE PENITENCIARIA EVARISTO DE MORAES,1
8,AC,Senador Guiomard,1200450,UNIDADE PENITENCIARIA DO QUINARI,1
9,AC,Tarauacá,1200609,UNIDADE PENITENCIARIA MOACIR PRADO,1
10,AC,Tarauacá,1200609,UNIDADE PENITENCIÁRIA FEMININA DE TARAUACÁ,1

In [ ]:
uf_mun['Código IBGE'] = (uf_mun['Código IBGE'] // 10).astype(int)
uf_mun

,UF,Município,Código IBGE,Nome do Estabelecimento,n_estabelecimentos
0,AC,Cruzeiro do Sul,120020,UNIDADE PENITENCIARIA MANOEL NERI DA SILVA,1
1,AC,Cruzeiro do Sul,120020,UNIDADE PENITENCIÁRIA GUIMARÃES LIMA,1
2,AC,Rio Branco,120040,UNIDADE DE RECOLHIMENTO PROVISÓRIO,1
3,AC,Rio Branco,120040,UNIDADE DE REGIME FECHADO FEMININO,1
4,AC,Rio Branco,120040,UNIDADE DE REGIME FECHADO N1,1
...,...,...,...,...,...
1382,TO,Paraíso do Tocantins,171610,UNIDADE PENAL REGIONAL DE PARAÍSO,1
1383,TO,Porto Nacional,171820,UNIDADE PENAL DE PORTO NACIONAL,1
1384,TO,Taguatinga,172090,UNIDADE PENAL DE TAGUATINGA,1
1385,TO,Talismã,172097,UNIDADE PENAL FEMININA DE TALISMÃ,1
1386,TO,Tocantinópolis,172120,UNIDADE PENAL DE TOCANTINÓPOLIS,1

In [ ]:
pnaisp2 = pnaisp.groupby(["UF", "MUNICIPIO", "Código IBGE", "TP_REPASSE"]).size().reset_index(name="n_estabelecimentos").sort_values(by=["UF", "n_estabelecimentos"], ascending=[True, False])
pnaisp3

     UF             MUNICIPIO  Código IBGE TP_REPASSE  n_estabelecimentos
0    AC            RIO BRANCO       120040   ESTADUAL                   1
1    AC        SENA MADUREIRA       120050  MUNICIPAL                   1
2    AC      SENADOR GUIOMARD       120045  MUNICIPAL                   1
3    AC              TARAUACA       120060  MUNICIPAL                   1
4    AL                MACEIO       270430   ESTADUAL                   1
..   ..                   ...          ...        ...                 ...
258  TO         PALMEIROPOLIS       171575  MUNICIPAL                   1
259  TO  PARAISO DO TOCANTINS       171610  MUNICIPAL                   1
260  TO        PORTO NACIONAL       171820  MUNICIPAL                   1
261  TO               TALISMA       172097  MUNICIPAL                   1
262  TO        TOCANTINOPOLIS       172120  MUNICIPAL                   1

[263 rows x 5 columns]

In [ ]:
uf_mun['Código IBGE'] = uf_mun['Código IBGE'].astype(int)
uf_mun

In [ ]:
comparacao = uf_mun.merge(
    pnaisp,
    on='Código IBGE',
    how='outer',
    suffixes=('_ufmun', '_pnaisp'),
    indicator=True
)
comparacao

,UF_ufmun,Município,Código IBGE,Nome do Estabelecimento,n_estabelecimentos,NU_PROCESSO,NU_PORTARIA,DT_PORTARIA,MÊS,TP_REPASSE,...,UF_pnaisp,MUNICIPIO,ENTIDADE,CNPJ,BLOCO,COMPONENTE,PROGRAMA,Valor Bruto,Valor Liquido,_merge
0,RO,Alta Floresta D'Oeste,110001,CADEIA PÚBLICA DE ALTA FLORESTA,1.0,NaN,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,RO,Ariquemes,110002,CASA DO ALBERGADO DE ARIQUEMES,1.0,NaN,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,RO,Ariquemes,110002,CENTRO DE RESSOCIALIZAÇÃO DE ARIQUEMES,1.0,NaN,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,RO,Cacoal,110004,CASA DE DETENÇÃO DE CACOAL,1.0,2.500013e+16,7513.0,2025-07-17,jul,MUNICIPAL,...,RO,CACOAL,FUNDO MUNICIPAL DE SAUDE DE CACOAL,1.911232e+13,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,7251.57,7251.57,both
4,RO,Cerejeiras,110005,CADEIA PÚBLICA DE CEREJEIRAS,1.0,NaN,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1463,DF,Brasília,530010,PENITENCIÁRIA DO DISTRITO FEDERAL I,1.0,2.500013e+16,7513.0,2025-07-17,jul,ESTADUAL,...,DF,BRASILIA,FUNDO DE SAUDE DO DISTRITO FEDERAL,1.211625e+13,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,287456.49,287456.49,both
1464,DF,Brasília,530010,PENITENCIÁRIA DO DISTRITO FEDERAL II,1.0,2.500013e+16,7513.0,2025-07-17,jul,ESTADUAL,...,DF,BRASILIA,FUNDO DE SAUDE DO DISTRITO FEDERAL,1.211625e+13,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,287456.49,287456.49,both
1465,DF,Brasília,530010,PENITENCIÁRIA DO DISTRITO FEDERAL IV,1.0,2.500013e+16,7513.0,2025-07-17,jul,ESTADUAL,...,DF,BRASILIA,FUNDO DE SAUDE DO DISTRITO FEDERAL,1.211625e+13,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,287456.49,287456.49,both
1466,DF,Brasília,530010,PENITENCIÁRIA FEMININA DO DISTRITO FEDERAL,1.0,2.500013e+16,7513.0,2025-07-17,jul,ESTADUAL,...,DF,BRASILIA,FUNDO DE SAUDE DO DISTRITO FEDERAL,1.211625e+13,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,287456.49,287456.49,both
1467,DF,Brasília,530010,Penitenciária Federal em Brasília,1.0,2.500013e+16,7513.0,2025-07-17,jul,ESTADUAL,...,DF,BRASILIA,FUNDO DE SAUDE DO DISTRITO FEDERAL,1.211625e+13,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,287456.49,287456.49,both

In [ ]:
comparacao['_merge'].value_counts()

_merge
left_only     874
both          590
right_only      4
Name: count, dtype: int64

In [ ]:
presentes_em_ambas = comparacao[comparacao['_merge'] == 'both']
presentes_em_ambas

,UF_ufmun,Município,Código IBGE,Nome do Estabelecimento,n_estabelecimentos,NU_PROCESSO,NU_PORTARIA,DT_PORTARIA,MÊS,TP_REPASSE,...,UF_pnaisp,MUNICIPIO,ENTIDADE,CNPJ,BLOCO,COMPONENTE,PROGRAMA,Valor Bruto,Valor Liquido,_merge
3,RO,Cacoal,110004,CASA DE DETENÇÃO DE CACOAL,1.0,2.500013e+16,7513.0,2025-07-17,jul,MUNICIPAL,...,RO,CACOAL,FUNDO MUNICIPAL DE SAUDE DE CACOAL,1.911232e+13,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,7251.57,7251.57,both
7,RO,Guajará-Mirim,110010,CASA DE DETENÇÃO DE GUAJARÁ MIRIM,1.0,2.500013e+16,7513.0,2025-07-17,jul,MUNICIPAL,...,RO,GUAJARA-MIRIM,FUNDO MUNICIPAL DE SAUDE,2.327368e+13,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,5815.44,5815.44,both
8,RO,Guajará-Mirim,110010,CASA DE PRISÃO ALBERGUE FEMININO DE GUAJARÁ MIRIM,1.0,2.500013e+16,7513.0,2025-07-17,jul,MUNICIPAL,...,RO,GUAJARA-MIRIM,FUNDO MUNICIPAL DE SAUDE,2.327368e+13,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,5815.44,5815.44,both
9,RO,Guajará-Mirim,110010,PENITENCIÁRIA REGIONAL DE NOVA MAMORÉ,1.0,2.500013e+16,7513.0,2025-07-17,jul,MUNICIPAL,...,RO,GUAJARA-MIRIM,FUNDO MUNICIPAL DE SAUDE,2.327368e+13,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,5815.44,5815.44,both
10,RO,Guajará-Mirim,110010,UNIDADE PRISIONAL SEMIABERTO MASCULINO DE GUAJ...,1.0,2.500013e+16,7513.0,2025-07-17,jul,MUNICIPAL,...,RO,GUAJARA-MIRIM,FUNDO MUNICIPAL DE SAUDE,2.327368e+13,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,5815.44,5815.44,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1463,DF,Brasília,530010,PENITENCIÁRIA DO DISTRITO FEDERAL I,1.0,2.500013e+16,7513.0,2025-07-17,jul,ESTADUAL,...,DF,BRASILIA,FUNDO DE SAUDE DO DISTRITO FEDERAL,1.211625e+13,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,287456.49,287456.49,both
1464,DF,Brasília,530010,PENITENCIÁRIA DO DISTRITO FEDERAL II,1.0,2.500013e+16,7513.0,2025-07-17,jul,ESTADUAL,...,DF,BRASILIA,FUNDO DE SAUDE DO DISTRITO FEDERAL,1.211625e+13,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,287456.49,287456.49,both
1465,DF,Brasília,530010,PENITENCIÁRIA DO DISTRITO FEDERAL IV,1.0,2.500013e+16,7513.0,2025-07-17,jul,ESTADUAL,...,DF,BRASILIA,FUNDO DE SAUDE DO DISTRITO FEDERAL,1.211625e+13,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,287456.49,287456.49,both
1466,DF,Brasília,530010,PENITENCIÁRIA FEMININA DO DISTRITO FEDERAL,1.0,2.500013e+16,7513.0,2025-07-17,jul,ESTADUAL,...,DF,BRASILIA,FUNDO DE SAUDE DO DISTRITO FEDERAL,1.211625e+13,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,287456.49,287456.49,both
1467,DF,Brasília,530010,Penitenciária Federal em Brasília,1.0,2.500013e+16,7513.0,2025-07-17,jul,ESTADUAL,...,DF,BRASILIA,FUNDO DE SAUDE DO DISTRITO FEDERAL,1.211625e+13,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,287456.49,287456.49,both

In [ ]:
pnaisp['MUNICIPIO'].value_counts()

MUNICIPIO
BELEM             3
RIO DE JANEIRO    2
FLORIANOPOLIS     2
PORTO ALEGRE      2
NATAL             2
                 ..
SENA MADUREIRA    1
ITUMBIARA         1
RIO DO SUL        1
SANTO ANGELO      1
IGUATEMI          1
Name: count, Length: 255, dtype: int64

In [ ]:
df_municipios = pnaisp['MUNICIPIO'].value_counts().reset_index()
df_municipios.columns = ['MUNICIPIO', 'n_registros']
df_municipios

          MUNICIPIO  n_registros
0             BELEM            3
1    RIO DE JANEIRO            2
2     FLORIANOPOLIS            2
3      PORTO ALEGRE            2
4             NATAL            2
..              ...          ...
250  SENA MADUREIRA            1
251       ITUMBIARA            1
252      RIO DO SUL            1
253    SANTO ANGELO            1
254        IGUATEMI            1

[255 rows x 2 columns]

In [ ]:
uf_mun2 = uf_mun.merge(pnaisp, on='Código IBGE')
uf_mun2

,UF_x,Município,Código IBGE,Nome do Estabelecimento,n_estabelecimentos,NU_PROCESSO,NU_PORTARIA,DT_PORTARIA,MÊS,TP_REPASSE,NU_OB,UF_y,MUNICIPIO,ENTIDADE,CNPJ,BLOCO,COMPONENTE,PROGRAMA,Valor Bruto,Valor Liquido
0,AC,Rio Branco,120040,UNIDADE DE RECOLHIMENTO PROVISÓRIO,1,25000127996202597,7513,2025-07-17,jul,ESTADUAL,34014,AC,RIO BRANCO,FUNDO ESTADUAL DE SAUDE - FUNDES,7458465000130,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,74022.75,74022.75
1,AC,Rio Branco,120040,UNIDADE DE REGIME FECHADO FEMININO,1,25000127996202597,7513,2025-07-17,jul,ESTADUAL,34014,AC,RIO BRANCO,FUNDO ESTADUAL DE SAUDE - FUNDES,7458465000130,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,74022.75,74022.75
2,AC,Rio Branco,120040,UNIDADE DE REGIME FECHADO N1,1,25000127996202597,7513,2025-07-17,jul,ESTADUAL,34014,AC,RIO BRANCO,FUNDO ESTADUAL DE SAUDE - FUNDES,7458465000130,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,74022.75,74022.75
3,AC,Rio Branco,120040,UNIDADE DE REGIME FECHADO N2,1,25000127996202597,7513,2025-07-17,jul,ESTADUAL,34014,AC,RIO BRANCO,FUNDO ESTADUAL DE SAUDE - FUNDES,7458465000130,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,74022.75,74022.75
4,AC,Rio Branco,120040,UNIDADE DE REGIME SEMIABERTO N1,1,25000127996202597,7513,2025-07-17,jul,ESTADUAL,34014,AC,RIO BRANCO,FUNDO ESTADUAL DE SAUDE - FUNDES,7458465000130,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,74022.75,74022.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,TO,Palmeirópolis,171575,UNIDADE PENAL DE PALMEIRÓPOLIS,1,25000127994202506,7513,2025-07-17,jul,MUNICIPAL,34068,TO,PALMEIROPOLIS,FUNDO MUNICIPAL DE SAUDE DE PALMEIROPOLIS,13936229000184,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,797.85,797.85
586,TO,Paraíso do Tocantins,171610,UNIDADE PENAL REGIONAL DE PARAÍSO,1,25000127994202506,7513,2025-07-17,jul,MUNICIPAL,34068,TO,PARAISO DO TOCANTINS,FUNDO MUNICIPAL DE SAUDE DE PARAISO DO TOCANTINS,11230086000165,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,4733.91,4733.91
587,TO,Porto Nacional,171820,UNIDADE PENAL DE PORTO NACIONAL,1,25000127994202506,7513,2025-07-17,jul,MUNICIPAL,34068,TO,PORTO NACIONAL,FUNDO MUNICIPAL DE SAUDE DE PORTO NACIONAL,11315054000162,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,1773.00,1773.00
588,TO,Talismã,172097,UNIDADE PENAL FEMININA DE TALISMÃ,1,25000127994202506,7513,2025-07-17,jul,MUNICIPAL,34068,TO,TALISMA,FUNDO MUNICIPAL DE SAUDE DE TALISMA,13111001000155,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,407.79,407.79
589,TO,Tocantinópolis,172120,UNIDADE PENAL DE TOCANTINÓPOLIS,1,25000127994202506,7513,2025-07-17,jul,MUNICIPAL,34068,TO,TOCANTINOPOLIS,FUNDO MUNICIPAL DE SAUDE,11266993000164,Manutenção Das Ações E Serviços Públicos De Saúde,ASSISTÊNCIA FARMACÊUTICA,PNAISP - PROMOÇÃO DA ASSISTÊNCIA FARMACÊUTICA ...,1773.00,1773.00

## Continuação tratamento saude mental

In [ ]:
df_todos.columns.tolist()

['ciclo',
 'Ano',
 'Referência',
 'Tipo do Estabelecimento',
 'Situação de Preenchimento',
 'Nome do Estabelecimento',
 'Situação do Estabelecimento',
 'Outras Denominações',
 'Endereço',
 'Bairro',
 'CEP',
 'Âmbito',
 'UF',
 'Município',
 'Código IBGE',
 'Telefone Principal',
 '1.1 Estabelecimento originalmente destinado a pessoa privadas de liberdade do sexo',
 '1.2 Tipo de estabelecimento - originalmente destinado',
 '1.3 Capacidade do estabelecimento | Presos provisórios | Masculino',
 '1.3 Capacidade do estabelecimento | Presos provisórios | Feminino',
 '1.3 Capacidade do estabelecimento | Presos provisórios | Total',
 '1.3 Capacidade do estabelecimento | Regime fechado | Masculino',
 '1.3 Capacidade do estabelecimento | Regime fechado | Feminino',
 '1.3 Capacidade do estabelecimento | Regime fechado | Total',
 '1.3 Capacidade do estabelecimento | Regime semiaberto | Masculino',
 '1.3 Capacidade do estabelecimento | Regime semiaberto | Feminino',
 '1.3 Capacidade do estabelecimento | Regime semiaberto | Total',
 '1.3 Capacidade do estabelecimento | Regime aberto | Masculino',
 '1.3 Capacidade do estabelecimento | Regime aberto | Feminino',
 '1.3 Capacidade do estabelecimento | Regime aberto | Total',
 '1.3 Capacidade do estabelecimento | Regime Disciplinar Diferenciado (RDD) | Masculino',
 '1.3 Capacidade do estabelecimento | Regime Disciplinar Diferenciado (RDD) | Feminino',
 '1.3 Capacidade do estabelecimento | Regime Disciplinar Diferenciado (RDD) | Total',
 '1.3 Capacidade do estabelecimento | Medidas de segurança de internação | Masculino',
 '1.3 Capacidade do estabelecimento | Medidas de segurança de internação | Feminino',
 '1.3 Capacidade do estabelecimento | Medidas de segurança de internação | Total',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)?',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)? | Masculino',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)? | Feminino',
 '1.3 Capacidade do estabelecimento | Outro(s). Qual(is)? | Total',
 '1.3 Capacidade do estabelecimento | Masculino | Total',
 '1.3 Capacidade do estabelecimento | Feminino | Total',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Celas não aptas',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Vagas desativadas - Masculino',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Vagas desativadas - Feminino',
 '1.3 Capacidade do estabelecimento | Celas interditadas/ desativadas e respectivas vagas | Total de vagas desativadas',
 '1.4 Gestão do estabelecimento',
 '1.5 Quais serviços são terceirizados? | Nenhum',
 '1.5 Quais serviços são terceirizados? | Alimentação',
 '1.5 Quais serviços são terceirizados? | Limpeza',
 '1.5 Quais serviços são terceirizados? | Lavanderia',
 '1.5 Quais serviços são terceirizados? | Saúde',
 '1.5 Quais serviços são terceirizados? | Segurança',
 '1.5 Quais serviços são terceirizados? | Assistência educacional',
 '1.5 Quais serviços são terceirizados? | Assistência laboral',
 '1.5 Quais serviços são terceirizados? | Assistência social',
 '1.5 Quais serviços são terceirizados? | Assistência jurídica',
 '1.5 Quais serviços são terceirizados? | Serviços administrativos',
 '1.5 Quais serviços são terceirizados? | Outro',
 '1.6 Data de inauguração do estabelecimento',
 '1.7 O estabelecimento foi concebido como estabelecimento penal ou foi construído para outra utilização e foi adaptado?',
 '1.8 Possui regimento interno?',
 '1.9 O regimento interno é específico para este estabelecimento ou se aplica aos demais estabelecimentos do Estado?',
 '2.1 Há cela adequada/ dormitório para gestantes? (apenas para estabelecimentos com vagas para mulheres)',
 '2.2 Possui berçário e/ou centro de referência materno-infantil? (apenas para estabelecimentos com vagas para mulheres)',
 '2.2 Possui berçário e/ou centro de referência materno-infantil? (apenas para estabelecimentos com vagas para mulheres) | Sim. Capacidade de bebês: | Quantidade',
 '2.3 Possui creche? (apenas para estabelecimentos com vagas para mulheres)',
 '2.3 Possui creche? (apenas para estabelecimentos com vagas para mulheres) | Sim. Capacidade de crianças: | Quantidade',
 '2.4 Módulo de saúde | Consultório médico',
 '2.4 Módulo de saúde | Consultório médico | Quantidade',
 '2.4 Módulo de saúde | Consultório médico | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Consultório odontológico',
 '2.4 Módulo de saúde | Consultório odontológico | Quantidade',
 '2.4 Módulo de saúde | Consultório odontológico | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de coleta de material para laboratório',
 '2.4 Módulo de saúde | Sala de coleta de material para laboratório | Quantidade',
 '2.4 Módulo de saúde | Sala de coleta de material para laboratório | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de curativos, suturas, vacinas e posto de enfermagem',
 '2.4 Módulo de saúde | Sala de curativos, suturas, vacinas e posto de enfermagem | Quantidade',
 '2.4 Módulo de saúde | Sala de curativos, suturas, vacinas e posto de enfermagem | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Cela de observação',
 '2.4 Módulo de saúde | Cela de observação | Quantidade',
 '2.4 Módulo de saúde | Cela de observação | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Cela de enfermaria com solário',
 '2.4 Módulo de saúde | Cela de enfermaria com solário | Quantidade',
 '2.4 Módulo de saúde | Cela de enfermaria com solário | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sanitário para pacientes',
 '2.4 Módulo de saúde | Sanitário para pacientes | Quantidade',
 '2.4 Módulo de saúde | Sanitário para pacientes | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sanitários para equipe de saúde',
 '2.4 Módulo de saúde | Sanitários para equipe de saúde | Quantidade',
 '2.4 Módulo de saúde | Sanitários para equipe de saúde | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Farmácia ou sala de estoque/ dispensação de medicamentos',
 '2.4 Módulo de saúde | Farmácia ou sala de estoque/ dispensação de medicamentos | Quantidade',
 '2.4 Módulo de saúde | Farmácia ou sala de estoque/ dispensação de medicamentos | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Central de material esterilizado/ expurgo',
 '2.4 Módulo de saúde | Central de material esterilizado/ expurgo | Quantidade',
 '2.4 Módulo de saúde | Central de material esterilizado/ expurgo | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de lavagem e descontaminação',
 '2.4 Módulo de saúde | Sala de lavagem e descontaminação | Quantidade',
 '2.4 Módulo de saúde | Sala de lavagem e descontaminação | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de esterilização',
 '2.4 Módulo de saúde | Sala de esterilização | Quantidade',
 '2.4 Módulo de saúde | Sala de esterilização | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Vestiário',
 '2.4 Módulo de saúde | Vestiário | Quantidade',
 '2.4 Módulo de saúde | Vestiário | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Depósito de material de limpeza - DML',
 '2.4 Módulo de saúde | Depósito de material de limpeza - DML | Quantidade',
 '2.4 Módulo de saúde | Depósito de material de limpeza - DML | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de atendimento clínico multiprofissional',
 '2.4 Módulo de saúde | Sala de atendimento clínico multiprofissional | Quantidade',
 '2.4 Módulo de saúde | Sala de atendimento clínico multiprofissional | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de procedimentos',
 '2.4 Módulo de saúde | Sala de procedimentos | Quantidade',
 '2.4 Módulo de saúde | Sala de procedimentos | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Sala de raio x',
 '2.4 Módulo de saúde | Sala de raio x | Quantidade',
 '2.4 Módulo de saúde | Sala de raio x | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Laboratório de diagnóstico',
 '2.4 Módulo de saúde | Laboratório de diagnóstico | Quantidade',
 '2.4 Módulo de saúde | Laboratório de diagnóstico | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Cela de espera',
 '2.4 Módulo de saúde | Cela de espera | Quantidade',
 '2.4 Módulo de saúde | Cela de espera | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Solário para pacientes',
 '2.4 Módulo de saúde | Solário para pacientes | Quantidade',
 '2.4 Módulo de saúde | Solário para pacientes | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Outro(s). Qual(is)?',
 '2.4 Módulo de saúde | Outro(s). Qual(is)? | Quantidade',
 '2.4 Módulo de saúde | Outro(s). Qual(is)? | O espaço também é destinado a outras finalidades?',
 '2.4 Módulo de saúde | Não possui módulo de saúde',
 '2.5 Módulo de educação | Sala de aula',
 '2.5 Módulo de educação | Sala de aula | Quantidade de salas',
 '2.5 Módulo de educação | Sala de aula | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Sala de informática',
 '2.5 Módulo de educação | Sala de informática | Quantidade de salas',
 '2.5 Módulo de educação | Sala de informática | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Sala de encontros com a sociedade/ sala de reuniões',
 '2.5 Módulo de educação | Sala de encontros com a sociedade/ sala de reuniões | Quantidade de salas',
 '2.5 Módulo de educação | Sala de encontros com a sociedade/ sala de reuniões | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Biblioteca',
 '2.5 Módulo de educação | Biblioteca | Quantidade de salas',
 '2.5 Módulo de educação | Biblioteca | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Sala de professores',
 '2.5 Módulo de educação | Sala de professores | Quantidade de salas',
 '2.5 Módulo de educação | Sala de professores | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Outro(s). Qual(is)?',
 '2.5 Módulo de educação | Outro(s). Qual(is)? | Quantidade de salas',
 '2.5 Módulo de educação | Outro(s). Qual(is)? | Capacidade para quantas pessoas',
 '2.5 Módulo de educação | Não possui',
 '2.5.1 Há local específico para biblioteca?',
 '2.5.2 Há acervo de obras na biblioteca?',
 '2.5.2 Há acervo de obras na biblioteca? | Sim. Quantidade de obras: | Quantidade',
 '2.5.3 A origem do acervo da biblioteca?',
 '2.5.4 Há controle do acervo bibliotecário do estabelecimento?',
 '2.5.5 Há manutenção permanente do acervo bibliotecário do estabelecimento?',
 '2.5.5 Há manutenção permanente do acervo bibliotecário do estabelecimento? | Caso o estabelecimento possua manutenção permanente do acervo bibliotecário, qual a periodicidade de manutenção do acervo?',
 '2.6 Módulo de oficinas | Não possui',
 '2.6 Módulo de oficinas | Sala de produção',
 '2.6 Módulo de oficinas | Sala de controle/ supervisão',
 '2.6 Módulo de oficinas | Sanitários',
 '2.6 Módulo de oficinas | Estoque',
 '2.6 Módulo de oficinas | Carga/ descarga',
 '2.6 Módulo de oficinas | Outro(s). Qual(is)?',
 '2.6 Módulo de oficinas | Artefatos de concreto',
 '2.6 Módulo de oficinas | Artefatos de concreto | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Blocos e tijolos',
 '2.6 Módulo de oficinas | Blocos e tijolos | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Padaria e panificação',
 '2.6 Módulo de oficinas | Padaria e panificação | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Corte e costura industrial',
 '2.6 Módulo de oficinas | Corte e costura industrial | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Artesanato',
 '2.6 Módulo de oficinas | Artesanato | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Marcenaria',
 '2.6 Módulo de oficinas | Marcenaria | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Serralheria',
 '2.6 Módulo de oficinas | Serralheria | Capacidade para quantas pessoas',
 '2.6 Módulo de oficinas | Outro(s). Qual(is)? | Espaços complementares',
 '2.6 Módulo de oficinas | Outro(s). Qual(is)? | Espaços complementares | Capacidade para quantas pessoas',
 '2.7 Há local específico para visitação?',
 '2.8 Há local específico para visita íntima?',
 '2.9 Há sala de atendimento para serviço social?',
 '2.10 Há sala de atendimento para psicologia?',
 '2.11 Há local destinado ao atendimento jurídico gratuito no estabelecimento?',
 '2.12 Possui sala de videoconferência?',
 '2.13 Há "cela(s)-seguro"?',
 '2.14 Há ala ou cela destinadas exclusivamente às pessoas privadas de liberdade que se declarem lésbicas, gays, bissexuais, travestis e transexuais (LGBT)?',
 '2.14 Há ala ou cela destinadas exclusivamente às pessoas privadas de liberdade que se declarem lésbicas, gays, bissexuais, travestis e transexuais (LGBT)? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.14 Há ala ou cela destinadas exclusivamente às pessoas privadas de liberdade que se declarem lésbicas, gays, bissexuais, travestis e transexuais (LGBT)? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.15 Há ala ou cela destinada exclusivamente para idosos?',
 '2.15 Há ala ou cela destinada exclusivamente para idosos? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.15 Há ala ou cela destinada exclusivamente para idosos? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.16 Há ala ou cela destinada exclusivamente para indígenas?',
 '2.16 Há ala ou cela destinada exclusivamente para indígenas? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.16 Há ala ou cela destinada exclusivamente para indígenas? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.17 Há ala ou cela destinada exclusivamente para pessoas estrangeiras?',
 '2.17 Há ala ou cela destinada exclusivamente para pessoas estrangeiras? | Sim, há ala. Quantas vagas? | Quantidade',
 '2.17 Há ala ou cela destinada exclusivamente para pessoas estrangeiras? | Sim, há cela(s). Quantas vagas? | Quantidade',
 '2.18 Há acessibilidade para pessoas com deficiência?',
 '2.18 Há acessibilidade para pessoas com deficiência? | Sim, módulos/alas/celas adaptados em conformidade com a Norma Brasileira ABNT n. 9050, de 2004. Indique o número de vagas: | Quantidade',
 '2.18 Há acessibilidade para pessoas com deficiência? | Sim, módulos/alas/celas adaptados, não observando todos os requisitos da Norma Brasileira ABNT n. 9050, de 2004. Indique o número de vagas: | Quantidade',
 '2.19 Há terreno/ espaço disponível para construção de novos módulos?',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos  | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Cargos administrativos | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Temporário Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Temporário Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Órgão de lotação originária (para efetivos e comissionados)',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Efetivo Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Efetivo Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Comissionado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Comissionado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Terceirizado Masculino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Terceirizado Feminino',
 '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Temporário Masculino',

In [ ]:
col_masc = [
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Estadual Masculino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Federal Masculino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Estadual Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Federal Masculino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Estadual Masculino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Federal Masculino',
    '4.1 População prisional | Medida de segurança - internação | Outros(Just. Trab., cível) Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Estadual Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Federal Masculino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Outros(Just. Trab., cível) Masculino'
]

col_fem = [
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Estadual Feminino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Justiça Federal Feminino',
    '4.1 População prisional | Presos provisórios (sem condenação) | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime fechado | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime semiaberto | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Estadual Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Justiça Federal Feminino',
    '4.1 População prisional | Presos sentenciados - regime aberto | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Estadual Feminino',
    '4.1 População prisional | Medida de segurança - internação | Justiça Federal Feminino',
    '4.1 População prisional | Medida de segurança - internação | Outros(Just. Trab., cível) Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Estadual Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Justiça Federal Feminino',
    '4.1 População prisional | Medida de segurança - tratamento ambulatorial | Outros(Just. Trab., cível) Feminino'
]

In [ ]:
enf = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total'].sum()
aux_enf= df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total'].sum()
psi = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total'].sum()
dent = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Dentistas | Total'].sum()
tec_dent = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Técnico/ auxiliar odontológico | Total'].sum()
assits = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Assistentes sociais | Total'].sum()
adv = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Advogados | Total'].sum()
med_geral = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total'].sum()
med_gineco = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total'].sum()
med_psiq = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – psiquiatras | Total'].sum()
med_outros = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total'].sum()
ped = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Pedagogos | Total'].sum()
prof= df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Professores | Total'].sum()
terapeuta_ocup = df25['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Terapeuta/ terapeuta ocupacional | Total'].sum()

In [ ]:
dfs = [df25]
anos = list(range(2025,2026))  # de 2016 a 2024

In [ ]:
resultados = []

In [ ]:
col_enfs = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Enfermeiros | Total',
             '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Auxiliar e técnico de enfermagem | Total']

col_medicos_fisica = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - clínicos gerais | Total',
                        '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – ginecologistas | Total',
                       '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos - outras especialidades | Total']

col_medicos_mental = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Psicólogos | Total',
                    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Médicos – psiquiatras | Total',
                    '3.1 Quantidade de Servidores que atuam no Sistema Prisional | Terapeuta/ terapeuta ocupacional | Total']
col_assits = ['3.1 Quantidade de Servidores que atuam no Sistema Prisional | Assistentes sociais | Total']

col_pop = ['4.1 População prisional | Total']

In [ ]:
for df, ano in zip(dfs, anos):
    # Filtrando apenas celas físicas
    df = df[df['Tipo do Estabelecimento'] == 'Cela física'].copy()  # .copy() evita avisos de atribuição encadeada

    # Conversão para numérico
    for col_group in [col_medicos_fisica, col_medicos_mental, col_enfs, col_assits, col_masc, col_fem]:
        for col in col_group:
            df.loc[:, col] = pd.to_numeric(df[col], errors='coerce')

    # Cálculo de totais por linha com .loc
    df.loc[:, 'total_medicos_fisica'] = df[col_medicos_fisica].sum(axis=1)
    df.loc[:, 'total_medicos_mental'] = df[col_medicos_mental].sum(axis=1)
    df.loc[:, 'total_enfs'] = df[col_enfs].sum(axis=1)
    df.loc[:, 'total_assits'] = df[col_assits].sum(axis=1)
    df.loc[:, 'pop_masc'] = df[col_masc].sum(axis=1)
    df.loc[:, 'pop_fem'] = df[col_fem].sum(axis=1)
    df.loc[:, 'pop_total'] = df[col_pop]
    df.loc[:, 'ano'] = ano

    # Agrupamento por UF e ano
    grupo = df.groupby(['UF', 'ano'])[
        ['total_medicos_fisica', 'total_medicos_mental', 'total_enfs', 'total_assits',
         'pop_masc', 'pop_fem', 'pop_total']
    ].sum().reset_index()

    resultados.append(grupo)

# Concatenação dos resultados
saude_area_populacao_ano_uf = pd.concat(resultados, ignore_index=True)

In [ ]:
saude_area_populacao_ano_uf

,UF,ano,total_medicos_fisica,total_medicos_mental,total_enfs,total_assits,pop_masc,pop_fem,pop_total
0,AC,2025,5.0,12.0,12.0,19.0,5225.0,213.0,5438
1,AL,2025,21.0,36.0,131.0,26.0,5731.0,191.0,5922
2,AM,2025,14.0,34.0,70.0,25.0,5767.0,216.0,5983
3,AP,2025,5.0,8.0,24.0,5.0,3836.0,149.0,3985
4,BA,2025,65.0,109.0,286.0,73.0,16126.0,598.0,16724
5,CE,2025,50.0,40.0,131.0,41.0,24186.0,1227.0,25413
6,DF,2025,34.0,23.0,60.0,7.0,16360.0,661.0,17021
7,ES,2025,107.0,114.0,128.0,84.0,24201.0,1120.0,25321
8,GO,2025,67.0,58.0,138.0,42.0,18448.0,896.0,19344
9,MA,2025,77.0,69.0,380.0,69.0,12513.0,419.0,12932
10,MG,2025,194.0,311.0,551.0,275.0,70297.0,3135.0,73432
11,MS,2025,55.0,37.0,88.0,43.0,17198.0,1039.0,18237
12,MT,2025,25.0,38.0,118.0,41.0,14732.0,1000.0,15732
13,PA,2025,25.0,82.0,225.0,84.0,15907.0,701.0,16608
14,PB,2025,25.0,39.0,52.0,24.0,12591.0,710.0,13301
15,PE,2025,42.0,79.0,114.0,101.0,29913.0,997.0,30910
16,PI,2025,42.0,43.0,102.0,58.0,7678.0,306.0,7984
17,PR,2025,103.0,71.0,170.0,54.0,41239.0,2449.0,43688
18,RJ,2025,102.0,113.0,427.0,59.0,44844.0,1801.0,46645
19,RN,2025,33.0,24.0,65.0,14.0,7639.0,365.0,8004
20,RO,2025,31.0,16.0,136.0,25.0,7972.0,431.0,8403
21,RR,2025,8.0,7.0,35.0,3.0,2969.0,159.0,3128
22,RS,2025,81.0,162.0,220.0,168.0,38883.0,2172.0,41055
23,SC,2025,68.0,101.0,177.0,66.0,28893.0,1620.0,30513
24,SE,2025,12.0,23.0,91.0,21.0,6193.0,257.0,6450
25,SP,2025,160.0,176.0,787.0,185.0,210752.0,10468.0,221220
26,TO,2025,13.0,15.0,39.0,15.0,4314.0,188.0,4502

In [ ]:
saude_area_populacao_ano_uf['medicos_fisica_por_1000'] = (
    saude_area_populacao_ano_uf['total_medicos_fisica'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000

saude_area_populacao_ano_uf['medicos_mental_por_1000'] = (
    saude_area_populacao_ano_uf['total_medicos_mental'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000

saude_area_populacao_ano_uf['total_enfs_por_1000'] = (
    saude_area_populacao_ano_uf['total_enfs'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000
saude_area_populacao_ano_uf['total_assits_por_1000'] = (
    saude_area_populacao_ano_uf['total_assits'] /
    saude_area_populacao_ano_uf['pop_total']
) * 1000
saude_area_populacao_ano_uf

,UF,ano,total_medicos_fisica,total_medicos_mental,total_enfs,total_assits,pop_masc,pop_fem,pop_total,medicos_fisica_por_1000,medicos_mental_por_1000,total_enfs_por_1000,total_assits_por_1000
0,AC,2025,5.0,12.0,12.0,19.0,5225.0,213.0,5438,0.919456,2.206694,2.206694,3.493932
1,AL,2025,21.0,36.0,131.0,26.0,5731.0,191.0,5922,3.546099,6.079027,22.120905,4.390409
2,AM,2025,14.0,34.0,70.0,25.0,5767.0,216.0,5983,2.339963,5.682768,11.699816,4.178506
3,AP,2025,5.0,8.0,24.0,5.0,3836.0,149.0,3985,1.254705,2.007528,6.022585,1.254705
4,BA,2025,65.0,109.0,286.0,73.0,16126.0,598.0,16724,3.886630,6.517580,17.101172,4.364984
5,CE,2025,50.0,40.0,131.0,41.0,24186.0,1227.0,25413,1.967497,1.573998,5.154842,1.613347
6,DF,2025,34.0,23.0,60.0,7.0,16360.0,661.0,17021,1.997532,1.351272,3.525057,0.411257
7,ES,2025,107.0,114.0,128.0,84.0,24201.0,1120.0,25321,4.225741,4.502192,5.055093,3.317405
8,GO,2025,67.0,58.0,138.0,42.0,18448.0,896.0,19344,3.463606,2.998346,7.133995,2.171216
9,MA,2025,77.0,69.0,380.0,69.0,12513.0,419.0,12932,5.954222,5.335602,29.384473,5.335602
10,MG,2025,194.0,311.0,551.0,275.0,70297.0,3135.0,73432,2.641900,4.235211,7.503541,3.744961
11,MS,2025,55.0,37.0,88.0,43.0,17198.0,1039.0,18237,3.015847,2.028842,4.825355,2.357844
12,MT,2025,25.0,38.0,118.0,41.0,14732.0,1000.0,15732,1.589118,2.415459,7.500636,2.606153
13,PA,2025,25.0,82.0,225.0,84.0,15907.0,701.0,16608,1.505299,4.937380,13.547688,5.057803
14,PB,2025,25.0,39.0,52.0,24.0,12591.0,710.0,13301,1.879558,2.932110,3.909480,1.804376
15,PE,2025,42.0,79.0,114.0,101.0,29913.0,997.0,30910,1.358784,2.555807,3.688127,3.267551
16,PI,2025,42.0,43.0,102.0,58.0,7678.0,306.0,7984,5.260521,5.385772,12.775551,7.264529
17,PR,2025,103.0,71.0,170.0,54.0,41239.0,2449.0,43688,2.357627,1.625160,3.891229,1.236037
18,RJ,2025,102.0,113.0,427.0,59.0,44844.0,1801.0,46645,2.186730,2.422553,9.154250,1.264873
19,RN,2025,33.0,24.0,65.0,14.0,7639.0,365.0,8004,4.122939,2.998501,8.120940,1.749125
20,RO,2025,31.0,16.0,136.0,25.0,7972.0,431.0,8403,3.689159,1.904082,16.184696,2.975128
21,RR,2025,8.0,7.0,35.0,3.0,2969.0,159.0,3128,2.557545,2.237852,11.189258,0.959079
22,RS,2025,81.0,162.0,220.0,168.0,38883.0,2172.0,41055,1.972963,3.945926,5.358665,4.092072
23,SC,2025,68.0,101.0,177.0,66.0,28893.0,1620.0,30513,2.228558,3.310065,5.800806,2.163012
24,SE,2025,12.0,23.0,91.0,21.0,6193.0,257.0,6450,1.860465,3.565891,14.108527,3.255814
25,SP,2025,160.0,176.0,787.0,185.0,210752.0,10468.0,221220,0.723262,0.795588,3.557545,0.836272
26,TO,2025,13.0,15.0,39.0,15.0,4314.0,188.0,4502,2.887606,3.331853,8.662817,3.331853

In [ ]:
medicos_mental_pop = saude_area_populacao_ano_uf[['ano','UF','total_medicos_mental', 'pop_total', 'medicos_mental_por_1000']]
medicos_mental_pop

     ano  UF  total_medicos_mental  pop_total  medicos_mental_por_1000
0   2025  AC                  12.0       5438                 2.206694
1   2025  AL                  36.0       5922                 6.079027
2   2025  AM                  34.0       5983                 5.682768
3   2025  AP                   8.0       3985                 2.007528
4   2025  BA                 109.0      16724                 6.517580
5   2025  CE                  40.0      25413                 1.573998
6   2025  DF                  23.0      17021                 1.351272
7   2025  ES                 114.0      25321                 4.502192
8   2025  GO                  58.0      19344                 2.998346
9   2025  MA                  69.0      12932                 5.335602
10  2025  MG                 311.0      73432                 4.235211
11  2025  MS                  37.0      18237                 2.028842
12  2025  MT                  38.0      15732                 2.415459
13  2025  PA                  82.0      16608                 4.937380
14  2025  PB                  39.0      13301                 2.932110
15  2025  PE                  79.0      30910                 2.555807
16  2025  PI                  43.0       7984                 5.385772
17  2025  PR                  71.0      43688                 1.625160
18  2025  RJ                 113.0      46645                 2.422553
19  2025  RN                  24.0       8004                 2.998501
20  2025  RO                  16.0       8403                 1.904082
21  2025  RR                   7.0       3128                 2.237852
22  2025  RS                 162.0      41055                 3.945926
23  2025  SC                 101.0      30513                 3.310065
24  2025  SE                  23.0       6450                 3.565891
25  2025  SP                 176.0     221220                 0.795588
26  2025  TO                  15.0       4502                 3.331853

In [ ]:
medicos_mental_pop['profissao'] = 'Psiquiatras/psicólogos/terapeutas'

/tmp/ipykernel_2662/2164045910.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  medicos_mental_pop['profissao'] = 'Psiquiatras/psicólogos/terapeutas'

In [ ]:
medicos_mental_pop.columns

Index(['ano', 'UF', 'total_medicos_mental', 'pop_total',
       'medicos_mental_por_1000', 'profissao'],
      dtype='object')

In [ ]:
a = medicos_mental_pop[medicos_mental_pop['ano']==2024]
a['total_medicos_mental'].sum()

np.float64(0.0)

In [ ]:
medicos_mental_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ano                      27 non-null     int64
 1   UF                       27 non-null     object
 2   total_medicos_mental     27 non-null     float64
 3   pop_total                27 non-null     int64
 4   medicos_mental_por_1000  27 non-null     float64
 5   profissao                27 non-null     object
dtypes: float64(2), int64(2), object(2)
memory usage: 1.4+ KB

In [ ]:
medicos_mental_pop = medicos_mental_pop.rename(
                                            columns={'UF':'sigla_uf'
                                            })
medicos_mental_pop

,ano,sigla_uf,total_medicos_mental,pop_total,medicos_mental_por_1000,profissao
0,2025,AC,12.0,5438,2.206694,Psiquiatras/psicólogos/terapeutas
1,2025,AL,36.0,5922,6.079027,Psiquiatras/psicólogos/terapeutas
2,2025,AM,34.0,5983,5.682768,Psiquiatras/psicólogos/terapeutas
3,2025,AP,8.0,3985,2.007528,Psiquiatras/psicólogos/terapeutas
4,2025,BA,109.0,16724,6.517580,Psiquiatras/psicólogos/terapeutas
5,2025,CE,40.0,25413,1.573998,Psiquiatras/psicólogos/terapeutas
6,2025,DF,23.0,17021,1.351272,Psiquiatras/psicólogos/terapeutas
7,2025,ES,114.0,25321,4.502192,Psiquiatras/psicólogos/terapeutas
8,2025,GO,58.0,19344,2.998346,Psiquiatras/psicólogos/terapeutas
9,2025,MA,69.0,12932,5.335602,Psiquiatras/psicólogos/terapeutas
10,2025,MG,311.0,73432,4.235211,Psiquiatras/psicólogos/terapeutas
11,2025,MS,37.0,18237,2.028842,Psiquiatras/psicólogos/terapeutas
12,2025,MT,38.0,15732,2.415459,Psiquiatras/psicólogos/terapeutas
13,2025,PA,82.0,16608,4.937380,Psiquiatras/psicólogos/terapeutas
14,2025,PB,39.0,13301,2.932110,Psiquiatras/psicólogos/terapeutas
15,2025,PE,79.0,30910,2.555807,Psiquiatras/psicólogos/terapeutas
16,2025,PI,43.0,7984,5.385772,Psiquiatras/psicólogos/terapeutas
17,2025,PR,71.0,43688,1.625160,Psiquiatras/psicólogos/terapeutas
18,2025,RJ,113.0,46645,2.422553,Psiquiatras/psicólogos/terapeutas
19,2025,RN,24.0,8004,2.998501,Psiquiatras/psicólogos/terapeutas
20,2025,RO,16.0,8403,1.904082,Psiquiatras/psicólogos/terapeutas
21,2025,RR,7.0,3128,2.237852,Psiquiatras/psicólogos/terapeutas
22,2025,RS,162.0,41055,3.945926,Psiquiatras/psicólogos/terapeutas
23,2025,SC,101.0,30513,3.310065,Psiquiatras/psicólogos/terapeutas
24,2025,SE,23.0,6450,3.565891,Psiquiatras/psicólogos/terapeutas
25,2025,SP,176.0,221220,0.795588,Psiquiatras/psicólogos/terapeutas
26,2025,TO,15.0,4502,3.331853,Psiquiatras/psicólogos/terapeutas

In [ ]:
medicos_mental_pop['medicos_mental_por_1000_1']= medicos_mental_pop['medicos_mental_por_1000'].round(2)
medicos_mental_pop

,ano,sigla_uf,total_medicos_mental,pop_total,medicos_mental_por_1000,profissao,medicos_mental_por_1000_1
0,2025,AC,12.0,5438,2.206694,Psiquiatras/psicólogos/terapeutas,2.21
1,2025,AL,36.0,5922,6.079027,Psiquiatras/psicólogos/terapeutas,6.08
2,2025,AM,34.0,5983,5.682768,Psiquiatras/psicólogos/terapeutas,5.68
3,2025,AP,8.0,3985,2.007528,Psiquiatras/psicólogos/terapeutas,2.01
4,2025,BA,109.0,16724,6.517580,Psiquiatras/psicólogos/terapeutas,6.52
5,2025,CE,40.0,25413,1.573998,Psiquiatras/psicólogos/terapeutas,1.57
6,2025,DF,23.0,17021,1.351272,Psiquiatras/psicólogos/terapeutas,1.35
7,2025,ES,114.0,25321,4.502192,Psiquiatras/psicólogos/terapeutas,4.50
8,2025,GO,58.0,19344,2.998346,Psiquiatras/psicólogos/terapeutas,3.00
9,2025,MA,69.0,12932,5.335602,Psiquiatras/psicólogos/terapeutas,5.34
10,2025,MG,311.0,73432,4.235211,Psiquiatras/psicólogos/terapeutas,4.24
11,2025,MS,37.0,18237,2.028842,Psiquiatras/psicólogos/terapeutas,2.03
12,2025,MT,38.0,15732,2.415459,Psiquiatras/psicólogos/terapeutas,2.42
13,2025,PA,82.0,16608,4.937380,Psiquiatras/psicólogos/terapeutas,4.94
14,2025,PB,39.0,13301,2.932110,Psiquiatras/psicólogos/terapeutas,2.93
15,2025,PE,79.0,30910,2.555807,Psiquiatras/psicólogos/terapeutas,2.56
16,2025,PI,43.0,7984,5.385772,Psiquiatras/psicólogos/terapeutas,5.39
17,2025,PR,71.0,43688,1.625160,Psiquiatras/psicólogos/terapeutas,1.63
18,2025,RJ,113.0,46645,2.422553,Psiquiatras/psicólogos/terapeutas,2.42
19,2025,RN,24.0,8004,2.998501,Psiquiatras/psicólogos/terapeutas,3.00
20,2025,RO,16.0,8403,1.904082,Psiquiatras/psicólogos/terapeutas,1.90
21,2025,RR,7.0,3128,2.237852,Psiquiatras/psicólogos/terapeutas,2.24
22,2025,RS,162.0,41055,3.945926,Psiquiatras/psicólogos/terapeutas,3.95
23,2025,SC,101.0,30513,3.310065,Psiquiatras/psicólogos/terapeutas,3.31
24,2025,SE,23.0,6450,3.565891,Psiquiatras/psicólogos/terapeutas,3.57
25,2025,SP,176.0,221220,0.795588,Psiquiatras/psicólogos/terapeutas,0.80
26,2025,TO,15.0,4502,3.331853,Psiquiatras/psicólogos/terapeutas,3.33

In [ ]:
medicos_mental_pop[medicos_mental_pop['ano']==2025]['total_medicos_mental'].sum()

np.float64(1840.0)

In [ ]:
medicos_mental_pop.columns

Index(['ano', 'sigla_uf', 'total_medicos_mental', 'pop_total',
       'medicos_mental_por_1000', 'profissao', 'medicos_mental_por_1000_1'],
      dtype='object')

In [ ]:
medicos_mental_pop[(medicos_mental_pop['ano'] == 2025) & (medicos_mental_pop['medicos_mental_por_1000_1'] < 2.62)].sort_values(by='medicos_mental_por_1000_1', ascending=True)

,ano,sigla_uf,total_medicos_mental,pop_total,medicos_mental_por_1000,profissao,medicos_mental_por_1000_1
25,2025,SP,176.0,221220,0.795588,Psiquiatras/psicólogos/terapeutas,0.80
6,2025,DF,23.0,17021,1.351272,Psiquiatras/psicólogos/terapeutas,1.35
5,2025,CE,40.0,25413,1.573998,Psiquiatras/psicólogos/terapeutas,1.57
17,2025,PR,71.0,43688,1.625160,Psiquiatras/psicólogos/terapeutas,1.63
20,2025,RO,16.0,8403,1.904082,Psiquiatras/psicólogos/terapeutas,1.90
3,2025,AP,8.0,3985,2.007528,Psiquiatras/psicólogos/terapeutas,2.01
11,2025,MS,37.0,18237,2.028842,Psiquiatras/psicólogos/terapeutas,2.03
0,2025,AC,12.0,5438,2.206694,Psiquiatras/psicólogos/terapeutas,2.21
21,2025,RR,7.0,3128,2.237852,Psiquiatras/psicólogos/terapeutas,2.24
12,2025,MT,38.0,15732,2.415459,Psiquiatras/psicólogos/terapeutas,2.42
18,2025,RJ,113.0,46645,2.422553,Psiquiatras/psicólogos/terapeutas,2.42
15,2025,PE,79.0,30910,2.555807,Psiquiatras/psicólogos/terapeutas,2.56

In [ ]:
medicos_mental_pop[medicos_mental_pop['ano']==2025].sort_values(by='medicos_mental_por_1000', ascending=False)

,ano,sigla_uf,total_medicos_mental,pop_total,medicos_mental_por_1000,profissao,medicos_mental_por_1000_1
4,2025,BA,109.0,16724,6.517580,Psiquiatras/psicólogos/terapeutas,6.52
1,2025,AL,36.0,5922,6.079027,Psiquiatras/psicólogos/terapeutas,6.08
2,2025,AM,34.0,5983,5.682768,Psiquiatras/psicólogos/terapeutas,5.68
16,2025,PI,43.0,7984,5.385772,Psiquiatras/psicólogos/terapeutas,5.39
9,2025,MA,69.0,12932,5.335602,Psiquiatras/psicólogos/terapeutas,5.34
13,2025,PA,82.0,16608,4.937380,Psiquiatras/psicólogos/terapeutas,4.94
7,2025,ES,114.0,25321,4.502192,Psiquiatras/psicólogos/terapeutas,4.50
10,2025,MG,311.0,73432,4.235211,Psiquiatras/psicólogos/terapeutas,4.24
22,2025,RS,162.0,41055,3.945926,Psiquiatras/psicólogos/terapeutas,3.95
24,2025,SE,23.0,6450,3.565891,Psiquiatras/psicólogos/terapeutas,3.57
26,2025,TO,15.0,4502,3.331853,Psiquiatras/psicólogos/terapeutas,3.33
23,2025,SC,101.0,30513,3.310065,Psiquiatras/psicólogos/terapeutas,3.31
19,2025,RN,24.0,8004,2.998501,Psiquiatras/psicólogos/terapeutas,3.00
8,2025,GO,58.0,19344,2.998346,Psiquiatras/psicólogos/terapeutas,3.00
14,2025,PB,39.0,13301,2.932110,Psiquiatras/psicólogos/terapeutas,2.93
15,2025,PE,79.0,30910,2.555807,Psiquiatras/psicólogos/terapeutas,2.56
18,2025,RJ,113.0,46645,2.422553,Psiquiatras/psicólogos/terapeutas,2.42
12,2025,MT,38.0,15732,2.415459,Psiquiatras/psicólogos/terapeutas,2.42
21,2025,RR,7.0,3128,2.237852,Psiquiatras/psicólogos/terapeutas,2.24
0,2025,AC,12.0,5438,2.206694,Psiquiatras/psicólogos/terapeutas,2.21
11,2025,MS,37.0,18237,2.028842,Psiquiatras/psicólogos/terapeutas,2.03
3,2025,AP,8.0,3985,2.007528,Psiquiatras/psicólogos/terapeutas,2.01
20,2025,RO,16.0,8403,1.904082,Psiquiatras/psicólogos/terapeutas,1.90
17,2025,PR,71.0,43688,1.625160,Psiquiatras/psicólogos/terapeutas,1.63
5,2025,CE,40.0,25413,1.573998,Psiquiatras/psicólogos/terapeutas,1.57
6,2025,DF,23.0,17021,1.351272,Psiquiatras/psicólogos/terapeutas,1.35
25,2025,SP,176.0,221220,0.795588,Psiquiatras/psicólogos/terapeutas,0.80

In [ ]:
medicos_mental_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ano                        27 non-null     int64
 1   sigla_uf                   27 non-null     object
 2   total_medicos_mental       27 non-null     float64
 3   pop_total                  27 non-null     int64
 4   medicos_mental_por_1000    27 non-null     float64
 5   profissao                  27 non-null     object
 6   medicos_mental_por_1000_1  27 non-null     float64
dtypes: float64(3), int64(2), object(2)
memory usage: 1.6+ KB

# Agregando dados de anos anteriores

In [ ]:
medicos_mental_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ano                        27 non-null     int64
 1   sigla_uf                   27 non-null     object
 2   total_medicos_mental       27 non-null     float64
 3   pop_total                  27 non-null     int64
 4   medicos_mental_por_1000    27 non-null     float64
 5   profissao                  27 non-null     object
 6   medicos_mental_por_1000_1  27 non-null     float64
dtypes: float64(3), int64(2), object(2)
memory usage: 1.6+ KB

In [ ]:
query = """SELECT * FROM `repositoriodedadosgpsp.perfil_remuneracao.SENAPPEN_profissionais_saude_mental_mil_presos`"""
# Execute the query using pandas_gbq.read_gbq and load the result into a pandas DataFrame called 'df'.
# The 'project_id' specifies the Google Cloud Project to use.
df_old = pandas_gbq.read_gbq(query, project_id='repositoriodedadosgpsp')

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

Downloading: 100%|██████████|

In [ ]:
df_old.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ano                        243 non-null    Int64
 1   sigla_uf                   243 non-null    object
 2   profissao                  243 non-null    object
 3   total_medicos_mental       243 non-null    float64
 4   pop_total                  243 non-null    float64
 5   medicos_mental_por_1000    243 non-null    float64
 6   medicos_mental_por_1000_1  243 non-null    float64
dtypes: Int64(1), float64(4), object(2)
memory usage: 13.7+ KB

In [ ]:
df_final = pd.concat([medicos_mental_pop, df_old], ignore_index=True)

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ano                        270 non-null    Int64
 1   sigla_uf                   270 non-null    object
 2   total_medicos_mental       270 non-null    float64
 3   pop_total                  270 non-null    float64
 4   medicos_mental_por_1000    270 non-null    float64
 5   profissao                  270 non-null    object
 6   medicos_mental_por_1000_1  270 non-null    float64
dtypes: Int64(1), float64(4), object(2)
memory usage: 15.2+ KB

# Subindo no GBQ

In [ ]:
# Define the BigQuery table schema with Portuguese descriptions
schema=[bigquery.SchemaField('ano','INTEGER',description='Ano de referencia'),
        bigquery.SchemaField('sigla_uf','STRING',description='Sigla da Unidade da Federação'),
        bigquery.SchemaField('profissao','STRING',description='Profissional'),
        bigquery.SchemaField('total_medicos_mental','FLOAT',description='Quantidade de médicos responsáveis pela saúde mental'),
        bigquery.SchemaField('pop_total','FLOAT',description='Total da população prisional'),
        bigquery.SchemaField('medicos_mental_por_1000','FLOAT',description='Taxa de médicos responsáveis pela saúde mental por 1000 presos'),
        bigquery.SchemaField('medicos_mental_por_1000_1','FLOAT',description='Taxa de médicos  responsáveis pela saúde mental por 1000 presos arredondado')
 ]


# Initialize BigQuery client connection
client = bigquery.Client(project='repositoriodedadosgpsp')

# Create reference to target dataset
dataset_ref = client.dataset('perfil_remuneracao')

# Create reference to target table with standardized naming convention:
# FONTE_algo_intuitivo_dado (INEP_esforco_docente_temporal_v2)
table_ref = dataset_ref.table('SENAPPEN_profissionais_saude_mental_mil_presos_v1')

# Configure the load job with our schema definition
job_config = bigquery.LoadJobConfig(schema=schema)

# Execute the load job to upload DataFrame to BigQuery
job = client.load_table_from_dataframe(
    dataframe=df_final,
    destination=table_ref,
    job_config=job_config
)

# Wait for the job to complete
job.result()

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

LoadJob<project=repositoriodedadosgpsp, location=US, id=2428c93d-6b1b-418d-8b2c-af597a12a729>