In [ ]:
# Install required Google Cloud packages (commented out as these are typically one-time setup commands)
!pip install gcloud
!gcloud auth application-default login

# Import necessary Python libraries
import pandas as pd                # Data manipulation and analysis
import numpy as np                 # Numerical computing
import time                        # Time-related functions
import os                          # Operating system interfaces
import pandas_gbq                  # Pandas integration with BigQuery
from google.cloud import bigquery  # BigQuery client library
import glob                        # File path pattern matching
import openpyxl                    # Excel file handling
import csv                         # CSV file handling
import re                          # Regular expressions

# Note: The actual imports remain exactly as in the original code

Collecting gcloud
  Downloading gcloud-0.18.3.tar.gz (454 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 454.4/454.4 kB 8.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: httplib2>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from gcloud) (0.32.0)
Requirement already satisfied: googleapis-common-protos in /usr/local/lib/python3.12/dist-packages (from gcloud) (1.75.0)
Requirement already satisfied: oauth2client>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from gcloud) (4.1.3)
Requirement already satisfied: protobuf!=3.0.0.b2.post1,>=3.0.0b2 in /usr/local/lib/python3.12/dist-packages (from gcloud) (5.29.6)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from gcloud) (1.17.0)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2>=0.9.1->gcloud) (3.3.2)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (0.6.4)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (0.4.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (4.9.1)
Building wheels for collected packages: gcloud
  Building wheel for gcloud (setup.py) ... done
  Created wheel for gcloud: filename=gcloud-0.18.3-py3-none-any.whl size=602927 sha256=e18ecc79650b0132de20b379b486c9f527f6dcb5f0fb34b476c75bdf7718b720
  Stored in directory: /root/.cache/pip/wheels/2a/62/75/3d74209bfebb8805823ae74afa28653aa1ea76d8b5a9d741ff
Successfully built gcloud
Installing collected packages: gcloud
Successfully installed gcloud-0.18.3
Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fapplicationdefaultauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=74mNgcr9BvInvOXn2GZF8lwyrBNzQl&prompt=consent&token_usage=remote&access_type=offline&code_challenge=mTgl8dDMS9uMhtF3ZpbaljJ5yYO73J7HcCZCFDa11RM&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0AXEQxIArvYxvjtsuAw548Xx7wAHGyWsSnOataJhTynCWbQBQ5gcCkrfkeft0SR_2AaNnYA

Credentials saved to file: [/content/.config/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.


To take a quick anonymous survey, run:
  $ gcloud survey

In [ ]:
df = pd.read_excel("/content/PEP_CARREIRAS_ALL_ATT2026.xlsx", decimal=",", thousands=".")
df

,Agrupamentos de Cargos 2,Agrupamentos de Cargos 1,Grupo-Cargo (sigla),Cargo (com código),Escolaridade do Cargo,Cargo em Extinção (indicador),Subsídio (indicador),Plano/Carreira,Nome do Cargo,Código do Cargo,Órgão (Sigla),Qtd. Cargos Ocupados,Qtd. Cargos Aprovados,Qtd. Cargos Distribuidos,Qtd. Cargos Vagos,Remuneração - Mínimo Valor Inicial\n,Remuneração - Máximo Valor Final
0,Total da Seleção,Total da Seleção,Total da Seleção,Total da Seleção,Total da Seleção,Total da Seleção,Total da Seleção,Total da Seleção,Total da Seleção,Total da Seleção,Total da Seleção,468971.0,722958.0,583255.0,253987.0,1590.73,33721.23
1,ABIN - Agência Brasileira de Inteligência - (C...,Agente de Inteligência - NI (Carreira de Agent...,ABIN,Agente De Inteligencia (617002),NM,0,S,Plano de Carreiras e Cargos da Agência Brasile...,AGENTE DE INTELIGENCIA,617002,ABIN,51.0,937.0,125.0,886.0,6869.43,11805.13
2,ABIN - Agência Brasileira de Inteligência - (C...,Agente Técnico de Inteligência - NI (Carreira ...,ABIN,Agente Tecnico De Inteligencia (617004),NM,0,S,Plano de Carreiras e Cargos da Agência Brasile...,AGENTE TECNICO DE INTELIGENCIA,617004,ABIN,14.0,229.0,47.0,215.0,6181.8,10623.45
3,ABIN - Agência Brasileira de Inteligência - (C...,Oficial de Inteligência - NS (Carreira de Ofic...,ABIN,Oficial De Inteligencia (617001),NS,0,S,Plano de Carreiras e Cargos da Agência Brasile...,OFICIAL DE INTELIGENCIA,617001,ABIN,727.0,2131.0,831.0,1404.0,18116.3,25718.98
4,ABIN - Agência Brasileira de Inteligência - (C...,Oficial Técnico de Inteligência - NS (Carreira...,ABIN,Oficial Tecnico De Inteligencia (617003),NS,0,S,Plano de Carreiras e Cargos da Agência Brasile...,OFICIAL TECNICO DE INTELIGENCIA,617003,ABIN,90.0,439.0,162.0,349.0,16690.89,23144.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13882,-,-,-,-,-,0,-,-,-,400001,MCTI,0.0,1.0,1.0,1.0,-,-
13883,-,-,-,-,-,0,-,-,-,700001,SIPEC,0.0,2.0,0.0,2.0,-,-
13884,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13885,Selection Status:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13886,Aba: Carreiras,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.columns

Index(['Agrupamentos de Cargos 2', 'Agrupamentos de Cargos 1',
       'Grupo-Cargo (sigla)', 'Cargo (com código)', 'Escolaridade do Cargo',
       'Cargo em Extinção (indicador)', 'Subsídio (indicador)',
       'Plano/Carreira', 'Nome do Cargo', 'Código do Cargo', 'Órgão (Sigla)',
       'Qtd. Cargos Ocupados', 'Qtd. Cargos Aprovados',
       'Qtd. Cargos Distribuidos', 'Qtd. Cargos Vagos',
       'Remuneração - Mínimo Valor Inicial\n',
       'Remuneração - Máximo Valor Final'],
      dtype='object')

In [ ]:
df['Órgão (Sigla)'].unique()

array(['ABIN', 'ANAC', 'ANATEL', 'ANCINE', 'ANEEL', 'ANP', 'ANS', 'ANTAQ',
       'ANTT', 'ANVS', 'ANA', 'ANM', 'C.AER', 'CM', 'CNEN', 'FIOCRUZ',
       'INCRA', 'MAPA', 'MCOM', 'MCTI', 'MEC', 'MF', 'MGI', 'MIDR',
       'MINC', 'MME', 'MS', 'MT', 'FUNAI', 'FUNASA', 'IFFLU', 'IFMA',
       'INSS', 'IPHAN', 'MDA', 'MDS', 'MPA', 'MPOR', 'MPS', 'UFRRJ',
       'UNB', 'DNIT', 'MCID', 'MTE', 'AGU', 'DPU', 'ME', 'SIPEC', 'CNPQ',
       'AEB', 'C.EX', 'CAPES', 'F.CENTRO', 'FCRB', 'FJN', 'INPI', 'ITI',
       'JBRJ', 'MD', 'MMA', 'UFF', 'INMETRO', 'UFJF', 'CVM', 'SUSEP',
       'DPF', 'DPRF', 'MJ', 'MRE', 'C.PEDROII', 'CEFET/MG', 'CEFET/RJ',
       'FUFS', 'IFAC', 'IFAL', 'IFAM', 'IFAP', 'IFBA', 'IFBAIANO',
       'IFBRASILIA', 'IFCATARINA', 'IFCE', 'IFES', 'IFFARROUP', 'IFG',
       'IFGOIANO', 'IFMG', 'IFMS', 'IFMT', 'IFNORTEMG', 'IFPA', 'IFPB',
       'IFPE', 'IFPI', 'IFPR', 'IFRJ', 'IFRN', 'IFRO', 'IFRR', 'IFRS',
       'IFSC', 'IFSE', 'IFSERTPE', 'IFSP', 'IFSRIOGRAN', 'IFSUDMG',
       'IFSULMG', 'IFTO', 'IFTRIANMG', 'UFAC', 'UFBA', 'UFCG', 'UFES',
       'UFGO', 'UFLA', 'UFMA', 'UFMG', 'UFPA', 'UFPB', 'UFPE', 'UFPI',
       'UFPR', 'UFRGS/RS', 'UFRJ', 'UFRN', 'UFRPE', 'UFRR', 'UFSC',
       'UFSM/RS', 'UFTM', 'UFU', 'UFV', 'FUAM', 'FUFOP', 'FUFPEL',
       'FUFSCAR', 'FUFT', 'FUNREI', 'FURG', 'UFABC', 'UFAL', 'UFAPE',
       'UFCA', 'UFCAT', 'UFCE', 'UFCSPA', 'UFDPAR', 'UFERSA-RN', 'UFESBA',
       'UFFS', 'UFGD', 'UFJ', 'UFMS', 'UFMT', 'UFNT', 'UFOB', 'UFOPA',
       'UFR', 'UFRA', 'UFRB', 'UFVJM', 'UNIFAL-MG', 'UNIFAP', 'UNIFEI',
       'UNIFESP', 'UNIFESSPA', 'UNILA', 'UNILAB', 'UNIPAMPA', 'UNIR',
       'UNIRIO', 'UNIVASF', 'UTFPR', 'EX-TER/AP', 'EX-TER/RR',
       'EX-TER/RO', 'F.OSORIO', 'MTUR', 'EMBRATUR', 'DNOCS', 'MPO',
       'SUDECO', 'SUDENE', 'CFIA', 'FAG', 'MDIC', 'MEMP', 'MESP',
       'MINFRA', 'MTP', 'SUDAM', 'ICMBIO', 'PR', 'FNDE', 'CGU', 'IBGE',
       'INEP', 'IPEA', 'IBAMA', 'CADE', 'DECIP/SGP', 'ENAP', 'MC', 'FBN',
       'FCP', 'SUFRAMA', 'IBRAM', 'PREVIC', 'FUNARTE', nan], dtype=object)

In [ ]:
df = df[~df['Órgão (Sigla)'].isin(['Selection Status:', 'Aba: Carreiras', 'Total da Seleção'])]
df['Órgão (Sigla)'].unique()

array(['ABIN', 'ANAC', 'ANATEL', 'ANCINE', 'ANEEL', 'ANP', 'ANS', 'ANTAQ',
       'ANTT', 'ANVS', 'ANA', 'ANM', 'C.AER', 'CM', 'CNEN', 'FIOCRUZ',
       'INCRA', 'MAPA', 'MCOM', 'MCTI', 'MEC', 'MF', 'MGI', 'MIDR',
       'MINC', 'MME', 'MS', 'MT', 'FUNAI', 'FUNASA', 'IFFLU', 'IFMA',
       'INSS', 'IPHAN', 'MDA', 'MDS', 'MPA', 'MPOR', 'MPS', 'UFRRJ',
       'UNB', 'DNIT', 'MCID', 'MTE', 'AGU', 'DPU', 'ME', 'SIPEC', 'CNPQ',
       'AEB', 'C.EX', 'CAPES', 'F.CENTRO', 'FCRB', 'FJN', 'INPI', 'ITI',
       'JBRJ', 'MD', 'MMA', 'UFF', 'INMETRO', 'UFJF', 'CVM', 'SUSEP',
       'DPF', 'DPRF', 'MJ', 'MRE', 'C.PEDROII', 'CEFET/MG', 'CEFET/RJ',
       'FUFS', 'IFAC', 'IFAL', 'IFAM', 'IFAP', 'IFBA', 'IFBAIANO',
       'IFBRASILIA', 'IFCATARINA', 'IFCE', 'IFES', 'IFFARROUP', 'IFG',
       'IFGOIANO', 'IFMG', 'IFMS', 'IFMT', 'IFNORTEMG', 'IFPA', 'IFPB',
       'IFPE', 'IFPI', 'IFPR', 'IFRJ', 'IFRN', 'IFRO', 'IFRR', 'IFRS',
       'IFSC', 'IFSE', 'IFSERTPE', 'IFSP', 'IFSRIOGRAN', 'IFSUDMG',
       'IFSULMG', 'IFTO', 'IFTRIANMG', 'UFAC', 'UFBA', 'UFCG', 'UFES',
       'UFGO', 'UFLA', 'UFMA', 'UFMG', 'UFPA', 'UFPB', 'UFPE', 'UFPI',
       'UFPR', 'UFRGS/RS', 'UFRJ', 'UFRN', 'UFRPE', 'UFRR', 'UFSC',
       'UFSM/RS', 'UFTM', 'UFU', 'UFV', 'FUAM', 'FUFOP', 'FUFPEL',
       'FUFSCAR', 'FUFT', 'FUNREI', 'FURG', 'UFABC', 'UFAL', 'UFAPE',
       'UFCA', 'UFCAT', 'UFCE', 'UFCSPA', 'UFDPAR', 'UFERSA-RN', 'UFESBA',
       'UFFS', 'UFGD', 'UFJ', 'UFMS', 'UFMT', 'UFNT', 'UFOB', 'UFOPA',
       'UFR', 'UFRA', 'UFRB', 'UFVJM', 'UNIFAL-MG', 'UNIFAP', 'UNIFEI',
       'UNIFESP', 'UNIFESSPA', 'UNILA', 'UNILAB', 'UNIPAMPA', 'UNIR',
       'UNIRIO', 'UNIVASF', 'UTFPR', 'EX-TER/AP', 'EX-TER/RR',
       'EX-TER/RO', 'F.OSORIO', 'MTUR', 'EMBRATUR', 'DNOCS', 'MPO',
       'SUDECO', 'SUDENE', 'CFIA', 'FAG', 'MDIC', 'MEMP', 'MESP',
       'MINFRA', 'MTP', 'SUDAM', 'ICMBIO', 'PR', 'FNDE', 'CGU', 'IBGE',
       'INEP', 'IPEA', 'IBAMA', 'CADE', 'DECIP/SGP', 'ENAP', 'MC', 'FBN',
       'FCP', 'SUFRAMA', 'IBRAM', 'PREVIC', 'FUNARTE', nan], dtype=object)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13886 entries, 1 to 13886
Data columns (total 17 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Agrupamentos de Cargos 2             13885 non-null  object
 1   Agrupamentos de Cargos 1             13883 non-null  object
 2   Grupo-Cargo (sigla)                  13883 non-null  object
 3   Cargo (com código)                   13883 non-null  object
 4   Escolaridade do Cargo                13883 non-null  object
 5   Cargo em Extinção (indicador)        13883 non-null  object
 6   Subsídio (indicador)                 13883 non-null  object
 7   Plano/Carreira                       13883 non-null  object
 8   Nome do Cargo                        13883 non-null  object
 9   Código do Cargo                      13883 non-null  object
 10  Órgão (Sigla)                        13883 non-null  object
 11  Qtd. Cargos Ocupados                 13883 non-null  float64
 12  Qtd. Cargos Aprovados                13883 non-null  float64
 13  Qtd. Cargos Distribuidos             13883 non-null  float64
 14  Qtd. Cargos Vagos                    13883 non-null  float64
 15  Remuneração - Mínimo Valor Inicial
  13883 non-null  object
 16  Remuneração - Máximo Valor Final     13883 non-null  object
dtypes: float64(4), object(13)
memory usage: 1.9+ MB

In [ ]:
df_renamed = df.rename(columns={
    'Órgão (Sigla)': 'orgao_sigla',
    'Qtd. Cargos Ocupados': 'qtd_cargos_ocupados',
    'Qtd. Cargos Aprovados': 'qtd_cargos_aprovados',
    'Qtd. Cargos Distribuidos': 'qtd_cargos_distribuidos',
    'Agrupamentos de Cargos 2': 'agrupamentos_de_cargos_2',
    'Agrupamentos de Cargos 1': 'agrupamentos_de_cargos_1',
    'Grupo-Cargo (sigla)': 'grupo_cargo_sigla',
    'Cargo (com código)': 'cargo_com_codigo',
    'Escolaridade do Cargo': 'escolaridade_do_cargo',
    'Cargo em Extinção (indicador)': 'cargo_em_extincao_indicador',
    'Subsídio (indicador)': 'subsidio_indicador',
    'Plano/Carreira': 'plano_carreira',
    'Nome do Cargo': 'nome_do_cargo',
    'Código do Cargo': 'codigo_do_cargo',
    'Qtd. Cargos Vagos': 'qtd_cargos_vagos',
    'Remuneração - Mínimo Valor Inicial\n': 'remuneracao_minimo_valor_inicial',
    'Remuneração - Máximo Valor Final': 'remuneracao_maximo_valor_final'
})

In [ ]:
for col in ['remuneracao_minimo_valor_inicial', 'remuneracao_maximo_valor_final']:
    df_renamed[col] = (
        df_renamed[col]
        .replace('-', np.nan)
        .astype(str)
        .str.replace(',', '', regex=False)
        .replace('nan', np.nan)
        .astype(float)
    )

/tmp/ipykernel_1357/1040596475.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace('-', np.nan)

In [ ]:
df_renamed['orgao_sigla'].unique()

array(['ABIN', 'ANAC', 'ANATEL', 'ANCINE', 'ANEEL', 'ANP', 'ANS', 'ANTAQ',
       'ANTT', 'ANVS', 'ANA', 'ANM', 'C.AER', 'CM', 'CNEN', 'FIOCRUZ',
       'INCRA', 'MAPA', 'MCOM', 'MCTI', 'MEC', 'MF', 'MGI', 'MIDR',
       'MINC', 'MME', 'MS', 'MT', 'FUNAI', 'FUNASA', 'IFFLU', 'IFMA',
       'INSS', 'IPHAN', 'MDA', 'MDS', 'MPA', 'MPOR', 'MPS', 'UFRRJ',
       'UNB', 'DNIT', 'MCID', 'MTE', 'AGU', 'DPU', 'ME', 'SIPEC', 'CNPQ',
       'AEB', 'C.EX', 'CAPES', 'F.CENTRO', 'FCRB', 'FJN', 'INPI', 'ITI',
       'JBRJ', 'MD', 'MMA', 'UFF', 'INMETRO', 'UFJF', 'CVM', 'SUSEP',
       'DPF', 'DPRF', 'MJ', 'MRE', 'C.PEDROII', 'CEFET/MG', 'CEFET/RJ',
       'FUFS', 'IFAC', 'IFAL', 'IFAM', 'IFAP', 'IFBA', 'IFBAIANO',
       'IFBRASILIA', 'IFCATARINA', 'IFCE', 'IFES', 'IFFARROUP', 'IFG',
       'IFGOIANO', 'IFMG', 'IFMS', 'IFMT', 'IFNORTEMG', 'IFPA', 'IFPB',
       'IFPE', 'IFPI', 'IFPR', 'IFRJ', 'IFRN', 'IFRO', 'IFRR', 'IFRS',
       'IFSC', 'IFSE', 'IFSERTPE', 'IFSP', 'IFSRIOGRAN', 'IFSUDMG',
       'IFSULMG', 'IFTO', 'IFTRIANMG', 'UFAC', 'UFBA', 'UFCG', 'UFES',
       'UFGO', 'UFLA', 'UFMA', 'UFMG', 'UFPA', 'UFPB', 'UFPE', 'UFPI',
       'UFPR', 'UFRGS/RS', 'UFRJ', 'UFRN', 'UFRPE', 'UFRR', 'UFSC',
       'UFSM/RS', 'UFTM', 'UFU', 'UFV', 'FUAM', 'FUFOP', 'FUFPEL',
       'FUFSCAR', 'FUFT', 'FUNREI', 'FURG', 'UFABC', 'UFAL', 'UFAPE',
       'UFCA', 'UFCAT', 'UFCE', 'UFCSPA', 'UFDPAR', 'UFERSA-RN', 'UFESBA',
       'UFFS', 'UFGD', 'UFJ', 'UFMS', 'UFMT', 'UFNT', 'UFOB', 'UFOPA',
       'UFR', 'UFRA', 'UFRB', 'UFVJM', 'UNIFAL-MG', 'UNIFAP', 'UNIFEI',
       'UNIFESP', 'UNIFESSPA', 'UNILA', 'UNILAB', 'UNIPAMPA', 'UNIR',
       'UNIRIO', 'UNIVASF', 'UTFPR', 'EX-TER/AP', 'EX-TER/RR',
       'EX-TER/RO', 'F.OSORIO', 'MTUR', 'EMBRATUR', 'DNOCS', 'MPO',
       'SUDECO', 'SUDENE', 'CFIA', 'FAG', 'MDIC', 'MEMP', 'MESP',
       'MINFRA', 'MTP', 'SUDAM', 'ICMBIO', 'PR', 'FNDE', 'CGU', 'IBGE',
       'INEP', 'IPEA', 'IBAMA', 'CADE', 'DECIP/SGP', 'ENAP', 'MC', 'FBN',
       'FCP', 'SUFRAMA', 'IBRAM', 'PREVIC', 'FUNARTE', nan], dtype=object)

In [ ]:
df_renamed

,agrupamentos_de_cargos_2,agrupamentos_de_cargos_1,grupo_cargo_sigla,cargo_com_codigo,escolaridade_do_cargo,cargo_em_extincao_indicador,subsidio_indicador,plano_carreira,nome_do_cargo,codigo_do_cargo,orgao_sigla,qtd_cargos_ocupados,qtd_cargos_aprovados,qtd_cargos_distribuidos,qtd_cargos_vagos,remuneracao_minimo_valor_inicial,remuneracao_maximo_valor_final
1,ABIN - Agência Brasileira de Inteligência - (C...,Agente de Inteligência - NI (Carreira de Agent...,ABIN,Agente De Inteligencia (617002),NM,0,S,Plano de Carreiras e Cargos da Agência Brasile...,AGENTE DE INTELIGENCIA,617002,ABIN,51.0,937.0,125.0,886.0,6869.43,11805.13
2,ABIN - Agência Brasileira de Inteligência - (C...,Agente Técnico de Inteligência - NI (Carreira ...,ABIN,Agente Tecnico De Inteligencia (617004),NM,0,S,Plano de Carreiras e Cargos da Agência Brasile...,AGENTE TECNICO DE INTELIGENCIA,617004,ABIN,14.0,229.0,47.0,215.0,6181.80,10623.45
3,ABIN - Agência Brasileira de Inteligência - (C...,Oficial de Inteligência - NS (Carreira de Ofic...,ABIN,Oficial De Inteligencia (617001),NS,0,S,Plano de Carreiras e Cargos da Agência Brasile...,OFICIAL DE INTELIGENCIA,617001,ABIN,727.0,2131.0,831.0,1404.0,18116.30,25718.98
4,ABIN - Agência Brasileira de Inteligência - (C...,Oficial Técnico de Inteligência - NS (Carreira...,ABIN,Oficial Tecnico De Inteligencia (617003),NS,0,S,Plano de Carreiras e Cargos da Agência Brasile...,OFICIAL TECNICO DE INTELIGENCIA,617003,ABIN,90.0,439.0,162.0,349.0,16690.89,23144.49
5,ABIN - Agência Brasileira de Inteligência - (G...,Cargos de Nível Auxiliar - NA do Grupo Apoio d...,GAA,Auxiliar Operacional Servicos Diversos (620036),NF,0,N,Plano de Carreiras e Cargos da Agência Brasile...,AUXILIAR OPERACIONAL SERVICOS DIVERSOS,620036,ABIN,1.0,1.0,1.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13882,-,-,-,-,-,0,-,-,-,400001,MCTI,0.0,1.0,1.0,1.0,NaN,NaN
13883,-,-,-,-,-,0,-,-,-,700001,SIPEC,0.0,2.0,0.0,2.0,NaN,NaN
13884,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13885,Selection Status:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13886,Aba: Carreiras,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_renamed

,agrupamentos_de_cargos_2,agrupamentos_de_cargos_1,grupo_cargo_sigla,cargo_com_codigo,escolaridade_do_cargo,cargo_em_extincao_indicador,subsidio_indicador,plano_carreira,nome_do_cargo,codigo_do_cargo,orgao_sigla,qtd_cargos_ocupados,qtd_cargos_aprovados,qtd_cargos_distribuidos,qtd_cargos_vagos,remuneracao_minimo_valor_inicial,remuneracao_maximo_valor_final
1,ABIN - Agência Brasileira de Inteligência - (C...,Agente de Inteligência - NI (Carreira de Agent...,ABIN,Agente De Inteligencia (617002),NM,0,S,Plano de Carreiras e Cargos da Agência Brasile...,AGENTE DE INTELIGENCIA,617002,ABIN,51.0,937.0,125.0,886.0,6869.43,11805.13
2,ABIN - Agência Brasileira de Inteligência - (C...,Agente Técnico de Inteligência - NI (Carreira ...,ABIN,Agente Tecnico De Inteligencia (617004),NM,0,S,Plano de Carreiras e Cargos da Agência Brasile...,AGENTE TECNICO DE INTELIGENCIA,617004,ABIN,14.0,229.0,47.0,215.0,6181.80,10623.45
3,ABIN - Agência Brasileira de Inteligência - (C...,Oficial de Inteligência - NS (Carreira de Ofic...,ABIN,Oficial De Inteligencia (617001),NS,0,S,Plano de Carreiras e Cargos da Agência Brasile...,OFICIAL DE INTELIGENCIA,617001,ABIN,727.0,2131.0,831.0,1404.0,18116.30,25718.98
4,ABIN - Agência Brasileira de Inteligência - (C...,Oficial Técnico de Inteligência - NS (Carreira...,ABIN,Oficial Tecnico De Inteligencia (617003),NS,0,S,Plano de Carreiras e Cargos da Agência Brasile...,OFICIAL TECNICO DE INTELIGENCIA,617003,ABIN,90.0,439.0,162.0,349.0,16690.89,23144.49
5,ABIN - Agência Brasileira de Inteligência - (G...,Cargos de Nível Auxiliar - NA do Grupo Apoio d...,GAA,Auxiliar Operacional Servicos Diversos (620036),NF,0,N,Plano de Carreiras e Cargos da Agência Brasile...,AUXILIAR OPERACIONAL SERVICOS DIVERSOS,620036,ABIN,1.0,1.0,1.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13882,-,-,-,-,-,0,-,-,-,400001,MCTI,0.0,1.0,1.0,1.0,NaN,NaN
13883,-,-,-,-,-,0,-,-,-,700001,SIPEC,0.0,2.0,0.0,2.0,NaN,NaN
13884,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13885,Selection Status:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13886,Aba: Carreiras,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_renamed = df_renamed[~df_renamed['orgao_sigla'].isin(['Selection Status:', 'Aba: Carreiras', 'Total da Seleção'])]
df_renamed['orgao_sigla'].unique()

array(['ABIN', 'ANAC', 'ANATEL', 'ANCINE', 'ANEEL', 'ANP', 'ANS', 'ANTAQ',
       'ANTT', 'ANVS', 'ANA', 'ANM', 'C.AER', 'CM', 'CNEN', 'FIOCRUZ',
       'INCRA', 'MAPA', 'MCOM', 'MCTI', 'MEC', 'MF', 'MGI', 'MIDR',
       'MINC', 'MME', 'MS', 'MT', 'FUNAI', 'FUNASA', 'IFFLU', 'IFMA',
       'INSS', 'IPHAN', 'MDA', 'MDS', 'MPA', 'MPOR', 'MPS', 'UFRRJ',
       'UNB', 'DNIT', 'MCID', 'MTE', 'AGU', 'DPU', 'ME', 'SIPEC', 'CNPQ',
       'AEB', 'C.EX', 'CAPES', 'F.CENTRO', 'FCRB', 'FJN', 'INPI', 'ITI',
       'JBRJ', 'MD', 'MMA', 'UFF', 'INMETRO', 'UFJF', 'CVM', 'SUSEP',
       'DPF', 'DPRF', 'MJ', 'MRE', 'C.PEDROII', 'CEFET/MG', 'CEFET/RJ',
       'FUFS', 'IFAC', 'IFAL', 'IFAM', 'IFAP', 'IFBA', 'IFBAIANO',
       'IFBRASILIA', 'IFCATARINA', 'IFCE', 'IFES', 'IFFARROUP', 'IFG',
       'IFGOIANO', 'IFMG', 'IFMS', 'IFMT', 'IFNORTEMG', 'IFPA', 'IFPB',
       'IFPE', 'IFPI', 'IFPR', 'IFRJ', 'IFRN', 'IFRO', 'IFRR', 'IFRS',
       'IFSC', 'IFSE', 'IFSERTPE', 'IFSP', 'IFSRIOGRAN', 'IFSUDMG',
       'IFSULMG', 'IFTO', 'IFTRIANMG', 'UFAC', 'UFBA', 'UFCG', 'UFES',
       'UFGO', 'UFLA', 'UFMA', 'UFMG', 'UFPA', 'UFPB', 'UFPE', 'UFPI',
       'UFPR', 'UFRGS/RS', 'UFRJ', 'UFRN', 'UFRPE', 'UFRR', 'UFSC',
       'UFSM/RS', 'UFTM', 'UFU', 'UFV', 'FUAM', 'FUFOP', 'FUFPEL',
       'FUFSCAR', 'FUFT', 'FUNREI', 'FURG', 'UFABC', 'UFAL', 'UFAPE',
       'UFCA', 'UFCAT', 'UFCE', 'UFCSPA', 'UFDPAR', 'UFERSA-RN', 'UFESBA',
       'UFFS', 'UFGD', 'UFJ', 'UFMS', 'UFMT', 'UFNT', 'UFOB', 'UFOPA',
       'UFR', 'UFRA', 'UFRB', 'UFVJM', 'UNIFAL-MG', 'UNIFAP', 'UNIFEI',
       'UNIFESP', 'UNIFESSPA', 'UNILA', 'UNILAB', 'UNIPAMPA', 'UNIR',
       'UNIRIO', 'UNIVASF', 'UTFPR', 'EX-TER/AP', 'EX-TER/RR',
       'EX-TER/RO', 'F.OSORIO', 'MTUR', 'EMBRATUR', 'DNOCS', 'MPO',
       'SUDECO', 'SUDENE', 'CFIA', 'FAG', 'MDIC', 'MEMP', 'MESP',
       'MINFRA', 'MTP', 'SUDAM', 'ICMBIO', 'PR', 'FNDE', 'CGU', 'IBGE',
       'INEP', 'IPEA', 'IBAMA', 'CADE', 'DECIP/SGP', 'ENAP', 'MC', 'FBN',
       'FCP', 'SUFRAMA', 'IBRAM', 'PREVIC', 'FUNARTE', nan], dtype=object)

In [ ]:
df_renamed['cargo_em_extincao_indicador'] = df_renamed['cargo_em_extincao_indicador'].map({0: False, 1: True, '0': False, '1': True})

In [ ]:
schema = [
    bigquery.SchemaField('orgao_sigla', 'STRING', description='Sigla do órgão.'),
    bigquery.SchemaField('qtd_cargos_ocupados', 'FLOAT', description='Quantidade de cargos ocupados.'),
    bigquery.SchemaField('qtd_cargos_aprovados', 'FLOAT', description='Quantidade de cargos aprovados.'),
    bigquery.SchemaField('qtd_cargos_distribuidos', 'FLOAT', description='Quantidade de cargos distribuídos.'),
    bigquery.SchemaField('agrupamentos_de_cargos_2', 'STRING', description='Agrupamento de cargos 2.'),
    bigquery.SchemaField('agrupamentos_de_cargos_1', 'STRING', description='Agrupamento de cargos 1.'),
    bigquery.SchemaField('grupo_cargo_sigla', 'STRING', description='Sigla do grupo-cargo.'),
    bigquery.SchemaField('cargo_com_codigo', 'STRING', description='Cargo e código de acordo com o site.'),
    bigquery.SchemaField('escolaridade_do_cargo', 'STRING', description='Escolaridade do cargo.'),
    bigquery.SchemaField('cargo_em_extincao_indicador', 'BOOLEAN', description='Indicador de cargo em extinção.'),
    bigquery.SchemaField('subsidio_indicador', 'STRING', description='Indicador de subsídio.'),
    bigquery.SchemaField('plano_carreira', 'STRING', description='Plano ou carreira.'),
    bigquery.SchemaField('nome_do_cargo', 'STRING', description='Nome do cargo.'),
    bigquery.SchemaField('codigo_do_cargo', 'FLOAT', description='Código do cargo.'),
    bigquery.SchemaField('qtd_cargos_vagos', 'FLOAT', description='Quantidade de cargos vagos.'),
    bigquery.SchemaField('remuneracao_minimo_valor_inicial', 'FLOAT', description='Remuneração mínima, valor inicial.'),
    bigquery.SchemaField('remuneracao_maximo_valor_final', 'FLOAT', description='Remuneração máxima, valor final.')
]

In [ ]:
## Subindo para datalake
client = bigquery.Client(project='repositoriodedadosgpsp')
dataset_ref = client.dataset('estrutura_organizacional_carreiras')

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

In [ ]:
table_ref = dataset_ref.table('PEP_carreiras_v1') # nome da tabela no padrão FONTE_algo_intuitivo_dado
job_config = bigquery.LoadJobConfig(schema=schema)
job = client.load_table_from_dataframe(df_renamed, table_ref, job_config=job_config)
job.result()

LoadJob<project=repositoriodedadosgpsp, location=US, id=e07fd037-cf9f-4e96-9704-98956b10265e>