In [ ]:
# Install required Google Cloud packages (commented out as these are typically one-time setup commands)
!pip install gcloud
!gcloud auth application-default login

# Import necessary Python libraries
import pandas as pd                # Data manipulation and analysis
import numpy as np                 # Numerical computing
import time                        # Time-related functions
import os                          # Operating system interfaces
import pandas_gbq                  # Pandas integration with BigQuery
from google.cloud import bigquery  # BigQuery client library
import glob                        # File path pattern matching
import openpyxl                    # Excel file handling
import csv                         # CSV file handling
import re                          # Regular expressions

# Note: The actual imports remain exactly as in the original code

Collecting gcloud
  Downloading gcloud-0.18.3.tar.gz (454 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 454.4/454.4 kB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: httplib2>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from gcloud) (0.32.0)
Requirement already satisfied: googleapis-common-protos in /usr/local/lib/python3.12/dist-packages (from gcloud) (1.75.0)
Requirement already satisfied: oauth2client>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from gcloud) (4.1.3)
Requirement already satisfied: protobuf!=3.0.0.b2.post1,>=3.0.0b2 in /usr/local/lib/python3.12/dist-packages (from gcloud) (5.29.6)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from gcloud) (1.17.0)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2>=0.9.1->gcloud) (3.3.2)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (0.6.4)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (0.4.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from oauth2client>=2.0.1->gcloud) (4.9.1)
Building wheels for collected packages: gcloud
  Building wheel for gcloud (setup.py) ... done
  Created wheel for gcloud: filename=gcloud-0.18.3-py3-none-any.whl size=602927 sha256=0e6a920e7652f1600cf3771790cbc00194baacf261b00b276ae4774860c18f1e
  Stored in directory: /root/.cache/pip/wheels/2a/62/75/3d74209bfebb8805823ae74afa28653aa1ea76d8b5a9d741ff
Successfully built gcloud
Installing collected packages: gcloud
Successfully installed gcloud-0.18.3
Go to the following link in your browser, and complete the sign-in prompts:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fsdk.cloud.google.com%2Fapplicationdefaultauthcode.html&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login&state=E7lEL46vMRzypIPg10bnbjRCSLuDeQ&prompt=consent&token_usage=remote&access_type=offline&code_challenge=CtXFdeJGJnnZbopodII5A3RUQjwj64ZUcVMmf5XAyYk&code_challenge_method=S256

Once finished, enter the verification code provided in your browser: 4/0ATsMZqBGu9zSB8QAfmp6HhS2Eoqy0LrhMDSUIOGuA00KK_ZFp4uQtZwEFUZnjlND8W5AnQ

Credentials saved to file: [/content/.config/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.

In [ ]:
df = pd.read_excel('/content/Base_MUNIC_2024_20251107.xlsx', sheet_name='Agropecuária', usecols=['Cod Uf','Cod Munic','Desc Mun','Magr01','Magr03','Magr04','Magr05','Magr06'])
df

,Cod Munic,Cod Uf,Desc Mun,Magr01,Magr03,Magr04,Magr05,Magr06
0,1100015,11,Alta Floresta DOeste,Secretaria municipal exclusiva,Masculino,45,Branca,Especialização
1,1100023,11,Ariquemes,Secretaria municipal em conjunto com outras po...,Masculino,52,Branca,Especialização
2,1100031,11,Cabixi,Secretaria municipal exclusiva,Masculino,47,Branca,Ensino médio (2o. Grau) completo
3,1100049,11,Cacoal,Secretaria municipal exclusiva,Masculino,49,Parda,Ensino médio (2o. Grau) completo
4,1100056,11,Cerejeiras,Secretaria municipal em conjunto com outras po...,Masculino,67,Branca,Ensino médio (2o. Grau) completo
...,...,...,...,...,...,...,...,...
5565,5222005,52,Vianópolis,Secretaria municipal exclusiva,Feminino,34,Branca,Ensino médio (2o. Grau) completo
5566,5222054,52,Vicentinópolis,Secretaria municipal em conjunto com outras po...,Feminino,40,Parda,Ensino superior completo
5567,5222203,52,Vila Boa,Secretaria municipal exclusiva,Masculino,55,Preta,Ensino médio (2o. Grau) completo
5568,5222302,52,Vila Propício,Secretaria municipal exclusiva,Masculino,39,Parda,Ensino médio (2o. Grau) completo
5569,5300108,53,Brasília,Secretaria municipal exclusiva,Masculino,41,Branca,Mestrado

In [ ]:
df.rename(columns={'Cod Munic': 'CodMun', 'Cod Uf': 'Cod UF', 'Desc Mun':'Mun'}, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CodMun  5570 non-null   int64
 1   Cod UF  5570 non-null   int64
 2   Mun     5570 non-null   object
 3   Magr01  5570 non-null   object
 4   Magr03  5570 non-null   object
 5   Magr04  5570 non-null   object
 6   Magr05  5570 non-null   object
 7   Magr06  5570 non-null   object
dtypes: int64(2), object(6)
memory usage: 348.3+ KB

In [ ]:
cod_uf = pd.read_csv('/content/ESTADIC_2019 - Variáveis externas.csv', sep=',')[['UF','COD_UF']]

In [ ]:
x= cod_uf.pivot_table(columns=('UF','COD_UF'), aggfunc='size')

In [ ]:
cod_uf = pd.DataFrame(x).reset_index()[['UF','COD_UF']]

In [ ]:
df = df.merge(cod_uf, right_on='COD_UF',left_on='Cod UF')
df

,CodMun,Cod UF,Mun,Magr01,Magr03,Magr04,Magr05,Magr06,UF,COD_UF
0,1100015,11,Alta Floresta DOeste,Secretaria municipal exclusiva,Masculino,45,Branca,Especialização,RO,11
1,1100023,11,Ariquemes,Secretaria municipal em conjunto com outras po...,Masculino,52,Branca,Especialização,RO,11
2,1100031,11,Cabixi,Secretaria municipal exclusiva,Masculino,47,Branca,Ensino médio (2o. Grau) completo,RO,11
3,1100049,11,Cacoal,Secretaria municipal exclusiva,Masculino,49,Parda,Ensino médio (2o. Grau) completo,RO,11
4,1100056,11,Cerejeiras,Secretaria municipal em conjunto com outras po...,Masculino,67,Branca,Ensino médio (2o. Grau) completo,RO,11
...,...,...,...,...,...,...,...,...,...,...
5565,5222005,52,Vianópolis,Secretaria municipal exclusiva,Feminino,34,Branca,Ensino médio (2o. Grau) completo,GO,52
5566,5222054,52,Vicentinópolis,Secretaria municipal em conjunto com outras po...,Feminino,40,Parda,Ensino superior completo,GO,52
5567,5222203,52,Vila Boa,Secretaria municipal exclusiva,Masculino,55,Preta,Ensino médio (2o. Grau) completo,GO,52
5568,5222302,52,Vila Propício,Secretaria municipal exclusiva,Masculino,39,Parda,Ensino médio (2o. Grau) completo,GO,52
5569,5300108,53,Brasília,Secretaria municipal exclusiva,Masculino,41,Branca,Mestrado,DF,53

In [ ]:
df = df.drop(columns=['COD_UF'])

In [ ]:
df['ano']=2024

In [ ]:
df = df.rename(columns={'UF':'sigla_uf',
                        'Cod UF':'cod_uf',
                        'CodMun':'id_municipio',
                        'Mun':'nome_municipio',
                        'Magr01':'caracterizacao_orgao_gestor',
                        'Magr03':'genero',
                        'Magr04':'idade',
                        'Magr05':'cor_raca',
                        'Magr06':'grau_instrucao'})

In [ ]:
df['caracterizacao_orgao_gestor']=df['caracterizacao_orgao_gestor'].str.title()

In [ ]:
#padronizando os dados da coluna 'tipo_orgao'
df['caracterizacao_orgao_gestor']=np.where(df['caracterizacao_orgao_gestor']=='Não Informou','Sem dados',df['caracterizacao_orgao_gestor'])
df['caracterizacao_orgao_gestor']=np.where(df['caracterizacao_orgao_gestor']=='Sem gestor','Sem dados',df['caracterizacao_orgao_gestor'])

#padronizando os dados da coluna 'genero'
df['genero']=np.where(df['genero']=='Não informou','Sem dados',df['genero'])
df['genero']=np.where(df['genero']=='Sem gestor','Sem dados',df['genero'])
df['genero']=np.where(df['genero']=='-','Sem dados',df['genero'])

#padronizando os dados da coluna 'idade'
df['idade']=np.where(df['idade']=='(*) Não soube informar',np.nan,df['idade'])
df['idade']=np.where(df['idade']=='-',np.nan,df['idade'])
df['idade']=np.where(df['idade']=='Não informou',np.nan,df['idade'])
df['idade']=np.where(df['idade']=='Recusa',np.nan,df['idade'])
df['idade']=np.where(df['idade']=='Sem titular',np.nan,df['idade'])
df['idade']=np.where(df['idade']=='Sem gestor',np.nan,df['idade'])


#padronizando os dados da coluna 'cor_raca'

df['cor_raca']=np.where(df['cor_raca']=='Não informou','Sem dados',df['cor_raca'])
df['cor_raca']=np.where(df['cor_raca']=='Sem gestor','Sem dados',df['cor_raca'])
df['cor_raca']=np.where(df['cor_raca']=='-','Sem dados',df['cor_raca'])


#padronizando os dados da coluna 'escolaridade'
df['grau_instrucao']=np.where(df['grau_instrucao']=='-','Sem dados',df['grau_instrucao'])
df['grau_instrucao']=np.where(df['grau_instrucao']=='Não informou','Sem dados',df['grau_instrucao'])
df['grau_instrucao']=np.where(df['grau_instrucao']=='Sem gestor','Sem dados',df['grau_instrucao'])

In [ ]:
df['caracterizacao_orgao_gestor'].unique()
df['genero'].unique()
df['idade'].unique()
df['cor_raca'].unique()
df['grau_instrucao'].unique()

array(['Especialização', 'Ensino médio (2o. Grau) completo',
       'Ensino médio (2o. Grau) incompleto',
       'Ensino fundamental (1o. Grau) completo',
       'Ensino superior completo',
       'Ensino fundamental (1o. Grau) incompleto',
       'Ensino superior incompleto', 'Mestrado', 'Recusa', 'Sem dados',
       'Doutorado'], dtype=object)

In [ ]:
df['idade'] = pd.to_numeric(df['idade']) #transformando em numerico

In [ ]:
limites = [18, 30, 50, 65, 120]
categorias = ['Entre 18-29', 'Entre 30-49', 'Entre 50-64', 'Acima de 65']

df['faixa_etaria'] = pd.cut(df['idade'], bins=limites, labels=categorias, right=False)

In [ ]:
df.columns

Index(['id_municipio', 'cod_uf', 'nome_municipio',
       'caracterizacao_orgao_gestor', 'genero', 'idade', 'cor_raca',
       'grau_instrucao', 'sigla_uf', 'ano', 'faixa_etaria'],
      dtype='object')

In [ ]:
df=df[['ano', 'sigla_uf','nome_municipio','id_municipio','caracterizacao_orgao_gestor', 'genero', 'cor_raca', 'grau_instrucao', 'faixa_etaria']] #reorganizando as colunas

In [ ]:
# criando dicionário
dict_esco = {'Ensino fundamental (1º Grau) incompleto':'Até Ensino Fundamental',
             'Ensino fundamental (1o. Grau) completo':'Até Ensino Fundamental',
             'Ensino fundamental (1o. Grau) incompleto':'Até Ensino Fundamental',
             'Ensino fundamental (1º Grau) completo':'Até Ensino Fundamental',
            'Ensino médio (2º Grau) incompleto':'Até Ensino Médio',
             'Ensino médio (2º Grau) completo':'Até Ensino Médio',
             'Ensino médio (2o. Grau) completo':'Até Ensino Médio',
             'Ensino médio (2o. Grau) incompleto':'Até Ensino Médio',
             'Ensino superior incompleto':'Até Ensino Superior Completo',
             'Ensino superior completo':'Até Ensino Superior Completo',
             'Especialização':'Até Pós Graduação ou Mestrado',
             'Mestrado':'Até Pós Graduação ou Mestrado',
             'Doutorado':'Até Doutorado'}

In [ ]:
df = df.replace({'grau_instrucao':dict_esco}) #substituindo valores para padronizar

In [ ]:
df['grau_instrucao'].unique()

array(['Até Pós Graduação ou Mestrado', 'Até Ensino Médio',
       'Até Ensino Fundamental', 'Até Ensino Superior Completo', 'Recusa',
       'Sem dados', 'Até Doutorado'], dtype=object)

In [ ]:
df.columns

Index(['ano', 'sigla_uf', 'nome_municipio', 'id_municipio',
       'caracterizacao_orgao_gestor', 'genero', 'cor_raca', 'grau_instrucao',
       'faixa_etaria'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ano                          5570 non-null   int64
 1   sigla_uf                     5570 non-null   object
 2   nome_municipio               5570 non-null   object
 3   id_municipio                 5570 non-null   int64
 4   caracterizacao_orgao_gestor  5570 non-null   object
 5   genero                       5570 non-null   object
 6   cor_raca                     5570 non-null   object
 7   grau_instrucao               5570 non-null   object
 8   faixa_etaria                 5153 non-null   category
dtypes: category(1), int64(2), object(6)
memory usage: 353.9+ KB

# Consumindo a base anterior para agregar o novo ano

In [ ]:


query = """SELECT * FROM `repositoriodedadosgpsp.cargos_lideranca.MUNIC_perfil_gestor_agropecuaria_tipo_orgao`"""
# Execute the query using pandas_gbq.read_gbq and load the result into a pandas DataFrame called 'df'.
# The 'project_id' specifies the Google Cloud Project to use.
df_old = pandas_gbq.read_gbq(query, project_id='repositoriodedadosgpsp')

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

Downloading: 100%|██████████|

In [ ]:
df_old.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ano                          5570 non-null   Int64
 1   sigla_uf                     5570 non-null   object
 2   nome_municipio               5570 non-null   object
 3   id_municipio                 5570 non-null   Int64
 4   caracterizacao_orgao_gestor  5570 non-null   object
 5   genero                       5570 non-null   object
 6   cor_raca                     5570 non-null   object
 7   grau_instrucao               5570 non-null   object
 8   faixa_etaria                 4980 non-null   object
dtypes: Int64(2), object(7)
memory usage: 402.6+ KB

In [ ]:
df_final = pd.concat([df, df_old], ignore_index=True)

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11140 entries, 0 to 11139
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ano                          11140 non-null  Int64
 1   sigla_uf                     11140 non-null  object
 2   nome_municipio               11140 non-null  object
 3   id_municipio                 11140 non-null  Int64
 4   caracterizacao_orgao_gestor  11140 non-null  object
 5   genero                       11140 non-null  object
 6   cor_raca                     11140 non-null  object
 7   grau_instrucao               11140 non-null  object
 8   faixa_etaria                 10133 non-null  object
dtypes: Int64(2), object(7)
memory usage: 805.2+ KB

Subindo para o GBQ

In [ ]:
# Define the BigQuery table schema with Portuguese descriptions
schema=[bigquery.SchemaField('ano','INTEGER',description='Ano de referência da observação'),
        bigquery.SchemaField('sigla_uf','STRING',description='Sigla da Unidade da Federação referente municipio'),
        bigquery.SchemaField('nome_municipio','STRING',description='Nome do município'),
        bigquery.SchemaField('id_municipio','INTEGER',description='Código do IBGE do município'),
        bigquery.SchemaField('caracterizacao_orgao_gestor','STRING',description='Caracterização do órgão no qual o gestor está'),
        bigquery.SchemaField('genero','STRING',description='Gênero autodeclarado ou não'),
        bigquery.SchemaField('cor_raca','STRING',description='Raça/cor da pessoa observada'),
        bigquery.SchemaField('grau_instrucao','STRING',description='Escolaridade da pessoa ou do vínculo observado com detalhamento na pós-graduação'),
        bigquery.SchemaField('faixa_etaria','STRING',description='faixa etária da observação')
        ]


# Initialize BigQuery client connection
client = bigquery.Client(project='repositoriodedadosgpsp')

# Create reference to target dataset
dataset_ref = client.dataset('cargos_lideranca')

# Create reference to target table with standardized naming convention:
# FONTE_algo_intuitivo_dado (MUNIC_quantidade_vinculos_mapa_v1)
table_ref = dataset_ref.table('MUNIC_perfil_gestor_agropecuaria_tipo_orgao_v4')

# Configure the load job with our schema definition
job_config = bigquery.LoadJobConfig(
    schema=schema,
    # Optional parameters (commented out):
    # write_disposition="WRITE_TRUNCATE",  # Overwrites table if exists
    # create_disposition="CREATE_IF_NEEDED"  # Default behavior
)

# Execute the load job to upload DataFrame to BigQuery
job = client.load_table_from_dataframe(
    dataframe=df_final,
    destination=table_ref,
    job_config=job_config
)

# Wait for the job to complete
job.result()

/usr/local/lib/python3.12/dist-packages/google/auth/_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

LoadJob<project=repositoriodedadosgpsp, location=US, id=d86a5021-76b1-4da2-8421-f8d8fd3a2c7a>