# Dependências

In [1]:
# Install required Google Cloud packages (commented out as these are typically one-time setup commands)
#!pip install gcloud
#!gcloud auth application-default login

# Import necessary Python libraries
import pandas as pd                # Data manipulation and analysis
import numpy as np                 # Numerical computing
import time                        # Time-related functions
import os                          # Operating system interfaces
import pandas_gbq                  # Pandas integration with BigQuery
from google.cloud import bigquery  # BigQuery client library
import glob                        # File path pattern matching
import openpyxl                    # Excel file handling
import csv                         # CSV file handling

c:\Users\ana.sales_republica\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

# Tratamento

In [2]:
diretorio = 'G:\\Drives compartilhados\\República.org\\4. Equipes\\Dados e Comunicação\\DADOS E CONHECIMENTO\\415 - Repositório de Dados\\Repositório Local\\PNAD\\2025'

In [3]:
os.chdir(diretorio)

In [5]:
os.listdir(diretorio)

['pnad_indicadores.xlsx']

In [4]:
df = pd.read_excel('pnad_indicadores.xlsx', sheet_name='indicador_pnad_06')

In [6]:
df.columns

Index(['esfera', 'cor', 'sexo', 'freq', 'freq_se', 'freq_cv', 'prop',
       'prop_se', 'prop_cv'],
      dtype='object')

In [7]:
df["freq"] = df["freq"].round().astype("Int64")
df = df.drop(columns=['freq_se', 'freq_cv','prop_se', 'prop_cv'])
df["prop"] = (df["prop"] * 100).round(2)
df['ano'] = 2025
df = df.rename(columns= {'freq':'quantidade_vinculos', 'sexo':'genero','cor':'cor_raca'})   
df = df[['ano','esfera', 'cor_raca', 'genero','quantidade_vinculos', 'prop']]              
df

     ano     esfera cor_raca  genero  quantidade_vinculos   prop
0   2025    Federal   Branca   Homem               537910  33.08
1   2025    Federal   Branca  Mulher               360222  22.16
2   2025    Federal    Negra   Homem               488829  30.07
3   2025    Federal    Negra  Mulher               203310  12.50
4   2025    Federal    Outra   Homem                17171   1.06
5   2025    Federal    Outra  Mulher                18431   1.13
6   2025   Estadual   Branca   Homem               806370  23.12
7   2025   Estadual   Branca  Mulher               900013  25.81
8   2025   Estadual    Negra   Homem               876241  25.13
9   2025   Estadual    Negra  Mulher               854745  24.51
10  2025   Estadual    Outra   Homem                22673   0.65
11  2025   Estadual    Outra  Mulher                27223   0.78
12  2025  Municipal   Branca   Homem               968122  13.61
13  2025  Municipal   Branca  Mulher              2028101  28.51
14  2025  Municipal    Negra   Homem              1414051  19.88
15  2025  Municipal    Negra  Mulher              2632849  37.01
16  2025  Municipal    Outra   Homem                30932   0.43
17  2025  Municipal    Outra  Mulher                39439   0.55

In [96]:
df1 = pd.read_excel('G:\\Drives compartilhados\\República.org\\4. Equipes\\Dados e Comunicação\\DADOS E CONHECIMENTO\\415 - Repositório de Dados\\Repositório Local\\PNAD\\2024\\pnad_tabelas_graficos2024.xlsx', sheet_name='Dados6')
df1

       cor    sexo     esfera           sum  prop         cv  Unnamed: 6
0   Branca   Homem   Estadual  8.197671e+05  23.7   2.649866    0.236537
1   Branca  Mulher   Estadual  9.068609e+05  26.2   2.634666    0.261667
2    Negra   Homem   Estadual  8.675198e+05  25.0   2.646677    0.250316
3    Negra  Mulher   Estadual  8.269196e+05  23.9   2.536364    0.238601
4    Outra   Homem   Estadual  2.276095e+04   0.7  21.573643    0.006567
5    Outra  Mulher   Estadual  2.187346e+04   0.6  17.451043    0.006311
6   Branca   Homem    Federal  5.434920e+05  32.1   3.836764    0.321076
7   Branca  Mulher    Federal  3.671908e+05  21.7   4.813619    0.216924
8    Negra   Homem    Federal  5.152359e+05  30.4   3.655313    0.304384
9    Negra  Mulher    Federal  2.286794e+05  13.5   5.554415    0.135096
10   Outra   Homem    Federal  2.049096e+04   1.2  21.665190    0.012105
11   Outra  Mulher    Federal  1.762944e+04   1.0  19.665543    0.010415
12  Branca   Homem  Municipal  9.475998e+05  13.8   2.279506         NaN
13  Branca  Mulher  Municipal  1.951554e+06  28.5   1.259806         NaN
14   Negra   Homem  Municipal  1.415889e+06  20.6   1.819427         NaN
15   Negra  Mulher  Municipal  2.465844e+06  36.0   0.953984         NaN
16   Outra   Homem  Municipal  3.806274e+04   0.6  15.129929         NaN
17   Outra  Mulher  Municipal  4.003715e+04   0.6  10.302486         NaN

In [97]:
df1['ano'] = 2024
df1["sum"] = df1["sum"].round().astype("Int64")
df1 = df1.drop(columns=['cv', 'Unnamed: 6'])
df1 = df1.rename(columns= {'sum':'quantidade_vinculos', 'cor':'cor_raca','sexo':'genero'}) 
df1 = df1[['ano','esfera', 'cor_raca', 'genero','quantidade_vinculos', 'prop']]              
df1

     ano     esfera cor_raca  genero  quantidade_vinculos  prop
0   2024   Estadual   Branca   Homem               819767  23.7
1   2024   Estadual   Branca  Mulher               906861  26.2
2   2024   Estadual    Negra   Homem               867520  25.0
3   2024   Estadual    Negra  Mulher               826920  23.9
4   2024   Estadual    Outra   Homem                22761   0.7
5   2024   Estadual    Outra  Mulher                21873   0.6
6   2024    Federal   Branca   Homem               543492  32.1
7   2024    Federal   Branca  Mulher               367191  21.7
8   2024    Federal    Negra   Homem               515236  30.4
9   2024    Federal    Negra  Mulher               228679  13.5
10  2024    Federal    Outra   Homem                20491   1.2
11  2024    Federal    Outra  Mulher                17629   1.0
12  2024  Municipal   Branca   Homem               947600  13.8
13  2024  Municipal   Branca  Mulher              1951554  28.5
14  2024  Municipal    Negra   Homem              1415889  20.6
15  2024  Municipal    Negra  Mulher              2465844  36.0
16  2024  Municipal    Outra   Homem                38063   0.6
17  2024  Municipal    Outra  Mulher                40037   0.6

In [100]:
df_merged= pd.merge(df, df1, on=['ano', 'esfera', 'cor_raca', 'genero', 'quantidade_vinculos', 'prop'], how='outer')
df_merged

     ano     esfera cor_raca  genero  quantidade_vinculos   prop
0   2024   Estadual   Branca   Homem               819767  23.70
1   2024   Estadual   Branca  Mulher               906861  26.20
2   2024   Estadual    Negra   Homem               867520  25.00
3   2024   Estadual    Negra  Mulher               826920  23.90
4   2024   Estadual    Outra   Homem                22761   0.70
5   2024   Estadual    Outra  Mulher                21873   0.60
6   2024    Federal   Branca   Homem               543492  32.10
7   2024    Federal   Branca  Mulher               367191  21.70
8   2024    Federal    Negra   Homem               515236  30.40
9   2024    Federal    Negra  Mulher               228679  13.50
10  2024    Federal    Outra   Homem                20491   1.20
11  2024    Federal    Outra  Mulher                17629   1.00
12  2024  Municipal   Branca   Homem               947600  13.80
13  2024  Municipal   Branca  Mulher              1951554  28.50
14  2024  Municipal    Negra   Homem              1415889  20.60
15  2024  Municipal    Negra  Mulher              2465844  36.00
16  2024  Municipal    Outra   Homem                38063   0.60
17  2024  Municipal    Outra  Mulher                40037   0.60
18  2025   Estadual   Branca   Homem               806370  23.12
19  2025   Estadual   Branca  Mulher               900013  25.81
20  2025   Estadual    Negra   Homem               876241  25.13
21  2025   Estadual    Negra  Mulher               854745  24.51
22  2025   Estadual    Outra   Homem                22673   0.65
23  2025   Estadual    Outra  Mulher                27223   0.78
24  2025    Federal   Branca   Homem               537910  33.08
25  2025    Federal   Branca  Mulher               360222  22.16
26  2025    Federal    Negra   Homem               488829  30.07
27  2025    Federal    Negra  Mulher               203310  12.50
28  2025    Federal    Outra   Homem                17171   1.06
29  2025    Federal    Outra  Mulher                18431   1.13
30  2025  Municipal   Branca   Homem               968122  13.61
31  2025  Municipal   Branca  Mulher              2028101  28.51
32  2025  Municipal    Negra   Homem              1414051  19.88
33  2025  Municipal    Negra  Mulher              2632849  37.01
34  2025  Municipal    Outra   Homem                30932   0.43
35  2025  Municipal    Outra  Mulher                39439   0.55

# Upload

In [101]:
client = bigquery.Client(project='repositoriodedadosgpsp')

In [104]:
schema = [bigquery.SchemaField('ano', 'INTEGER', description= 'Ano de referência da observação'),
          bigquery.SchemaField('esfera', 'STRING', description= 'Nível da esfera do governo referente da observação'),
          bigquery.SchemaField('cor_raca', 'STRING', description= 'Raça/cor autodeclarado ou não'),
          bigquery.SchemaField('genero', 'STRING', description= 'Gênero autodeclarado ou não'),         
          bigquery.SchemaField('quantidade_vinculos', 'INTEGER', description= 'Número total de vinculos observados'),
          bigquery.SchemaField('prop', 'FLOAT', description= 'Proporção de vínculos em relação ao total naquele ano'),
          ]

dataset_ref = client.dataset('perfil_remuneracao')

table_ref = dataset_ref.table('PNAD_vinculos_genero_cor') 
job_config = bigquery.LoadJobConfig(schema=schema)
job = client.load_table_from_dataframe(df_merged, table_ref, job_config=job_config)
job.result()

LoadJob<project=repositoriodedadosgpsp, location=US, id=994c9731-4334-4523-8b23-f7882a4e2860>